### ISSUE TITLE
GPT生成模型推理时，如何设置max_length或max_new_tokens参数？

### ISSUE THREAD

**Issue by chasonlee** [modelscope/modelscope#100]
我自行微调了一个新的模型，`sequence_length`设为512后，推理时会有如下警告：
Input length of input_ids is 511, but `max_length` is set to 128. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

基于官方推理代码：
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
text_generation_zh = pipeline(Tasks.text_generation, model='damo/nlp_gpt3_text-generation_chinese-large')
result_zh = text_generation_zh("随着计算机视觉的飞速发展,人脸识别技术已从简单场景发展到复杂场景,也即姿态、光照、表情、噪声、遮挡、化妆、年龄、种族、性别等差异化所呈现的复杂场景。尽管已有的人脸识别系统在特定约束环境下的识别成功率较高,")
print(result_zh['text'])
```
不知应该在何处设置`max_length` ，翻遍文档没有看到相关说明。翻阅源码，似乎不能从`pipeline`把参数传到gpt3/text_generation.py中的generate函数里的`max_length`。
在实际推理结果中，也确实出现生成结果不完整的情况。只要输入文本稍微长（100个字符）但远小于`sequence_length`，输出结果就半途截断。

测试版本：v1.1.3（测试过v1.2.0，有audio库依赖问题没跑通）

**Comment by Firmament-cyou** [comment]
您好，我们在 v1.2.0 版本中修改了 gpt3 模型 generate 的实现，不再使用 transformers 的相关库函数。这里的报错来自于 transformers 库，这一问题在新版本已经修复，麻烦您使用新版本进行下测试

**Comment by zzclynn** [comment]
测试过v1.2.0，有audio库依赖问题没跑通
audio依赖库是指？你安装的时候是只安装nlp还是全安装了？

**Comment by chasonlee** [comment]
> 测试过v1.2.0，有audio库依赖问题没跑通 audio依赖库是指？你安装的时候是只安装nlp还是全安装了？

只安装nlp，显示没装audio跑不了，继续装audio后，又显示`Detected that PyTorch and TorchAudio were compiled with different CUDA version`，之后就没试了。

我看到你们发布了v1.2.1好像移除了audio的依赖，我再试试看

**Comment by chasonlee** [comment]
@zzclynn @Firmament-cyou 目前我测试v1.2.1，发现以上问题已修复，可以生成完整的结果，也没有audio依赖问题。

另外有个小问题，就是我在fine-tune的数据中已经去除了`所有的空格`，但生成结果中却很多空格，比如`出生日期9月2日`会生成为：`出 生日 期 9 月 2 日`，我可以通过代码过滤这些空格，问题不大，但还是想问问原理上如何解释这种现象？是因为预训练数据中有很多空格吗？（或者是推理代码的bug？我还没细看这部分），v1.1.3和v1.2.1均有这个现象。

**Comment by Firmament-cyou** [comment]
> @zzclynn @Firmament-cyou 目前我测试v1.2.1，发现以上问题已修复，可以生成完整的结果，也没有audio依赖问题。
> 
> 另外有个小问题，就是我在fine-tune的数据中已经去除了`所有的空格`，但生成结果中却很多空格，比如`出生日期9月2日`会生成为：`出 生日 期 9 月 2 日`，我可以通过代码过滤这些空格，问题不大，但还是想问问原理上如何解释这种现象？是因为预训练数据中有很多空格吗？（或者是推理代码的bug？我还没细看这部分），v1.1.3和v1.2.1均有这个现象。

看起来像是 pipeline 中生成文本后处理的问题，我们后续排查一下

**Comment by Firmament-cyou** [comment]
> 另外有个小问题，就是我在fine-tune的数据中已经去除了`所有的空格`，但生成结果中却很多空格，比如`出生日期9月2日`会生成为：`出 生日 期 9 月 2 日`，我可以通过代码过滤这些空格，问题不大，但还是想问问原理上如何解释这种现象？是因为预训练数据中有很多空格吗？（或者是推理代码的bug？我还没细看这部分），v1.1.3和v1.2.1均有这个现象。

您好，生成中文字符之间出现空格的问题我们已经在新版本 1.3.0 中进行了修复

**Comment by chasonlee** [comment]
@Firmament-cyou 已实测v1.3.0可以👍
