### ISSUE TITLE
模型导出到onnx格式报错：KeyError('**** is not in the models registry group*****)

### ISSUE THREAD

**Issue by AOldDriverA** [modelscope/modelscope#1000]
导出cv_unet_skin_retouching_torch模型，但是报错如下：
KeyError('skin retouching is not in the models registry group skin-retouching-torch. Please make sure the correct version of ModelScope library is used.')
其中，model type 是从模型卡片中获取的：
model_type:
- skin retouching
模型可以正常使用，就是导出有问题。model type也试了几个，都是同样的报错，不清楚model type应该在哪里获取或注册

**Comment by yingdachen** [comment]
looks like onnx export is not supported for this model, @tastelikefeet please take a look and confirm.

**Comment by AOldDriverA** [comment]
@tastelikefeet 能帮忙看一下这个问题嘛？目前比较需要cv_unet_skin_retouching_torch这个模型的导出，谢谢
