### ISSUE TITLE
如何获取分类模型的全部类别？

### ISSUE THREAD

**Issue by olin-Ai** [modelscope/modelscope#1001]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

img_path = '/root/Workspace/bob/next_vit/model/1.jpg'
image_classification = pipeline(Tasks.image_classification, 
                                model='/root/Workspace/bob/next_vit/model/')

result = image_classification(img_path)
print(result)
这是推理代码，如何获取这个模型的全部分类类别

**Comment by yingdachen** [comment]
参见文档 https://www.modelscope.cn/docs/%E4%BB%BB%E5%8A%A1%E7%9A%84%E4%BB%8B%E7%BB%8D
