### ISSUE TITLE
不知道如何操作才能生成预览文件

### ISSUE THREAD

**Issue by Joker1212** [modelscope/modelscope#1003]
@wangxingjun778 不知道到底要如何操作才能生成预览文件，就两张图片不上传zip，就有预览，10来张图就又没有预览了
希望能明确告知规则和流程

**Comment by wangxingjun778** [comment]
可否提供一下数据集链接?

预览的一般策略是：1. 通常sdk能够加载成功，预览应该就正常预览； 2. 预览是个异步任务，可能要稍等几分钟； 3. 对数据文件中除了README以为的文件进行增删改操作，都会触发异步预览任务。

**Comment by Joker1212** [comment]
https://www.modelscope.cn/datasets/jockerK/TEDS_TEST/files 这是我数据集，刚刚发现还是只有两张图预览，我是先传了两张，然后增加了很多图和一个zip文件，然后预览就只有两张

**Comment by wangxingjun778** [comment]
看了一下这个数据集的文件组织形式，有点问题，一般的数据结构可以参考这俩数据集：

https://modelscope.cn/datasets/wangxingjun778/test_img_dataset
https://modelscope.cn/datasets/wangxingjun778/test_new_dataset  (待metadata.csv的形式)

相关文档： https://modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E5%88%9B%E5%BB%BA

**Comment by Joker1212** [comment]
按照第一个这样设置了好像还是不行，非常感谢回复
