### ISSUE TITLE
modelscope.tools.run_auto_label

### ISSUE THREAD

**Issue by Chengyang852** [modelscope/modelscope#1007]
调用run_auto_label工具进行打包，提示
WARNING:root:wav_basename=kange_1050_S0000 not in text_dict, prosody could be missing!

最后生成的prosody.txt文件为空，请问应该怎么解决

**Comment by tastelikefeet** [comment]
咨询了相关模型负责人，这个脚本目前已经不维护了，可以魔改下或使用其他替代方案
