### ISSUE TITLE
如何利用Python SDK上传单个文件到之前的模型库?

### ISSUE THREAD

**Issue by YujieOuO** [modelscope/modelscope#1012]
如果用模型库存放了很多ckpt，如果想新增ckpt，只能用git方法全部拔下来然后又重新全部上传吗

**Comment by yingdachen** [comment]
通过命令行上传单文件的接口，预期最近会支持。目前可以通过GIT上传，为了避免git clone全量下载所有的大文件，可以用GIT_LFS_SKIP_SMUDGE配置，来跳过下载LFS文件。

具体命令如下：
GIT_LFS_SKIP_SMUDGE=1  git clone <your git patb>

这样子下载模型repo会跳过下载实际大文件。
