### ISSUE TITLE
Mac M1 cannot install modelscope[audio]

### ISSUE THREAD

**Issue by CSLukkun** [modelscope/modelscope#1014]
Just follow as the step from the office website. 

The terminal will show:

```
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

Steps:
```
conda create -n modelscope python=3.8
conda activate modelscope
pip3 install torch==1.11.0 torchvision torchaudio
pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
```

**Comment by timchenxiaoyu** [comment]
same problem

**Comment by yingdachen** [comment]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/e5bfc59b-7f9a-4b72-aaf2-ff97b51eac36">

unfortunately some of the audio models can only be used on linux, as specified on the documentation.
