### ISSUE TITLE
ModelScope platform lacks features such as user blocking, blackout, reporting, etc.

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#1015]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

无论组织还是个人均需要

**Comment by yingdachen** [comment]
please describe example scenarios where such features are necessary

**Comment by monetjoe** [comment]
> please describe example scenarios where such features are necessary

比如申请加入组织的申请留言、模型数据集空间等提issue的地方就都可以搞事情
