### ISSUE TITLE
some losses mentioned in paper are not in this implementation

### ISSUE THREAD

**Issue by yunlong10** [modelscope/modelscope#102]
https://github.com/modelscope/modelscope/blob/fb17fb01a6ad5857a040c27ac30cb968ba25c69e/modelscope/models/cv/language_guided_video_summarization/summarizer.py#L123

I didn't find the implementation of Reconstruction Loss and Diversity Loss mentioned in [the paper](https://arxiv.org/pdf/2107.00650.pdf). I think without that, the adopted transformer decoder may be meaningless?

**Comment by wjgaas** [comment]
> https://github.com/modelscope/modelscope/blob/fb17fb01a6ad5857a040c27ac30cb968ba25c69e/modelscope/models/cv/language_guided_video_summarization/summarizer.py#L123
> 
> I didn't find the implementation of Reconstruction Loss and Diversity Loss mentioned in [the paper](https://arxiv.org/pdf/2107.00650.pdf). I think without that, the adopted transformer decoder may be meaningless?

Reconstruction Loss and Diversity Loss will be added in the next version.
