### ISSUE TITLE
千问大模型推理报错

### ISSUE THREAD

**Issue by guzy** [modelscope/modelscope#1020]
启动模型服务：
python3 -m vllm.entrypoints.openai.api_server --host [0.0.0.0](http://0.0.0.0/) \
--port 10023 --seed 1024 \
--served-model qwen1.5-4b \
--model "/home/work/ssd1/Qwen1.5-4B-Chat" --trust-remote-code \
--tokenizer-mode slow --max-model-len 128 \
--dtype float16 
进行模型推理：
curl http://127.0.0.1:10023/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model":"qwen1.5-4b", "max_tokens":64, "seed":0, "top_k":1, "top_p":0.8, "temperature":0.3, 
"prompt": "谈谈你对大模型的理解"
}'
报错信息：
No heartbeat received from MQLLMEngine

**Comment by yingdachen** [comment]
this is more appropriate for qwen github issue (https://github.com/QwenLM/Qwen) or vllm github.

you may also try ms-swift integration of vllm
