### ISSUE TITLE
modelscope platform lacks user self-service account deletion function

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#1023]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

Please refer to https://m.thepaper.cn/kuaibao_detail.jsp?contid=1936177&from=kuaibao

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by yingdachen** [comment]
the feature is currently in testing. stay tuned.

**Comment by yingdachen** [comment]
the feature was released last week.
