### ISSUE TITLE
[Bug] 模型存在重复下载的问题，不能正确识别已经上传至缓存文件夹的权重文件

### ISSUE THREAD

**Issue by zydmtaichi** [modelscope/modelscope#1029]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
将一个下载容易断线的模型权重先单独离线下载，再上传至缓存文件夹`.cache/modelscope/hub/组织名/模型名/`下，再次运行`modelscope download --model 组织名/模型名`，发现会重复下载模型权重，对于已有的离线下载后并上传的模型权重文件不识别

**To Reproduce**
1.首先在[网页](https://modelscope.cn/models/X-D-Lab/MindChat-Qwen-7B-v2/files)上分别下载模型的所有文件，上传至服务器的`.cache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2`下
2.运行`modelscope download --model X-D-Lab/MindChat-Qwen-7B-v2`
3.发现modelscope未识别已经上传的权重bin文件，仍然重复从网络下载已有权重，没有及时报告下载已完成

**Your Environments (__required__)**
* OS: Linux ld-PT6620W 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
* CPU: Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
* modelscope version 1.18.1

Please @ corresponding people according to your problem:

Model hub related: @liuyhwangyh @tastelikefeet @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

**Comment by yingdachen** [comment]
have you set env variable?

please echo $MODELSCOPE_CACHE to check

**Comment by zydmtaichi** [comment]
> have you set env variable?
> 
> please echo $MODELSCOPE_CACHE to check

yes，the $MODELSCOPE_CACHE is set in bashrc file.
here is my $MODELSCOPE_CACHE : `/mnt/sdb/hugcache/modelscope`

**Comment by yingdachen** [comment]
then 

> > have you set env variable?
> > please echo $MODELSCOPE_CACHE to check
> 
> yes，the $MODELSCOPE_CACHE is set in bashrc file. here is my $MODELSCOPE_CACHE : `/mnt/sdb/hugcache/modelscope`

then you should copy file to /mnt/sdb/hugcache/modelscope/X-D-Lab/MindChat-Qwen-7B-v2 , instead of .cache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2

**Comment by zydmtaichi** [comment]
> then
> 
> > > have you set env variable?
> > > please echo $MODELSCOPE_CACHE to check
> > 
> > 
> > yes，the $MODELSCOPE_CACHE is set in bashrc file. here is my $MODELSCOPE_CACHE : `/mnt/sdb/hugcache/modelscope`
> 
> then you should copy file to /mnt/sdb/hugcache/modelscope/X-D-Lab/MindChat-Qwen-7B-v2 , instead of .cache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2

I mentioned the addr `.cache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2` to make an example for general case. Actually, on my server, the model is located under `/mnt/sdb/hugcache/modelscope/X-D-Lab/MindChat-Qwen-7B-v2` and the issue still exists

**Comment by zydmtaichi** [comment]
@yingdachen If i run command `modelscope download --model X-D-Lab/MindChat-Qwen-7B-v2`, downloading process will always start even the weight file is put into `/mnt/sdb/hugcache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2`. for large file like `pytorch_model-00001-of-00008.bin`, the downloading process create a temp folder and download the separated parts of large file under `/mnt/sdb/hugcache/modelscope/hub/._____temp/X-D-Lab/MindChat-Qwen-7B-v2`

**Comment by yingdachen** [comment]
thanks for reporting the issue, we will try to reproduce

**Comment by yingdachen** [comment]
there are hidden meta file to keep track of cache in your local model directory, using `cp` command will not include those hidden files, please use 'mv' to make sure the entire directory is mv.

for example, say you use `modelscope download --model X-D-Lab/MindChat-Qwen-7B-v2 --local_dir ./tmp` to download the model to local directory `tmp`, and you would like to use it in local cache, you may `mv ./tmp /mnt/sdb/hugcache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2` .

or if you want to use `cp`, make sure you copy all hidden files (e.g., the `.msc` file) to target directory.

**Comment by yingdachen** [comment]
> > there are hidden meta file to keep track of cache in your local model directory, using `cp` command will not include those hidden files, please use 'mv' to make sure the entire directory is mv.
> > for example, say you use `modelscope download --model X-D-Lab/MindChat-Qwen-7B-v2 --local_dir ./tmp` to download the model to local directory `tmp`, and you would like to use it in local cache, you may `mv ./tmp /mnt/sdb/hugcache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2` .
> > or if you want to use `cp`, make sure you copy all hidden files (e.g., the `.msc` file) to target directory.
> 
> hi @yingdachen , However, the msc file can't be obtained directly from website(like [this file list](https://modelscope.cn/models/X-D-Lab/MindChat-Qwen-7B-v2/files) ) sometimes the network speed is slow, I use another download software(like Thunder) to get the weight file and copy into the folder, then the track which .msc keep is diffirent with the actual track in folder. And the content of msc file can't be edited manually. Is there any chance to get the model file from other ways and recognized by modelscope?

unfortunately msc file is not considered part of model repo, it is merely a managed file used by modelscope library. therefore third-party tool would not be able to generate the file.

you can, however, use modelscope library (insted of command line) which provide `snapshot_download` method with `local_files_only` option via parameter.  we would consider adding this parameter to command line later, or you can open an issue for this request.

**Comment by zydmtaichi** [comment]
> > > there are hidden meta file to keep track of cache in your local model directory, using `cp` command will not include those hidden files, please use 'mv' to make sure the entire directory is mv.
> > > for example, say you use `modelscope download --model X-D-Lab/MindChat-Qwen-7B-v2 --local_dir ./tmp` to download the model to local directory `tmp`, and you would like to use it in local cache, you may `mv ./tmp /mnt/sdb/hugcache/modelscope/hub/X-D-Lab/MindChat-Qwen-7B-v2` .
> > > or if you want to use `cp`, make sure you copy all hidden files (e.g., the `.msc` file) to target directory.
> > 
> > 
> > hi @yingdachen , However, the msc file can't be obtained directly from website(like [this file list](https://modelscope.cn/models/X-D-Lab/MindChat-Qwen-7B-v2/files) ) sometimes the network speed is slow, I use another download software(like Thunder) to get the weight file and copy into the folder, then the track which .msc keep is diffirent with the actual track in folder. And the content of msc file can't be edited manually. Is there any chance to get the model file from other ways and recognized by modelscope?
> 
> unfortunately msc file is not considered part of model repo, it is merely a managed file used by modelscope library. therefore third-party tool would not be able to generate the file.
> 
> you can, however, use modelscope library (insted of command line) which provide `snapshot_download` method with `local_files_only` option via parameter. we would consider adding this parameter to command line later, or you can open an issue for this request.

hi @yingdachen ,
I did some research and found the trace files can be modified manually via pickle loading/dumping. For example, to create a .mcs file, you need the model file names and the revision code. The revision Info can be gotten by api supplied in repo( like [this for file revision](https://github.com/modelscope/modelscope/blob/master/modelscope/hub/api.py#L639) and [this for model repo revision](https://github.com/modelscope/modelscope/blob/master/modelscope/hub/api.py#L585) ). I hope we can add some docs to give instruction about how to create and organize trace files(.mv, .mdl, .mcs) manually for the model files which downloaded from 3rd party tools, thanks
