### ISSUE TITLE
Will modelscope open up the ability to change usernames in the future?

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#1032]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by yingdachen** [comment]
there is no such plan. you may change your nickname, but not user name.
