### ISSUE TITLE
ModuleNotFoundError: No module named 'modelscope.models.cv.facial_68ldk_detection'

### ISSUE THREAD

**Issue by f549263766** [modelscope/modelscope#1045]
## Question
The module exists in GitHub's modelscope-v1.19.1 source code at [modelscope/models/cv/facial_68ldk_detection](https://github.com/modelscope/modelscope/tree/master/modelscope/models/cv/facial_68ldk_detection), but is not found using command *pip install modelscope[cv]*.

## Environment
Python-3.10.14 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
modelscope-1.19.1

## Minimal Reproducible Example
```python
import cv2
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

model_id = 'Damo_XR_Lab/cv_human_68-facial-landmark-detection'
estimator = pipeline(Tasks.facial_68ldk_detection, model=model_id)

Input_file = 'assets/sample.jpg'
results = estimator(input=Input_file)
landmarks = results['landmarks']

image_draw = cv2.imread(Input_file)
for num in range(landmarks.shape[0]):
    cv2.circle(image_draw, (round(landmarks[num][0]), round(landmarks[num][1])), 2, (0, 255, 0), -1)
cv2.imwrite('result.png', image_draw)
```

## Error
ModuleNotFoundError: No module named 'modelscope.models.cv.facial_68ldk_detection'

**Comment by gylcalex1314** [comment]
Sorry for reply late. 
For solving the problem you mentioned, you can install as follows: 
`git clone https://github.com/modelscope/modelscope.git`
`cd modelscope`
`pip install -e .`
then it'll be ok .
