### ISSUE TITLE
megatron 还是megatron_util

### ISSUE THREAD

**Issue by liuxz0801** [modelscope/modelscope#105]
https://github.com/modelscope/modelscope/blob/fb17fb01a6ad5857a040c27ac30cb968ba25c69e/modelscope/models/nlp/gpt3/distributed_gpt3.py#L23
已经安装了平台根据megatron修改提供的 megartron_util包。
在mdoelscope 1.1.0版本 中是直接import megatron，不会报错
在1.2.1中改为了megatron_util 会报错，是否需要修改回来？

**Comment by Firmament-cyou** [comment]
您好，我们在新版本中对于 megatron 必要的工具库使用了统一的抽象，使用 from megatron_util 是新版本正确的调用方式，我们只为 from megatron 提供了有限的兼容性，目前已经不推荐使用。请问您能否提供一下使用 from megatron_util 时的报错信息？

**Comment by liuxz0801** [comment]
已经解决。
目前使用了最新的megatron_util 1.3.0。
在官方提供的megatron_util 下载页面上显示存在错误。
https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html地址下存在两个重名megatron_util_1.2.0。
实际一个为1.3.0
[megatron_util-1.2.0-py3-none-any.whl](https://github.com/modelscope/modelscope/issues/dependencies/megatron_util-1.3.0-py3-none-any.whl)

**Comment by wenmengzhou** [comment]
> 已经解决。 目前使用了最新的megatron_util 1.3.0。 在官方提供的megatron_util 下载页面上显示存在错误。 [https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html地址下存在两个重名megatron_util_1.2.0。](https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html%E5%9C%B0%E5%9D%80%E4%B8%8B%E5%AD%98%E5%9C%A8%E4%B8%A4%E4%B8%AA%E9%87%8D%E5%90%8Dmegatron_util_1.2.0%E3%80%82) 实际一个为1.3.0 [megatron_util-1.2.0-py3-none-any.whl](https://github.com/modelscope/modelscope/issues/dependencies/megatron_util-1.3.0-py3-none-any.whl)

感谢建议，已经修复
