### ISSUE TITLE
 cannot import name 'OfflineModeIsEnabled' 

### ISSUE THREAD

**Issue by emmettng** [modelscope/modelscope#1050]
**Describe the bug**
```
from modelscope.pipelines import pipeline
```
leads to error : 
```
cannot import name 'OfflineModeIsEnabled' from 'datasets.utils.file_utils' 
```

**To Reproduce**
1. install latest version (1.19.2)
2. from modelscope.pipelines import pipeline 

**Your Environments (__required__)**
* OS: `Ubuntu 20.04`

Pipeline related: @tastelikefeet @wangxingjun778

**Comment by ancientswar** [comment]
upgrade 1.19.2 and the issue has been solved

**Comment by yingdachen** [comment]
latest version of dataset 3.0.2 introduced breaking change, please keep it <=3.0.1

this is also specified in latest requirement , so if you do `pip install modelscope[dataset] -U`, you will also be prompted with an error if you have dataset verison >=3.0.2

**Comment by ancientswar** [comment]
thanks, i try it

**Comment by ancientswar** [comment]
it doesn't work until now

**Comment by wangxingjun778** [comment]
datasets==3.0.1 , that works for me :)

**Comment by machiba** [comment]
Describe the bug
from modelscope import snapshot_download, Model
model = Model.from_pretrained(model_dir, device_map="auto", trust_remote_code=True, torch_dtype=torch.float16)
leads to error :
cannot import name 'OfflineModeIsEnabled' from 'datasets.utils.file_utils'
please help me

**Comment by yingdachen** [comment]
> Describe the bug from modelscope import snapshot_download, Model model = Model.from_pretrained(model_dir, device_map="auto", trust_remote_code=True, torch_dtype=torch.float16) leads to error : cannot import name 'OfflineModeIsEnabled' from 'datasets.utils.file_utils' please help me

please take a look at the discucssion above and let us know if you have datasets>=3.0.2
