### ISSUE TITLE
modelscope.cn上 非公开 模型/数据集 仓库存在“疑似越权漏洞” 的问题

### ISSUE THREAD

**Issue by okwinds** [modelscope/modelscope#1054]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
找了[modelscope](https://github.com/modelscope/modelscope)所有代码仓库，没有看到modelscope.cn的issue区，所以只好提交到这里。希望对问题能够有所跟踪
步骤：
1.上传一个非公开模型或数据集
2.静待12-24小时
3.出现下载次数
过程中账号非共享，模型或数据集无外链。

以上 @yingdachen ，感谢跟踪解决问题！

**Comment by yingdachen** [comment]
私有模型下载计数的问题已经修复，可以验证一下。
目前唯一残留的一个不是非常自然的计数，是git push操作因为会自动涉及到和后端的交互，隐含一个pull，所以git push操作本身也会导致下载计数+1.

**Comment by yingdachen** [comment]
also i have removed all picture snapshot taken from chat history, since it does not appear to be  appropriate to share them here. thanks for your understanding

**Comment by okwinds** [comment]
> also i have removed all picture snapshot taken from chat history, since it does not appear to be appropriate to share them here. thanks for your understanding

yep, I completely understand. Please keep me upd with any news, thank u.

**Comment by okwinds** [comment]
> 私有模型下载计数的问题已经修复，可以验证一下。 目前唯一残留的一个不是非常自然的计数，是git push操作因为会自动涉及到和后端的交互，隐含一个pull，所以git push操作本身也会导致下载计数+1. @okwinds

了解，我持续关注一下

**Comment by okwinds** [comment]
> please let us know if issue is resolved.

I uploaded the models `okwinds/GPT-2` and the dataset `okwinds/ptb_text_only` for testing purposes yesterday. 
Currently, `okwinds/GPT-2` has been downloaded 4 times, and `okwinds/ptb_text_only` has been downloaded 3 times. Is this level of activity normal?

**Comment by yingdachen** [comment]
> > please let us know if issue is resolved.
> 
> I uploaded the models `okwinds/GPT-2` and the dataset `okwinds/ptb_text_only` for testing purposes yesterday. Currently, `okwinds/GPT-2` has been downloaded **_4_** times, and `okwinds/ptb_text_only` has been downloaded **_3_** times. Is this level of activity normal?

We have cross checked the access history of the aforementioned model and dataset, and things appear to check out:
1. model okwinds/GPT-2 was accessed via git four times in 11/27 evening
2. dataset  okwinds/ptb_text_only was accessed twice via git in 11/27 evening, and once via SDK once, also in 11/27 evening.

all accesses were authorized properly.

**Comment by okwinds** [comment]
> > > please let us know if issue is resolved.
> > 
> > 
> > I uploaded the models `okwinds/GPT-2` and the dataset `okwinds/ptb_text_only` for testing purposes yesterday. Currently, `okwinds/GPT-2` has been downloaded **_4_** times, and `okwinds/ptb_text_only` has been downloaded **_3_** times. Is this level of activity normal?
> 
> We have cross checked the access history of the aforementioned model and dataset, and things appear to check out:
> 
> 1. model okwinds/GPT-2 was accessed via git four times in 11/27 evening
> 2. dataset  okwinds/ptb_text_only was accessed twice via git in 11/27 evening, and once via SDK once, also in 11/27 evening.
> 
> all accesses were authorized properly.

so,,

when uploading models and datasets using `git push`, does the characteristic of git lead to such counting in modelscope, right?

However, it seems that the number of model downloads (4 times) is one more than that of the datasets (3 times). Both are uploaded using git push.  Is this correct?

Thx ~

**Comment by yingdachen** [comment]
> > > > please let us know if issue is resolved.
> > > 
> > > 
> > > I uploaded the models `okwinds/GPT-2` and the dataset `okwinds/ptb_text_only` for testing purposes yesterday. Currently, `okwinds/GPT-2` has been downloaded **_4_** times, and `okwinds/ptb_text_only` has been downloaded **_3_** times. Is this level of activity normal?
> > 
> > 
> > We have cross checked the access history of the aforementioned model and dataset, and things appear to check out:
> > 
> > 1. model okwinds/GPT-2 was accessed via git four times in 11/27 evening
> > 2. dataset  okwinds/ptb_text_only was accessed twice via git in 11/27 evening, and once via SDK once, also in 11/27 evening.
> > 
> > all accesses were authorized properly.
> 
> so,,
> 
> when uploading models and datasets using `git push`, does the characteristic of git lead to such counting in modelscope, right?
> 
> However, it seems that the number of model downloads (4 times) is one more than that of the datasets (3 times). Both are uploaded using git push. Is this correct?
> 
> Thx ~

yes. git push would lead to additonal pull-like behaviors, which would induce counting incrementation. 

from what we can tell, the model has 4 git-related counting behavior and the dataset only has 2(another sdk download so total is 3).

**Comment by okwinds** [comment]
> > > > > please let us know if issue is resolved.
> > > > 
> > > > 
> > > > I uploaded the models `okwinds/GPT-2` and the dataset `okwinds/ptb_text_only` for testing purposes yesterday. Currently, `okwinds/GPT-2` has been downloaded **_4_** times, and `okwinds/ptb_text_only` has been downloaded **_3_** times. Is this level of activity normal?
> > > 
> > > 
> > > We have cross checked the access history of the aforementioned model and dataset, and things appear to check out:
> > > 
> > > 1. model okwinds/GPT-2 was accessed via git four times in 11/27 evening
> > > 2. dataset  okwinds/ptb_text_only was accessed twice via git in 11/27 evening, and once via SDK once, also in 11/27 evening.
> > > 
> > > all accesses were authorized properly.
> > 
> > 
> > so,,
> > when uploading models and datasets using `git push`, does the characteristic of git lead to such counting in modelscope, right?
> > However, it seems that the number of model downloads (4 times) is one more than that of the datasets (3 times). Both are uploaded using git push. Is this correct?
> > Thx ~
> 
> yes. git push would lead to additonal pull-like behaviors, which would induce counting incrementation.
> 
> from what we can tell, the model has 4 git-related counting behavior and the dataset only has 2(another sdk download so total is 3).

THX !
