### ISSUE TITLE
明明导入torch模型报错却显示：缺少TensorFlow环境

### ISSUE THREAD

**Issue by tianchiguaixia** [modelscope/modelscope#1058]
模型地址：https://www.modelscope.cn/models/iic/cv_resnet18_ocr-detection-db-line-level_damo

代码：
![1730365392481_7BAC5E63-765A-49a2-A09A-2E82B41EAB32](https://github.com/user-attachments/assets/54c206b5-e536-4651-a7ed-17f2739fa880)

报错：
![1730365702654_A1CC519F-F020-42c1-8F30-C8FB0F9943C1](https://github.com/user-attachments/assets/ba171a06-7d4a-452f-9898-21e640c5526f)

**Comment by yingdachen** [comment]
#1059
