### ISSUE TITLE
GPT-3 pipeline 如何设置 top_k, temperature等参数？

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#106]
如题，按照官方示例做推理，怎么设置超参数？

**Comment by Firmament-cyou** [comment]
> 如题，按照官方示例做推理，怎么设置超参数？

目前可以在 config.json 文件中进行修改生成相关参数，例如：
```json
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 768,
  "max_position_embeddings": 2048,
  "num_attention_heads": 12, 
  "num_hidden_layers": 12, 
  "type_vocab_size": 2,
  "vocab_size": 25600,
  "attention_type": "self",
  "layernorm_epsilon": 1e-12,
  "top_k": 20,
  "top_p": 0.95
}
```
模型运行相关的配置文件默认会下载到 <workdir>/.cache/modelscope/hub/damo/<model_id> 下，您可以在这个路径找到 config.json 文件

**Comment by David-Lee-1990** [comment]
好的，非常感谢。我试了下，是不支持同时设置 topP, topK, 对吗？

`  File "/root/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 197, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/root/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 232, in _process_single
    out = self.forward(out, **forward_params)
  File "/root/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 473, in forward
    [inputs] * self.world_size)
  File "/root/anaconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/anaconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: cannot set both top-k and top-p samplings.`

**Comment by Firmament-cyou** [comment]
> 好的，非常感谢。我试了下，是不支持同时设置 topP, topK, 对吗？
> 
> ` File "/root/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 197, in __call__ output = self._process_single(input, *args, **kwargs) File "/root/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 232, in _process_single out = self.forward(out, **forward_params) File "/root/anaconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 473, in forward [inputs] * self.world_size) File "/root/anaconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 268, in map return self._map_async(func, iterable, mapstar, chunksize).get() File "/root/anaconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 657, in get raise self._value AssertionError: cannot set both top-k and top-p samplings.`

目前是这样，后续我们会更新模型的生成逻辑，使 top_k 和 top_p 采样可以同时生效

**Comment by David-Lee-1990** [comment]
好的，好的，多谢
