### ISSUE TITLE
中文版文档命令错误/Chinese version document command error

### ISSUE THREAD

**Issue by sandy9707** [modelscope/modelscope#1065]
<img width="895" alt="image" src="https://github.com/user-attachments/assets/8fc5401f-7011-466b-a013-908fd80575a8">

快速开始的模型下载部分, 给出的命令是
`modelscope download --model="Qwen/Qwen2.5-0.5B-Instruct --local_dir ./model-dir"`

疑似因为版本变动命令变动--model后的=号是多余的

The command provided for the model download section to start quickly is:

`modelscope download --model="Qwen/Qwen2.5-0.5B-Instruct" --local_dir ./model-dir`

It seems that the equal sign (=) after --model might be unnecessary due to a potential change in the version of the command.

**Comment by yingdachen** [comment]
谢谢指出。

这里主要是typo，把后面一个引号的位置写错了。事实上对于下载模型，以下3种写法都支持
modelscope download --model="Qwen/Qwen2.5-0.5B-Instruct" --local_dir ./model-dir
modelscope download --model "Qwen/Qwen2.5-0.5B-Instruct" --local_dir ./model-dir
modelscope download "Qwen/Qwen2.5-0.5B-Instruct" --local_dir ./model-dir

文档中已经修复引号的位置。
