### ISSUE TITLE
AttributeError: 'ClassDef' object has no attribute 'type_params'

### ISSUE THREAD

**Issue by havinggood** [modelscope/modelscope#1072]
运行from modelscope.msdatasets import MsDataset出现报错，详细报错为：
Traceback (most recent call last):
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 508, in _get_single_file_scan_result
    output = self.astScaner.generate_ast(file)
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 414, in generate_ast
    output, _ = self.scan_import(node, indent='  ', show_offsets=False)
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 200, in scan_import
    local_out, local_print = _scan_import(
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 162, in _scan_import
    return self.scan_import(
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 184, in scan_import
    attr = getattr(node, field)
AttributeError: 'ClassDef' object has no attribute 'type_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/CVPR_Anti_UAV/modelscope/msdatasets/__init__.py", line 2, in <module>
    from . import cv
  File "/private/CVPR_Anti_UAV/modelscope/msdatasets/cv/__init__.py", line 2, in <module>
    from . import (image_classification, image_semantic_segmentation,
  File "/private/CVPR_Anti_UAV/modelscope/msdatasets/cv/image_classification/__init__.py", line 4, in <module>
    from modelscope.utils.import_utils import LazyImportModule
  File "/private/CVPR_Anti_UAV/modelscope/utils/import_utils.py", line 358, in <module>
    class LazyImportModule(ModuleType):
  File "/private/CVPR_Anti_UAV/modelscope/utils/import_utils.py", line 361, in LazyImportModule
    AST_INDEX = load_index()
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 761, in load_index
    _update_index(index, files_mtime)
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 678, in _update_index
    updated_index = file_scanner.get_files_scan_results(updated_files)
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 574, in get_files_scan_results
    decorator_list, import_list = self._get_single_file_scan_result(
  File "/private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py", line 511, in _get_single_file_scan_result
    raise Exception(
Exception: During ast indexing the file /private/CVPR_Anti_UAV/modelscope/models/audio/sv/generic_speaker_verification.py, a related error excepted in the file /private/CVPR_Anti_UAV/modelscope/utils/ast_utils.py at line: 184: "attr = getattr(node, field)" with error msg: "AttributeError: 'ClassDef' object has no attribute 'type_params'", please double check the origin file /private/CVPR_Anti_UAV/modelscope/models/audio/sv/generic_speaker_verification.py to see whether the file is correctly edited.

**Comment by yingdachen** [comment]
please describe the case how this issue is found, and/or how to reproduce the problem

**Comment by havinggood** [comment]
> 请描述案例、如何发现此问题和/或如何重现问题

我在复现modelscope社区的3rd-无人机检测竞赛_CodeBase_CVPR23时，正在进行数据集的下载，
from modelscope.msdatasets import MsDataset
from modelscope.utils.constant import DownloadMode


## set dataset path
cache_dir = '/home/ly261666/datasets' 

# Download train set
train_set = MsDataset.load('3rd_Anti-UAV', namespace='ly261666', split='train', cache_dir=cache_dir, download_mode=DownloadMode.FORCE_REDOWNLOAD)
print(next(iter(train_set)))

# Download validation set
val_set = MsDataset.load('3rd_Anti-UAV', namespace='ly261666', split='validation', cache_dir=cache_dir, download_mode=DownloadMode.FORCE_REDOWNLOAD)
print(next(iter(val_set)))

Because I git clone this project CVPR_Anti_UAV under the CVPR_Anti_UAV path, which provides a folder named modelscope, as shown in the following figure

![image](https://github.com/user-attachments/assets/0994d852-8a62-4d89-8c8f-fdf467f34a68)

When I run the python code that loads the dataset file, it seems to run based on the many files provided in the modelscope folder, which causes it to report an error.


However, it is worth mentioning that I tried to load the data set in a blank environment (there is no modelscope folder), only loaded the library pip install modelscope[framework] in advance, and then ran the above data set download, which can run normally. So I think my modelscope folder and its many files are causing the error, but I don't know how to deal with it, the dumbest thing to do is load it somewhere else and then upload it, but I hope to solve this problem once and for all.

**Comment by yingdachen** [comment]
looks like you are using a forked version of modelscope source code. unfortunately we are not sure what changes are made in a forked version.  

from your description " pip install modelscope[framework] in advance, and then ran the above data set download, which can run normally". things seem to behave normally as expected...

the sample code on https://www.modelscope.cn/datasets/ly261666/3rd_Anti-UAV/ also seems to work fine in an environment where modelsope is installd:

https://modelscope.cn/notebook/share/ipynb/ed63c6da/anti-uav-dataset-loading.ipynb

**Comment by havinggood** [comment]
> 看起来您使用的是 ModelScope 源代码的分叉版本。不幸的是，我们不确定 fork 版本中进行了哪些更改。
> 
> 从你的描述中 “pip 提前安装 ModelScope[framework]，然后运行上述数据集下载，可以正常运行”。一切似乎都如预期的那样正常......
> 
> https://www.modelscope.cn/datasets/ly261666/3rd_Anti-UAV/ 上的示例代码在安装了 ModelsOpe 的环境中似乎也能正常工作：
> 
> https://modelscope.cn/notebook/share/ipynb/ed63c6da/anti-uav-dataset-loading.ipynb

thanks, i'll use it that way

**Comment by yu1yu1yu** [comment]
maybe update your modelscope is useful
