### ISSUE TITLE
gr.Video() cannot work on studios

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#1074]
If using filepath, the studio can go online without error, but the video cannot display, like below:
![image](https://github.com/user-attachments/assets/6592026e-1e44-4ac6-9545-dab3cd96d39f)

If using url, the studio cannot go online by runtime error (ssl error, even if I upload video onto modelscope hostname, it still reports www.modelscope.com did not pass the ssl security check 🤣)

Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh @tastelikefeet @wangxingjun778

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by LiJiayi96** [comment]
We will resolve the SSL error next week. In the meantime, you might try using the image of version ModelScope 1.17.1, which typically does not encounter SSL errors.

The 'video cannot display' issue is related to the sensitive content check, which may take anywhere from a few seconds to several minutes, particularly for longer videos.

**Comment by monetjoe** [comment]
> We will resolve the SSL error next week. In the meantime, you might try using the image of version ModelScope 1.17.1, which typically does not encounter SSL errors.
> 
> The 'video cannot display' issue is related to the sensitive content check, which may take anywhere from a few seconds to several minutes, particularly for longer videos.

No SSL error does not mean the gr.Video can work well:
![image](https://github.com/user-attachments/assets/6e4f9413-eb17-4638-bfcb-987eead66a38)
