### ISSUE TITLE
请问支持异步吗？

### ISSUE THREAD

**Issue by cgq0816** [modelscope/modelscope#1086]
例如：
import asyncio

async def hello():
    print("Hello world!")
    # 异步调用asyncio.sleep(1):
    await asyncio.sleep(1)
    print("Hello again!")

asyncio.run(hello())
如果支持，该如何使用呢

**Comment by yingdachen** [comment]
支持什么异步

**Comment by cgq0816** [comment]
> 支持什么异步

例如：
>>> import cv2
>>> from modelscope.pipelines import pipeline

>>> portrait_matting = pipeline('portrait-matting')
>>> result = portrait_matting('https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/image_matting.png')
>>> cv2.imwrite('result.png', result['output_img'])

readme里的推理都是同步，是否支持异步推理
