### ISSUE TITLE
pip and docker urls outside mainland china

### ISSUE THREAD

**Issue by fengwang** [modelscope/modelscope#11]
I noticed it is nearly impossible to retrieve the pip pakckages (https://github.com/modelscope/modelscope/blob/master/docker/rcfiles/pip.conf.tsinghua) and the docker images
(https://github.com/modelscope/modelscope/blob/master/docker/Dockerfile.ubuntu#L1) outside China.

For example, I cannot download `easyasr>=0.0.2` from tsinghua pip source, but I cannot find it elsewhere.

Can you please provide yet another docker file for the users living overseas?

**Comment by yingdachen** [comment]
we are in the process of internationalizing modelscope, and provide more accesbility for users beyond mainland china. 

we host some of the package in our cloud stroage (oss bucket), for installation, you may install all modlescope dependency with pip -f option, such as

pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

for more details, plesae refer to our documetation

https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85

thanks.
