### ISSUE TITLE
Will ms platform automatically switch lang between CN/EN based on the visitor's IP?

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#1103]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by monetjoe** [comment]
> no. it will detect your browser's language setting and follow that.

So, if broswer's setting is Non-Chinese, it shows English, elsewhere CN?

**Comment by yingdachen** [comment]
> > no. it will detect your browser's language setting and follow that.
> 
> So, if broswer's setting is Non-Chinese, it shows English, elsewhere CN?

yes. that is the idea.

**Comment by monetjoe** [comment]
Fine. I think this makes sense. I guess this is the logic for the first visit, once you changed the lang manually, next it would switch by cookie.

**Comment by yingdachen** [comment]
> > > > no. it will detect your browser's language setting and follow that.
> > > 
> > > 
> > > So, if broswer's setting is Non-Chinese, it shows English, elsewhere CN?
> > 
> > 
> > yes. that is the idea.
> 
> Fine. I think this makes sense. I guess this is the logic for the first visit, once you changed the lang manually, next it would switch by cookie.

and you can always switching between cn/en by toggling the cn/en switch on top-right corner
