### ISSUE TITLE
GPT3-2.7B多卡训练，保存模型失败

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#111]
您好，在用GPT3-2.7B训练，使用4张卡，tensor 并行4，保存后失败了。
在预测时，用单张卡load的话，报错参数量是原来的1/4

        size mismatch for language_model.encoder.layers.28.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([2560, 2560]) from checkpoint, the shape in current model is torch.Size([2560, 10240]).
        size mismatch for language_model.encoder.layers.29.self_attention.query_key_value.weight: copying a param with shape torch.Size([1920, 2560]) from checkpoint, the shape in current model is torch.Size([7680, 2560]).
        size mismatch for language_model.encoder.layers.29.self_attention.query_key_value.bias: copying a param with shape torch.Size([1920]) from checkpoint, the shape in current model is torch.Size([7680]).
        size mismatch for language_model.encoder.layers.29.self_attention.dense.weight: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([2560, 2560]).
        size mismatch for language_model.encoder.layers.29.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([2560, 2560]) from checkpoint, the shape in current model is torch.Size([10240, 2560]).
        size mismatch for language_model.encoder.layers.29.mlp.dense_h_to_4h.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([10240]).
        size mismatch for language_model.encoder.layers.29.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([2560, 2560]) from checkpoint, the shape in current model is torch.Size([2560, 10240]).

**Comment by Firmament-cyou** [comment]
> 您好，在用GPT3-2.7B训练，使用4张卡，tensor 并行4，保存后失败了。 在预测时，用单张卡load的话，报错参数量是原来的1/4
> 
> ```
>     size mismatch for language_model.encoder.layers.28.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([2560, 2560]) from checkpoint, the shape in current model is torch.Size([2560, 10240]).
>     size mismatch for language_model.encoder.layers.29.self_attention.query_key_value.weight: copying a param with shape torch.Size([1920, 2560]) from checkpoint, the shape in current model is torch.Size([7680, 2560]).
>     size mismatch for language_model.encoder.layers.29.self_attention.query_key_value.bias: copying a param with shape torch.Size([1920]) from checkpoint, the shape in current model is torch.Size([7680]).
>     size mismatch for language_model.encoder.layers.29.self_attention.dense.weight: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([2560, 2560]).
>     size mismatch for language_model.encoder.layers.29.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([2560, 2560]) from checkpoint, the shape in current model is torch.Size([10240, 2560]).
>     size mismatch for language_model.encoder.layers.29.mlp.dense_h_to_4h.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([10240]).
>     size mismatch for language_model.encoder.layers.29.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([2560, 2560]) from checkpoint, the shape in current model is torch.Size([2560, 10240]).
> ```

您好，请问保存后失败是指保存模型的过程中出现报错了吗？

如果只是预测过程中 load 阶段的报错，这是一个新版本 1.3.0 中已经修复的已知 bug，新版本的保存过程会将 tensor 并行模型完整地保存下来以便后续加载使用

**Comment by David-Lee-1990** [comment]
哦哦，好的，我的确是安装的老版本1.2.0，我试下1.3.0

多谢啦
