### ISSUE TITLE
仓库目录显示系统挂了

### ISSUE THREAD

**Issue by kakamond** [modelscope/modelscope#1120]
获取模型目录树失败，信息：rpc error: code = DeadlineExceeded desc = context deadline exceeded
![image](https://github.com/user-attachments/assets/06249329-28fd-4baf-9706-d27c23d7e344)

Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh @tastelikefeet @wangxingjun778

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by yingdachen** [comment]
the platform was experiencing abnormal traffic, it is now recovered back to normal. please reopen the issue if the problem still persisit on your end.
