### ISSUE TITLE
更改头像后仅个人主页才能看到头像更改，左右上角用户信息的头像未更新(非未提交问题)

### ISSUE THREAD

**Issue by kakamond** [modelscope/modelscope#1128]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh @tastelikefeet @wangxingjun778

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by justmywyw** [comment]
你好，目前个人设置页滚动到下方保存账号设置才会 修改生效，可以先试着操作下哈～
<img width="780" alt="image" src="https://github.com/user-attachments/assets/c7106f1b-0865-4346-b976-f27c475e8906">

我们也后续优化下这里的交互，目前确实有歧义会导致未注意保存。

**Comment by kakamond** [comment]
> 你好，目前个人设置页滚动到下方保存账号设置才会 修改生效，可以先试着操作下哈～ <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/7821375/392647532-c7106f1b-0865-4346-b976-f27c475e8906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzE0MTAsIm5iZiI6MTczMzM3MTExMCwicGF0aCI6Ii83ODIxMzc1LzM5MjY0NzUzMi1jNzEwNmYxYi0wODY1LTQzNDYtYjk3Ni1mMjdjNDc1ZTg5MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDM1ODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDViNGYwMTlmM2YwODJjYjhmYTA4MWExMzE5MjZlYzMxNjk5NDU4ZmJjNWU4YmM3M2E3YWM2OTI1ZmIwODJmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.H3UdmXZCFoxN2WeKFVo0b5Bf_DBHGARssDm17ehgWxs">
> 
> 我们也后续优化下这里的交互，目前确实有歧义会导致未注意保存。

点了，并且见 #1129

**Comment by kakamond** [comment]
> 你好，目前个人设置页滚动到下方保存账号设置才会 修改生效，可以先试着操作下哈～ <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/7821375/392647532-c7106f1b-0865-4346-b976-f27c475e8906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzE4NzcsIm5iZiI6MTczMzM3MTU3NywicGF0aCI6Ii83ODIxMzc1LzM5MjY0NzUzMi1jNzEwNmYxYi0wODY1LTQzNDYtYjk3Ni1mMjdjNDc1ZTg5MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDQwNjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVhZmUwZDg1MzdmMDY2YTQ5NzQwZWYwNzVlNTNmMTQ3YTRjZDZmMjI5OWNkMDA3ZjZkODk2YzI4NmQzNGJmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tD83qP8RwqSEgrsX1Hd2vVwBHV_xFYcN7zA-DEfdjX8">
> 
> 我们也后续优化下这里的交互，目前确实有歧义会导致未注意保存。

歧义是另一个问题，也需要优化，建议放在一起修复吧

**Comment by kakamond** [comment]
> 你好，目前个人设置页滚动到下方保存账号设置才会 修改生效，可以先试着操作下哈～ <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/7821375/392647532-c7106f1b-0865-4346-b976-f27c475e8906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDk1NjQsIm5iZiI6MTczMzQwOTI2NCwicGF0aCI6Ii83ODIxMzc1LzM5MjY0NzUzMi1jNzEwNmYxYi0wODY1LTQzNDYtYjk3Ni1mMjdjNDc1ZTg5MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMTQzNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVlYjdjYTVmOGU0YzlmODg1ODA3MTUwOTFmYWI2ZmI0MjQ4Y2RhNjNkYWFhYTgwZTZjMjdlMzcxOGU4ZWVlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7Xndn8jEo8V2N3mDxm2k0rQWQvozof_VAvc_uboRWuM">
> 
> 我们也后续优化下这里的交互，目前确实有歧义会导致未注意保存。

感谢贵团队的努力，目前经过检查头像显示BUG已修复，之后修改头像歧义问题修复后可关闭issue

**Comment by yingdachen** [comment]
这不是别人的头像，是默认的头像（之一）。看起来是获取头像失败，所以用了默认的头像兜底了。获取失败的问题我们看一下。

**Comment by yingdachen** [comment]
> > 这不是别人的头像，是默认的头像（之一）。看起来是获取头像失败，所以用了默认的头像兜底了。获取失败的问题我们看一下。
> 
> 之前修好过，这次更新后又犯老毛病了

在用户未提供邮箱的情况下，有概率触发头像保存/获取的bug，已经修复。请再观察一下。
