### ISSUE TITLE
Convert the website content into English and address bot blocking issues with NotebookLM and major crawling systems.

### ISSUE THREAD

**Issue by Ayaan-Sharif** [modelscope/modelscope#1137]
Describe the feature
The feature involves translating the website into English for better accessibility and addressing bot-blocking mechanisms that prevent tools like NotebookLM and a "major rag system" from functioning effectively.

Motivation

It is inconvenient when users cannot access the website in English, as it limits usability for non-native speakers.
NotebookLM and other tools are blocked by the bot detection system, which affects automated workflows.
There is a crawling system that struggles to interact with the website due to existing restrictions, impacting data extraction tasks.
Related resources

Website translation APIs: Google Translate API, AWS Translate.
Articles on bot detection and crawling system management.
Tools for controlled crawling: Puppeteer, Scrapy, or Selenium.
Additional context
Handling these issues will improve the accessibility and usability of the website for global users, especially for projects involving automated data extraction and analysis. If needed, I can contribute by proposing a detailed implementation plan and submitting a PR.

**Comment by yingdachen** [comment]
is this a dup of #1136?

**Comment by Ayaan-Sharif** [comment]
> is this a dup of #1136?

sorry 

i may havenetwork lag
