### ISSUE TITLE
收藏个人非公开仓库会暴露动态给关注者

### ISSUE THREAD

**Issue by ghost** [modelscope/modelscope#1138]
隐私保护严重漏洞

Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh @tastelikefeet @wangxingjun778

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by yingdachen** [comment]
非公开仓库的动态，只会同步给有该仓库访问权限的关注者。如果发现非符合该设计的行为，请提供具体的仓库id，以及非预期看到该仓库动态的用户id

**Comment by yingdachen** [comment]
> > 非公开仓库的动态，只会同步给有该仓库访问权限的关注者。如果发现非符合该设计的行为，请提供具体的仓库id，以及非预期看到该仓库动态的用户id
> 
> 通病，不是具体哪个用户或仓库的问题，另外为保护用户隐私，还请自上而下排查
we tested and did not find this to be a general problem. please provide specific repo id and user id if you find anything that does not comply with our intended design. 

if you feel there is privacy concern, you can create dedicate mock repo for testing.

**Comment by yingdachen** [comment]
> > > > 非公开仓库的动态，只会同步给有该仓库访问权限的关注者。如果发现非符合该设计的行为，请提供具体的仓库id，以及非预期看到该仓库动态的用户id
> > > 
> > > 
> > > 通病，不是具体哪个用户或仓库的问题，另外为保护用户隐私，还请自上而下排查
> > 
> > 
> > we tested and did not find this to be a general problem. please provide specific repo id and user id if you find anything that does not comply with our intended design.
> > if you feel there is privacy concern, you can create dedicate mock repo for testing.
> 
> 。。。刚刚数据集模型创空间每个都完全重建了一个新的仓库点收藏测试了下，又复现不了了。。。是偷偷改好了？

we did not make any release on this today. the update notification will take an hour or so to push to followers anyway, you can wait a bit to see.

**Comment by yingdachen** [comment]
收藏信息推送的问题已经解决。请再观察一下。
