### ISSUE TITLE
urlparse被滥用导致无法解析标准 Windows 本地文件路径

### ISSUE THREAD

**Issue by ALEX000V** [modelscope/modelscope#1149]
### **问题描述**
在至少 12 个脚本中，`urlparse` 被用于解析所有情况的文件路径。然而，对于本地文件路径，仅处理了标准文件 URL（例如 `file:///D:/data/`），而标准 Windows 文件路径（例如 `D:\data\`） ~~和标准 Linux 文件路径（例如 `/mnt/d/data/`）~~ 无法被正确识别。这会导致文件路径被错误地判断为网络 URL，进而反复尝试网络请求，直至报错。

---

### **复现步骤**
1. 在 `modelscope/preprocessors/video.py` 中，找到 `ReadVideoData` 函数。
2. 使用以下代码片段：
   ```python
   url_parsed = urlparse(video_path)
   if url_parsed.scheme in ('file', '') and exists(url_parsed.path):  # Possibly a local file
       data = _decode_video(cfg, video_path, num_temporal_views_override)
   else:
       with TemporaryDirectory() as temporary_cache_dir:
           random_str = uuid.uuid4().hex
           http_get_file(
               url=video_path,
               local_dir=temporary_cache_dir,
               file_name=random_str,
               cookies=None)
           temp_file_path = os.path.join(temporary_cache_dir, random_str)
           data = _decode_video(cfg, temp_file_path, num_temporal_views_override)
   ```
3. 设置 `video_path` 为标准 Windows 文件路径（例如 `D:\data\video.mp4`） ~~或标准 Linux 文件路径（例如 `/mnt/d/data/video.mp4`）~~ 。
4. 运行代码，观察到文件路径被错误地判断为网络 URL，并尝试进行网络请求，最终导致报错。

---

### **预期行为**
- 对于标准本地文件路径（例如 `D:\data\video.mp4`  ~~或 `/mnt/d/data/video.mp4`~~ ），代码应直接判断文件是否存在，并调用 `_decode_video` 进行处理。
- 仅当文件路径无法通过 `os.path.exists` 判断时，才尝试使用 `urlparse` 解析 URL。

---

### **实际行为**
- 代码仅处理了标准文件 URL（例如 `file:///D:/data/video.mp4`），而忽略了标准 Windows 文件路径 ~~和标准 Linux 文件路径~~ 。
- 对于标准 Windows 文件路径，代码会错误地判断为网络 URL，并尝试进行网络请求，最终导致报错。

---

### **建议的解决方案**
更合理的方法是直接使用 `os.path.exists` 判断文件是否存在，如果判断失败再进入 URL 解析。例如：

```python
import os.path as osp

url_parsed = urlparse(video_path)
if osp.exists(video_path):  # 优先检查本地文件是否存在
    data = _decode_video(cfg, video_path, num_temporal_views_override)
elif url_parsed.scheme in ('file', '') and exists(url_parsed.path):  # 处理标准文件 URL
    data = _decode_video(cfg, video_path, num_temporal_views_override)
else:  # 处理远程 URL
    with TemporaryDirectory() as temporary_cache_dir:
        random_str = uuid.uuid4().hex
        http_get_file(
            url=video_path,
            local_dir=temporary_cache_dir,
            file_name=random_str,
            cookies=None)
        temp_file_path = os.path.join(temporary_cache_dir, random_str)
        data = _decode_video(cfg, temp_file_path, num_temporal_views_override)
```

---

### **环境信息**
- **ModelScope**：1.21.0

**Comment by yingdachen** [comment]
<img width="861" alt="image" src="https://github.com/user-attachments/assets/da559956-4fcc-48e6-b17c-bb7ae7d16421" />
测试效果如上，可见对于linux/mac的路径，以及file:/// 路径能正常处理，对于windows的原生路径确实处理的不完美。但这些逻辑大部分是模型贡献者在linux上测试通过，如果windows上使用，建议还是使用file:/// 路径。
