### ISSUE TITLE
NER 任务的批量推理没起作用

### ISSUE THREAD

**Issue by xiabingbao-ok** [modelscope/modelscope#116]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline('named-entity-recognition', 'damo/nlp_raner_named-entity-recognition_chinese-base-ecom')
res = p(['欧美单 秋季女装时尚百搭休闲修身 亚麻混纺短款 外套西装', '亚麻混纺短款 外套西装'], batch_size=2)
print(res)
 当输入列表有100多万行，我设置batch_size=32。预测结果迟迟没有，是不是batch没有起作用？

**Comment by wenmengzhou** [comment]
预测结果迟迟没有，是指运行程序一直没有输出？   怀疑是在加载输入列表上，可以用pystack-debugger查看下程序运行在什么代码上
