### ISSUE TITLE
无法下载数据集

### ISSUE THREAD

**Issue by Slipstream-Max** [modelscope/modelscope#1161]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs) [yes]
* I have searched related issues but cannot get the expected help. [yes]
* The bug has not been fixed in the latest version. [yes]

**Describe the bug**
在服务器使用modelscope下载数据集。无法下载数据集，进度条进度为0，若干重试之后退出下载。
之后在本地电脑重试同样操作发现依然无法下载。
服务器：[linux]
![image](https://github.com/user-attachments/assets/b518cf5d-26d3-4b9f-bf88-61ec08a457ab)

本地电脑：[win]
![image](https://github.com/user-attachments/assets/e8329a23-86ac-49ee-82e4-036ac0fd30e0)

**To Reproduce**
* What command or script did you run?
* 下面所有的命令都不能让我下载到数据集数据。无论是更换数据集，还是少输入参数，都无法下载。
```bash
modelscope download --dataset AI-ModelScope/MMMLU --local_dir AI-ModelScope/MMMLU
modelscope download --dataset AI-ModelScope/MMMLU
modelscope download --dataset BAAI/IndustryCorpus2 --local_dir BAAI/IndustryCorpus2
```
* What dataset did you use?
* 这个是我要下载的数据集
BAAI/IndustryCorpus2

**Your Environments (__required__)**
* OS: `windows11`
* CPU: `i5 13600kf`
* You may add addition that may be helpful for locating the problem, such as
* 纯净conda环境 只安装了modelscope
* conda create -n down python=3.11
* pip install modelscope[datasets]

Dataset releated: @wangxingjun778

**Comment by yingdachen** [comment]
thanks for reporting. we are looking into this issue.

**Comment by yingdachen** [comment]
@Slipstream-Max this was a regression bug introduced in version 1.21.0, it has been use in the latest master code.

for now please use either the previous version of 1.20.1 `pip install modelscope==1.20.1`, or install from the source code. we will release a hot fix soon.

sorry for the inconvenience.

**Comment by Slipstream-Max** [comment]
thanks you guy are the best😃



---原始邮件---
发件人: "Yingda ***@***.***&gt;
发送时间: 2024年12月29日(周日) 晚上9:08
收件人: ***@***.***&gt;;
抄送: "gu ***@***.******@***.***&gt;;
主题: Re: [modelscope/modelscope] 无法下载数据集 (Issue #1161)




 
@Slipstream-Max this was a regression bug introduced in version 1.21.0, it has been use in the latest master code.
 
for now please use either the previous version of 1.20.1 pip install modelscope==1.20.1, or install from the source code. we will release a hot fix soon.
 
sorry for the inconvenience.

**Comment by wangxingjun778** [comment]
Fixed, please reinstall the modelscope: 

pip install modelscope==1.21.1

**Comment by Slipstream-Max** [comment]
yes!!just now i kept refreshing pypi site. then saw this fix thanks again.And finally it works.
