### ISSUE TITLE
如何设置shuffle训练数据？

### ISSUE THREAD

**Issue by chasonlee** [modelscope/modelscope#121]
根据观察，官方训练例程没有shuffle训练数据，因为我的数据中有部分是易学习样本，loss下降很明显，我将易学习样本放在训练数据前面，loss会先下降很低，然后上升，每个epoch都如此；若我将易学习样本放在训练数据中间，loss会大概在每个epoch的中间部分下降很多，之后再上升，可见训练数据没有shuffle。
查看源码后，试着增加一个shuffle参数，但没有起到shuffle作用：
```
cfg.train.dataloader = {
    "batch_size_per_gpu": 10,
    "workers_per_gpu": 1,
    "shuffle": True
}
```
请问shuffle的正确方式是怎样的？
PS: 测试版本v1.3.0

**Comment by wenmengzhou** [comment]
你可以参考 #122 的示例代码修改先跑起来，相关修复会在近期发布的版本中发布

**Comment by chasonlee** [comment]
好的，感谢，提醒我了，这个确实是单GPU才有的问题
