### ISSUE TITLE
How to read the Uni-Fold dataset?

### ISSUE THREAD

**Issue by shawn-hsyu** [modelscope/modelscope#127]
Thank you for providing an excellent library. 
I successfully download the Uni-Fold dataset and I have a question about the dataset.
After downloading and extracting the dataset, the extracted file names are like "134ffc6f87b3bcf6c8b2a048aeec7dd2ec4b18f4fc015c024e16077f7231fc83". 
How can I read these kinds of files? The example file in the original Uni-Fold dataset is a pickle file but the files I download through modelscope seem very different.

**Comment by wangxingjun778** [comment]
The name like "134ffc6f87b3bcf6c8b2a048aeec7dd2ec4b18f4fc015c024e16077f7231fc83" is a hash value for this file, to read the dataset from cache, please refer to readme: https://modelscope.cn/datasets/DPTech/Uni-Fold-Data/summary

**Comment by shawn-hsyu** [comment]
It works very well! Thanks :)
