### ISSUE TITLE
"damo/nlp_gpt3_text-generation_1.3B" inference error

### ISSUE THREAD

**Issue by zongking123** [modelscope/modelscope#130]
-----inference code:

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
import torch
if __name__ == '__main__':
   
    input = '程序员脱发用什么洗发水'
    model_id = 'damo/nlp_gpt3_text-generation_1.3B'
    pipe = pipeline(Tasks.text_generation, model=model_id)

    print(pipe(input))

------error info:
RuntimeError: Failed to import modelscope.models.nlp.gpt3.distributed_gpt3 because of the following error (look up to see its traceback):
Error building extension 'fused_mix_prec_layer_norm_cuda'

**Comment by David-Lee-1990** [comment]
是不是没有安装 megatron_utils

**Comment by zongking123** [comment]
安装完megatron_utils，然后报错 Megatron util requires CUDA

**Comment by yingdachen** [comment]
模型需要使用gpu
