### ISSUE TITLE
POI模型使用问题

### ISSUE THREAD

**Issue by chinesejunzai12** [modelscope/modelscope#131]
task = Tasks.text_ranking
model = 'damo/mgeo_geographic_textual_similarity_rerank_chinese_base'
# 模型可接受单模态输入
pipeline_ins = pipeline(task=task, model=model)
print(pipeline_ins(input=single_modal_inputs))
按照官方文档, 在加载模型的时候报错, 信息如下:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/103180175/220314452-5ca83719-f4d3-4221-b7c9-0d8dbb49c76a.png">
希望可以得到解答, 谢谢

**Comment by yingdachen** [comment]
用户群里已经解答，更新modelscope版本到最新即可。
