### ISSUE TITLE
GPT3 跑官方给的代码 一直卡在> compiling and loading fused kernels ...

### ISSUE THREAD

**Issue by weizhenzhao** [modelscope/modelscope#134]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/13706689/220845726-b97f7a86-6b14-47e3-9b32-3f1839d4c54d.png">
GPT3 跑官方给的代码 一直卡在> compiling and loading fused kernels ... 没有反应
看阿里云上面说是因为 编译的时候有锁冲突了？
能不能告诉应该删除哪个临时文件夹？
具体应该怎么解决呀？
一直加载不了
感激不尽。

**Comment by weizhenzhao** [comment]
`from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

if __name__ == '__main__':
    input = '程序员脱发用什么洗发水'
    model_id = 'nlp_gpt3_text-generation_2.7B'
    pipe = pipeline(Tasks.text_generation, model=model_id)

    print(pipe(input))`

**Comment by chenchun0629** [comment]
仅用参考：`path_to_dist-packages/megatron_util/fused_kernels/build/build.ninja`

```
> compiling and loading fused kernels ...
Detected CUDA files, patching ldflags
Emitting ninja build file /usr/local/lib/python3.8/dist-packages/megatron_util/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
```

**Comment by daoboke** [comment]
rm fused_kernels/build/lock

**Comment by dune-p** [comment]
> rm fused_kernels/build/lock

it works! thanks!
