### ISSUE TITLE
Fail to run example code of PAI/nlp_gpt3_text-generation_0.35B_MoE-64

### ISSUE THREAD

**Issue by zyeric** [modelscope/modelscope#136]
Throw error: modelscope.hub.errors.NoValidRevisionError: The model: PAI/nlp_gpt3_text-generation_0.35B_MoE-64 has no valid revision!.

The code is copied from [modelscope](https://www.modelscope.cn/models/PAI/nlp_gpt3_text-generation_0.35B_MoE-64/summary).

**Comment by yingdachen** [comment]
can you check what is your version of modelscope library?

**Comment by zyeric** [comment]
Thanks for reply.

```bash
import modelscope
print(modelscope.__version)
```

The result is *1.3.0*.

**Comment by JingliangGao** [comment]
Hi,
   I have solved this question that " The model: * has no valid revision!" by reinstall modelscope package. I believe that something in modelscope we have install  is too old to be suitable for the new case we test. Have fun : )
