### ISSUE TITLE
异常图像检测的label输出和readme中给的不匹配

### ISSUE THREAD

**Issue by whalefa1I** [modelscope/modelscope#139]
[异常图像检测](https://www.modelscope.cn/models/damo/cv_mobilenet-v2_bad-image-detecting/summary)中写的`输出图像检测类型，包含[花屏， 绿屏， 黑屏， 正常]`但模型输出只有三个类别

**Comment by charlesMrH** [comment]
README.md中未及时更新不及时, 当前版本不支持黑屏检测，请知悉。现已更新README.md。

**Comment by charlesMrH** [comment]
> [异常图像检测](https://www.modelscope.cn/models/damo/cv_mobilenet-v2_bad-image-detecting/summary)中写的`输出图像检测类型，包含[花屏， 绿屏， 黑屏， 正常]`但模型输出只有三个类别
README.md中未及时更新不及时, 当前版本不支持黑屏检测，请知悉。现已更新README.md。
