### ISSUE TITLE
in 1.3.0 Version, ROM语义相关性 model predict results is random

### ISSUE THREAD

**Issue by alphanlp** [modelscope/modelscope#140]
in 1.3.0 Version, ROM语义相关性 model predict results is random

**Comment by alphanlp** [comment]
bert.embeddings.word_embeddings.weight: found shape torch.Size([21128, 768]) in the checkpoint and torch.Size([30522, 768]) in the model instantiated

**Comment by afalf** [comment]
您好，请问一下具体是哪个模型呢？ROM语义相关性模型的基础底座是达摩院(structbert)[https://modelscope.cn/models/damo/nlp_structbert_backbone_base_std/summary], 并不是原版的BERT，两者的词表存在一定差异。

**Comment by afalf** [comment]
已解决
