### ISSUE TITLE
PLUG-27B 二次训练报错

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#142]
![image](https://user-images.githubusercontent.com/29653610/221498259-fbfc0478-b865-43b2-aa70-bfcc0da5f68b.png)

您好，在使用PLUG-27B训练的时候，使用deepspeed 启动，多卡貌似起不起来，总是报错端口占用，但是换了很多端口都不行。

请问如何解决呢？

**Comment by Firmament-cyou** [comment]
> ![image](https://user-images.githubusercontent.com/29653610/221498259-fbfc0478-b865-43b2-aa70-bfcc0da5f68b.png)
> 
> 您好，在使用PLUG-27B训练的时候，使用deepspeed 启动，多卡貌似起不起来，总是报错端口占用，但是换了很多端口都不行。
> 
> 请问如何解决呢？

您好，您可以参考 plug 大模型训练的最佳实践运行训练：https://modelscope.cn/docs/NLG%E5%A4%A7%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8%E4%BB%8B%E7%BB%8D#%E8%AE%AD%E7%BB%83

我测试基于 1.3.0 版本使用 deepspeed --num_gpus=8 --num_nodes=1 finetune_plug.py 拉起训练，训练可以正常运行，不会出现端口占用的报错～

**Comment by David-Lee-1990** [comment]
哦哦，好的，我照您的做法试下，谢啦

**Comment by David-Lee-1990** [comment]
您好，按照严格的流程，的确跑起来了。感谢～

有个问题，为什么只能用8张卡？不能用4张卡呢？看模型的配置文件configuration.json里面，即便把 world_size=4，也跑不起来。。

**Comment by David-Lee-1990** [comment]
您好，我试了下，8卡的确可以跑起来，但是如果是4卡的话，就跑不起来。请问，是哪里设定的必须用8张卡呢？

**Comment by tastelikefeet** [comment]
您好，我试了下，8卡的确可以跑起来，但是如果是4卡的话，就跑不起来。请问，是哪里设定的必须用8张卡呢？
---
目前plug的checkpoint是8 sharding的，在代码中也是一对一加载和存储的，因此设定为其他的数量目前并不支持，后续我们会把大模型使用任意卡数训练的feature加入开发中

plug的推理可以查看ModelCard中的示例：https://www.modelscope.cn/models/damo/nlp_plug_question-generation_27B/summary
