### ISSUE TITLE
大模型使用介绍：大模型finetune最佳实践---链接失效

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#143]
https://modelscope.cn/models/damo/nlp_plug_text-generation_27B/summary
以上链接中对应的如下图所示的链接失效了：
<img width="838" alt="image" src="https://user-images.githubusercontent.com/29653610/221512589-de686a4b-e639-4a66-91b2-b11fdabb1be7.png">

以下链接失效：
https://pre.modelscope.cn/docs/NLG%E5%A4%A7%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8%E4%BB%8B%E7%BB%8D

**Comment by zzclynn** [comment]
https://www.modelscope.cn/docs/NLG%E5%A4%A7%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8%E4%BB%8B%E7%BB%8D
用上面这个，我后续再检查一下链接。

**Comment by David-Lee-1990** [comment]
好的，多谢
