### ISSUE TITLE
找不到cv_controlnet_controllable-image-generation_all

### ISSUE THREAD

**Issue by yanchaoguo** [modelscope/modelscope#144]
官网给的controlnet例子
Tasks 下面没有 cv_controlnet_controllable-image-generation_all

**Comment by yingdachen** [comment]
模型代码还未在Library发布版本中完成即成，预期本周会提供对应版本升级。

**Comment by yanchaoguo** [comment]
> 模型代码还未在Library发布版本中完成即成，预期本周会提供对应版本升级。

能支持中文吗

**Comment by zzclynn** [comment]
现在还不支持中文





来自钉钉专属商务邮箱------------------------------------------------------------------
***@***.***>
日　期：2023年02月28日 09:24:04
***@***.***>
***@***.***>
主　题：Re: [modelscope/modelscope] 找不到cv_controlnet_controllable-image-generation_all (Issue #144)


模型代码还未在Library发布版本中完成即成，预期本周会提供对应版本升级。 
能支持中文吗

**Comment by yanchaoguo** [comment]
> 现在还不支持中文 来自钉钉专属商务邮箱------------------------------------------------------------------ ***@***.***> 日　期：2023年02月28日 09:24:04 ***@***.***> ***@***.***> 主　题：Re: [modelscope/modelscope] 找不到cv_controlnet_controllable-image-generation_all (Issue #144) 模型代码还未在Library发布版本中完成即成，预期本周会提供对应版本升级。 能支持中文吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


> 模型代码还未在Library发布版本中完成即成，预期本周会提供对应版本升级。

@yingdachen 怎么3月1号没发布版本
