### ISSUE TITLE
megatron_util如何下载whl文件

### ISSUE THREAD

**Issue by felixstander** [modelscope/modelscope#146]
由于内网的限制，无法使用pip install megatron_util -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html联网下载megatron util，点击链接会自动跳转下载网页，官方文档也没有找到相应的whl下载方式，请问得如何才能下载到megatron_util的whl文件？

**Comment by felixstander** [comment]
已解决

**Comment by Lotayou** [comment]
@felixstander 您好，求问是如何解决的呢

**Comment by lrs1353281004** [comment]
根据html文件查找对应的路径: https://modelscope.oss-cn-beijing.aliyuncs.com/releases/dependencies/megatron_util-1.3.2-py3-none-any.whl
