### ISSUE TITLE
megatron库的安装问题

### ISSUE THREAD

**Issue by LTEnjoy** [modelscope/modelscope#15]
您好！
我按照官方的教程进行环境安装，但是megatron库的版本始终不对，报错如下：
ImportError: cannot import name 'get_global_memory_buffer' from 'megatron.global_vars' (/opt/anaconda3/envs/modelscope/lib/python3.7/site-packages/megatron/global_vars.py)
请问你们的megatron版本是多少？或者能否直接提供安装的链接？

**Comment by yingdachen** [comment]
which model are you trying to load?

**Comment by LTEnjoy** [comment]
gpt3

**Comment by yingdachen** [comment]
currently there are some specical requirements for larger gpt3 models, plesae refer to instrcution on model card, such as 

https://www.modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary

============================
依赖安装
要使用中文GPT3进行推理，需要额外安装DeepSpeed依赖，推荐使用0.7.2版本。另外，我们将GPT3模型依赖的megatron相关代码打包到了单独的包中，以上两个包通过以下命令进行安装：

`pip install deepspeed==0.7.2
pip install megatron_util -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`

**Comment by LTEnjoy** [comment]
感谢回复，我去尝试一下！

**Comment by yingdachen** [comment]
clse as resolved
