### ISSUE TITLE
speech_dfsmn_kws_char_farfield

### ISSUE THREAD

**Issue by Sundy1219** [modelscope/modelscope#151]
你们好，我关注了你们的kws远场项目，我看了你们的说明，你们用的是交叉熵作为loss. 对正样本唤醒词做了对齐，负样本不做对齐，标签用的是char，比如＂小爱同学",　网络输出是0 , 1, 2, 3, 4这五个节点，0代表filler，其它四个代表"小爱同学".  对于一段长音频wav, 你们是怎么计算唤醒词的置信度的? 我在你们的工程里没找到测试的decode部分，麻烦可以指点一下，谢谢

**Comment by bincard** [comment]
你好，感谢关注。声学模型输出后面是有解码器的，不过目前解码器是用C代码实现的，打包在python库py_sound_connect里，安装modelscope时会作为依赖安装。
这个项目采用的解码器是一种自适应HMM结构，一方面用于对网络的输出做平滑，另外还利用了Viterbi算法做了解码，把网络[0, 1]之间的输出转化为了最优状态序列。比如“小爱同学”，所看到的最优状态序列就类似于0001112233344440这种，根据这个序列可以判断是否出现了疑似唤醒词。最后再根据平滑后的概率和最优状态序列就可以计算置信度了。关于解码器和置信度更加详细的算法介绍可以参考这篇文章：Joint Ego-Noise Suppression and Keyword Spotting on Sweeping Robots。
