### ISSUE TITLE
contains components that are licenced CC-NC and GPL-3.0, mismatch with top level Apache 2.0 license

### ISSUE THREAD

**Issue by MarkAtwood** [modelscope/modelscope#155]
Hi!

This repo contains components that have licenses that have obligations more restrictive than the Apache 2.0 license declared in the top level LICENSE file.  

CC-BY-NC-1.0+:
modelscope-1.3.0-py3-none-any.whl/modelscope/models/cv/salient_detection/models/backbone/Res2Net_v1b.py
modelscope-1.3.0.tar.gz/modelscope-1.3.0/modelscope/models/cv/salient_detection/models/backbone/Res2Net_v1b.py
modelscope-1.3.0.tar.gz/modelscope-1.3.0/modelscope/models/cv/salient_detection/models/backbone/init.py
modelscope-1.3.0-py3-none-any.whl/modelscope/models/cv/salient_detection/models/backbone/init.py

GPL-3.0:
modelscope-1.3.0-py3-none-any.whl/modelscope/models/cv/image_depth_estimation_bts/networks/bts_model.py
modelscope-1.3.0.tar.gz/modelscope-1.3.0/modelscope/models/cv/image_depth_estimation_bts/networks/bts_model.py
modelscope-1.3.0.tar.gz/modelscope-1.3.0/modelscope/models/cv/image_depth_estimation_bts/networks/decoder.py
modelscope-1.3.0-py3-none-any.whl/modelscope/models/cv/image_depth_estimation_bts/networks/decoder.py
modelscope-1.3.0.tar.gz/modelscope-1.3.0/modelscope/models/cv/image_depth_estimation_bts/networks/encoder.py
modelscope-1.3.0-py3-none-any.whl/modelscope/models/cv/image_depth_estimation_bts/networks/encoder.py
modelscope-1.3.0-py3-none-any.whl/modelscope/models/cv/image_depth_estimation_bts/networks/tools.py
modelscope-1.3.0.tar.gz/modelscope-1.3.0/modelscope/models/cv/image_depth_estimation_bts/networks/tools.py

**Comment by yingdachen** [comment]
thank you for brining this to our attension, we will check with model-contributor to rectify the issue
