### ISSUE TITLE
是否可以像Hugging Face一样，对各类核心函数的调用给予详细说明，比如GPT3模型各种参数如何设定，比如各类Hooks

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#157]
如题～～

**Comment by David-Lee-1990** [comment]
比如现在非常不清楚如何通过cfg来配置lr_scheduler，没有看到任何详细的文档说明，只有代码示例。

**Comment by wenmengzhou** [comment]
https://modelscope.cn/docs/Configuration%E8%AF%A6%E8%A7%A3#lr_scheduler

**Comment by David-Lee-1990** [comment]
嗯嗯，注意到了这个，但是这里面没有详细的参数说明，比如都可以配置哪些？这里只有 StepLR。如果想配置Linear，该怎么办

<img width="892" alt="image" src="https://user-images.githubusercontent.com/29653610/222664627-ce9890f5-dc3d-472d-8d79-8118cd750c87.png">

**Comment by tastelikefeet** [comment]
简单来说，您安装的torch版本下，所有的lrscheduler都可以使用：https://pytorch.org/docs/stable/optim.html

将类名填入type字段，其他需要调节的参数以key-value的形式直接平铺在下面，比如：
```python
{
    "train": {
        "lr_scheduler": {
            "type": "LinearLR",
            "start_factor": 1.0,
            "end_factor": 0.0,
            "total_iters": 100
        }
    }
}
```

**Comment by David-Lee-1990** [comment]
哦哦，好，也就是参照torch网站的参数就可以哈，谢谢。
