### ISSUE TITLE
controlnet 启动失败 且control_ldm 无法安装

### ISSUE THREAD

**Issue by yanchaoguo** [modelscope/modelscope#159]
缺失the control_ldm library
![image](https://user-images.githubusercontent.com/11827802/222632084-c2a45c70-fe7d-469f-ab74-7be2f5cd7ebb.png)
root@VM-20-28-ubuntu:/data# pip3 install control_ldm 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement control_ldm (from versions: none)
ERROR: No matching distribution found for control_ldm

**Comment by wenmengzhou** [comment]
pip install control_ldm -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by yanchaoguo** [comment]
> pip install control_ldm -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

下面又出现了缺失mmcv  这个我这边pip 也无法安装成功 麻烦看下呢 @wenmengzhou 
---> 20 from modelscope.preprocessors.cv.controllable_image_generation import \
     21     ControllableImageGenerationPreprocessor
     22 from modelscope.utils.constant import Frameworks, Invoke, ModelFile, Tasks
     23 from modelscope.utils.logger import get_logger

File /usr/local/lib/python3.8/dist-packages/modelscope/preprocessors/cv/controllable_image_generation.py:16
     13 from torchvision import transforms
     15 from modelscope.metainfo import Preprocessors
---> 16 from modelscope.models.cv.controllable_image_generation.annotator.annotator import (
     17     CannyDetector, HEDdetector, MidasDetector, MLSDdetector, OpenposeDetector,
     18     SegformerDetector, nms)
     19 from modelscope.preprocessors.base import Preprocessor
     20 from modelscope.preprocessors.builder import PREPROCESSORS

File /usr/local/lib/python3.8/dist-packages/modelscope/models/cv/controllable_image_generation/annotator/annotator.py:6
      3 import os
      5 import cv2
----> 6 import mmcv
      7 import numpy as np
      8 import torch

ModuleNotFoundError: No module named 'mmcv'

**Comment by wenmengzhou** [comment]
参考这里： https://github.com/open-mmlab/mmcv#installation
