### ISSUE TITLE
Trainer 不支持 iteration级别的 early stop

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#163]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/29653610/222701605-6dd3e678-6081-4094-8209-1f4faf11f9f9.png">

**Comment by tastelikefeet** [comment]
您好，可以看下：https://github.com/modelscope/modelscope/blob/master/modelscope/trainers/hooks/early_stop_hook.py 是否能满足需求，这个hook在evaluate metric不增长时进行early stop

**Comment by David-Lee-1990** [comment]
嗯嗯，这个是用来设定early stop的，不过由于Trainer代码中，if self._stop_training 只有在一个epoch运行结束之后，才会终止训练，因此，还是达不到在 iteration 级别进行early stop, 不知道我理解的对不对～

**Comment by tastelikefeet** [comment]
明白你的需求了，这个feature 1.4版本我们添加进去
