### ISSUE TITLE
vad并行报错

### ISSUE THREAD

**Issue by TongtongSong** [modelscope/modelscope#166]
linux
Python3.9
modelscope1.3.0 FUNASR0.3.0
speech_fsmn_vad_zh-cn-16k-common-pytorch
多个并行报错
![image](https://user-images.githubusercontent.com/57550373/223009295-f98b5391-7632-4446-8550-d455eebf1310.png)
![image](https://user-images.githubusercontent.com/57550373/223009368-d6d63a04-e1d4-4a98-9d7c-f91c1c61bb6b.png)
报错内容
![igEcAqNwbmcDAQTNA3cFzPoG2gAjhAGkIQWd4gKqNKjqsBoYCSmWlAPPAAABhrTOcs0EzgBBVzUHzhfJQE4IAAoEC84AAYDA png_620x10000q90](https://user-images.githubusercontent.com/57550373/223009434-96e2041e-358e-497d-9c5a-433ea5235541.jpg)
感谢解答

**Comment by langgz** [comment]
如之前在funasr群里沟通，python，多进程不可以share模型，多线程可以share模型，你是开了多进程，同时模型share，所以报错了。参考用法：https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/infer.py

**Comment by TongtongSong** [comment]
不过按照infer.py那样的话，一次也只能处理一条数据，数据多的话很慢。怎样可以批量处理更多数据呢，batch并行支持吗？
