### ISSUE TITLE
 module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by JuncFang-git** [modelscope/modelscope#167]
依赖环境numpy为1.24.0以上能够安装成功，但由于1.24.0后不再支持np.float，而需改为np.float64，导致贵代码有许多模型无法正常运行。希望你们能尽快做出兼容处理。此处以/modelscope/pipelines/cv/skin_retouching_pipeline.py 108行为例，代码做如下修改运行正常：

``` python
# 原代码
# img = img.astype(np.float)
# 修改后
img = img.astype(np.float64)
```

**Comment by Dong148** [comment]
好多依赖版本都太旧了，属实难用啊
