### ISSUE TITLE
模型GPT3的初始化错误

### ISSUE THREAD

**Issue by zhangzhenyu13** [modelscope/modelscope#170]
1.3.2版本的初始化会错误，其依赖megatron-util  1.3.2的部分报错：initialize.py文件，这个是由于初始化失败导致
        _set_random_seed(args.seed, args.data_parallel_random_init)
发现时由于magtron-util的mpu.py部分的321行：        def get_pipeline_model_parallel_rank():
调用时没完成初始化_MPU_PIPELINE_MODEL_PARALLEL_RANK。is None

1.3.0版本（与对应megatron-util）中存在保存权重不全的问题，因为其model-parallel的rank==0 ，而数据冰箱dist.get_rank()又存在多个rank，但是traine-itersave函数里，混淆了二者概念，最终只保存了1份数据，例如8卡机器ft后，只有1/8的参数被保存。虽然最新版本似乎修复了这个问题，但是却导致了更严重的如上问题

**Comment by Firmament-cyou** [comment]
> 1.3.2版本的初始化会错误，其依赖megatron-util 1.3.2的部分报错：initialize.py文件，这个是由于初始化失败导致 _set_random_seed(args.seed, args.data_parallel_random_init) 发现时由于magtron-util的mpu.py部分的321行： def get_pipeline_model_parallel_rank(): 调用时没完成初始化_MPU_PIPELINE_MODEL_PARALLEL_RANK。is None
> 
> 1.3.0版本（与对应megatron-util）中存在保存权重不全的问题，因为其model-parallel的rank==0 ，而数据冰箱dist.get_rank()又存在多个rank，但是traine-itersave函数里，混淆了二者概念，最终只保存了1份数据，例如8卡机器ft后，只有1/8的参数被保存。虽然最新版本似乎修复了这个问题，但是却导致了更严重的如上问题

您好，请先确认 <work_dir>/.cache/modelscope/hub/damo/nlp_gpt3_text-generation_2.7B/configuration.json 文件中的 megatron 部分的配置，其中 world_size 和 tensor_model_parallel_size 与实际并行度是否相同，如果不同初始化过程会失败。

相同的代码在 1.3.0 版本中可以跑通，因为那个版本对 configuration 中的参数保留了一定的宽容度，填写的与实际并行度不符也可以接受并运行，但这一设计引入了更复杂的问题，在 1.3.2 版本就强制要求使用正确的配置了

**Comment by zhangzhenyu13** [comment]
我加入了如下配置修改(WORDL_SIZE=4)：

`
    cfg.megatron.tensor_model_parallel_size = int(os.environ['WORLD_SIZE'])
    cfg.megatron.world_size = int(os.environ['WORLD_SIZE'])
    cfg.model.model_parallel_size= int(os.environ['WORLD_SIZE'])
    cfg.model.checkpoint_model_parallel_size = 1 #int(os.environ['WORLD_SIZE'])
`

依旧出现rbugs：

`
Traceback (most recent call last):
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/base/base_model.py", line 64, in _instantiate
    return cls(**kwargs)
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/text_generation.py", line 34, in __init__
    self.model = DistributedGPT3(model_dir, **kwargs)
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/distributed_gpt3.py", line 958, in __init__
    init_megatron_util(model_dir=model_dir, rank=rank)
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/megatron_utils.py", line 43, in init_megatron_util
    initialize_megatron(megatron_cfg)
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/initialize.py", line 70, in initialize_megatron
    finish_mpu_init()
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/initialize.py", line 56, in finish_mpu_init
    _set_random_seed(args.seed, args.data_parallel_random_init)
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/initialize.py", line 159, in _set_random_seed
    seed = seed_ + (100 * mpu.get_pipeline_model_parallel_rank())
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/mpu/initialize.py", line 326, in get_pipeline_model_parallel_rank
    return torch.distributed.get_rank(group=get_pipeline_model_parallel_group())
  File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/mpu/initialize.py", line 248, in get_pipeline_model_parallel_group
    'pipeline_model parallel group is not initialized'
AssertionError: pipeline_model parallel group is not initialized
`

**Comment by Firmament-cyou** [comment]
> 我加入了如下配置修改(WORDL_SIZE=4)：
> 
> `cfg.megatron.tensor_model_parallel_size = int(os.environ['WORLD_SIZE']) cfg.megatron.world_size = int(os.environ['WORLD_SIZE']) cfg.model.model_parallel_size= int(os.environ['WORLD_SIZE']) cfg.model.checkpoint_model_parallel_size = 1 #int(os.environ['WORLD_SIZE'])`
> 
> 依旧出现rbugs：
> 
> `Traceback (most recent call last): File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg return obj_cls._instantiate(**args) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/base/base_model.py", line 64, in _instantiate return cls(**kwargs) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/text_generation.py", line 34, in __init__ self.model = DistributedGPT3(model_dir, **kwargs) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/distributed_gpt3.py", line 958, in __init__ init_megatron_util(model_dir=model_dir, rank=rank) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/megatron_utils.py", line 43, in init_megatron_util initialize_megatron(megatron_cfg) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/initialize.py", line 70, in initialize_megatron finish_mpu_init() File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/initialize.py", line 56, in finish_mpu_init _set_random_seed(args.seed, args.data_parallel_random_init) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/initialize.py", line 159, in _set_random_seed seed = seed_ + (100 * mpu.get_pipeline_model_parallel_rank()) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/mpu/initialize.py", line 326, in get_pipeline_model_parallel_rank return torch.distributed.get_rank(group=get_pipeline_model_parallel_group()) File "/export/scratch/zhangzhenyu/miniconda3/envs/modelscope/lib/python3.7/site-packages/megatron_util/mpu/initialize.py", line 248, in get_pipeline_model_parallel_group 'pipeline_model parallel group is not initialized' AssertionError: pipeline_model parallel group is not initialized`

请在 <work_dir>/.cache/modelscope/hub/damo/nlp_gpt3_text-generation_2.7B/configuration.json 文件中修改 world_size 和其他参数，在 cfg_modify_fn 中关于 megatron 的修改在 1.3.2 版本中不会生效，下个版本才能这样修改

**Comment by zhangzhenyu13** [comment]
thanks a lot
