### ISSUE TITLE
vad多线程报错

### ISSUE THREAD

**Issue by 15651196171** [modelscope/modelscope#172]
推理模型：
![iwEcAqNwbmcDAQTRBOAF0QDABrDyGWEI88JfuQQAeHycQFcAB9MAAAAAqCCALggACaJpbQoAC9E6oA png_620x10000q90](https://user-images.githubusercontent.com/94610238/223389345-1d61fd78-b026-46cf-85a3-91da1a8d1da8.jpg)
报错信息
![iwEcAqNwbmcDAQTRAWoFSQawuy8OTOO5s44EAHiqoAB_AAfTAAAAAKgggC4IAAmiaW0KAAvRFRQ png_620x10000q90](https://user-images.githubusercontent.com/94610238/223389387-2a542658-a064-49f6-a178-28fc7eaaa01f.jpg)

**Comment by langgz** [comment]
如之前在funasr群里沟通，python，多进程不可以share模型，多线程可以share模型，你是开了多进程，同时模型share，所以报错了。

**Comment by TongtongSong** [comment]
不过按照infer.py那样的话，一次也只能处理一条数据，数据多的话很慢。怎样可以批量处理更多数据呢，batch并行支持吗？
