### ISSUE TITLE
人脸重建的后处理——如何生成gltf文件？

### ISSUE THREAD

**Issue by yfq512** [modelscope/modelscope#174]
感谢开源这么优秀的项目。[基于层次化表征的高精度人脸重建模型](https://www.modelscope.cn/models/damo/cv_resnet50_face-reconstruction/summary)项目可以运行，能够生成obj、mtl、jpg三个文件。
现在咨询下，如何用python将obj、mtl、jpg转成方便在前端展示的gltf文件？
（目前能借助三维建模软件实现转化，我需要把这部分工作放到服务器端实现，该如何做？）
![03083](https://user-images.githubusercontent.com/52442277/223647833-e71f8bc9-e809-4f2f-86ca-bef869e529d9.png)

**Comment by yfq512** [comment]
使用这个项目可以实现上述功能[obj2gltf](https://github.com/CesiumGS/obj2gltf)

**Comment by hooklee2000** [comment]
您好，方便给出能顺利安装的操作系统版本、python依赖、modelscope版本吗？ 我现在使用如下方式：

| 组件 | 推荐版本 | 说明 |
| :--- | :--- | :--- |
| OS | Ubuntu 22.04 LTS (WSL2) | 避免 24.04/26.04 的编译器过新问题 |
| Python | 3.10 | 3.11/3.12 对 numba/pytorch3d 支持仍有瑕疵 |
| CUDA | 12.1 | 兼顾新旧硬件，PyTorch 2.1.x 官方支持最好 |
| PyTorch | 2.1.2 + cu121 | v2.0.3 代码基于此时期 API，2.5+ 可能有破坏性更新 |
| PyTorch3D | 0.7.6 (预编译) | **切勿源码编译**，直接使用匹配 torch2.1/cu121/py310 的 whl |
| NumPy | <1.24.0 | 严格锁定，1.24 移除了 `np.float` 等别名导致老代码崩溃 |
| Pandas | <1.4.0 | 严格锁定，避免 API 变更 |
modelscope版本使用1.12.0，一启动就要升级numpy到2.2.6，还要下载tensorflow依赖。非常崩溃。装了一星期了，还没有结果。

**Comment by yfq512** [comment]
@hooklee2000 过去很久了，不太记得了。python版本你可以尝试一下3.7或者3.8。
或者直接使用codex之类的智能体直接帮你解决环境问题。
