### ISSUE TITLE
MPLUG finetune未注册模型至registry

### ISSUE THREAD

**Issue by Lotayou** [modelscope/modelscope#176]
问题：

Traceback (most recent call last):
  File "mplug_main.py", line 110, in <module>
    trainer = build_trainer(name=Trainers.mplug, default_args=args)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/modelscope/trainers/builder.py", line 19, in build_trainer
    return build_from_cfg(cfg, TRAINERS, default_args=default_args)
  File "/data/miniconda3/envs/env-3.7.7/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "MPlugTrainer: KeyError('mplug is not in the models registry group default. Please make sure the correct version of ModelScope library is used.')"

版本1.3.2

**Comment by Lotayou** [comment]
复现代码
```
import json
import os

from modelscope.metainfo import Trainers
from modelscope.trainers import build_trainer
from modelscope.utils.config_ds import DEFAULT_MS_CACHE_HOME
from modelscope.utils.constant import ModelFile
from torch.distributed.elastic.multiprocessing.errors import record

from build_dataset import MPlugBuilder as DatasetBuilder
from get_config import load_config

@record
def run_train(trainer):
    trainer.train()

pretrained_model_path = os.path.join(DEFAULT_MS_CACHE_HOME, 'damo/mplug_image-captioning_coco_large_en')
args = dict(
    model=pretrained_model_path,
    model_revision='v1.0.1',
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    cfg_file=config_file,
    # cfg_modify_fn=cfg_modify_fn,
    cfg_modify_fn=cfg_modify_no_eval_fn,
    work_dir=work_dir,
    freeze_epoch_num=MPlugFinetuneTrainer.MAX_EPOCH,
    freeze_modules=freeze_modules,
)
trainer = build_trainer(name=Trainers.mplug, default_args=args)

# Enable traceback of child process error
run_train(trainer)
```
关键config
```
'mplug_caption': {
        'framework': 'pytorch',  # 运行框架
        'task': 'image-captioning',  # 运行任务
        'model': {'type': 'mplug',  # 模型的类型（一般是模型backbone/骨架）这个key下面主要放了如何构建推断的ofa任务
                  'language': 'en',  # 输入输出语言
                  },
        'pipeline': {'type': 'image-captioning'},  # pipeline的类型
        'preprocessor': ["mplug-tasks-preprocessor"]
        ...
}
```

**Comment by Firmament-cyou** [comment]
> 复现代码
> 
> ```
> import json
> import os
> 
> from modelscope.metainfo import Trainers
> from modelscope.trainers import build_trainer
> from modelscope.utils.config_ds import DEFAULT_MS_CACHE_HOME
> from modelscope.utils.constant import ModelFile
> from torch.distributed.elastic.multiprocessing.errors import record
> 
> from build_dataset import MPlugBuilder as DatasetBuilder
> from get_config import load_config
> 
> @record
> def run_train(trainer):
>     trainer.train()
> 
> pretrained_model_path = os.path.join(DEFAULT_MS_CACHE_HOME, 'damo/mplug_image-captioning_coco_large_en')
> args = dict(
>     model=pretrained_model_path,
>     model_revision='v1.0.1',
>     train_dataset=train_dataset,
>     eval_dataset=test_dataset,
>     cfg_file=config_file,
>     # cfg_modify_fn=cfg_modify_fn,
>     cfg_modify_fn=cfg_modify_no_eval_fn,
>     work_dir=work_dir,
>     freeze_epoch_num=MPlugFinetuneTrainer.MAX_EPOCH,
>     freeze_modules=freeze_modules,
> )
> trainer = build_trainer(name=Trainers.mplug, default_args=args)
> 
> # Enable traceback of child process error
> run_train(trainer)
> ```
> 
> 关键config
> 
> ```
> 'mplug_caption': {
>         'framework': 'pytorch',  # 运行框架
>         'task': 'image-captioning',  # 运行任务
>         'model': {'type': 'mplug',  # 模型的类型（一般是模型backbone/骨架）这个key下面主要放了如何构建推断的ofa任务
>                   'language': 'en',  # 输入输出语言
>                   },
>         'pipeline': {'type': 'image-captioning'},  # pipeline的类型
>         'preprocessor': ["mplug-tasks-preprocessor"]
>         ...
> }
> ```

您好，您提供的复现代码中 MPlugBuilder，freeze_epoch_num 等并不属于 modelscope 提供的功能，config 格式也不是 modelscope 的标准 configuration.json 文件格式，能否麻烦您提供一下仅包含 modelscope 的能够复现报错的代码

您也可以基于我们提供的 finetune 代码进行修改，我测试可以直接运行没有报错的代码如下：
```python
import tempfile

from modelscope.msdatasets import MsDataset
from modelscope.metainfo import Trainers
from modelscope.trainers import build_trainer

datadict = MsDataset.load('coco_captions_small_slice')

train_dataset = MsDataset(
    datadict['train'].remap_columns({
        'image:FILE': 'image',
        'answer:Value': 'answer'
    }).map(lambda _: {'question': 'what the picture describes?'}))
test_dataset = MsDataset(
    datadict['test'].remap_columns({
        'image:FILE': 'image',
        'answer:Value': 'answer'
    }).map(lambda _: {'question': 'what the picture describes?'}))

# 可以在代码修改 configuration 的配置
def cfg_modify_fn(cfg):
    cfg.train.hooks = [{
        'type': 'CheckpointHook',
        'interval': 2
    }, {
        'type': 'TextLoggerHook',
        'interval': 1
    }, {
        'type': 'IterTimerHook'
    }]
    return cfg

kwargs = dict(
    model='damo/mplug_image-captioning_coco_large_en',
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    max_epochs=2,
    cfg_modify_fn=cfg_modify_fn,
    work_dir=tempfile.TemporaryDirectory().name)

trainer = build_trainer(
    name=Trainers.nlp_base_trainer, default_args=kwargs)
trainer.train()
```
