### ISSUE TITLE
docker镜像

### ISSUE THREAD

**Issue by speakstone** [modelscope/modelscope#18]
能否直接发布各子模块的docker镜像，配置环境花费了太长的时间，感觉这不利于用户体验和大批量推广，十分感谢

**Comment by xmxxiong** [comment]
赞同

**Comment by speakstone** [comment]
检索到了一个可能的镜像，不知道是否可行，正在尝试，https://hub.docker.com/r/xuxumengmeng/modelscope

**Comment by yingdachen** [comment]
We provide ready-to-use environment through our Notebook integration, and the same cpu/gpu images are also publicly-available:
GPU: ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.0.2
CPU: ubuntu20.04-py37-torch1.11.0-tf1.15.5-1.0.2

We will be updating our documetnation to provide clearer instrcution on how to retrive official ModelScope images. Thanks for the feedback!

**Comment by yingdachen** [comment]
to be exact, the images are:
CPU:registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-py37-torch1.11.0-tf1.15.5-1.0.2
GPU:registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.0.2

**Comment by alphanlp** [comment]
> registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.0.2

can not open the link

**Comment by zzclynn** [comment]
Try “docker pull”





来自钉钉专属商务邮箱------------------------------------------------------------------
***@***.***>
日　期：2023年02月24日 12:26:56
***@***.***>
***@***.***>
主　题：Re: [modelscope/modelscope] docker镜像 (Issue #18)


registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.0.2 
can not open the link

**Comment by SidneyRey** [comment]
有cuda10.1，cudnn7的镜像，tensorflow2.2.0，pytorch的镜像吗
