### ISSUE TITLE
AssertionError: GPT3Trainer: GPT3ForTextGeneration: pipeline_model parallel group is not initialized

### ISSUE THREAD

**Issue by adzhua** [modelscope/modelscope#188]
请问按照https://modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary继续训练gpt3报如下错误：
AssertionError: GPT3Trainer: GPT3ForTextGeneration: pipeline_model parallel group is not initialized是什么原因啦？是因为某个参数设置错误吗？

**Comment by adzhua** [comment]
modelscope的版本是1.3.2，降到1.3.0就可以了

**Comment by Firmament-cyou** [comment]
> 请问按照[https://modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary继续训练gpt3报如下错误：](https://modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary%E7%BB%A7%E7%BB%AD%E8%AE%AD%E7%BB%83gpt3%E6%8A%A5%E5%A6%82%E4%B8%8B%E9%94%99%E8%AF%AF%EF%BC%9A) AssertionError: GPT3Trainer: GPT3ForTextGeneration: pipeline_model parallel group is not initialized是什么原因啦？是因为某个参数设置错误吗？

您好，这个报错是因为运行进程数和 configuration 中的配置不匹配，请参考 model card 中下图部分正确配置后再次测试

![image](https://user-images.githubusercontent.com/57580313/225016204-10ef75c2-2b11-48ca-b3bc-7ad64f26f635.png)
