### ISSUE TITLE
官方案例报错

### ISSUE THREAD

**Issue by Sciki-Lee** [modelscope/modelscope#19]
![image](https://user-images.githubusercontent.com/59435537/200773978-ac37be75-3b83-4b80-850f-b66307ac35d0.png)
![image](https://user-images.githubusercontent.com/59435537/200774296-5847ea3e-4df8-4a1a-bcd6-981602f89c66.png)
![image](https://user-images.githubusercontent.com/59435537/200774871-ba201dd5-087e-49d4-9b96-709e22586430.png)
以上代码在modelscope集成的notebook里面运行没问题，自己配的环境就报一堆错，太奇怪了

**Comment by Sciki-Lee** [comment]
> 您好，重试一直这样吗？您访问别的站点正常吗？

一直有这个问题，包括使用#issue4里作者提供的镜像也是有这个网络连接的错误，但我这边网络应该是没问题的

**Comment by Sciki-Lee** [comment]
> 您好，重试一直这样吗？您访问别的站点正常吗？

一直有这个问题，包括使用#issue4里作者提供的镜像也是有这个网络连接的错误，但我这边网络应该是没问题的

**Comment by liuyhwangyh** [comment]
> > 您好，重试一直这样吗？您访问别的站点正常吗？
> 
> 一直有这个问题，包括使用#issue4里作者提供的镜像也是有这个网络连接的错误，但我这边网络应该是没问题的，Transformers pipeline可以正常运行

Transformer pipeline是modelscope上的其他模型？

**Comment by Sciki-Lee** [comment]
> > > 您好，重试一直这样吗？您访问别的站点正常吗？
> > 
> > 
> > 一直有这个问题，包括使用#issue4里作者提供的镜像也是有这个网络连接的错误，但我这边网络应该是没问题的，Transformers pipeline可以正常运行
> 
> Transformer pipeline是modelscope上的其他模型？

HuggingFace上的

**Comment by zzclynn** [comment]
> ![image](https://user-images.githubusercontent.com/59435537/200773978-ac37be75-3b83-4b80-850f-b66307ac35d0.png) ![image](https://user-images.githubusercontent.com/59435537/200774296-5847ea3e-4df8-4a1a-bcd6-981602f89c66.png) ![image](https://user-images.githubusercontent.com/59435537/200774871-ba201dd5-087e-49d4-9b96-709e22586430.png) 以上代码在modelscope集成的notebook里面运行没问题，自己配的环境就报一堆错，太奇怪了

pip freeze | grep 'modelscope'看一下notebook和本地分别是什么版本？

**Comment by yingdachen** [comment]
close as fail-to-reproduce
