### ISSUE TITLE
如何设定推理时的线程数？

### ISSUE THREAD

**Issue by cgisky1980** [modelscope/modelscope#194]
pipelines 里面怎么设定？

**Comment by cgisky1980** [comment]
暂时 在\miniconda3\envs\xxx\lib\python3.7\site-packages\modelscope\pipelines\base.py  里
加上了 torch.set_num_threads(4)
RK3588  4个大核4个小核  要是跑满8线程很慢。  希望有个设置   找半天没找到

**Comment by wenmengzhou** [comment]
现在的问题是pipeline占用cpu核数过多，导致程序运行缓慢？

**Comment by cgisky1980** [comment]
> 现在的问题是pipeline占用cpu核数过多，导致程序运行缓慢？

是的  改成4 反而快双倍  因为默认是8个核  但是这8个核 4大4小，数据交换就堵塞了
