### ISSUE TITLE
Range Param of Http Header may be Denied by Many Router

### ISSUE THREAD

**Issue by CodingFatman** [modelscope/modelscope#197]
i pull a docker image from here
![1678849026014](https://user-images.githubusercontent.com/38900882/225193617-d89942e0-6072-4dec-88ef-cbffd01dd236.png)
but when i run it use the sample code provided by funasr project, an error occured as below:
![baf1ebe984fb6700f6692f8de7bc295](https://user-images.githubusercontent.com/38900882/225194068-8a8b7b55-0852-4be0-9aab-4b597de820bf.png)
i did a lot of debug and find out the result finally. here comes the truth below:
![238bd421bb488bd7be78e270550d90a](https://user-images.githubusercontent.com/38900882/225194430-a5fb6327-7b0a-4965-af04-277b16a5e627.png)
![c4ad44cad16a8e737b78cd91850e2dc](https://user-images.githubusercontent.com/38900882/225194523-b071dd19-95ac-4153-84b9-c4552c27a4b1.png)
![9d7c416d057960dffd5da1b67b6795e](https://user-images.githubusercontent.com/38900882/225194630-dafab8da-a97c-4e92-9565-f522b02a5d3b.png)
![ddda891dbbb7c657de3ac6716b91d90](https://user-images.githubusercontent.com/38900882/225194680-81574396-71e8-40c9-b2ec-689217587cf2.png)

i make a summary here:
many company have some policy to limit employees of accessing internet. so many routers was setup for this purpose.
in my situation, the range param will cause the router blocking the request to  file "am.mvn" of modelscope. 
when i modify the source code of "modelscope/hub/file_download.py" and remove the "Range" parameter, everthing goes well.
the welcome screen of funasr has appeared.

i think there may be some solutions to solve this problem, because the limit of routers will always exist.
for my opinion,  it should detect wheter the range request was success or not.  may be shoud remove the range param if range request was failed. or you shoud set a value to decide whether to make a range request.  it shoud not to make a range request if the file requested was very small. this is my thought. you guys must have more advanced solutions. ：）

good luck! guys. ：）

**Comment by yingdachen** [comment]
thanks for bringing this to our attention. 

agree that range should not apply for smalled files (say less than 50MB), we shall incorporate this adatatbility in later release.

**Comment by CodingFatman** [comment]
@yingdachen Amazing! &#129309;&#128516;
