### ISSUE TITLE
gpt3-2.7B模型训练后推理报错 TypeError: DistributedGPT3Pipeline: unsupported operand type(s) for *: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by yinzhang809** [modelscope/modelscope#200]
看了一下是在这一行去掉了配置中的checkpoint_tensor_model_parallel_size
https://github.com/modelscope/modelscope/blob/9c2ca892ce727ca33896e747391471af4e76da5a/modelscope/models/nlp/gpt3/distributed_gpt3.py#L1263
推理时试图获取checkpoint_tensor_model_parallel_size，得到None
https://github.com/modelscope/modelscope/blob/9c2ca892ce727ca33896e747391471af4e76da5a/modelscope/models/nlp/gpt3/distributed_gpt3.py#L977

请问配置中这个参数的正确用法是什么？

**Comment by Firmament-cyou** [comment]
> 看了一下是在这一行去掉了配置中的checkpoint_tensor_model_parallel_size
> 
> https://github.com/modelscope/modelscope/blob/9c2ca892ce727ca33896e747391471af4e76da5a/modelscope/models/nlp/gpt3/distributed_gpt3.py#L1263
> 
> 
> 推理时试图获取checkpoint_tensor_model_parallel_size，得到None
> https://github.com/modelscope/modelscope/blob/9c2ca892ce727ca33896e747391471af4e76da5a/modelscope/models/nlp/gpt3/distributed_gpt3.py#L977
> 
> 请问配置中这个参数的正确用法是什么？

这个参数表示存储 checkpoint 的并行片数，您遇到的问题是一个已知 bug，会在 modelscope 1.4 版本中修复，1.3.2 版本可以通过在 configuration 中设置 checkpoint_tensor_model_parallel_size = tensor_model_parallel_size 使保存的 checkpoint 可以用作推理
