### ISSUE TITLE
the example code of UniAsr can only output one result when wav.scp has more than one wav files

### ISSUE THREAD

**Issue by CodingFatman** [modelscope/modelscope#201]
i pull a docker image from [GPU docker file of ModelScope](https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#Python%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)
and use the example code of UniAsr listed here:[UniASR](https://github.com/alibaba-damo-academy/FunASR/wiki/UniASR)
but it can only output one wav file's result when i put more than one wav files in wav.scp.
finally, i find a bug in modelscope and i attempt to fix it like below:
![ce25908c9db2974902d40791f0d070c](https://user-images.githubusercontent.com/38900882/225508794-8653cbcf-0cbb-4784-88fb-9dfe2ab5c937.png)
![e7534d500615c3600056e0632cc0b31](https://user-images.githubusercontent.com/38900882/225508813-492ac5b5-3f52-426d-ab88-55166ced96f6.png)
![c7021c1cb5ef1470feb1fbfacf4f8a7](https://user-images.githubusercontent.com/38900882/225508829-6cf56053-b518-4fa3-ad7c-266edb53109a.png)
![850b5982d5618c28a70880a9ab24aa8](https://user-images.githubusercontent.com/38900882/225508844-236633bc-3e74-4b9a-a123-23b94a2367bb.png)

i don't know whether am i right, and i am a new b to Python too, but i want to contribute the effort of mine to ModelScope
good luck! guys! 
may god bless you! ：）

**Comment by hnluo** [comment]
you can get asr results from decoder_dir/1best_recog/tokens file

**Comment by CodingFatman** [comment]
![image](https://user-images.githubusercontent.com/38900882/225798111-1b8b4241-9ad3-45e6-9923-0e936a840f24.png)
well, you are right! 👍 
by the way, it's hard for somebody to admit that some mistake was made especially an IT expert at DAMO.  ：）
good luck! guys. ：）
