### ISSUE TITLE
请问gpt3模型文件哪里可以下载

### ISSUE THREAD

**Issue by yanchaoguo** [modelscope/modelscope#202]
请问damo/nlp_gpt3_text-generation_13B以及30B 对应的权重文件在哪里可以下载到

**Comment by wenmengzhou** [comment]
您好，实验室申请模型下载，可以辛苦您写出具体的实验室的名称，以及申请的背景，发送邮件到[contact@modelscope.cn](mailto:contact@modelscope.cn), 我们请模型的贡献者评估后给您答复。
175B的模型目前还没有明确在modelscope社区的在线体验的时间，如果确认可以体验后，会随着release note发出，请关注社区公告，谢谢您
