### ISSUE TITLE
PunctuationProcessingPipeline: cannot import name 'check_argument_types' from 'typeguard'

### ISSUE THREAD

**Issue by zhangsz1998** [modelscope/modelscope#205]
According to [the doc](https://typeguard.readthedocs.io/en/stable/versionhistory.html). Typeguard has removed the function check_argment_types since version 3.0.0. I think either the dependency file or the code should be modified.

**Comment by wenmengzhou** [comment]
can you provide the original error log and traceback？

**Comment by zhangsz1998** [comment]
Sorry, I found that I happened to install typeguard >= 0.3.0 and caused the above error. After I reinstalled modelscope[audio] using the official command, typeguard==2.13.3 was installed, and everything works fine now.
