### ISSUE TITLE
pipelines\nlp\siamese_uie_pipeline.py 中  with autocast() ARMcpu不支持

### ISSUE THREAD

**Issue by cgisky1980** [modelscope/modelscope#208]
两处 with autocast()  要去掉

**Comment by cgisky1980** [comment]
应该加个判断

**Comment by wenmengzhou** [comment]
welcome to create a pull request to fix this for ARM

**Comment by cgisky1980** [comment]
> welcome to create a pull request to fix this for ARM

我不确定是什么错误，我的环境是  RK3588   其他模型也出现类似问题。 目前只是暂时解决办法，就是把 with autocast() 注释掉
