### ISSUE TITLE
Half precision for video synthesis model?

### ISSUE THREAD

**Issue by kabachuha** [modelscope/modelscope#209]
Hello!

I wonder if it's possible to allow half precision for the video diffusion model. It would be very nice since it's crashing the free tier colab at this moment.

**Comment by WangJiuniu** [comment]
We use half precision for the video diffusion model as default. And it can be run on Colab now.

See [this page](https://colab.research.google.com/drive/1uW1ZqswkQ9Z9bp5Nbo5z59cAn7I0hE6R?usp=sharing).

**Comment by kabachuha** [comment]
Oh, thanks!

**Comment by amrrs** [comment]
@WangJiuniu Thanks for the colab, I just tried running it on Colab (from the link) but the RAM crashed. Any suggestions?
