### ISSUE TITLE
语音识别任务，输入文件的格式

### ISSUE THREAD

**Issue by wwfcnu** [modelscope/modelscope#211]
语音识别任务，输入文件的格式不支持mp3吗，怎么修改呢

**Comment by CodingFatman** [comment]
@wwfcnu 我也问过类似的问题，目前funasr还不支持多种格式的文件，唯一的解决办法是通过类似sox或者ffmpeg把他们转换成单通道、16000hz的wav文件。注意转换后的wav文件一定要是16000hz的，否则识别效果会大打折扣。

**Comment by wwfcnu** [comment]
> @wwfcnu 我也问过类似的问题，目前funasr还不支持多种格式的文件，唯一的解决办法是通过类似sox或者ffmpeg把他们转换成单通道、16000hz的wav文件。注意转换后的wav文件一定要是16000hz的，否则识别效果会大打折扣。

再源码里加上识别mp3格式，识别的时候是不是会快一些

**Comment by langgz** [comment]
是支持的，需要升级到最新版本，升级指令：
pip install "modelscope[audio_asr]" --upgrade -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install --editable ./

包括mp3在内的多种音频格式，采样率都是支持的，用户不需要关心输入音频格式，如果遇到不支持的音频，可以反馈一下（repo：https://github.com/alibaba-damo-academy/FunASR），欢迎加入funasr钉钉群沟通您遇到的问题：27215013275

**Comment by wwfcnu** [comment]
> 是支持的，需要升级到最新版本，升级指令： pip install "modelscope[audio_asr]" --upgrade -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html git clone https://github.com/alibaba/FunASR.git && cd FunASR pip install --editable ./
> 
> 包括mp3在内的多种音频格式，采样率都是支持的，用户不需要关心输入音频格式，如果遇到不支持的音频，可以反馈一下，repo：https://github.com/alibaba-damo-academy/FunASR
> 
> 欢迎加入funasr钉钉群沟通您遇到的问题：27215013275
主要是 torchaudio版本的问题，看能不能把源码处理语音的sox换成ffmpeg
