### ISSUE TITLE
Batch and single are not uniform

### ISSUE THREAD

**Issue by ezeli** [modelscope/modelscope#215]
https://github.com/modelscope/modelscope/blob/fe673953b1f8cfe2a2f1ed2ef7c3207fefc28f43/modelscope/pipelines/base.py#L298

should be changed to:
```python
out[k] = element[batch_idx:batch_idx+1] 
```

In this way, **_process_batch** is unified with **_process_single** when calling the **postprocess** function.

**Comment by ezeli** [comment]
And when processing other types of elements, it should be iterated. For example, when **output_hidden_states=True**, the tuple object will be returned.

**Comment by wenmengzhou** [comment]
thanks，  can you open a pull request to fix this issue?
