### ISSUE TITLE
Downloading the model fails at 6%, any mirrors?

### ISSUE THREAD

**Issue by tin2tin** [modelscope/modelscope#218]
I guess there is just too much traffic, and the download of the module times out over and over again. Are there any mirrors where the model can be download? (I'm working on getting modelscope to work from within the open source Blender Video Sequence Editor)

![image](https://user-images.githubusercontent.com/1322593/226319018-888c95d6-5cb5-4ad5-b5f8-614cb3c27a90.png)

**Comment by tin2tin** [comment]
ConnectionResetError: [WinError 10054] An existing connection was forcibly terminated by a remote host:
![image](https://user-images.githubusercontent.com/1322593/226327991-818b4ab2-f197-470c-b530-fb2236a58676.png)

**Comment by team79** [comment]
@tin2tin May I ask which command you used to download and from which region? Thank you.

**Comment by tin2tin** [comment]
I'm having the Blender add-on just run these:

```
pip install git+https://github.com/modelscope/modelscope.git
pip install open_clip_torch
pip install pytorch-lightning
```

After downloading (from Denmark) many, many hours, this is how it ended:
![image](https://user-images.githubusercontent.com/1322593/226543261-a30b55c2-a100-4262-9c48-5b1f1e692ebd.png)

Can I download the models manually somewhere and then place them inside the modelscope installation?

**Comment by tin2tin** [comment]
Can these weights be used? https://huggingface.co/damo-vilab/modelscope-damo-text-to-video-synthesis/tree/main

**Comment by wenmengzhou** [comment]
> Reference

yes

**Comment by wenmengzhou** [comment]
> I have no such folder in my local modelscope installation? (I only downloaded those files from huggin face, I need to run it locally on my computer and not use huggin face)

you can run another small model using modelscope such as https://modelscope.cn/models/damo/nlp_structbert_sentiment-classification_chinese-base/summary and then place the model under the auto-created cache directory

**Comment by wenmengzhou** [comment]
@tin2tin  is this problem solved ?

**Comment by tin2tin** [comment]
Well, the speeds seemed to go up at some point. I ended up manually downloading the weights. However, doing a local install of ModelScope keeps failing for me in other like it can't be found after installation and the CUDA of my RTX card can't be detected. So, I'll wait and hope the project will iron out things like these. It would be great though, if the video editor of Blender could generate footage directly inside the timeline. https://github.com/tin2tin/text_to_video

**Comment by wenmengzhou** [comment]
> Well, the speeds seemed to go up at some point. I ended up manually downloading the weights. However, doing a local install of ModelScope keeps failing for me in other like it can't be found after installation and the CUDA of my RTX card can't be detected. So, I'll wait and hope the project will iron out things like these. It would be great though, if the video editor of Blender could generate footage directly inside the timeline. https://github.com/tin2tin/text_to_video

can you address a issue about the installation problem？ We will check it soon

**Comment by tin2tin** [comment]
This seems to describe one of the problems: https://github.com/openai/whisper/discussions/1032
And the one with ModelScope not found, could be bc the installation process do not fully respect a local install(Blender comes with its own Python).
