### ISSUE TITLE
语音功能什么时候能支持window啊?

### ISSUE THREAD

**Issue by Lao-Feng** [modelscope/modelscope#223]
![image](https://user-images.githubusercontent.com/35493712/226537329-7df96926-93c9-4529-b004-d14712d18800.png)

**Comment by Lizerui9926** [comment]
ASR是支持Windows安装的，可使用以下命令来进行安装

**Comment by Lizerui9926** [comment]
是支持Windows安装的，可使用以下命令来进行安装： pip install "modelscope[audio_asr]" --upgrade -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by Lao-Feng** [comment]
> Reference in new issue
> 
> ### Reference in new issue

官网的文档上, 确实没有看到这个命令

**Comment by wenmengzhou** [comment]
currently  we support install modelscope[audio_asr]  which will install asr related library on windows successfully

**Comment by wenmengzhou** [comment]
close as this issue has already been addressed

**Comment by jialongP** [comment]
我想问下，window 下载 【CV领域模型】能成功吗，我这里一直报这个
Successfully built zhconv fairseq sacremoses jieba seqeval audioread emoji
Failed to build healpy
ERROR: Could not build wheels for healpy which use PEP 517 and cannot be installed directly
后面就下载不了，求解决方法
