### ISSUE TITLE
长音频离线报错

### ISSUE THREAD

**Issue by 15651196171** [modelscope/modelscope#226]
![image](https://user-images.githubusercontent.com/94610238/226582485-ff511c5e-d639-454f-8b8b-6d8b3371c1e4.png)
这是用的测试模型
下面是报错
![image](https://user-images.githubusercontent.com/94610238/226582623-890e7e81-f2b4-459c-8313-bc5368ec03d6.png)
我把模型按照文档都下载到本地后，在里面把路径改成自己的依旧报错，这是什么原因

**Comment by yingdachen** [comment]
这个模型应该是用到了多个model hub上的模型文件。如果要在本地使用，可能还需要改一下代码。

我们还是建议在联网情况下使用。
