### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array.

### ISSUE THREAD

**Issue by seawater668** [modelscope/modelscope#229]
Python 3.7.13 (default, Oct 18 2022, 18:57:03) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.11.0+cu113'
>>> torch.cuda.is_available()
True
>>> import tensorflow as tf
2023-03-23 10:17:01.522937: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
>>> tf.__version__
'1.15.5'
>>> tf.test.is_gpu_available()

**Comment by wenmengzhou** [comment]
check your bumpy version, make sure it is lower or equal to 1.18
