### ISSUE TITLE
人脸质量评估模型的输出

### ISSUE THREAD

**Issue by ljdang** [modelscope/modelscope#230]
人脸质量评估模型face quality assessment model的输出为float32[1，10]，代码这里却只是输出了第一个值 https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/cv/face_quality_assessment_pipeline.py#L91 
测试了一下第一个值的分数都是很高的，所以应该怎么来获得具体的质量分数呢，或者有该方法的论文参考吗？

**Comment by MIaomiao426** [comment]
> 人脸质量评估模型face quality assessment model的输出为float32[1，10]，代码这里却只是输出了第一个值 https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/cv/face_quality_assessment_pipeline.py#L91 测试了一下第一个值的分数都是很高的，所以应该怎么来获得具体的质量分数呢，或者有该方法的论文参考吗？

输出是十个值的平均

**Comment by ZihaoW123** [comment]
> > 人脸质量评估模型face quality assessment model的输出为float32[1，10]，代码这里却只是输出了第一个值 https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/cv/face_quality_assessment_pipeline.py#L91 测试了一下第一个值的分数都是很高的，所以应该怎么来获得具体的质量分数呢，或者有该方法的论文参考吗？
> 
> 输出是十个值的平均

这十个值的标签分别是什么呢？就是这十个值分辨代表哪些得分呢？
