### ISSUE TITLE
训练好的模型加载报错

### ISSUE THREAD

**Issue by yanchaoguo** [modelscope/modelscope#234]
pipeline = pipeline(task=Tasks.multi_modal_embedding, model='clip/ckpts/' ) 

‘’‘
File /usr/local/lib/python3.8/dist-packages/modelscope/pipelines/multi_modal/multi_modal_embedding_pipeline.py:32, in MultiModalEmbeddingPipeline.__init__(self, model, preprocessor, **kwargs)
     31 super().__init__(model=model, preprocessor=preprocessor, **kwargs)
---> 32 self.model.eval()
     33 if preprocessor is None:

AttributeError: 'str' object has no attribute 'eval'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[12], line 1
----> 1 pipeline = pipeline(task=Tasks.multi_modal_embedding, model='clip/ckpts/' ) 

File /usr/local/lib/python3.8/dist-packages/modelscope/pipelines/builder.py:141, in pipeline(task, model, preprocessor, config_file, pipeline_name, framework, device, model_revision, plugins, **kwargs)
    138 if preprocessor is not None:
    139     cfg.preprocessor = preprocessor
--> 141 return build_pipeline(cfg, task_name=task)

File /usr/local/lib/python3.8/dist-packages/modelscope/pipelines/builder.py:54, in build_pipeline(cfg, task_name, default_args)
     43 def build_pipeline(cfg: ConfigDict,
     44                    task_name: str = None,
     45                    default_args: dict = None):
     46     """ build pipeline given model config dict.
     47 
     48     Args:
   (...)
     52         default_args (dict, optional): Default initialization arguments.
     53     """
---> 54     return build_from_cfg(
     55         cfg, PIPELINES, group_key=task_name, default_args=default_args)

File /usr/local/lib/python3.8/dist-packages/modelscope/utils/registry.py:215, in build_from_cfg(cfg, registry, group_key, default_args)
    212         return obj_cls(**args)
    213 except Exception as e:
    214     # Normal TypeError does not print class name.
--> 215     raise type(e)(f'{obj_cls.__name__}: {e}')

AttributeError: MultiModalEmbeddingPipeline: 'str' object has no attribute 'eval'
’‘’
****

**Comment by yanchaoguo** [comment]
@wenmengzhou 请大神跟看下这个问题 目前模型训练的权重文件，该如何加载

**Comment by wenmengzhou** [comment]
> @wenmengzhou 请大神跟看下这个问题 目前模型训练的权重文件，该如何加载

用的哪个版本？
检查一下输出目录的configuration.json，贴一下？

**Comment by yanchaoguo** [comment]
> > @wenmengzhou 请大神跟看下这个问题 目前模型训练的权重文件，该如何加载
> 
> 用的哪个版本？ 检查一下输出目录的configuration.json，贴一下？

https://modelscope.cn/docs/CLIP_CN_Tutorial
是按照这个做的

**Comment by wenmengzhou** [comment]
> > > @wenmengzhou 请大神跟看下这个问题 目前模型训练的权重文件，该如何加载
> > 
> > 
> > 用的哪个版本？ 检查一下输出目录的configuration.json，贴一下？
> 
> https://modelscope.cn/docs/CLIP_CN_Tutorial 是按照这个做的

clip/ckpts/ 这个目录下的内容请展示一下，另外贴一下这个目录下的configuration.json
