### ISSUE TITLE
请问用ocr_recognition进行ocr文本识别训练任务时，如何安排本地图片、标签文件的层次结构，以及如何使用MsDataset.load语句将图片和对应的标签传递到train_dataset中呢？

### ISSUE THREAD

**Issue by balicheng** [modelscope/modelscope#235]

**Comment by zwsjink** [comment]
可以仿照这个数据集的python文件的写法，组装您自己的数据结构 https://modelscope.cn/datasets/modelscope/ocr_fudanvi_zh/file/view/master/ocr_fudanvi_zh.py

并参考这里的方式加载：
[加载本地python脚本](https://modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#3.%20%E5%8A%A0%E8%BD%BD%E6%9C%AC%E5%9C%B0python%E8%84%9A%E6%9C%AC)
