### ISSUE TITLE
这里的text_to_video_synthesis是基于VideoFusion实现的吗？

### ISSUE THREAD

**Issue by shencuifeng** [modelscope/modelscope#239]

**Comment by yingdachen** [comment]
请参考model card上的介绍。

https://www.modelscope.cn/models/damo/text-to-video-synthesis/summary#%E7%9B%B8%E5%85%B3%E8%AE%BA%E6%96%87%E4%BB%A5%E5%8F%8A%E5%BC%95%E7%94%A8%E4%BF%A1%E6%81%AF
