### ISSUE TITLE
i want to use scrfd 34g_gnkps_v2 

### ISSUE THREAD

**Issue by nemodleo** [modelscope/modelscope#24]
https://modelscope.cn/models/damo/cv_resnet_facedetection_scrfd10gkps/summary

The above site introduces the improved model V2 (34g_gnkps_v2).
'damo/cv_resnet_facedetection_scrfd10gkps' mentioned in the usage code Is this model SCRFD_34G_GNKPS_v2?
If not, how can I use it?

**Comment by nemodleo** [comment]
![image](https://user-images.githubusercontent.com/49754293/201592149-fa8150a8-47f6-4b20-a8ab-82dd9d319c29.png)


![rstImg_10g](https://user-images.githubusercontent.com/49754293/201592071-3dbe38ec-b564-4432-bedd-7adefb0d20fc.jpg)
This is a picture I tested with 'damo/cv_resnet_facedetection_scrfd10gkps' .
It resembles the V2 model in the first photo above, I wonder if it is the same model.

**Comment by tuoyuxiang** [comment]
> ![image](https://user-images.githubusercontent.com/49754293/201592149-fa8150a8-47f6-4b20-a8ab-82dd9d319c29.png)
> 
> ![rstImg_10g](https://user-images.githubusercontent.com/49754293/201592071-3dbe38ec-b564-4432-bedd-7adefb0d20fc.jpg) This is a picture I tested with 'damo/cv_resnet_facedetection_scrfd10gkps' . It resembles the V2 model in the first photo above, I wonder if it is the same model.

Yes, the default model is v2 now. The model id `damo/cv_resnet_facedetection_scrfd10gkps` is assigned before the update.

**Comment by nemodleo** [comment]
Thanks @tuoyuxiang
