### ISSUE TITLE
后期会开源模型的代码实现吗

### ISSUE THREAD

**Issue by BeyondYourself** [modelscope/modelscope#25]
看到开源了好多模型，甚是欣慰。想问问后续会开源模型的代码实现吗

**Comment by yingdachen** [comment]
目前主要开源模型加载以及进行finetune/continue-train的代码。至于模型代码（原始训练实现），因为普通用户用起来还是比较困难的，目前暂时没有系统性开放的计划。

有些模型有单独全面开源的计划，会在模型页面做具体介绍。

**Comment by BeyondYourself** [comment]
期待一下开源模型
