### ISSUE TITLE
Pickle detected this about the MODELS, how do I know they are safe? 

### ISSUE THREAD

**Issue by Stable777** [modelscope/modelscope#253]
Hello I noticed this about the models, PICKEL detected these lines:

![image](https://user-images.githubusercontent.com/114045211/229179567-d894b8da-8a2e-448a-9663-1ba4f46df660.png)

How can I be sure they are safe?
Thanks

**Comment by cafeTechne** [comment]
Warning

The pickle module is not secure. Only unpickle data you trust.

It is possible to construct malicious pickle data which will execute arbitrary code during unpickling. Never unpickle data that could have come from an untrusted source, or that could have been tampered with.

Consider signing data with [hmac](https://docs.python.org/3/library/hmac.html#module-hmac) if you need to ensure that it has not been tampered with.

Safer serialization formats such as [json](https://docs.python.org/3/library/json.html#module-json) may be more appropriate if you are processing untrusted data. See [Comparison with json](https://docs.python.org/3/library/pickle.html#comparison-with-json).

source: https://docs.python.org/3/library/pickle.html

**Comment by wenmengzhou** [comment]
Thanks a lot, we will check it and try to fix it soon
