### ISSUE TITLE
Where are the models stored?

### ISSUE THREAD

**Issue by olaviinha** [modelscope/modelscope#255]
**General Question**

When running text-to-video, files of several gigabytes are downloaded. Where are these files stored in the running system, or more specifically, in Google Colab's runtime?

It takes over an hour to download them, so I'd like to store them in Google Drive for faster utilization in the future.

**Comment by olaviinha** [comment]
Nevermind, it actually showed the path once everything was downloaded.

**Comment by asvin-kumar** [comment]
Adding a comment for anyone who comes back here.  
modelscope files are saved in the cache dir by default. For Linux, the default cache dir is `~/.cache/modelscope`
