### ISSUE TITLE
face_processing_base_pipeline.py local variable 'align_img'

### ISSUE THREAD

**Issue by hbo-lambda** [modelscope/modelscope#257]
没有深入函数细节，只是运行的时候报错了，没有命中if条件的话，align_img不存在

![Snip20230404_1](https://user-images.githubusercontent.com/7626261/229707307-b16d6ab6-fd90-4cb9-8c34-74e2d9294be5.png)

**Comment by ly19965** [comment]
感谢指出哈，下个版本会fix。
