### ISSUE TITLE
Pipeline对象线程安全问题

### ISSUE THREAD

**Issue by icylord** [modelscope/modelscope#273]
请问下，用fastapi框架集成asr/tts这些pipeline提供restapi服务的话，pipeline对象使用时是否需要加锁？

例如下面的代码：
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
   model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch')
   
@router.post("/asr")
def asr():
// 这里是否需要加锁
    rec_result = inference_pipeline(audio_in='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
    return rec_result

**Comment by langgz** [comment]
FunASR supports the multi-threads inference on CPU or multi GPU, please ref to the [docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#inference-with-multi-thread-cpus-or-multi-gpus)

**Comment by icylord** [comment]
> FunASR supports the multi-threads inference on CPU or multi GPU, please ref to the [docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#inference-with-multi-thread-cpus-or-multi-gpus)

OK
