### ISSUE TITLE
NLP命名实体识别

### ISSUE THREAD

**Issue by feifaxiaoming** [modelscope/modelscope#274]
**General Question**

我想问一下，我在使用nlp命名识别识别的时候，输出的结果中没有给结果打分，没有score，我想咨询的我在代码中哪里可以看到这个score，或者加入这个score。我使用的是下列的代码：

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

ner_pipeline = pipeline(Tasks.named_entity_recognition, 'damo/nlp_raner_named-entity-recognition_chinese-base-generic')
result = ner_pipeline('天猫618全球狂欢节')

print(result)

输出结果：
{'output': [{'type': 'ORG', 'start': 0, 'end': 2, 'span': '天猫'}]}

里面没有这个span的得分，我想知道，我在代码中哪里可以获取这个分数。谢谢。

**Comment by njustczr** [comment]
我也有同样的需求  需要返回score

**Comment by lajiyuan** [comment]
我也有同样的需求 需要返回score !!!

**Comment by lajiyuan** [comment]
@feifaxiaoming  请问您有解决办法了吗？

**Comment by wenmengzhou** [comment]
https://github.com/modelscope/modelscope/pull/551 which has fix this problem
