### ISSUE TITLE
How to accelerate asr inferencing?

### ISSUE THREAD

**Issue by treya-lin** [modelscope/modelscope#277]
Hi currently I am using this pipeline https://github.com/alibaba-damo-academy/FunASR/discussions/278 to decode a large number of long audio files. I once also tried multi threading for the pipeline to processing multiple audio files at the same time but it threw out errors at the vad stage, so I went back to the basic pipeline. So now it is a bit slow mainly in that it is transcribing and adding punctuations for each segment each time. Is there any advice or good example showing how to speed it up? 

Thank you very much in advance!

**Comment by langgz** [comment]
FunASR supports the multi-threads inference on CPU or multi GPU, please ref to the [docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#inference-with-multi-thread-cpus-or-multi-gpus)

**Comment by treya-lin** [comment]
> FunASR supports the multi-threads inference on CPU or multi GPU, please ref to the [docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#inference-with-multi-thread-cpus-or-multi-gpus)

Hi. Thanks for the reply, but this link is unable to open. Is the link working on your end?
