### ISSUE TITLE
如何进行多gpu推理

### ISSUE THREAD

**Issue by zhiyongLiu1114** [modelscope/modelscope#279]
**Describe the feature**
如何进行多gpu推理

**Motivation**
显存不够

**Related resources**
比如transformers可以这样把一个模型拆分到多个卡上
max_memory_mapping = {0: "1GB", 1: "2GB"}
model_name = "bigscience/bloom-3b"
model_8bit = AutoModelForCausalLM.from_pretrained(
    model_name, device_map="auto", load_in_8bit=True, max_memory=max_memory_mapping
)

**Additional context**

**Comment by wenmengzhou** [comment]
which model do you want to use for distributed inference?

**Comment by zhiyongLiu1114** [comment]
> which model do you want to use for distributed inference?

较大的模型都有这个需求

**Comment by wenmengzhou** [comment]
currently we have supported distributed inference for gpt3 using Distributed  Pipeline, which is based on Megatron actually,  about which you can refer to https://modelscope.cn/docs/%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%BC%80%E5%8F%91#DistributedPipeline%E4%BB%8B%E7%BB%8D

As for the auto device mapping provided by Huggingface we have not supported but we will check it and schedule the development

**Comment by wenmengzhou** [comment]
pass the argument device_map='auto' to pipeline will support multi-gpu inference
