### ISSUE TITLE
What is the use of this repository if you are unable to download the checkpoints ??

### ISSUE THREAD

**Issue by ChandanVerma** [modelscope/modelscope#280]
I was trying to download the checkpoints for the model : damo/multi-modal_hitea_video-captioning_base_en/

It took almost 1 hr to download 10Mb of it and it got reset due to connection failure. Guys if you claim to open source these models at least try to make sure that it can be consumed by everyone for other downstream task. If not its better to make it a private repo. Was really excited with the work you were doing but really disappointed what it turned out to be.

Thanks

**Comment by yingdachen** [comment]
thank you for bringing this to our attension. ineed we are aware that network connection can be flaky when accesing modelscope from outside of china, where most of our host servers are located. we are working on introducing hosting servels in multiple locations across the globe to allow automatic CDN, situations should improve by then, thanks.
