### ISSUE TITLE
Running error in python=3.9

### ISSUE THREAD

**Issue by Zjq9409** [modelscope/modelscope#281]
**Describe the bug**

Running an error in python==3.9, but can be run in 3.7

>>> done with compiling and loading fused kernels. Compilation time: 2.010 seconds
{'text': '程序员脱发用什么洗发水好?\n脱发是一种常见的现象,很多人都有脱发的烦恼,脱发严重的人,不仅影响个人形象,而且脱发还会影响到患者的心理健康,那么脱发用什么洗发水好?\n脱发是一种常见的现象,很多人都有脱发的烦恼,脱发严重的人,不仅影响个人形象,而且脱发还会影响'}
Exception ignored in: <function DistributedPipeline.__del__ at 0x7fc3212e6280>
Traceback (most recent call last):
  File "/home/intel/zjq/anaconda3/envs/bloom/lib/python3.9/site-packages/modelscope/pipelines/base.py", line 467, in __del__
  File "/home/intel/zjq/anaconda3/envs/bloom/lib/python3.9/multiprocessing/pool.py", line 652, in terminate
AttributeError: 'NoneType' object has no attribute 'debug'
Exception ignored in: <function Pool.__del__ at 0x7fc1ffae9a60>
Traceback (most recent call last):
  File "/home/intel/zjq/anaconda3/envs/bloom/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
  File "/home/intel/zjq/anaconda3/envs/bloom/lib/python3.9/multiprocessing/queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

**To Reproduce**
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

if __name__ == '__main__':
    input = '程序员脱发用什么洗发水'
    #input = '天气不错'
    model_id = 'damo/nlp_gpt3_text-generation_1.3B'
    pipe = pipeline(Tasks.text_generation, model=model_id)
    print(pipe(input))

**Your Environments (__required__)**
* OS: Linux intel-02 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* CPU: 
* Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          112
On-line CPU(s) list:             0-111
Thread(s) per core:              2
Core(s) per socket:              28
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel

**Comment by wenmengzhou** [comment]
@Firmament-cyou  please look at this problem and verify it with the newested version
