### ISSUE TITLE
FQA  face quality assessment outputs. 

### ISSUE THREAD

**Issue by MIaomiao426** [modelscope/modelscope#288]
Can someone tell me what exactly do the ten scores of the face quality assessment output correspond to?

**Comment by ljdang** [comment]
测试了下第一个数值基本都是0.99以上，感觉模型输出不是很对

**Comment by MIaomiao426** [comment]
> 测试了下第一个数值基本都是0.99以上，感觉模型输出不是很对

确实是这样，不过我拿一些图片做过测试，整体求平均之后分数倒也说的过去
