### ISSUE TITLE
将任意两张人脸图输入FRFM-large 这个模型，输出的向量做余弦相似度都在0.99以上

### ISSUE THREAD

**Issue by xyzkk3** [modelscope/modelscope#290]
问题如标题，modelscope版本1.5.2
Model revision not specified, use the latest revision: v1.0
用的是范例代码

**Comment by hariag** [comment]
出来的特征没l2 norm. 得再做一次

**Comment by xyzkk3** [comment]
> 出来的特征没l2 norm. 得再做一次

做了，我l2norm之后还是原来的值
