### ISSUE TITLE
GPU加载模型，内存占用比较大

### ISSUE THREAD

**Issue by njustczr** [modelscope/modelscope#299]
我把model-scope起了一个flask服务，GPU加载模型，单个falsk服务内存也要占1.5GB，另起一个没有model-scope的flask服务，内存基本不占，问下为啥加载model-scope占用这么多内存？

**Comment by wenmengzhou** [comment]
一般模型权重是会先加载到内存，然后加载到显存，另外基础的机器学习框架tensorflow / pytorch也会有一定的内存占用
