### ISSUE TITLE
添加对视频流的支持

### ISSUE THREAD

**Issue by spencerswagger** [modelscope/modelscope#304]
目前针对视频的模型只能引入一段视频文件用于分析，但对于一些特定的模型或场景，需要使用视频流作为入参而不是一段静态视频，以获得更好的应用。

**Comment by yingdachen** [comment]
具体哪个模型？

**Comment by spencerswagger** [comment]
@yingdachen 例如“damo/cv_yolov5_video-multi-object-tracking_fairmot 视频多目标跟踪-行人”这个模型
