### ISSUE TITLE
OCR.vitstr forward() 

### ISSUE THREAD

**Issue by BoxFishLab** [modelscope/modelscope#313]
There is a code in the OCR.vitstr forward function.         
        features_1d_concat = torch.ones(x.shape[0] // 3, 201, x.shape[2]).type_as(x)
        features_1d_concat[:, :69, :] = ap[:, 0, :69, :]
        features_1d_concat[:, 69:69 + 63, :] = ap[:, 1, 6:-6, :]
        features_1d_concat[:, 69 + 63:, :] = ap[:, 2, 6:, :]
Not quite sure why this is necessary

**Comment by wenmengzhou** [comment]
close  stabled issue
