### ISSUE TITLE
ZhipuAI/Multilingual-GLM-Summarization-zh 测试用例报错

### ISSUE THREAD

**Issue by xiabingbao-ok** [modelscope/modelscope#317]
from modelscope.models import Model
from modelscope.pipelines import pipeline
from modelscope.preprocessors import MGLMSummarizationPreprocessor
from modelscope.utils.constant import Tasks

model = 'ZhipuAI/Multilingual-GLM-Summarization-zh'
preprocessor = MGLMSummarizationPreprocessor()
pipe = pipeline(
    task=Tasks.text_summarization,
    model=model,
    preprocessor=preprocessor,
    model_revision='v1.0.1',
)
result = pipe(
    '据中国载人航天工程办公室消息，北京时间2022年10月25日，梦天实验舱与长征五号B遥四运载火箭组合体已转运至发射区。后续将按计划开展发射前各项功能检查和联合测试等工作，计划于近日择机实施发射。目前，文昌航天发射场设施设备状态良好，参试各单位正在加紧开展任务准备，全力以赴确保空间站建造任务决战决胜。'
)  
print(result)

报错信息：
from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)

**Comment by wenmengzhou** [comment]
在modelscope notebook中跑会报错吗？ 怀疑是pyramid版本问题

**Comment by xiabingbao-ok** [comment]
> 在modelscope notebook中跑会报错吗？ 怀疑是pyramid版本问题

没在 modelscope notebook中试过，需要降低pytamid版本？？？
