### ISSUE TITLE
OCR识别模型支持本地LMDB文件训练

### ISSUE THREAD

**Issue by vance-coder** [modelscope/modelscope#320]
读光-文字识别-行识别模型-中英-通用领域
尝试使用本地文件进行训练，但是一直没找到好的办法
尝试使用Demo的方式，传入local_lmdb但是报错： TypeError: init() got an unexpected keyword argument 'local_lmdb'

**Comment by wenmengzhou** [comment]
which ocr recognition model do you use?

**Comment by vance-coder** [comment]
> which ocr recognition model do you use?

damo/cv_convnextTiny_ocr-recognition-general_damo

**Comment by lipeng1109** [comment]
> 

我也想使用lmdb数据进行训练，不知道怎么加载自己的数据集，现在有好的方案了吗

**Comment by lipeng1109** [comment]
> > which ocr recognition model do you use?
> 
> damo/cv_convnextTiny_ocr-recognition-general_damo

我也想使用本地的lmdb数据进行训练，你现在找到好的办法加载本地数据了吗

**Comment by yingdachen** [comment]
this particular model damo/cv_convnextTiny_ocr-recognition-general_damo does not support finetune.

you may try the following two models:
https://modelscope.cn/models/damo/cv_resnet18_ocr-detection-db-line-level_damo
https://modelscope.cn/models/damo/cv_crnn_ocr-recognition-general_damo/summary

**Comment by lipeng1109** [comment]
> this particular model damo/cv_convnextTiny_ocr-recognition-general_damo does not support finetune.
> 
> you may try the following two models: https://modelscope.cn/models/damo/cv_resnet18_ocr-detection-db-line-level_damo https://modelscope.cn/models/damo/cv_crnn_ocr-recognition-general_damo/summary

你好，我就是使用的cv_crnn_ocr-recognition-general_damo尝试识别模型训练，按照文档上的本地lmdb配置方式，发现也会指向远程数据仓库，不能成功加载本地数据。现在是不支持直接加载本地数据吗？使用流程是需要将数据托管到modelscope进行使用吗

**Comment by wangxingjun778** [comment]
> 

目前对于.mdb格式文件，暂时还不支持直接从本地加载并解析，目前的方式是通过sdk连接到hub端加载到本地缓存，然后在进行模型finetune时，其预处理逻辑会自动解析文件夹结构并读入.mdb数据；

具体地，对于cv_crnn_ocr-recognition-general_damo这个模型所使用的的数据集，ICDAR13_HCTR_Dataset，加载：

ds = MsDataset.load('damo/ICDAR13_HCTR_Dataset', split='test')
print(next(iter(ds)))

默认存放路径在：
~/.cache/modelscope/hub/datasets/damo/ICDAR13_HCTR_Dataset/master/data_files/extracted/de4ca3f5b45bfdcb3bb83cadbe4435748eab0ec1f8a0eee5eb67177265cf6a4a

即为对应的文件夹结构，里面存放的就是lmdb数据目录。

**Comment by lipeng1109** [comment]
> > 
> 
> 目前对于.mdb格式文件，暂时还不支持直接从本地加载并解析，目前的方式是通过sdk连接到hub端加载到本地缓存，然后在进行模型finetune时，其预处理逻辑会自动解析文件夹结构并读入.mdb数据；
> 
> 具体地，对于cv_crnn_ocr-recognition-general_damo这个模型所使用的的数据集，ICDAR13_HCTR_Dataset，加载：
> 
> ds = MsDataset.load('damo/ICDAR13_HCTR_Dataset', split='test') print(next(iter(ds)))
> 
> 默认存放路径在： ~/.cache/modelscope/hub/datasets/damo/ICDAR13_HCTR_Dataset/master/data_files/extracted/de4ca3f5b45bfdcb3bb83cadbe4435748eab0ec1f8a0eee5eb67177265cf6a4a
> 
> 即为对应的文件夹结构，里面存放的就是lmdb数据目录。

你好，后续有计划支持读取本地lmdb数据进行训练吗

**Comment by wenmengzhou** [comment]
您好，暂时没有计划
