### ISSUE TITLE
创空间巨bug

### ISSUE THREAD

**Issue by dingli06** [modelscope/modelscope#321]
![1686030750928](https://github.com/modelscope/modelscope/assets/63959467/ff034177-9c47-41bc-a10e-9091b6f04c30)
空间莫名其妙运行一段时间后会报这种错.........，且是重启以后才会有的

**Comment by zzclynn** [comment]
具体哪个创空间链接发一下

**Comment by wenmengzhou** [comment]
看起来是安装了高版本的mm系列库需要安装mmengine？ 尝试限定低版本的mm库
