### ISSUE TITLE
请问何时释放CoROM语义相关性-中文-通用领域-【base】模型能力？

### ISSUE THREAD

**Issue by favbox** [modelscope/modelscope#322]
CoROM语义相关性-英文-通用领域-base(nlp_corom_passage-ranking_chinese-base)已经提供，请问 CoROM 对应的中文语义相关性模型大概何时会开放出来？

**Comment by wenmengzhou** [comment]
try this one:  https://modelscope.cn/models/damo/nlp_corom_passage-ranking_chinese-tiny/summary
