### ISSUE TITLE
BAStructBERT分词-中文-新闻领域-base模型 打包后运行出错

### ISSUE THREAD

**Issue by gerry520** [modelscope/modelscope#324]
OS：Window
python==3.7.16
torch==1.13.1
modelscope==1.6.1
torchaudio ==0.13.1
funasr==0.5.7
transformers = 4.29.1
tqdm = 4.65.0
模型：BAStructBERT分词-中文-新闻领域-base damo/nlp_structbert_word-segmentation_chinese-base
代码 https://www.modelscope.cn/models/damo/nlp_structbert_word-segmentation_chinese-base/summary 中的代码范例，pyinstaller 打包在文件里面后，手动添加transformers，modelscope，funasr，importlib_metadata，datasets，librosa，jamo，tokenizers，torchaudio
报错：
运行exe
![df66578ca11c8b63ab7220fd5f35080](https://github.com/modelscope/modelscope/assets/64216665/0044a5f1-e7f1-4172-a0bb-a197edc7b31a)

importlib_metadata.PackageNotError:No package was found for the 'tqdm >=4.27'……
try pip install transformers -U or pip install -e……
困惑：
打包后会有一些依赖需要手动添加，但是比较难的点是需要添加哪些依赖

**Comment by gerry520** [comment]
我的tqdm = 4.65.0

**Comment by wenmengzhou** [comment]
可以检查下打包后的环境，从报错来看是tqdm版本问题

**Comment by gerry520** [comment]
谢谢，最后我用了笨方法，把整个环境依赖考进去就行了
