### ISSUE TITLE
Videos synthesized by text-to-video model contain watermarks

### ISSUE THREAD

**Issue by nihaomiao** [modelscope/modelscope#325]
Hi, Thanks a lot for your very interesting work! I try to utilize your text-to-video model to generate some videos. But all of them contain watermarks (see below). I am wondering whether it is possible to remove these watermarks. Thanks a lot!

![a_burning_mountain_with_thunderstorm](https://github.com/modelscope/modelscope/assets/39548279/22ceb6cb-169e-4048-963e-7cfe2e5e0670)

![a_burning_mountain](https://github.com/modelscope/modelscope/assets/39548279/dd2a844b-64b1-405b-8328-1f497f241ef0)

![Hyper-realistic_photo_of_an_abandoned_industrial_site_during_a_storm](https://github.com/modelscope/modelscope/assets/39548279/5fbb7d0d-c9e6-4699-8f0c-7f63c281d1b7)

**Comment by wenmengzhou** [comment]
Thank you, we have also noticed this issue, and we will resolve it as soon as possible and release the new version

**Comment by nihaomiao** [comment]
Great! Looking forward to your new version!
