### ISSUE TITLE
在哪里下载表格检测模型的onnx文件？python怎么调用？

### ISSUE THREAD

**Issue by nissansz** [modelscope/modelscope#327]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

在哪里下载表格检测模型的onnx文件？python怎么调用？
[读光-表格结构识别-有线表格](https://www.modelscope.cn/models/damo/cv_dla34_table-structure-recognition_cycle-centernet)
[读光-表格结构识别-无线表格](https://www.modelscope.cn/models/damo/cv_resnet-transformer_table-structure-recognition_lore/summary)

**Comment by wenmengzhou** [comment]
目前没有提供onnx模型，可以先试用python接口按照示例代码调用

**Comment by nissansz** [comment]
现在除了onnx，其余模型都要一大堆包，安装总会报错

  Using cached av-10.0.0-cp38-cp38-win_amd64.whl (25.4 MB)
Collecting bmt-clipit>=1.0 (from modelscope[cv])
  Using cached https://modelscope.oss-cn-beijing.aliyuncs.com/releases/dependencies/bmt_clipit-1.0-py3-none-any.whl (42 kB)
Collecting chumpy (from modelscope[cv])
  Using cached chumpy-0.70.tar.gz (50 kB)
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in C:\Users\Ni\AppData\Local\Temp\pip-pip-egg-info-bhivo0_t
