### ISSUE TITLE
a [BUG] for the latest version

### ISSUE THREAD

**Issue by ticoAg** [modelscope/modelscope#330]
/modelscope/hub/api.py
```python
class HubApi:
    def push_model():
        line 325
```
场景:
未在主页手工创建模型仓库，通过以下模式自动创建仓库
```python
api = HubApi()
api.login(YOUR_ACCESS_TOKEN)
api.push_model(
    model_id="", 
    model_dir=""
)
```
line 325:
branches变量值大概为(不是很精准) ['remote master \n -> master']
此时revision = 'master'
则会执行line326 line 327 Create new branch逻辑
但此时master branch 已存在
报错: 创建一个已存在的分支
目前line 325调整为
```python
if revision not in branches[0]:
```
暂时解决模型初始化创建仓库并推送问题

**Comment by ticoAg** [comment]
GitError: stdout: , stderr: fatal: a branch named 'master' already exists

**Comment by wenmengzhou** [comment]
welcome to create a pull request to fix this problem,   if any problem,  you can ask @liuyhwangyh  for help
