### ISSUE TITLE
AI-ModelScope/BELLE-LLaMA-13B-2M 预测脚本报错

### ISSUE THREAD

**Issue by xiabingbao-ok** [modelscope/modelscope#338]
环境：
torch                  1.11.0
torchaudio             0.11.0
torchvision            0.12.0
cuda                   10.2
modelscope       1.6.1

from modelscope.utils.constant import Tasks
from modelscope.pipelines import pipeline
pipe = pipeline(task=Tasks.text_generation, model='AI-ModelScope/BELLE-LLaMA-13B-2M', model_revision='v1.0.1')
prompt = '你好'
inputs = 'Human: ' + prompt.strip() + '\n\nAssistant:'
rets = pipe(inputs)
print(rets)

报错信息：
RecursionError: BELLELLaMA13B2MTextGenerationPipeline: maximum recursion depth exceeded while calling a Python object

**Comment by wenmengzhou** [comment]
this issue has been fixed, please try it again using 1.7.0 version
