### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flynnamy** [modelscope/modelscope#34]
I run face_2d_keypoints task but it has an error:bboxes, scores, labels = bboxes[inds], scores[inds], labels[inds] RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu). It seems that it has bug in detection!

**Comment by wenmengzhou** [comment]
can you provide the environment info, running code  and original output error info

**Comment by yingdachen** [comment]
close as fail-to-reproduce
