### ISSUE TITLE
Can not create account with overseas cell phone number

### ISSUE THREAD

**Issue by wyy511511** [modelscope/modelscope#344]
**Describe the bug**
When I want to register with an overseas cell phone number (US), I can receive the Chinese text message with the verification code normally, but when I enter my account name, it reports that my cell phone number is in the wrong format. I had to switch to a mainland China phone number again.

**To Reproduce**

1.create account with overseas cell phone number.
2. After verify text message code and input your account name, it will alert and fail.

**Comment by wenmengzhou** [comment]
oversea cell phone number has been supported, can you provide a dummy phone number and the alert info for us to verify this problem

**Comment by rin2401** [comment]
i have the same problem, when input username after verification code
+84... 
手机号码格式不正确，请重新输入
The mobile phone number format is incorrect, please re-enter it.

**Comment by gigadeplex** [comment]
Well guys you don't actually need a Chinese number to register. Even if the website says so... 🤫

**Comment by pribadihcr** [comment]
> Well guys you don't actually need a Chinese number to register. Even if the website says so... 🤫

How did you register without a  Chinese number?

**Comment by doctorpangloss** [comment]
The CSDN flow is still showing

```
手机号码格式不正确，请重新输入
```

**Comment by wyy511511** [comment]
> The CSDN flow is still showing
> 
> ```
> 手机号码格式不正确，请重新输入
> ```

maybe try to  use one time phone number platform

**Comment by Respaired** [comment]
still persists, why is there any need for sms based otp again?
let that be optional like any other websites.

**Comment by shekharbhujbal** [comment]
Mine is got easily done with Indian phone number, received OTP same minute and had no issue setting up username.
