### ISSUE TITLE
微调代码中 mrr@1 指标找不到

### ISSUE THREAD

**Issue by gynnash** [modelscope/modelscope#351]
OS:  linux
Python/C++ Version：python 3.7
Package Version：pytorch 1.11.0+cu102、modelscope-1.6.1
Model：damo/mgeo_backbone_chinese_base
evaluation配置：
 "evaluation": {
          "dataloader": {
              "batch_size_per_gpu": 16,
              "workers_per_gpu": 16,
              "shuffle": false
          },
          "period": {
              "by_epoch": true
          },
          "metrics": "mrr@1"
      }
问题描述：
KeyError: 'mrr@1 is not in the metrics registry group default. Please make sure the correct version of ModelScope library is used.'
![image](https://github.com/modelscope/modelscope/assets/4327548/238c8b3e-278c-41e9-ac68-75401567af0d)

**Comment by Firmament-cyou** [comment]
You can try to change the `cfg['evaluation']['metrics'] = 'mrr@1'` which in cfg_modify_fn function to `cfg['evaluation']['metrics'] = 'text-ranking-metric'`.
