### ISSUE TITLE
about  HTTPError  ?

### ISSUE THREAD

**Issue by zhanghongyong123456** [modelscope/modelscope#361]
this   my  error about  modelscope
my environment installation：
conda create -n dctnet python=3.7
conda activate dctnet
pip install --upgrade tensorflow-gpu==1.15 # GPU support, use tensorflow for CPU only
pip install "modelscope[cv]==1.3.2" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
pip install "modelscope[multi-modal]==1.3.2" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

![image](https://github.com/modelscope/modelscope/assets/48466610/cb7c96f9-d503-4ea2-bbd2-9c2482d1614f)

**Comment by wenmengzhou** [comment]
the model you used does not exists, please use https://modelscope.cn/models/damo/cv_unet_person-image-cartoon_compound-models/summary

**Comment by zhanghongyong123456** [comment]
> the model you used does not exists, please use https://modelscope.cn/models/damo/cv_unet_person-image-cartoon_compound-models/summary

非常感谢您的解答，麻烦再请教一下这个数据集格式对吗，正确的应该是什么样子的
https://github.com/menyifang/DCT-Net/issues/60
