### ISSUE TITLE
文档OCR识别模型

### ISSUE THREAD

**Issue by njustczr** [modelscope/modelscope#363]
ocr识别模型（不带检测模型）
document_recognition = pipeline(Tasks.ocr_recognition, model='damo/cv_convnextTiny_ocr-recognition-document_damo', device='cuda:0')
能优化对空格的识别吗？似乎一行文本带空格，空格符号无法识别出来

**Comment by wenmengzhou** [comment]
空格一般识别的不会太好，建议先用检测模型检测不同的文本块，然后针对不同的文本块使用航识别模型

**Comment by njustczr** [comment]
> 空格一般识别的不会太好，建议先用检测模型检测不同的文本块，然后针对不同的文本块使用航识别模型

我们现在就是用自己的检测模型，只使用了你们的识别模型，按行调用识别模型的，空格识别的不太好😂

**Comment by njustczr** [comment]
> 空格一般识别的不会太好，建议先用检测模型检测不同的文本块，然后针对不同的文本块使用航识别模型

大佬你们是识别的时候，数据没标注空格吗？我感觉识别的数据集空格加上，识别起来效果应该还可以的，但是我目前没那么大的识别数据集。

**Comment by njustczr** [comment]
> > 空格一般识别的不会太好，建议先用检测模型检测不同的文本块，然后针对不同的文本块使用航识别模型
> 
> 大佬你们是识别的时候，数据没标注空格吗？我感觉识别的数据集空格加上，识别起来效果应该还可以的，但是我目前没那么大的识别数据集。

![image](https://github.com/modelscope/modelscope/assets/30426320/e9c5aa29-29d3-41c3-b816-6e8e6cde0144)
像这种 “影像学检查”  后面的空格这种都无法识别到
