### ISSUE TITLE
Multi-threaded Downloading Dataset

### ISSUE THREAD

**Issue by yinanhe** [modelscope/modelscope#366]
**Describe the feature**
Currently, downloading the dataset is done using a single thread. Could it be possible to perform multi-threaded downloads based on the existing meta file?

**Motivation**
When downloading the mPLUG-youku dataset, I noticed that there is a large number of files. Even when using `MSdataset.load_dataset` with `use_streaming`, which returns a generator, consuming this generator with multiple threads still results in slow downloads due to the single-threaded data retrieval from OSS. Is there a way for me to execute multi-threaded data downloads based on my token and cached meta files?

**Comment by wenmengzhou** [comment]
@wangxingjun778  pls look at this issue

**Comment by FredHuang16** [comment]
Have same problem. Any update of this issue?  @wenmengzhou @wangxingjun778

**Comment by 459737087** [comment]
Hi ! Did you solve it?
