### ISSUE TITLE
是否可以将数据集相关的方法从modelscope中单独为一个独立的包？

### ISSUE THREAD

**Issue by SWHL** [modelscope/modelscope#369]
### 诉求：
- 希望可以有一个单独管理魔搭数据集的轻量包，类似于Hugging Face中的[`datasets`](https://github.com/huggingface/datasets)

### 缘起：
- **初衷：** 想着在魔搭平台上托管自己构建的，用于测试基准的小型数据集。相比于Hugging Face，对国内用户友好。
- **现实：** 通过阅读[魔搭数据集使用指南](https://modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)文档，发现：**如果想要使用魔搭上的数据集，就要安装整个modelscope包。** modelscope包依赖众多，而我只需要其中数据集相关的部分，其余依赖大部分用不到。

比较喜欢魔搭这个平台，利好国内开发者，希望可以越来越好。😁

**Comment by wenmengzhou** [comment]
try  'pip install modelscope'  which will install the necessary dependencies for the core function of modelscope such as modelhub and dataset

**Comment by SWHL** [comment]
OK， I will try, thanks.
