### ISSUE TITLE
Question about training dataset for text-to-video models

### ISSUE THREAD

**Issue by nihaomiao** [modelscope/modelscope#378]
Hi, thanks a lot for your interesting work! I am wondering whether you can give more details about the training dataset you used for text-to-video models. On your official website, you simply mentioned "The training data includes LAION5B, ImageNet, Webvid and **other public datasets**."  So what do other public datasets include? Thanks!

**Comment by WangJiuniu** [comment]
Thanks. We mainly use LAION5B and Webvid. We also use UCF101 and MSR-VTT during experiments (evaluation).

**Comment by nihaomiao** [comment]
@WangJiuniu, thanks a lot for your reply! I am a Ph.D. student and we are doing some research about applying pre-trained models to new domain (out-of-distribution) data. So we need to figure out all the training datasets of your pre-trained model. For the training, besides LAION5B and WebVid, do you use other datasets? And you mentioned that UCF101 and MSR-VTT for evaluation. So do you also include them in your training set? Thanks for your time!
