### ISSUE TITLE
离线如何源码安装？如果仅需要audio相关模型？

### ISSUE THREAD

**Issue by zyjcsf** [modelscope/modelscope#38]
您好，我想请问下，离线没有网的Linux环境，如何通过源码安装？我仅需要audio相关的模块；

**Comment by yingdachen** [comment]
即便是源码，dependency也是需要pip install安装的。完全没有网会比较困难

**Comment by zyjcsf** [comment]
您好，我现在在进行源码安装，python setup.py install ，然后对于audio下面的一些库，比如easyasr这些在https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html中的包应该从哪里可以下载安装？谢谢。

**Comment by yingdachen** [comment]
pip install easyasr -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
