### ISSUE TITLE
在做说话人身份确认是，只能传入.wav文件，增加6段代码，即可实现输入流式数据，不需传入.wav文件

### ISSUE THREAD

**Issue by 2662448726** [modelscope/modelscope#380]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.
使用 model='damo/speech_campplus_sv_zh-cn_16k-common'模型，在做说话人身份确认是，只能传入.wav文件，在/modelscope/pipelines/audio/speaker_verification_light_pipeline.py文件的基础上在99行下面增加了 elif isinstance(inputs[i], np.ndarray):
                data = inputs[i]
                if len(data.shape) == 2:
                     data = data[:, 0]
                output['data%d' %
                       (i + 1)] = torch.from_numpy(data).unsqueeze(0)
该代码即可通过传入流式的数据，不需通过传入.wav文件，即可进行比较，希望可以对该代码增加一个补丁

**Comment by wenmengzhou** [comment]
Thank you for your feedback, and you're welcome to submit a PR to implement this feature as well.
