### ISSUE TITLE
下载模型有问题

### ISSUE THREAD

**Issue by lym0302** [modelscope/modelscope#381]
使用下述代码：
from modelscope.pipelines import pipeline
p = pipeline('text-classification', 'damo/nlp_structbert_qd_spoken_chinese-base') 

发现下载模型有问题：
modelscope.hub.errors.NoValidRevisionError: The model: damo/nlp_structbert_qd_spoken_chinese-base has no valid revision!

麻烦帮忙看看，谢谢

**Comment by lifenqi** [comment]
are you ok？
