### ISSUE TITLE
text-classification 使用的时候有问题

### ISSUE THREAD

**Issue by lym0302** [modelscope/modelscope#382]
执行下述代码：
from modelscope.models import Model
text_classification = pipeline('text-classification',model='mypath/nlp_structbert_qd_spoken_chinese-base')
output = text_classification('今天天气不错，适合出去游玩')

出现下述问题：
TypeError: _batch_encode_plus() got an unexpected keyword argument 'label2id'

麻烦帮忙看看，谢谢

**Comment by yinzhang809** [comment]
请问后来是怎么解决的呀，遇到了同样的问题

**Comment by cowcomic** [comment]
怎么解决的啊，遇到同样的问题了

**Comment by lqzzy** [comment]
@lym0302 请问你是解决了吗，我也有相同的问题，能否请你告诉我该怎么解决呢，网上搜不到这方面的资料
