### ISSUE TITLE
fatal: Out of memory, realloc failed

### ISSUE THREAD

**Issue by hezhiyang2000** [modelscope/modelscope#388]
**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
On git cloning the reposit https://modelscope.cn/models/AI-ModelScope/stable-diffusion-v1.5-no-safetensor/summary using command 
```shell
git clone https://www.modelscope.cn/AI-ModelScope/stable-diffusion-v1.5-no-safetensor.git
```
It shows 
```shell
Cloning into 'stable-diffusion-v1.5-no-safetensor'...
remote: Enumerating objects: 58, done.
remote: Total 58 (delta 0), reused 0 (delta 0), pack-reused 58
Unpacking objects: 100% (58/58), done.
Downloading safety_checker/pytorch_model.bin (1.2 GB)
Downloading text_encoder/pytorch_model.bin (492 MB)
Downloading unet/diffusion_pytorch_model.bin (3.4 GB)
Downloading v1-5-pruned-emaonly.ckpt (4.3 GB)
Possibly malformed smudge on Windows: see `git lfs help smudge` for more info.
Downloading v1-5-pruned.ckpt (7.7 GB)
fatal: Out of memory, realloc failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```
After searching about the question, I think the key error is `fatal: Out of memory, realloc failed` which is closely related with the git server.

**To Reproduce**
* What command or script did you run?
> git clone https://www.modelscope.cn/AI-ModelScope/stable-diffusion-v1.5-no-safetensor.git
* Did you make any modifications on the code or config? Did you understand what you have modified? No
* What dataset did you use? No

**Your Environments (__required__)**
* OS: Linux diffuser1-5485 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* CPU:
* Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz
Stepping:              6
CPU MHz:               2095.078
BogoMIPS:              4190.15
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single rsb_ctxsw ibrs ibpb fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512vbmi pku ospke avx512_vpopcntdq spec_ctrl

**Comment by wenmengzhou** [comment]
you can use api from modelscope library to download this model which may need few memory:

```python
from modelscope.hub.snapshot_download import snapshot_download

model_dir = snapshot_download('damo/nlp_xlmr_named-entity-recognition_viet-ecommerce-title', cache_dir='path/to/local/dir', revision='v1.0.1')
```
