### ISSUE TITLE
https://www.modelscope.cn/models/damo/cv_dla34_table-structure-recognition_cycle-centernet/summary  这个表格模型，有谁有onnx版本吗？安装了个ubutn虚拟机，环境都安装失败了

### ISSUE THREAD

**Issue by nissansz** [modelscope/modelscope#390]
https://www.modelscope.cn/models/damo/cv_dla34_table-structure-recognition_cycle-centernet/summary  这个表格模型，有谁有onnx版本吗？安装了个ubutn虚拟机，环境都安装失败了

**Comment by phamkhactu** [comment]
Hi @nissansz,

Do you have any information?
