### ISSUE TITLE
BaSSL视频场景分割大视频时显存溢出

### ISSUE THREAD

**Issue by yfq512** [modelscope/modelscope#392]
**Describe the feature**
> 使用[BaSSL视频场景分割](https://modelscope.cn/models/damo/cv_resnet50-bert_video-scene-segmentation_movienet/summary)显存溢出
示例代码：
```
result = video_scene_seg('https://modelscope.oss-cn-beijing.aliyuncs.com/test/videos/movie_scene_segmentation_test_video.mp4')
```
> 当视频较大时，程序会由于显存不够而报错:
```
RuntimeError: CUDA out of memory. Tried to allocate 1.63 GiB (GPU 0; 23.65 GiB total capacity; 6.53 GiB already allocated; 381.44 MiB free; 7.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to
avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
> 我的测试视频信息(10分钟，640x360，15 fps):
```
  Duration: 00:10:00.02, start: 0.000000, bitrate: 483 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 640x360, 349 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc 
```
> 我测试几分钟的视频是正常的，但测试更大的视频就会报错，请问是否有控制线程等参数的方式使得程序不会占用大量显存？

**Comment by pida0** [comment]
请问调用pipeline时候的batch_size是多少？以及使用的显卡显存是多少？

**Comment by yfq512** [comment]
@pida0 感谢回复，batch_size没设置，示例上没看到这个参数😂。由于我的卡也跑了别的程序，仅剩10G的显存。

**Comment by pida0** [comment]
可以直接在configuration.json文件中修改pipeline的batch_size_per_gpu参数，默认的batch_size是32，所以会导致显存爆了。目前模型设置了按照batch_size读取视频帧，已经在显存上做了控制了，如果显存不够的话，建议还是直接调低batch_size
![image](https://github.com/modelscope/modelscope/assets/26628832/fc4d8a3a-8e6f-4cd2-91f7-9e4ee094e298)

**Comment by yfq512** [comment]
batch_size 可以直接传参进去么，如 
```
pipeline(Tasks.movie_scene_segmentation, model='damo/cv_resnet50-bert_video-scene-segmentation_movienet', batch_size_per_gpu=4)
```
我没找到这个文件：configuration.json

**Comment by pida0** [comment]
抱歉，目前暂时没有办法直接传参进去，后面我会提交一个fix。目前要修改的话只能从文件改，配置文件一般位于`YOUR_HOME_PATH/.cache/modelscope/hub/damo/cv_resnet50-bert_video-scene-segmentation_movienet`文件夹下面

**Comment by yfq512** [comment]
我将batch_size改小了确实可以处理之前处理不了的视频（20分钟），但处理更长的视频（50分钟）会依旧报错。目前只能把大视频分割，然后单线程处理后又把结果拼起来。😂
