### ISSUE TITLE
is data load can set MODELSCOPE_CACHE in bashrc as the model load not load from /root/.cache as default?

### ISSUE THREAD

**Issue by foocker** [modelscope/modelscope#400]
as the title. 
the main resason is, the space of /root is samll in general.

**Comment by yingdachen** [comment]
@wangxingjun778 please take a look to see if it is possible to control dataset storage location via MODELSCOPE_CACHE as well.

**Comment by wangxingjun778** [comment]
2 ways to set the local cache for datasets:

1. MsDataset.load(..., cache_dir='/your/cache_dir')
2. set env: MS_CACHE_HOME to your dir in bashrc

**Comment by yingdachen** [comment]
> MODELSCOPE_CACHE

it is worth considering consolidate the to env var into one (MODELSCOPE_CACHE)
