### ISSUE TITLE
创空间依托的资源是什么

### ISSUE THREAD

**Issue by 28H2O2** [modelscope/modelscope#401]
想知道提供给创空间的资源是什么？
比如CPU/GPU以及有多少的硬盘存储资源？（这一点似乎ModelScope的官方文档并没有说明）
是否是易失性存储（即关闭创空间之后能否保存记录）
比如能否在创空间上实现注册等需要记录用户少量信息的功能

**Comment by thomas-yanxin** [comment]
https://modelscope.cn/docs/%E5%88%9B%E7%A9%BA%E9%97%B4%E5%8D%A1%E7%89%87#%E5%88%9B%E7%A9%BA%E9%97%B4%E5%8D%A1%E7%89%87%E7%9A%84%E5%85%83%E6%95%B0%E6%8D%AE

**Comment by Joe-Hall-Lee** [comment]
我好像在文档里没看到磁盘空间有多大，是和 Notebook 一样的 100G 吗？
