### ISSUE TITLE
自动标注的疑问

### ISSUE THREAD

**Issue by laishujie** [modelscope/modelscope#411]
使用了run_auto_label 标注了之后，发现有些拼音是错误的比如下面的一条

62	袜子摊#1小老板#1陈永全#4
	wa4 zi5 tan1 xiao3 lao2 ban3 chen2 yong3 qvan2

全 不应该是 quan2 么？子应该是 zi1 如果我要矫正的话，应该怎么做？ 望解答谢谢

**Comment by zhaojie-666** [comment]
这个应该是音素，ü就是用v来表示，这个zi5应该表示的是轻声，不然第一声你读着也有点怪
