### ISSUE TITLE
无法利用gpu进行推理

### ISSUE THREAD

**Issue by 312shan** [modelscope/modelscope#417]
推理很慢！！！如何利用gpu进行推理？？？？
```python

pipeline = pipeline(Tasks.faq_question_answering, 'damo/nlp_mgimn_faq-question-answering_chinese-base',
                    model_revision="v1.0.0", device='gpu')
```
虽然打印设备显示是 gpu ，但是貌似不支持gpu推理，还没有用cpu快。

**Comment by slin000111** [comment]
> 推理很慢！！！如何利用gpu进行推理？？？？
> 
> ```python
> pipeline = pipeline(Tasks.faq_question_answering, 'damo/nlp_mgimn_faq-question-answering_chinese-base',
>                     model_revision="v1.0.0", device='gpu')
> ```
> 
> 虽然打印设备显示是 gpu ，但是貌似不支持gpu推理，还没有用cpu快。
本地测试，该pipeline默认使用gpu进行推理（您可以不加device='gpu'），gpu推理速度比cpu快（大约是cpu推理速度的十几倍，数据可能因设备差异有出入）。出现gpu推理比cpu推理慢的情况，可能和首次使用该模型时下载模型文件等因素有关，或者pipeline初始化被嵌入到了循环中。

**Comment by zhaofeng3012** [comment]
> > 推理很慢!!如何利用GPU进行推理????
> > ```python
> > pipeline = pipeline(Tasks.faq_question_answering, 'damo/nlp_mgimn_faq-question-answering_chinese-base',
> >                     model_revision="v1.0.0", device='gpu')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 虽然打印设备显示是 gpu ，但是貌似不支持 gpu推理，还没有用 cpu快。 本地测试，该pipeline默认使用GPU进行推理（您可以不加device='gpu'），gpu推理速度比CPU快（大约是CPU推理速度的十几倍，数据可能因设备差异有出入）。出现 GPU 推理比 CPU 推理慢的情况，可能和首次使用该模型时下载模型文件等因素有关，或者pipeline初始化被嵌入到了循环中。

@slin000111 那请问，目前pipeline支持多GPU的情况下指定使用某一张GPU进行推理吗？？

**Comment by im73** [comment]
> 推理很慢！！！如何利用gpu进行推理？？？？
> 
> ```python
> pipeline = pipeline(Tasks.faq_question_answering, 'damo/nlp_mgimn_faq-question-answering_chinese-base',
>                     model_revision="v1.0.0", device='gpu')
> ```
> 
> 虽然打印设备显示是 gpu ，但是貌似不支持gpu推理，还没有用cpu快。 本地测试，该pipeline默认使用gpu进行推理（您可以不加device='gpu'），gpu推理速度比cpu快（大约是cpu推理速度的十几倍，数据可能因设备差异有出入）。出现gpu推理比cpu推理慢的情况，可能和首次使用该模型时下载模型文件等因素有关，或者pipeline初始化被嵌入到了循环中。


我也遇到了同样的问题，pipline指定了gpu，但是模型根本没加载到gpu上,gpu根本没动
我的cuda版本是11.4，modelscope是1.9.4，torch是2.0.1

**Comment by im73** [comment]
> 推理很慢！！！如何利用gpu进行推理？？？？
> 
> ```python
> pipeline = pipeline(Tasks.faq_question_answering, 'damo/nlp_mgimn_faq-question-answering_chinese-base',
>                     model_revision="v1.0.0", device='gpu')
> ```
> 
> 虽然打印设备显示是 gpu ，但是貌似不支持gpu推理，还没有用cpu快。 本地测试，该pipeline默认使用gpu进行推理（您可以不加device='gpu'），gpu推理速度比cpu快（大约是cpu推理速度的十几倍，数据可能因设备差异有出入）。出现gpu推理比cpu推理慢的情况，可能和首次使用该模型时下载模型文件等因素有关，或者pipeline初始化被嵌入到了循环中。

pipeline1 = pipeline(Tasks.faq_question_answering, 'damo/nlp_structbert_faq-question-answering_chinese-base')
我也遇到了同样的问题，pipline指定了gpu，但是模型根本没加载到gpu上,gpu根本没动
我的cuda版本是11.4，modelscope是1.9.4，torch是2.0.1

**Comment by hbo-lambda** [comment]
> > 推理很慢！！！如何利用gpu进行推理？？？？
> > ```python
> > pipeline = pipeline(Tasks.faq_question_answering, 'damo/nlp_mgimn_faq-question-answering_chinese-base',
> >                     model_revision="v1.0.0", device='gpu')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 虽然打印设备显示是 gpu ，但是貌似不支持gpu推理，还没有用cpu快。 本地测试，该pipeline默认使用gpu进行推理（您可以不加device='gpu'），gpu推理速度比cpu快（大约是cpu推理速度的十几倍，数据可能因设备差异有出入）。出现gpu推理比cpu推理慢的情况，可能和首次使用该模型时下载模型文件等因素有关，或者pipeline初始化被嵌入到了循环中。
> 
> 我也遇到了同样的问题，pipline指定了gpu，但是模型根本没加载到gpu上,gpu根本没动 我的cuda版本是11.4，modelscope是1.9.4，torch是2.0.1

最后你们咋解决的啊，我这儿也遇到了

**Comment by huangyan20** [comment]
有是有加载到GPU，GPU显存利用的很少，对比了一下，cpu和gpu效率一样，也是神奇，感觉是没调好
