### ISSUE TITLE
示例文档压缩包中所有图片显示不全

### ISSUE THREAD

**Issue by seawenc** [modelscope/modelscope#426]
示例包路径：http://modelscope-ipynb-hz.oss-cn-hangzhou-internal.aliyuncs.com/default/tutorial_documentation/tutorial_documentation.tar.gz

![截图_选择区域_20230728170546](https://github.com/modelscope/modelscope/assets/40030020/17d5bc67-49d8-4027-bc5d-467cb2348154)

我把它下载下来解压，图片仍然显示不全:

![image](https://github.com/modelscope/modelscope/assets/40030020/3667e08b-bb04-4bb8-b70a-f4aeddeb37c8)

![image](https://github.com/modelscope/modelscope/assets/40030020/dc215a0b-b32d-4147-a6ed-dd48b3acbf52)

**Comment by sewenc** [comment]
下载后本地效果：
![image](https://github.com/modelscope/modelscope/assets/40030020/5c9685ac-704e-4066-9da9-9969f1d5288e)
