### ISSUE TITLE
对于ofa 6b en 模型，当我们使用pipline时能否一张图片生成多个句子？

### ISSUE THREAD

**Issue by lizhiustc** [modelscope/modelscope#43]
对于image caption任务， ofa的其他模型，huggingface上可以找到，并且有一个参数 num_return_sequences 可以控制给定一张图片生成的句子个数，但是对于最大的模型ofa_image-caption_coco_6b_en只有mindscope才有，当我们使用pipline时能否一张图片生成多个句子？mindscope是否有相关参数？

@zhangyichang @wenmengzhou

**Comment by zhangyichang** [comment]
你好，可以参考阿里云开发者社区哈，后面我们会支持接受这个参数
https://developer.aliyun.com/ask/471701
