### ISSUE TITLE
img2video 

### ISSUE THREAD

**Issue by almfahd41** [modelscope/modelscope#438]
does modelscope  do img2video  similar  to runway gn2 ?

**Comment by wenmengzhou** [comment]
It's not available yet, but it's in the plans. Please stay tuned

**Comment by almfahd41** [comment]
> It's not available yet, but it's in the plans. Please stay tuned

i would love to see some sample results if it is possible

**Comment by wenmengzhou** [comment]
https://modelscope.cn/models/damo/Image-to-Video/summary
