### ISSUE TITLE
how can i use fp16 or int8 for inference

### ISSUE THREAD

**Issue by huashiyiqike** [modelscope/modelscope#444]
in pipeline config?

**Comment by wenmengzhou** [comment]
which model?

**Comment by huashiyiqike** [comment]
qianwen-7B, I didn't see the specific config option, but seems to be fp16 already

**Comment by goingHan** [comment]
nlp_raner_named-entity-recognition_chinese-base-literature模型也有同样的问题，推理时该怎么设置精度？

**Comment by wenmengzhou** [comment]
for LLM, you can use code snipets like following

```python
model = AutoModel.from_pretrained(model_name)
# set model precision
model = model.to(torch.bfloat16)
```

for using pipeline in modelscope, you can access the model by pipeline.model  and then set the precision like above
