### ISSUE TITLE
cv_resnet18_ocr-detection-line-level_damo 这个模型什么时候能支持自定义微调？

### ISSUE THREAD

**Issue by jialongP** [modelscope/modelscope#448]
<img width="766" alt="image" src="https://github.com/modelscope/modelscope/assets/75554901/19aae4ff-6e60-42d6-a4f9-524495f2a19c">

**Comment by wenmengzhou** [comment]
try this model: https://modelscope.cn/models/damo/cv_resnet18_ocr-detection-db-line-level_damo/summary
