### ISSUE TITLE
macbookpro2019（intell芯片） 安装ModelScope Libarary [nlp]报错

### ISSUE THREAD

**Issue by handsometong** [modelscope/modelscope#456]
Building wheels for collected packages: safetensors
  Building wheel for safetensors (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for safetensors (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-37
      creating build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      copying py_src/safetensors/paddle.py -> build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      copying py_src/safetensors/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      copying py_src/safetensors/numpy.py -> build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      copying py_src/safetensors/tensorflow.py -> build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      copying py_src/safetensors/torch.py -> build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      copying py_src/safetensors/flax.py -> build/lib.macosx-10.9-x86_64-cpython-37/safetensors
      running build_ext
      running build_rust
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for safetensors
Failed to build safetensors
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects

**Comment by handsometong** [comment]
`ERROR: Cannot install modelscope[nlp]==0.2.3, modelscope[nlp]==0.2.4, modelscope[nlp]==0.2.5, modelscope[nlp]==0.3.1, modelscope[nlp]==0.3.2, modelscope[nlp]==0.3.3, modelscope[nlp]==0.3.4, modelscope[nlp]==0.3.5, modelscope[nlp]==0.3.6, modelscope[nlp]==0.3.7, modelscope[nlp]==0.4.0, modelscope[nlp]==0.4.1, modelscope[nlp]==0.4.2, modelscope[nlp]==0.4.3, modelscope[nlp]==0.4.4, modelscope[nlp]==0.4.5, modelscope[nlp]==0.4.6, modelscope[nlp]==0.4.7, modelscope[nlp]==0.5.0, modelscope[nlp]==0.5.1, modelscope[nlp]==1.0.0, modelscope[nlp]==1.0.1, modelscope[nlp]==1.0.2, modelscope[nlp]==1.0.3, modelscope[nlp]==1.0.4, modelscope[nlp]==1.1.0, modelscope[nlp]==1.1.1, modelscope[nlp]==1.1.2, modelscope[nlp]==1.1.3, modelscope[nlp]==1.1.4, modelscope[nlp]==1.2.0, modelscope[nlp]==1.3.1, modelscope[nlp]==1.4.1, modelscope[nlp]==1.4.3, modelscope[nlp]==1.5.1, modelscope[nlp]==1.6.0, modelscope[nlp]==1.6.1, modelscope[nlp]==1.7.0 and modelscope[nlp]==1.8.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    modelscope[nlp] 1.8.1 depends on stanza; extra == "nlp"
    modelscope[nlp] 1.7.0 depends on stanza; extra == "nlp"
    modelscope[nlp] 1.6.1 depends on datasets<=2.8.0 and >=2.7.0
    modelscope[nlp] 1.6.0 depends on datasets<=2.8.0 and >=2.7.0
    modelscope[nlp] 1.5.1 depends on datasets<=2.8.0 and >=2.7.0
    modelscope[nlp] 1.4.3 depends on jsonplus
    modelscope[nlp] 1.4.1 depends on jsonplus
    modelscope[nlp] 1.3.1 depends on jsonplus
    modelscope[nlp] 1.2.0 depends on easydict
    modelscope[nlp] 1.1.4 depends on datasets<=2.5.2
    modelscope[nlp] 1.1.3 depends on datasets<=2.5.2
    modelscope[nlp] 1.1.2 depends on datasets<=2.5.2
    modelscope[nlp] 1.1.1 depends on datasets<=2.5.2
    modelscope[nlp] 1.1.0 depends on datasets<=2.5.2
    modelscope[nlp] 1.0.4 depends on datasets<=2.5.2
    modelscope[nlp] 1.0.3 depends on datasets<=2.5.2
    modelscope[nlp] 1.0.2 depends on datasets<=2.5.2
    modelscope[nlp] 1.0.1 depends on datasets<=2.5.2
    modelscope[nlp] 1.0.0 depends on opencv-python
    modelscope[nlp] 0.5.1 depends on opencv-python
    modelscope[nlp] 0.5.0 depends on opencv-python
    modelscope[nlp] 0.4.7 depends on opencv-python
    modelscope[nlp] 0.4.6 depends on opencv-python
    modelscope[nlp] 0.4.5 depends on opencv-python
    modelscope[nlp] 0.4.4 depends on opencv-python
    modelscope[nlp] 0.4.3 depends on opencv-python
    modelscope[nlp] 0.4.2 depends on opencv-python
    modelscope[nlp] 0.4.1 depends on opencv-python
    modelscope[nlp] 0.4.0 depends on opencv-python
    modelscope[nlp] 0.3.7 depends on easydict
    modelscope[nlp] 0.3.6 depends on easydict
    modelscope[nlp] 0.3.5 depends on easydict
    modelscope[nlp] 0.3.4 depends on easydict
    modelscope[nlp] 0.3.3 depends on easydict
    modelscope[nlp] 0.3.2 depends on easydict
    modelscope[nlp] 0.3.1 depends on easydict
    modelscope[nlp] 0.2.5 depends on easydict
    modelscope[nlp] 0.2.4 depends on easydict
    modelscope[nlp] 0.2.3 depends on easydict

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by wenmengzhou** [comment]
try  safetensors==0.3.1
