### ISSUE TITLE
句中停顿时间比句末更长

### ISSUE THREAD

**Issue by jupinter** [modelscope/modelscope#458]
在使用16k声音定制模型tts模型，输入一段文字合成语音时，句中的逗号的停顿时长明显长于句子间的句号、问号的停顿时长。而且合成代码中的文本前端是通过动态库的方式调用，不太容易基于规则增加后处理。这块有没有什么比较好的方法？谢谢。

**Comment by Insswer** [comment]
能贴一下你测试的文本么？你是自己训练的模型还是使用的我们提供的pretrain模型推理？前端库目前分句后并不会加上停顿，而模型不会添加尾静音，所以是有可能出现你说的现象的。解决方法可以这样，根据前端库分句的结果（也就是一行一行的symbols）合成完后代码添加一个静音。

**Comment by jupinter** [comment]
不用文本，就是#3当前的时长在0.8秒左右。这个说话人的语速很快，训练数据当前采用自动标注的方式，说得很快但没有停顿的句子会被合并到一起，韵律标记都是#1，在内部长时停顿的位置标记出了#3. 
我其实也希望#3能够学习到目标人这种停顿非常短的状态，所以想把“声学上没有明显停顿但语义上是一个句子的结束位置也标记成#3”，不知道这种方式是否合适？
