### ISSUE TITLE
img变量未定义

### ISSUE THREAD

**Issue by co63oc** [modelscope/modelscope#46]
modelscope/pipelines/cv/face_recognition_pipeline.py
91行 img变量未定义
`        if top_face > 1 and center_face and bboxes.shape[0] > 1:
            img_center = [img.shape[1] // 2, img.shape[0] // 2]
            min_dist = float('inf')`

**Comment by yingdachen** [comment]
thanks for bringing this up, we are working on a fix and overallr refactoring of vacinity codes

**Comment by yingdachen** [comment]
fixed in latest release
