### ISSUE TITLE
你好，想请教下TTS模型训练的一些疑问

### ISSUE THREAD

**Issue by laishujie** [modelscope/modelscope#460]
![image](https://github.com/modelscope/modelscope/assets/16934884/84cc81cb-ad13-478c-970f-78054b9c0a5a)

1.你好，我看到在声音克隆个人定制里面里面有些一些TTS模型，请问这些模型能提供下载吗？
2.现在有提供训练这种TTS的方案吗？模型是基于发布的这个文章《SambertHifigan个性化语音合成-中文-预训练-16k》训练出来的吗？

**Comment by wenmengzhou** [comment]
https://modelscope.cn/models/damo/speech_ptts_autolabel_16k/summary
