### ISSUE TITLE
请求发布ttsfrd的aarch64版本

### ISSUE THREAD

**Issue by twkun** [modelscope/modelscope#461]
你好，能分发一下 ttsfrd 的aarch64版本吗，在tts模型部署的链条上，貌似就差这个的aarch64版本，就可以在各种边缘计算设备上跑通了

**Comment by wenmengzhou** [comment]
您好，很抱歉，这个模型暂时没有arm环境的支持计划

**Comment by twkun** [comment]
好的，我在x86机器上引入ttsfrd做成grpc服务，然后在边缘设备上自己做了个python的ttsfrd包远程调用服务，这样就可以用modelscope加载各种tts模型了，总算是可以运行了，只是感觉性能有点差
