### ISSUE TITLE
一个问题关于交流

### ISSUE THREAD

**Issue by didiyasidi** [modelscope/modelscope#465]
“你好，我的中文不太好，所以我只能用翻译软件来翻译。我真的很喜欢这个社区的风格。然而，今天下午当我扫描了网页在modelscope.cn上的二维码，希望通过群与大家交流，并且按照指示加入了一个关于VisualGLM的讨论群，微信突然崩溃了。重新登录后，微信告诉我，我的账号被禁止与任何人进行交流。请问你能帮我理解出现了什么问题吗？

**Comment by wenmengzhou** [comment]
can you paste the url of website which contains the qrcode?    you can leave message on github use english to communicate
