### ISSUE TITLE
Qwen-7b-chat长文本推理

### ISSUE THREAD

**Issue by Maxhyl** [modelscope/modelscope#466]
短文本的问答是没有问题，根据说明文档，修改了use_dynamc_ntk和use_logn_attn为True，输入一个7000多长度的文本会报错维度不匹配。The size of tensor a (6144) must match the size of tensor b (6228) at non-singleton dimension 3，修改seq_length和n_positions后返回的结果为空

**Comment by wenmengzhou** [comment]
请帖一下调用代码，包括参数修改部分

**Comment by Maxhyl** [comment]
> 请帖一下调用代码，包括参数修改部分

config.py文件：
{
  "activation": "swiglu",
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "QWenLMHeadModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_qwen.QWenConfig",
    "AutoModelForCausalLM": "modeling_qwen.QWenLMHeadModel"
  },
  "attn_pdrop": 0.0,
  "bf16": false,
  "fp16": false,
  "fp32": false,
  "bias_dropout_fusion": true,
  "bos_token_id": 151643,
  "embd_pdrop": 0.0,
  "eos_token_id": 151643,
  "ffn_hidden_size": 22016,
  "initializer_range": 0.02,
  "kv_channels": 128,
  "layer_norm_epsilon": 1e-06,
  "model_type": "qwen",
  "n_embd": 4096,
  "n_head": 32,
  "n_layer": 32,
  "n_positions": 8192,
  "no_bias": true,
  "onnx_safe": null,
  "padded_vocab_size": 151936,
  "params_dtype": "torch.bfloat16",
  "pos_emb": "rotary",
  "resid_pdrop": 0.1,
  "rotary_emb_base": 10000,
  "rotary_pct": 1.0,
  "scale_attn_weights": true,
  "seq_length": 4096,
  "tie_word_embeddings": false,
  "tokenizer_type": "QWenTokenizer",
  "transformers_version": "4.31.0",
  "use_cache": true,
  "use_flash_attn": "auto",
  "vocab_size": 151936,
  "use_dynamic_ntk": true,
  "use_logn_attn": true
}

调用代码：
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
tokenizer = AutoTokenizer.from_pretrained("/home/Qwen/Qwen-7B-Chat", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("/home/Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
model.generation_config = GenerationConfig.from_pretrained("/home/Qwen/Qwen-7B-Chat", trust_remote_code=True)
input_txt = "长文本"
response, history = model.chat(tokenizer, input_txt, history=None)
print ("Qwen-Chat：", response)

**Comment by Maxhyl** [comment]
@wenmengzhou 请问这个问题有解决方案吗？

**Comment by wenmengzhou** [comment]
According to https://github.com/QwenLM/Qwen-7B/issues/50 ,  try to update the model to the latest version

**Comment by Maxhyl** [comment]
我从configuration_qwen.py文件打印了"use_dynamic_ntk"，"use_logn_attn"两个参数，确认是开启了的，但是返回的结果依旧是空白。

**Comment by Maxhyl** [comment]
![image](https://github.com/modelscope/modelscope/assets/49184062/cf21285a-3bc9-4e19-8039-5d78544785fb)

**Comment by wenmengzhou** [comment]
please check whether your local code in model directory contains following commit:

https://huggingface.co/Qwen/Qwen-7B/commit/e7ecd2aabf8581570c47387b022e17a501bdb8b2

**Comment by wenmengzhou** [comment]
close issue as no updates
