### ISSUE TITLE
unittest 失败信息 No module named 'numpy.testing'

### ISSUE THREAD

**Issue by co63oc** [modelscope/modelscope#47]
unittest 失败信息
https://github.com/modelscope/modelscope/actions/runs/3607072488/jobs/6078852334
    from .._constraints import (
  File "/opt/conda/lib/python3.7/site-packages/scipy/optimize/_constraints.py", line 8, in <module>
    from numpy.testing import suppress_warnings
ModuleNotFoundError: No module named 'numpy.testing'

**Comment by wenmengzhou** [comment]
known problem, will fix it tomorrow

**Comment by yingdachen** [comment]
close as fixed.
