### ISSUE TITLE
VAD result problem

### ISSUE THREAD

**Issue by fclearner** [modelscope/modelscope#471]
vad pipeline result dict , key is not matched with value,
I found the code made the problem, why i=0 add the "text" key?
Here is the code:
https://github.com/modelscope/modelscope/blob/a67d339e3bf8abd25d224818f6fd6512078f6f37/modelscope/pipelines/audio/voice_activity_detection_pipeline.py#L157C9-L157C9

**Comment by wenmengzhou** [comment]
@funasr  please help to see this issue
