### ISSUE TITLE
i can't install modelsope

### ISSUE THREAD

**Issue by cestcode** [modelscope/modelscope#477]
When i was run this command:  "pip install modelscope"

and i want  to use 

"  from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks  "

I'm seeing  :
" modelscope.utils.constant could not be resolved " and " modelscope.pipelines could not be resolved "

Why it does not working? Please help.

**Comment by wenmengzhou** [comment]
what is the output of  `pip install modelscope`

**Comment by cestcode** [comment]
I'm sorry, but I'm no longer working on this project, so I don't remember the output. Nevertheless, thank you for reaching out.
