### ISSUE TITLE
提供的 aishell3  tts数据集，中的 每个wav对应的 interval 文件如何得到的？

### ISSUE THREAD

**Issue by wangdabee** [modelscope/modelscope#478]
https://modelscope.cn/datasets/speech_tts/AISHELL-3/summary

这里提到的数据集格式中的 interval 文件如何得到的？

**Comment by mumuszhang** [comment]
有个tts autolabel 自己执行下

from modelscope.tools import run_auto_label

input_wav = "datasets/"
output_data = "training_data/"

ret, report = run_auto_label(input_wav=input_wav, work_dir=output_data, resource_revision="v1.0.7")
