### ISSUE TITLE
请问何时 ASR/TTS 才能完全支持 Windows 环境.

### ISSUE THREAD

**Issue by Ibuprofenighty** [modelscope/modelscope#485]
像 nls-fa, ttsfrd这些闭源的库都只支持linux系统.

什么时候能让语音类的完全支持windows系统呀.

**Comment by Insswer** [comment]
ttsfrd是一个前端库，目前没有时间来做windows移植，可以考虑自行实现或者寻找其他开源的前端方案替换。
