### ISSUE TITLE
[error]出现conda环境问题无法运行

### ISSUE THREAD

**Issue by zzclynn** [modelscope/modelscope#49]
根据官方文档安装：https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85

```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline('image-classification', 'damo/cv_vit-base_image-classification_Dailylife-labels')
```
报错如下
![image](https://user-images.githubusercontent.com/5746653/206388211-08dce821-008e-4fd2-8016-a0ad7652d990.png)

ENV:

modelscope version: 1.1.1
阿里云 ubuntu  4 vCPU
15 GiB
200 Mbps
GPU：NVIDIA T4

**Comment by yingdachen** [comment]
close as failed-to-reproduce. if necessary, please reopen with more information
