### ISSUE TITLE
Connection broken: ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by mzolfaghari** [modelscope/modelscope#501]
ChunkedEncodingError                      Traceback (most recent call last)
Cell In[6], line 6
      4 kwargs = {}
      5 image_to_video_pipe = pipeline(task="image-to-video", model='damo/Image-to-Video', model_revision='v1.1.0', device='cuda:0', maxsize=100, **kwargs)
----> 6 video_to_video_pipe = pipeline(task="video-to-video", model='damo/Video-to-Video', model_revision='v1.1.0', device='cuda:0', maxsize=100, **kwargs)
      8 def upload_file(file):
      9     return file.name

File /lib/python3.8/site-packages/modelscope/pipelines/builder.py:106, in pipeline(task, model, preprocessor, config_file, pipeline_name, framework, device, model_revision, **kwargs)
    104 if third_party is not None:
    105     kwargs.pop(ThirdParty.KEY)
--> 106 model = normalize_model_input(
    107     model, model_revision, third_party=third_party)
    108 pipeline_props = {'type': pipeline_name}
    109 if pipeline_name is None:
    110     # get default pipeline for this task

File /lib/python3.8/site-packages/modelscope/pipelines/builder.py:33, in normalize_model_input(model, model_revision, third_party)
     31         if third_party is not None:
     32             user_agent[ThirdParty.KEY] = third_party
---> 33         model = snapshot_download(
     34             model, revision=model_revision, user_agent=user_agent)
     35 elif isinstance(model, list) and isinstance(model[0], str):
     36     for idx in range(len(model)):

File /lib/python3.8/site-packages/modelscope/hub/snapshot_download.py:140, in snapshot_download(model_id, revision, cache_dir, user_agent, local_files_only, cookies, ignore_file_pattern)
    133 url = get_file_download_url(
    134     model_id=model_id,
    135     file_path=model_file['Path'],
    136     revision=revision)
    138 if MODELSCOPE_PARALLEL_DOWNLOAD_THRESHOLD_MB * 1000 * 1000 < model_file[
    139         'Size'] and MODELSCOPE_DOWNLOAD_PARALLELS > 1:
--> 140     parallel_download(
    141         url,
    142         temp_cache_dir,
    143         model_file['Name'],
    144         headers=headers,
    145         cookies=None
    146         if cookies is None else cookies.get_dict(),
    147         file_size=model_file['Size'])
    148 else:
    149     http_get_file(
    150         url,
    151         temp_cache_dir,
    152         model_file['Name'],
    153         headers=headers,
    154         cookies=cookies)

File /lib/python3.8/site-packages/modelscope/hub/file_download.py:243, in parallel_download(url, local_dir, file_name, cookies, headers, file_size)
    239     parallels = MODELSCOPE_DOWNLOAD_PARALLELS if MODELSCOPE_DOWNLOAD_PARALLELS <= 4 else 4
    240     with ThreadPoolExecutor(
    241             max_workers=parallels,
    242             thread_name_prefix='download') as executor:
--> 243         list(executor.map(download_part, tasks))
    245     progress.close()
    247 os.replace(temp_file.name, os.path.join(local_dir, file_name))

File /lib/python3.8/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield fs.pop().result()
    620     else:
    621         yield fs.pop().result(end_time - time.monotonic())

File /lib/python3.8/concurrent/futures/_base.py:444, in Future.result(self, timeout)
    442     raise CancelledError()
    443 elif self._state == FINISHED:
--> 444     return self.__get_result()
    445 else:
    446     raise TimeoutError()

File /lib/python3.8/concurrent/futures/_base.py:389, in Future.__get_result(self)
    387 if self._exception:
    388     try:
--> 389         raise self._exception
    390     finally:
    391         # Break a reference cycle with the exception in self._exception
    392         self = None

File /lib/python3.8/concurrent/futures/thread.py:57, in _WorkItem.run(self)
     54     return
     56 try:
---> 57     result = self.fn(*self.args, **self.kwargs)
     58 except BaseException as exc:
     59     self.future.set_exception(exc)

File /lib/python3.8/site-packages/modelscope/hub/file_download.py:203, in download_part(params)
    196 f.seek(start)
    197 r = requests.get(
    198     url,
    199     stream=True,
    200     headers=get_headers,
    201     cookies=cookies,
    202     timeout=API_FILE_DOWNLOAD_TIMEOUT)
--> 203 for chunk in r.iter_content(chunk_size=API_FILE_DOWNLOAD_CHUNK_SIZE):
    204     if chunk:  # filter out keep-alive new chunks
    205         f.write(chunk)

File /lib/python3.8/site-packages/requests/models.py:818, in Response.iter_content.<locals>.generate()
    816     yield from self.raw.stream(chunk_size, decode_content=True)
    817 except ProtocolError as e:
--> 818     raise ChunkedEncodingError(e)
    819 except DecodeError as e:
    820     raise ContentDecodingError(e)

ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

**Comment by mzolfaghari** [comment]
@wenmengzhou @wangxingjun778 Do you know how can I fix this problem? I tried almost 50 times and the connection fails always! I am running the code on GCP and the internet speed is very good. 
<img width="1194" alt="Screenshot 2023-08-25 at 18 42 46" src="https://github.com/modelscope/modelscope/assets/10133957/1830334c-1352-4504-84e6-f97d33795114">

**Comment by yingdachen** [comment]
the models on modelscope are currently hosing on mirrors in asia and north america, downding from from germany may be subject to the connectivity issues. 

is it possible that you can try on a gcp machine that is in north america region?

**Comment by Ravius** [comment]
Same issue, it drops after ~10 min 
is it possible to use pre-downloaded model? (as it available on huggingface)

**Comment by tin2tin** [comment]
https://github.com/modelscope/modelscope/issues/518#issuecomment-1732471003
