### ISSUE TITLE
how Modelscope pipeline release GPU memory?

### ISSUE THREAD

**Issue by ultimatech-cn** [modelscope/modelscope#503]
when load pipelin as following, the GPU memory will increase
self.skin_retouching = pipeline(Tasks.skin_retouching, model='damo/cv_unet_skin-retouching')

but it seems the memory isn't release after the pipeline is invoked, how release GPU memory?

I tried torch.cuda.empty_cache(), but it does not work for these pipeline of modelscope

**Comment by wenmengzhou** [comment]
del pipeline
torch.cuda.empty_cache()

**Comment by wenmengzhou** [comment]
damo/cv_unet_skin-retouching also use tensorflow, so if you want to release gpu memory after inference, you'd better run it in a subprocess

**Comment by ultimatech-cn** [comment]
Thank a lot @wenmengzhou .
I have tried "del and empty_cache) in debug model step by step, but  it didn't work so far.
There are about 10G GPU memory hold by modelscope pipeline,  I couldn't find way to remove them.

Sub process is a workround, but in gradio mode, it is not good way.

**Comment by wenmengzhou** [comment]
try this model which has removed the tensorflow model,  you can use torch releated api to release memory

https://modelscope.cn/models/damo/cv_unet_skin_retouching_torch/summary

**Comment by ultimatech-cn** [comment]
Thank you. It seems the problem is solved.

**Comment by 9527-csroad** [comment]
> Thank you. It seems the problem is solved.

Hello， could you plz tell me how to resolve this provlem?

**Comment by ultimatech-cn** [comment]
update to the latest version
