### ISSUE TITLE
安装Paraformer的时候，提示版本冲突

### ISSUE THREAD

**Issue by stoneHah** [modelscope/modelscope#508]
**环境**
windows 10
python 3.7

**目标**
在本地环境安装Paraformer环境

当前已经安装好了modelscope环境，但是在安装modelscope[audio]的时候提示版本冲突
![image](https://github.com/modelscope/modelscope/assets/13760810/bbbc64fc-9cc7-490a-abea-fa08687bfb16)

**Comment by wenmengzhou** [comment]
请尝试下1.9.0，我们去除了numpy以及pandas的低版本依赖，看下是否OK
