### ISSUE TITLE
pipeline 推理增加对可能的异常输入的处理

### ISSUE THREAD

**Issue by imhuay** [modelscope/modelscope#509]
**Describe the feature**
pipeline 推理增加对可能的异常输入的处理

**Motivation**
```
from modelscope.pipelines import pipeline

p = pipeline('named-entity-recognition', r'damo/nlp_raner_named-entity-recognition_english-large-ecom',
             sequence_length=64)

r = p('鞓ろ啝氚旍澊 敫旊（韴\ue107姢 bt12')
```
可能是字符编码或其他任何问题导致模型无法处理某些输入, 希望 API 能增加对这些异常输入的处理机制, 保证程序的正常执行;
目前只能按 batch_size=1 的方式推理, 但这会显著降低推理速度;

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
一些解决方案:
比如遇到某个 batch 中存在异常输入时, 退化到 process_single, 最重要的是保证 输入和输出 能一一对应, 对无法处理的输入用某个特殊输出占位

**Comment by wenmengzhou** [comment]
这个建议在外层过滤到异常的输入后再送入pipeline进行批量推理
