### ISSUE TITLE
Image-to-Video can't download via pipe: ChunkedEncodingError:

### ISSUE THREAD

**Issue by tin2tin** [modelscope/modelscope#518]
**Describe the bug**
pipe = pipeline(task='image-to-video', model='damo/Image-to-Video', model_revision='v1.1.0')
results in this:
ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

Reference: 
https://huggingface.co/damo-vilab/MS-Image2Video/discussions/10

Trying to download via mirrors on Hugging Face, doesn't work. Downloading the files manually, and placing them in the right folder, still makes the pipe try to download them again.

**Comment by wenmengzhou** [comment]
pipe = pipeline(task='image-to-video', model='path/to/your/folder')

**Comment by tin2tin** [comment]
Ah, thank you, this seems to be working. It's loading, until I get an out of memory error. I'm on 6 GB of VRAM, developing this free and open source add-on for Blender: https://github.com/tin2tin/Generative_AI I started it with the first Modelscope txt2vid was released. 

Any chance of a model version which will be able to run on this low specs? Maybe by making it 16bit or even 8bit?

**Comment by wenmengzhou** [comment]
check the latest 1.9.0 version of modelscope library(will be released today), which support fp16 inference for image to video model

**Comment by tin2tin** [comment]
Oh, great. Thank you. Please consider mirroring the model files on ex. hugging face. I would love to offer the new features of Modelscope to Blender users in my open source add-on, but the download needs to be a bit more fail-safe.

**Comment by wenmengzhou** [comment]
> Oh, great. Thank you. Please consider mirroring the model files on ex. hugging face. I would love to offer the new features of Modelscope to Blender users in my open source add-on, but the download needs to be a bit more fail-safe.

In 1.9.1 which will be released today, we add retry mechanism when download failed, which will make the download more robust

**Comment by tin2tin** [comment]
Thank you.

Actually, I didn't even notice the release of 1.9.0 bc of this: 
![image](https://github.com/modelscope/modelscope/assets/1322593/5fe3fded-977e-4dcd-9a89-6a1e09a61077)

Where can I find instructions on how to import the model with fp16?

**Comment by tin2tin** [comment]
I tried installing the GitHub version with those download retry patches, but there is still a problem downloading:
![image](https://github.com/modelscope/modelscope/assets/1322593/039e02b6-16a2-4242-bf27-1bacefe558a4)

**Comment by wenmengzhou** [comment]
it seems download failed exceeds maximum retry times which is 5  @liuyhwangyh  please follow this problem

**Comment by wenmengzhou** [comment]
Can you download any other small models from modelscope successfully?  Can you provide a enviroment info( which country, which region)  so that we can reproduce this error?

**Comment by tin2tin** [comment]
I could download the smaller files and the folder structure:
![image](https://github.com/modelscope/modelscope/assets/1322593/f48fb919-5cc9-4f45-b5ab-95b9b1485891)
I'm attempting to download from Denmark, but it doesn't seem like I'm the only one having that problem: https://huggingface.co/damo-vilab/MS-Image2Video/discussions/10

**Comment by tin2tin** [comment]
Still DL problems in 1.9.1:
![image](https://github.com/modelscope/modelscope/assets/1322593/21d34346-a349-4dcf-a8c3-57abb3c592ca)

**Comment by wenmengzhou** [comment]
try to increase the rery time and time ratio here

https://github.com/modelscope/modelscope/blob/cd976a366ac2fce2a403ad04e5696dfc0e875465/modelscope/hub/constants.py#L21

**Comment by tin2tin** [comment]
It doesn't fix the bad server situation:
![image](https://github.com/modelscope/modelscope/assets/1322593/56eccdc8-cd73-4cc9-873e-eb7e6828b24b)

**Comment by wenmengzhou** [comment]
@tin2tin have you tried to increase the TIMEOUT param to 600 which can be set here
https://github.com/modelscope/modelscope/blob/cd976a366ac2fce2a403ad04e5696dfc0e875465/modelscope/hub/constants.py#L22C2-L22C2

**Comment by tin2tin** [comment]
Well, yes, I can keep raising the timeout value, but as the above screenshot shows, is only downloading 480 MB(9%) out of 5.29 GB during 1 hour resulting in a 10-hours download, if it succeeds... This is not a durable solution for people using my free Blender add-on.

**Comment by wenmengzhou** [comment]
can you download the model using proxy and upload to Google drive or other storage for your belnd addons, you can use this model by passing a local directory path to pipeline after downloading models

**Comment by wenmengzhou** [comment]
@tin2tin we have add support for downloading acceleration in western Europe,  you can try to download to see whether the speed is ok
