### ISSUE TITLE
[question] Does modelscope has model inference running

### ISSUE THREAD

**Issue by vincent-pli** [modelscope/modelscope#520]
I mean something like huggingface, 
I saw there is a class in langchain named `HuggingFaceHub`, which can invoke model inference in huggingface
```
from langchain import HuggingFaceHub

repo_id = "google/flan-t5-xxl"
llm = HuggingFaceHub(
    repo_id=repo_id, model_kwargs={"temperature": 0.5, "max_length": 64}
)
```

does modelscope has similar thing?

**Comment by wenmengzhou** [comment]
![image](https://github.com/modelscope/modelscope/assets/4771825/409ebb30-0728-452e-a61f-a0908d9c158e)
currently inference api only support part of the models,  please stay tuned for llm support

**Comment by vincent-pli** [comment]
Great, thanks @wenmengzhou , so
1. Do we support rest invoke for these models
2. Do we have plan to contribute to `langchain`,  make the it more friendly just like the code snippet upper?

**Comment by wenmengzhou** [comment]
1.  restful api for llm is currently in progress
2. we will contribute to langchain when the restful api is supported

**Comment by vincent-pli** [comment]
Great, thanks
