### ISSUE TITLE
device cpu torch.from_numpy(data)  error 

### ISSUE THREAD

**Issue by xuantong** [modelscope/modelscope#524]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https:modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.
            image_face_fusion = pipeline('face_fusion_torch',
                                     model='damo/cv_unet_face_fusion_torch',
                                     model_revision='v1.0.5',device='cpu')
            result = image_face_fusion(dict(template=img, user=template_face))[OutputKeys.OUTPUT_IMG]
**Describe the bug**
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array with array.copy().)

**To Reproduce**
* What command or script did you run?

* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
设备名称	DESKTOP-JUNQK72
处理器	12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz
机带 RAM	32.0 GB (31.7 GB 可用)
设备 ID	97EAE2C5-032D-4D12-A059-F9DD544EAB24
产品 ID	00326-10000-00000-AA572
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
Python 3.7.12
modelscope                  1.5.0

需要修改
\modelscope\pipelines\base.py  中关于 torch.from_numpy的代码

**Comment by wenmengzhou** [comment]
您好，我们没有复现相关错误，请提供下输入图片，以及是否在GPU上推理。  另外可以使用下最新1.9.0版本

**Comment by slin000111** [comment]
damo/cv_unet_face_fusion_torch目前正在集成中，部分功能暂时还不能实现。推荐使用damo/cv_unet-image-face-fusion_damo，如果您使用cpu进行推理，可以在pipeline中指定device='cpu'，并在modelscope/models/cv/image_face_fusion/facegan/face_gan.py中对pretrained_dict指定map_location。pretrained_dict = torch.load(self.mfile, map_location='cpu')。
