### ISSUE TITLE
modelscope - WARNING - ('PIPELINES', 'text_to_speech', 'sambert-hifigan-tts') not found in ast index file

### ISSUE THREAD

**Issue by kli017** [modelscope/modelscope#530]
Unable to load the tts model offline. I was using the speech_sambert-hifigan_tts_zh-cn_16k model for tts task. Beacuse I want to use it offline, so I download the model manually. When I set the pipline with a local path and init the pipline I got the following error:
WARNING - ('PIPELINES', 'text_to_speech', 'sambert-hifigan-tts') not found in ast index file

* OS: `Ubuntu20`
I install the enviroment with pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by wenmengzhou** [comment]
check whether  these is a  modelscope/utils/ast_index_file.py  in the modelscope package directory which should contains info about ('PIPELINES', 'text_to_speech', 'sambert-hifigan-tts')

**Comment by kli017** [comment]
@wenmengzhou Thank you for the reply. Yes I found the ast_index_file.py in my env. Should I modified the filepath to my localpath?

**Comment by kli017** [comment]
@wenmengzhou Thanks for the reply. Should be 'text-to-speech'.
