### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by Fasuiker** [modelscope/modelscope#535]
raise HTTPError('Response details: %s' % message) from error
requests.exceptions.HTTPError: Response details: {'Code': 10010200001, 'Message': '获取模型版本失败，信息：获取模失败', 'RequestId': 'cb9c91e7-91b0-4794-a1aa-d86a7f94feed', 'Success': False}

**Comment by wenmengzhou** [comment]
which model？

**Comment by Fasuiker** [comment]
qwen-7b-chat

**Comment by wenmengzhou** [comment]
try this one: https://modelscope.cn/models/ccyh123/Qwen-7B-Chat/summary
