### ISSUE TITLE
AdaSeq multi-GPU training is not successful

### ISSUE THREAD

**Issue by srdfjy** [modelscope/modelscope#537]
Hi

In adaseq, training with single-machine multi-GPU (1 node/2 GPUs) and multi-machine multi-GPU (2 nodes/1 GPU per node) configurations is failing. It runs successfully with a single-machine single-GPU configuration. It seems like there might be an incompatibility issue between adaseq and modelscope versions. Can you help me investigate the cause？THX.

adaseq version：0.6.4
modelscope version：1.8.4

---

**multi-GPU (1 node/2 GPUs)**

2023/09/14 11:20:21 Total test samples with multi gpus:   0%|          | 0/269 [00:00<?, ?it/s]
2023/09/14 11:20:22 Total test samples with multi gpus:   0%|          | 0/269 [00:00<?, ?it/s]
2023/09/14 11:20:27 Total test samples with multi gpus:   0%|          | 1/269 [00:00<03:45,  1.19it/s]
2023/09/14 11:20:27 Total test samples with multi gpus:   0%|          | 0/269 [00:06<?, ?it/s]
2023/09/14 11:20:28 
2023/09/14 11:20:28 Total test samples with multi gpus:  96%|█████████▌| 257/269 [00:06<00:00, 40.59it/s]
2023/09/14 11:20:28 Total test samples with multi gpus: 100%|██████████| 269/269 [00:06<00:00, 40.90it/s]
2023/09/14 11:20:33     train_model_from_args(args)
2023/09/14 11:20:33   File "/adaseq/adaseq/commands/train.py", line 164, in train_model
2023/09/14 11:20:33     return super().train(checkpoint_path=checkpoint_path, *args, **kwargs)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1232, in train_loop
2023/09/14 11:20:33     getattr(hook, fn_name)(self)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py", line 67, in do_evaluate
2023/09/14 11:20:33     metric_values = self.evaluation_loop(self.eval_dataloader,
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/utils/inference.py", line 173, in multi_gpu_test
2023/09/14 11:20:33     cls_0.merge(cls_i)
2023/09/14 11:20:33 Traceback (most recent call last):
2023/09/14 11:20:33   File "/adaseq/adaseq/commands/train.py", line 84, in train_model_from_args
**2023/09/14 11:20:33 TypeError: merge() takes 1 positional argument but 2 were given**
2023/09/14 11:20:33     self.invoke_hook(TrainerStages.after_train_epoch)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 700, in train
2023/09/14 11:20:33     eval_res = trainer.evaluate()
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py", line 54, in after_train_epoch
2023/09/14 11:20:33     trainer.train(checkpoint_path)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1273, in evaluation_loop
2023/09/14 11:20:33     metric_classes = merge_metrics(metric_classes_list)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/utils/inference.py", line 302, in merge_metrics
2023/09/14 11:20:33     self.do_evaluate(trainer)
2023/09/14 11:20:33     self.train_loop(self.train_dataloader)
2023/09/14 11:20:33   File "scripts/train.py", line 38, in <module>
2023/09/14 11:20:33     train_model(
2023/09/14 11:20:33     metric_values = multi_gpu_test(
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 789, in evaluate
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1384, in invoke_hook
2023/09/14 11:20:33   File "/adaseq/adaseq/training/default_trainer.py", line 146, in train
2023/09/14 11:20:37 WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 175 closing signal SIGTERM
2023/09/14 11:20:38   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2023/09/14 11:20:38     exec(code, run_globals)
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 189, in main
2023/09/14 11:20:38     run(args)
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
2023/09/14 11:20:38     raise ChildFailedError(
2023/09/14 11:20:38 scripts/train.py FAILED
2023/09/14 11:20:38   <NO_OTHER_FAILURES>
2023/09/14 11:20:38 [0]:
2023/09/14 11:20:38   rank      : 0 (local_rank: 0)
2023/09/14 11:20:38   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
2023/09/14 11:20:38     main()
2023/09/14 11:20:38   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2023/09/14 11:20:38 Traceback (most recent call last):
2023/09/14 11:20:38     elastic_launch(
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 174, in launch
2023/09/14 11:20:38   error_file: <N/A>
2023/09/14 11:20:38   host      : job-1869360-279034012-gkqpk
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
2023/09/14 11:20:38 exec result:1

---

**multi-machine multi-GPU (2 nodes/1 GPU per node)**

2023/09/13 16:50:56 0 | 2023-09-13 16:50:55,865 - INFO - adaseq.training.hooks.text_logger_hook - Text logs will be saved to: /data/experiments/car_ner_bert_crf/230913165038.378534/metrics.json
2023/09/13 16:51:29 
2023/09/13 16:51:30 Total test samples with multi gpus:   0%|          | 0/269 [00:00<?, ?it/s]
2023/09/13 16:51:36 Total test samples with multi gpus:   0%|          | 1/269 [00:00<03:49,  1.17it/s]
2023/09/13 16:51:36 Total test samples with multi gpus: 100%|██████████| 269/269 [00:06<00:00, 41.88it/s]
2023/09/13 16:51:36 Total test samples with multi gpus:  96%|█████████▌| 257/269 [00:06<00:00, 41.64it/s]
2023/09/13 16:51:40     train_model_from_args(args)
2023/09/13 16:51:40   File "/adaseq/adaseq/commands/train.py", line 164, in train_model
2023/09/13 16:51:40     return super().train(checkpoint_path=checkpoint_path, *args, **kwargs)
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1232, in train_loop
2023/09/13 16:51:40 Traceback (most recent call last):
2023/09/13 16:51:40     self.invoke_hook(TrainerStages.after_train_epoch)
2023/09/13 16:51:40     trainer.train(checkpoint_path)
2023/09/13 16:51:40   File "/adaseq/adaseq/commands/train.py", line 84, in train_model_from_args
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py", line 54, in after_train_epoch
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 700, in train
2023/09/13 16:51:40     getattr(hook, fn_name)(self)
2023/09/13 16:51:40     eval_res = trainer.evaluate()
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py", line 67, in do_evaluate
2023/09/13 16:51:40   File "scripts/train.py", line 38, in <module>
2023/09/13 16:51:40   File "/adaseq/adaseq/training/default_trainer.py", line 146, in train
2023/09/13 16:51:40     metric_values = self.evaluation_loop(self.eval_dataloader,
2023/09/13 16:51:40     self.train_loop(self.train_dataloader)
2023/09/13 16:51:40     train_model(
2023/09/13 16:51:40     self.do_evaluate(trainer)
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1384, in invoke_hook
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1273, in evaluation_loop
2023/09/13 16:51:40     metric_classes_list = collect_results_cpu(
2023/09/13 16:51:40   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/utils/inference.py", line 170, in multi_gpu_test
2023/09/13 16:51:40     with open(part_file, 'rb') as f:
**2023/09/13 16:51:40 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpaosa1mii/metrics/part_1.pkl'**

**Comment by srdfjy** [comment]
"Is it because of the incompatibility between adaseq and modelscope versions? Because when I switched to single-machine multi-GPU, I encountered another error. adaseq version: 0.6.4, modelscope version: 1.9.0. Currently, it works fine with single-machine single-GPU."

---

2023/09/14 11:20:21 Total test samples with multi gpus:   0%|          | 0/269 [00:00<?, ?it/s]
2023/09/14 11:20:22 Total test samples with multi gpus:   0%|          | 0/269 [00:00<?, ?it/s]
2023/09/14 11:20:27 Total test samples with multi gpus:   0%|          | 1/269 [00:00<03:45,  1.19it/s]
2023/09/14 11:20:27 Total test samples with multi gpus:   0%|          | 0/269 [00:06<?, ?it/s]
2023/09/14 11:20:28 
2023/09/14 11:20:28 Total test samples with multi gpus:  96%|█████████▌| 257/269 [00:06<00:00, 40.59it/s]
2023/09/14 11:20:28 Total test samples with multi gpus: 100%|██████████| 269/269 [00:06<00:00, 40.90it/s]
2023/09/14 11:20:33     train_model_from_args(args)
2023/09/14 11:20:33   File "/adaseq/adaseq/commands/train.py", line 164, in train_model
2023/09/14 11:20:33     return super().train(checkpoint_path=checkpoint_path, *args, **kwargs)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1232, in train_loop
2023/09/14 11:20:33     getattr(hook, fn_name)(self)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py", line 67, in do_evaluate
2023/09/14 11:20:33     metric_values = self.evaluation_loop(self.eval_dataloader,
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/utils/inference.py", line 173, in multi_gpu_test
2023/09/14 11:20:33     cls_0.merge(cls_i)
2023/09/14 11:20:33 Traceback (most recent call last):
2023/09/14 11:20:33   File "/adaseq/adaseq/commands/train.py", line 84, in train_model_from_args
**2023/09/14 11:20:33 TypeError: merge() takes 1 positional argument but 2 were given**
2023/09/14 11:20:33     self.invoke_hook(TrainerStages.after_train_epoch)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 700, in train
2023/09/14 11:20:33     eval_res = trainer.evaluate()
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py", line 54, in after_train_epoch
2023/09/14 11:20:33     trainer.train(checkpoint_path)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1273, in evaluation_loop
2023/09/14 11:20:33     metric_classes = merge_metrics(metric_classes_list)
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/utils/inference.py", line 302, in merge_metrics
2023/09/14 11:20:33     self.do_evaluate(trainer)
2023/09/14 11:20:33     self.train_loop(self.train_dataloader)
2023/09/14 11:20:33   File "scripts/train.py", line 38, in <module>
2023/09/14 11:20:33     train_model(
2023/09/14 11:20:33     metric_values = multi_gpu_test(
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 789, in evaluate
2023/09/14 11:20:33   File "/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py", line 1384, in invoke_hook
2023/09/14 11:20:33   File "/adaseq/adaseq/training/default_trainer.py", line 146, in train
2023/09/14 11:20:37 WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 175 closing signal SIGTERM
2023/09/14 11:20:38   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2023/09/14 11:20:38     exec(code, run_globals)
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 189, in main
2023/09/14 11:20:38     run(args)
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
2023/09/14 11:20:38     raise ChildFailedError(
2023/09/14 11:20:38 scripts/train.py FAILED
2023/09/14 11:20:38   <NO_OTHER_FAILURES>
2023/09/14 11:20:38 [0]:
2023/09/14 11:20:38   rank      : 0 (local_rank: 0)
2023/09/14 11:20:38   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
2023/09/14 11:20:38     main()
2023/09/14 11:20:38   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2023/09/14 11:20:38 Traceback (most recent call last):
2023/09/14 11:20:38     elastic_launch(
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 174, in launch
2023/09/14 11:20:38   error_file: <N/A>
2023/09/14 11:20:38   host      : job-1869360-279034012-gkqpk
2023/09/14 11:20:38   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
2023/09/14 11:20:38 exec result:1

**Comment by wenmengzhou** [comment]
for the first error, check the evaluation metric class in adaseq, whether the metric has adapt to the interface in modelscope [metric class](https://github.com/modelscope/modelscope/blob/master/modelscope/metrics/base.py#L43)

for the second error, please set gpu_collect as True in configuration.json or using nas so that files can be read by each node so that evaluation results on different node can be gathered
```
"evaluation": {
    "gpu_collect": True
}
```

**Comment by srdfjy** [comment]
The example I ran is https://github.com/modelscope/AdaSeq/blob/master/examples/bert_crf/configs/maoe_example.yaml

The metric class is: SequenceLabelingMetric. I looked at the source code for SequenceLabelingMetric and found that it has implemented the merge method. With the same configuration, it works on a single machine with a single card, but reports the first mentioned error when running on a single machine with multiple cards.

SequenceLabelingMetric：https://github.com/modelscope/AdaSeq/blob/e829aae73abc0c6bc92519ea185a2c8031edb735/adaseq/metrics/sequence_labeling_metric.py#L89C28-L89C28

**Comment by srdfjy** [comment]
When I remove the 'ner-dumper（
https://github.com/modelscope/AdaSeq/blob/e829aae73abc0c6bc92519ea185a2c8031edb735/examples/bert_crf/configs/maoe_example.yaml#L53-L55）' metric, I encountered the following error.

**"2023/09/19 12:20:56 AttributeError: 'SequenceLabelingMetric' object has no attribute 'trainer'",**

err：
---
"2023/09/19 12:20:55   \"embedder.transformer_model.encoder.layer.9.attention.output.LayerNorm.bias\",",
"2023/09/19 12:20:55 0 | 2023-09-19 12:20:54,861 - INFO - adaseq.training.optimizer - Number of trainable parameters: 102274668",
"2023/09/19 12:20:56 Total test samples with multi gpus:   0%|          | 0/100 [00:00<?, ?it/s]",
"2023/09/19 12:20:56   File \"/usr/local/lib/python3.8/dist-packages/modelscope/trainers/hooks/evaluation_hook.py\", line 67, in do_evaluate",
"2023/09/19 12:20:56 0 | 2023-09-19 12:20:56,951 - INFO - root - >>>>>0 <class 'list'> 2 [[<adaseq.metrics.sequence_labeling_metric.SequenceLabelingMetric object at 0x7f366ba0ffa0>], [<adaseq.metrics.sequence_labeling_metric.SequenceLabelingMetric object at 0x7f366ba0ffd0>]]",
"2023/09/19 12:20:56     getattr(hook, fn_name)(self)",
"2023/09/19 12:20:56     return super().train(checkpoint_path=checkpoint_path, *args, **kwargs)",
"2023/09/19 12:20:56   File \"/usr/local/lib/python3.8/dist-packages/modelscope/trainers/trainer.py\", line 1225, in train_loop",
**"2023/09/19 12:20:56 AttributeError: 'SequenceLabelingMetric' object has no attribute 'trainer'",**
"2023/09/19 12:20:56 Total test samples with multi gpus: 100%|██████████| 100/100 [00:00<00:00, 720.09it/s]",
"2023/09/19 12:20:56     metric_values = self.evaluation_loop(self.eval_dataloader,",
"2023/09/19 12:20:56     train_model_from_args(args)",
"2023/09/19 12:20:56   File \"/adaseq/adaseq/commands/train.py\", line 164, in train_model",
"2023/09/19 12:20:56   File \"/usr/local/lib/python3.8/dist-packages/modelscope/trainers/utils/inference.py\", line 175, in multi_gpu_test",
"2023/09/19 12:20:56     metric_values.update(metric_cls.evaluate())",
"2023/09/19 12:20:57 terminate called after throwing an instance of 'c10::CUDAError'",
"2023/09/19 12:20:57 For debugging consider passing CUDA_LAUNCH_BLOCKING=1.",
"2023/09/19 12:20:57 CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.",
"2023/09/19 12:20:58 frame #1: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x11a (0x7f36eea392fa in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so)",
"2023/09/19 12:20:58 frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f36ed3df7d2 in /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so)",
"2023/09/19 12:20:58 frame #4: <unknown function> + 0xbd6df (0x7f37485e16df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)",
"2023/09/19 12:20:57   what():  CUDA error: driver shutting down",
"2023/09/19 12:20:58 frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x145 (0x7f36eea3c805 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so)",
"2023/09/19 12:20:57 Exception raised from query at ../aten/src/ATen/cuda/CUDAEvent.h:95 (most recent call first):",
"2023/09/19 12:20:58 frame #6: clone + 0x3f (0x7f3754ac3a3f in /lib/x86_64-linux-gnu/libc.so.6)",
"2023/09/19 12:20:58 ",
"2023/09/19 12:20:58 frame #2: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x50 (0x7f36eea3b570 in /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so)",
"2023/09/19 12:20:58 frame #5: <unknown function> + 0x76db (0x7f375478a6db in /lib/x86_64-linux-gnu/libpthread.so.0)",
"2023/09/19 12:21:08 WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 136 closing signal SIGTERM",
"2023/09/19 12:21:08   File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main",
"2023/09/19 12:21:08 Traceback (most recent call last):",
"2023/09/19 12:21:08   File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code",
"2023/09/19 12:21:08     exec(code, run_globals)",
"2023/09/19 12:21:08     main()",
"2023/09/19 12:21:08   File \"/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py\", line 189, in main",
"2023/09/19 12:21:08   File \"/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py\", line 131, in __call__",
"2023/09/19 12:21:08     run(args)",
"2023/09/19 12:21:08   File \"/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py\", line 174, in launch",
"2023/09/19 12:21:08     elastic_launch(",
"2023/09/19 12:21:08     raise ChildFailedError(",
"2023/09/19 12:21:08   File \"/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py\", line 245, in launch_agent",
"2023/09/19 12:21:08 scripts/train.py FAILED",

**Comment by wenmengzhou** [comment]
@huangshenno1 will fix this problem in adaseq
