### ISSUE TITLE
GridVLP 有能在gpu跑的版本吗

### ISSUE THREAD

**Issue by xxxyyycc** [modelscope/modelscope#538]
目前好像只能使用cpu做预测？

**Comment by lcl6679292** [comment]
您好，您现在用的是GridVLP哪个模型呢，是都可以用GPU预测的。如果您是构建了推理的.py文件，执行前面可以加个
CUDA_VISIBLE_DEVICES=0 python xx.py来执行试试，如果还是没有用到GPU，可以截图发下您的GPU型号相关信息

**Comment by xxxyyycc** [comment]
> 您好，您现在用的是GridVLP哪个模型呢，是都可以用GPU预测的。如果您是构建了推理的.py文件，执行前面可以加个 CUDA_VISIBLE_DEVICES=0 python xx.py来执行试试，如果还是没有用到GPU，可以截图发下您的GPU型号相关信息

用的模型是 https://www.modelscope.cn/models/rgtjf1/multi-modal_gridvlp_classification_chinese-base-ecom-cate/summary
gpu环境是正常的，我看代码里写死了用 cpu，手动改成gpu也不行，有一些参数应该是trace的时候绑定到cpu上了
https://github.com/modelscope/modelscope/blob/8e42de3ebc8ae26a490a3b1a5c2b52fec06f79be/modelscope/pipelines/multi_modal/gridvlp_pipeline.py#L97C1-L97C1

**Comment by wenmengzhou** [comment]
https://github.com/modelscope/modelscope/blob/8e42de3ebc8ae26a490a3b1a5c2b52fec06f79be/modelscope/pipelines/multi_modal/gridvlp_pipeline.py#L94

try to pass device='cuda'  to torch.jit.load

**Comment by xxxyyycc** [comment]
> https://github.com/modelscope/modelscope/blob/8e42de3ebc8ae26a490a3b1a5c2b52fec06f79be/modelscope/pipelines/multi_modal/gridvlp_pipeline.py#L94
> 
> try to pass map_location=torch.device('cuda') to torch.jit.load
感谢回复，之前试过了，input也挪到gpu上了，但是forward的时候会报错
Traceback of TorchScript, original code (most recent call last):
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py(1724): embedding
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/sparse.py(114): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/lxrt/modeling.py(345): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/lxrt/modeling.py(1220): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/lxrt/modeling.py(1391): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/lxrt/entry.py(152): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/cateqa/cateqa_model.py(50): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/merge_model_vis.py(191): forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/Users/junfeng.tjf/miniconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/merge_model_vis.py(416): handle
/Users/junfeng.tjf/PycharmSpace/e2evlp/udf/cateqa_udf/merge_model_vis.py(511): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by iamkissg** [comment]
Modelscope's GridVLP model is compiled by Torchscipt, so you can't run it with GPUs, right?
