### ISSUE TITLE
各个微调代码的差别

### ISSUE THREAD

**Issue by yzyz-77** [modelscope/modelscope#543]
请问大牛们和开发者们[https://github.com/modelscope/modelscope/blob/master/examples/pytorch/llama/run_train_lora.sh代码和https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/llama2_70b_chat/qlora/sft.sh这段代码是不是都可以模型分割并行呢？除了用torchrun、swift方面和qlora、lora方面有区别](https://github.com/modelscope/modelscope/blob/master/examples/pytorch/llama/run_train_lora.sh%E4%BB%A3%E7%A0%81%E5%92%8Chttps://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/llama2_70b_chat/qlora/sft.sh%E8%BF%99%E6%AE%B5%E4%BB%A3%E7%A0%81%E6%98%AF%E4%B8%8D%E6%98%AF%E9%83%BD%E5%8F%AF%E4%BB%A5%E6%A8%A1%E5%9E%8B%E5%88%86%E5%89%B2%E5%B9%B6%E8%A1%8C%E5%91%A2%EF%BC%9F%E9%99%A4%E4%BA%86%E7%94%A8torchrun%E3%80%81swift%E6%96%B9%E9%9D%A2%E5%92%8Cqlora%E3%80%81lora%E6%96%B9%E9%9D%A2%E6%9C%89%E5%8C%BA%E5%88%AB)，在数据并行方面有什么区别呀，前一个可以设置per_device_train_batch_size会不会每个gpu都可以跑batch_size更快些呢，感激感激，希望能模型并行和数据并行一起上跑更快些

**Comment by Jintao-Huang** [comment]
swift的代码是支持MP+DDP的, 如果你要使用DDP的话, 可以参考swift 中llm example的其他script,(e.g. qwen_7b_chat/full_mp_ddp/sft.sh). batch_size两边都是支持的.

**Comment by Jintao-Huang** [comment]
batch_size设置的比较大并不一定可以加快训练速度, 因为要padding

**Comment by Jintao-Huang** [comment]
可以参考这里的readme: https://github.com/Jintao-Huang/swift/tree/main/examples/pytorch/llm

**Comment by Jintao-Huang** [comment]
可以参考这里的readme: https://github.com/modelscope/swift/tree/main/examples/pytorch/llm
