### ISSUE TITLE
GPU 

### ISSUE THREAD

**Issue by Huzaif-Ahmed** [modelscope/modelscope#549]
**General Question**

I have downloaded the model and tried to use it as a inference i saw that this model is using cpu computation instead of gpu how should i be able to run this on my gpu of a100 nvidia

**Comment by yingdachen** [comment]
which model

**Comment by watt1010** [comment]
ms_wrapper.py这个文件看着是没有指定设备，用的一直都是CPU
sess = onnxruntime.InferenceSession(onnx_path)
是不是应该这样？
onnxruntime.InferenceSession('linear.onnx', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

**Comment by wenmengzhou** [comment]
> ms_wrapper.py这个文件看着是没有指定设备，用的一直都是CPU sess = onnxruntime.InferenceSession(onnx_path) 是不是应该这样？ onnxruntime.InferenceSession('linear.onnx', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

需要的，这是哪个模型？

**Comment by watt1010** [comment]
看着日志加载了： \modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd\pytorch_model.pt 这个不知道是不是你想要的

**Comment by wenmengzhou** [comment]
> 看着日志加载了： \modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd\pytorch_model.pt 这个不知道是不是你想要的

请升级到最新版本sdk，已修复这个问题
