### ISSUE TITLE
[Feature] will modelscope support prompt-based tuning for large language models?

### ISSUE THREAD

**Issue by rgtjf** [modelscope/modelscope#55]

**Comment by lcl6679292** [comment]
Thanks for your attention to the modelscope large language models. We have now provided the prompt-based tuning for the Chinese GPT-3 base/large/1.3B/2.7B models. You just need to handle the data and refer to the code of model card to start training. Later, we will consider supporting training larger models, including GPT-3 175B.

**Comment by rgtjf** [comment]
Thanks for your quick reply and looking forward to GPT-3 175B. I found that the fine-tuning examples exist in [GPT-3 large repo](https://modelscope.cn/models/damo/nlp_gpt3_text-generation_chinese-large/summary) and [GPT-3 poetry-generation](https://modelscope.cn/models/damo/nlp_gpt3_poetry-generation_chinese-large/summary), but not in GPT-3 13B. For GPT-3 13B and GPT-3 30B, is there a plan to release these checkpoints for the community?

**Comment by zzclynn** [comment]
We haven't had a plan to release the 13B and 30B for downloading,  yet the finetune procedures are the same with the smaller one.  So i will suggest you to run and test with smaller firstly.
