### ISSUE TITLE
How to set valid revision

### ISSUE THREAD

**Issue by wadeok** [modelscope/modelscope#550]
我通过
```
git tag v1.0.0
git push origin v1.0.0
```
在`git push`之后给仓库打上了标签，网页上能显示这些标签：
![image](https://github.com/modelscope/modelscope/assets/138575543/3fcfdc67-289a-4b2a-be72-6557f9939019)

但在实例化pipeline时 `inference = pipeline('talking-head', model='wwd123/sadtalker')`，如果不指定model_revision还是会报错：“modelscope.hub.errors.NoValidRevisionError: The model: wwd123/sadtalker has no valid revision!”。
我看了一下相关代码在`def list_model_revisions`，我获取了`path`变量，是http://www.modelscope.cn/api/v1/models/wwd123/sadtalker/revisions?EndTime=1693929600 ，打开一开，Tags是空的：
![image](https://github.com/modelscope/modelscope/assets/138575543/e7b64633-8209-4937-a88e-0d0b1cdbb895)
那么到底应该怎么操作才能生成有效的revision或Tags呢

**Comment by wenmengzhou** [comment]
pipeline中传入 model_revision='v1.1.8' 指定对应版本，   如果不填版本，默认会使用SDK发布日期前的最新版本，详细可以参考模型版本说明 https://modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E7%89%88%E6%9C%AC

**Comment by wadeok** [comment]
“如果不填版本，默认会使用SDK发布日期前的最新版本”，我现在就是这里遇到问题，我尝试不填版本，然后就报错：modelscope.hub.errors.NoValidRevisionError: The model: wwd123/sadtalker has no valid revision!，我不知道我哪里做错了，导致modelscope无法获取最新版本

**Comment by yingdachen** [comment]
> “如果不填版本，默认会使用SDK发布日期前的最新版本”，我现在就是这里遇到问题，我尝试不填版本，然后就报错：modelscope.hub.errors.NoValidRevisionError: The model: wwd123/sadtalker has no valid revision!，我不知道我哪里做错了，导致modelscope无法获取最新版本

请参考文档 https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E7%89%88%E6%9C%AC
