### ISSUE TITLE
Update mmcv from 1.x to 2.0，是否有计划更新支持mmcv2.0

### ISSUE THREAD

**Issue by hoveychen** [modelscope/modelscope#558]
**Describe the feature**

图像相关的代码依赖了mmcv1.0的写法，导致只能安装mmcv1.x（也就是mmcv-full包），而不能安装mmcv2

**Motivation**
这个事情就很恼人，因为如果使用torch2.0，那么[预编译包只有mmcv2的](https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html)。无论用pip还是mim，安装mmcv-full包都得从头开始编译，得花几个小时。

**Related resources**
我看到这个库的人也提issue了，但是没有任何后文？
https://github.com/modelscope/modelscope/issues/193

**Additional context**

**Comment by wenmengzhou** [comment]
您好，当前我们在镜像中提供了已安装mmcv环境的镜像，您可以直接使用
https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#%E6%9C%80%E6%96%B0%E9%95%9C%E5%83%8F

 mmcv升级2.0的方案和可行性我们内部会做一下调研和测试

**Comment by slin000111** [comment]
pip install mmcv_full=='1.7.0+torch2.1.1cu121' -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html，详见https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85

**Comment by liuyhwangyh** [comment]
We have no plan to upgrade, you can install mmcv-full whth 'mim install mmcv-full==1.7.2'
