### ISSUE TITLE
Origin of the Face Swapper Model

### ISSUE THREAD

**Issue by henryruhs** [modelscope/modelscope#559]
This framework looks like a collection of existing models to me.
I wonder who the original author of the face swapper of the model is? The face fusion "model" looks more like a chain to me.

https://github.com/modelscope/modelscope/blob/master/modelscope/models/cv/image_face_fusion/image_face_fusion.py#L56

**Comment by yaoyuan13** [comment]
> This framework looks like a collection of existing models to me. I wonder who the original author of the face swapper of the model is? The face fusion "model" looks more like a chain to me.
> 
> https://github.com/modelscope/modelscope/blob/master/modelscope/models/cv/image_face_fusion/image_face_fusion.py#L56

The face fusion model consists of two parts, face fusion itself and a post-processing model of face Restoration to enhance the face quality. As for the face fusion part, the backbone shares some similar part to that of faceshifter "https://arxiv.org/abs/1912.13457", but we have made a major revision by introducing a 3D reconstruction model and a flow field module to perceive the face contour（fat or thin）of user image and automatically transfer this feature to final results.

**Comment by henryruhs** [comment]
Thanks for letting us know.
