### ISSUE TITLE
modelscope下载的模型可以使用huggingface的transformer库吗？

### ISSUE THREAD

**Issue by tomjamescn** [modelscope/modelscope#560]
我下载了Baichuan2-13B-Base模型，但是发现pytorch_model-00003-of-00003.bin的md5值和从huggingface下载的是不一样的，有什么脚本可以将modelscope下载的模型转为huggingface兼容的格式吗？

**Comment by wenmengzhou** [comment]
您好，我们比对过是一样的， 您可以直接使用如下语句使用模型
```python
from modelscope import AutoModel, AutoTokenizer
model = AutoModel('baichuan-inc/Baichuan2-13B-Base', ...)

```
