### ISSUE TITLE
Xwin-LM 什么时候能上架？

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#561]

**Comment by Jintao-Huang** [comment]
你好, 你可以看看这里: 
1. 7B: https://modelscope.cn/models/AI-ModelScope/Xwin-LM-7B-V0.1/summary
2. 13B: https://modelscope.cn/models/AI-ModelScope/Xwin-LM-13B-V0.1/summary
3. 70B: https://modelscope.cn/models/AI-ModelScope/Xwin-LM-70B-V0.1/summary
