### ISSUE TITLE
使用官方提供的镜像及微调示例时有报错

### ISSUE THREAD

**Issue by zhujunjieit** [modelscope/modelscope#563]
### CPU环境使用的镜像
registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-py38-torch2.0.1-tf2.13.0-1.9.1
### 模型名称：
damo/nlp_structbert_siamese-uninlu_chinese-base
### 执行示例代码：

import os
import json
from modelscope.trainers import build_trainer
from modelscope.msdatasets import MsDataset
from modelscope.utils.hub import read_config
from modelscope.metainfo import Metrics
from modelscope.utils.constant import DownloadMode

model_id = 'damo/nlp_structbert_siamese-uninlu_chinese-base'

WORK_DIR = '/tmp'

train_dataset = MsDataset.load('people_daily_ner_1998_tiny', namespace='damo', split='train', download_mode=DownloadMode.FORCE_REDOWNLOAD)
eval_dataset = MsDataset.load('people_daily_ner_1998_tiny', namespace='damo', split='validation', download_mode=DownloadMode.FORCE_REDOWNLOAD)

max_epochs=3
kwargs = dict(
    model=model_id,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    max_epochs=max_epochs,
    work_dir=WORK_DIR)

trainer = build_trainer('siamese-uie-trainer', default_args=kwargs)

print('===============================================================')
print('pre-trained model loaded, training started:')
print('===============================================================')

trainer.train()

print('===============================================================')
print('train success.')
print('===============================================================')

for i in range(max_epochs):
    eval_results = trainer.evaluate(f'{WORK_DIR}/epoch_{i+1}.pth')
    print(f'epoch {i} evaluation result:')
    print(eval_results)

print('===============================================================')
print('evaluate success')
print('===============================================================')
### 错误如下：
![error](https://github.com/modelscope/modelscope/assets/42972147/119dacfc-8292-4412-9d8d-152cd0d56a42)

**Comment by wenmengzhou** [comment]
@tastelikefeet

**Comment by blackBatty** [comment]
请问后面解决了吗

**Comment by tastelikefeet** [comment]
最新模型版本已经解决，可以跑通readme的训练代码
另外需要配合最新的modelscope代码使用，方法为clone源代码安装或者安装>1.9.4版本（该版本会在11月末发布）

**Comment by zzzcccxx** [comment]
请问后面微调的代码如果使用自己的训练集也报相同的错误，该如何办呢？
