### ISSUE TITLE
如何进行自定义数据训练

### ISSUE THREAD

**Issue by monkeycc** [modelscope/modelscope#564]
https://www.modelscope.cn/models/damo/cv_nafnet_image-deblur_gopro/summary
去模糊
怎么用自定义数据集训练

查看官方文档

https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E8%AE%AD%E7%BB%83Train

```

加载用户自己的数据集：

from modelscope.msdatasets import MsDataset
# 载入训练数据
train_dataset = MsDataset.load('/path/to/my_train_file.txt')

查看配置文件详解

```
那么这里 my_train_file.txt 数据格式是什么

配置文件详解
https://www.modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
数据集使用指南

可以自定义txt和json
```
json格式文件

from modelscope.msdatasets import MsDataset

# 直接输入文件路径
ds = MsDataset.load('/path/to/my_file.json')
print(next(iter(ds)))

```
那么我选择 json

这个时候json数据 哪里找？
文档没有详细说明

只能靠猜
官方文档并没有写明白

猜测
https://modelscope.cn/datasets/damo/GOPRO/files
json csv 都在里面

那么从这里都下载
进行一一对应修改

最后代码要怎么训练
又一脸懵逼

可能要编写cfg_modify_fn方法
必然存在名为configuration.json或configuration.yaml的文件
？？
那怎么弄

**Comment by wenmengzhou** [comment]
https://modelscope.cn/datasets/damo/GOPRO/files   可以参考模型卡片的示例训练代码， 使用damo/GOPRO的数据集先跑通， 然后参考数据集上传文档(https://www.modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)  上传你的数据集进行训练

**Comment by wenmengzhou** [comment]
> 可以不上传数据吗
> 
> 本地数据直接训练
> 
> 数据集要保密

@wangxingjun778 请看下这个问题
