### ISSUE TITLE
Question about zeroscope_v2_xl High Resolution Text-to-Video Generation

### ISSUE THREAD

**Issue by nihaomiao** [modelscope/modelscope#571]
Hi, @wenmengzhou @tastelikefeet, thanks a lot for your interesting work! For your updated text-to-video model on https://www.modelscope.cn/models/baiguan18/zeroscope_v2_xl/summary, I followed the example code but it can only generate the video of 256\*256 instead of 576\*1024. I also dived into the code and found that the model can only synthesize the video of 256\*256. Could you help me to figure out the problem? Thanks a lot!

**Comment by yangxy** [comment]
Please try the following input:
`test_input = {
        'text': 'A panda eating bamboo on a rock.',
        "height": 320,
        "width": 576,
    }`
