### ISSUE TITLE
识别路径得分输出

### ISSUE THREAD

**Issue by im73** [modelscope/modelscope#576]
看到modelscope上模型的会输出识别路径的得分到score.txt，但我目前没有，请问是modelscope或者funasr的版本问题吗？
我的modelscope版本是1.9.1，funasr的版本是0.7.8，目前使用的是wav.scp的方式进行结果产出的
以下是我进行asr识别的代码

inference_pipeline = pipeline(
task=Tasks.auto_speech_recognition,
model='damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404',
vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
vad_model_revision="v1.1.8",
punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
param_dict=param_dict,
lm_model='damo/speech_transformer_lm_zh-cn-common-vocab8404-pytorch',
output_dir='./output_dir',    
batch_size=64
)
rec_result = inference_pipeline(audio_in="audio_files/wav.scp")

Pipeline related: @Firmament-cyou @wenmengzhou

**Comment by wenmengzhou** [comment]
@LauraGPT please help to look at this issue
