### ISSUE TITLE
V1.9.2：AttributeError: 'dict' object has no attribute 'model_dir'

### ISSUE THREAD

**Issue by Bonsen** [modelscope/modelscope#578]
from modelscope.models import Model
model = Model.from_pretrained("rgtjf1/multi-modal_gridvlp_classification_chinese-base-ecom-embedding")

It suggests like:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxxxxxxxx/anaconda3/envs/my/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 170, in from_pretrained
    model_cfg.model_dir = local_model_dir
AttributeError: 'dict' object has no attribute 'model_dir'

**Comment by wenmengzhou** [comment]
try to use following code as shown in model card,  the model class is not implemented so Model.from_pretrained is not supported
```python
from modelscope.pipelines.multi_modal.gridvlp_pipeline import GridVlpEmbeddingPipeline

pipeline = GridVlpEmbeddingPipeline('rgtjf1/multi-modal_gridvlp_classification_chinese-base-ecom-embedding')
inputs = pipeline.preprocess({'text': '女装快干弹力轻型短裤448575','image_url':'https://yejiabo-public.oss-cn-zhangjiakou.aliyuncs.com/alinlp/clothes.png'})
outputs = pipeline.forward(inputs)
print(outputs)
```

**Comment by Bonsen** [comment]
Thanks!
