### ISSUE TITLE
AttributeError: SiameseUiePipeline: 'torch.device' object has no attribute 'lower'

### ISSUE THREAD

**Issue by heihei2015** [modelscope/modelscope#581]
ModelScope中我在使用'damo/nlp_structbert_siamese-uninlu_chinese-base'模型时，根据模型示例finetune微调代码测试，报错：AttributeError: SiameseUiePipeline: 'torch.device' object has no attribute 'lower'

**Comment by wenmengzhou** [comment]
麻烦贴一下完整报错堆栈， @tastelikefeet 帮忙看下

**Comment by heihei2015** [comment]
`modelscope/trainers/nlp/siamese_uie_trainer.py` 中
```
def evaluate(self,
                 checkpoint_path: Optional[str] = None,
                 *args,
                 **kwargs) -> Dict[str, float]:

    pipeline_uie = pipeline(Tasks.siamese_uie, self.model, device=self.device)

```
改成
`pipeline_uie = pipeline(Tasks.siamese_uie, self.model, device=self.device if isinstance(self.device, str) else str(self.device))`
就可以了

**Comment by wenmengzhou** [comment]
@heihei2015  can you create a pull request for this issue

**Comment by yeyupiaoling** [comment]
我遇到这个问题，根据上面的做法解决了，谢谢大佬。

**Comment by slin000111** [comment]
modelscope/trainers/nlp/siamese_uie_trainer.py 中已修改：
pipeline_uie = pipeline(
            Tasks.siamese_uie, self.model, device=str(self.device))
