### ISSUE TITLE
yolox-pai_hand-detection is not in the pipelines registry group

### ISSUE THREAD

**Issue by KP-Zhang** [modelscope/modelscope#583]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

model_id = 'damo/cv_yolox-pai_hand-detection'
hand_detection = pipeline(Tasks.domain_specific_object_detection, model=model_id)
output = hand_detection('https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/hand_detection.jpg')

# the output contains boxes, scores and labels
print(output)

你好，我在本地机器上使用这个模型的过程中，遇见了以下问题。
KeyError: 'yolox-pai_hand-detection is not in the pipelines registry group domain-specific-object-detection. Please make sure the correct version of ModelScope library is used.'
modelscope 1.9.2
请问应该如何解决？

**Comment by wenmengzhou** [comment]
您好，请贴一下验证的报错信息

**Comment by KP-Zhang** [comment]
Traceback (most recent call last):
  File "hand_detector.py", line 5, in <module>
    hand_detection = pipeline(Tasks.domain_specific_object_detection, model=model_id)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 57, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 199, in build_from_cfg
    f'{obj_type} is not in the {registry.name}'
KeyError: 'yolox-pai_hand-detection is not in the pipelines registry group domain-specific-object-detection. Please make sure the correct version of ModelScope library is used.'

**Comment by KP-Zhang** [comment]
问题解决了，应该是mmcv和mmdet版本的问题。谢谢回复！

**Comment by ChaocunChen** [comment]
> 问题解决了，应该是mmcv和mmdet版本的问题。谢谢回复！
你好，你这具体怎么解决的，我也出现一样的问题，搞了一整天了没搞定，不知道啥问题。

**Comment by scutfrank** [comment]
> 问题解决了，应该是mmcv和mmdet版本的问题。
谢谢方便贴一下requirements.txt吗，我也报这个错误。
