### ISSUE TITLE
Errors while using git lfs and code

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [modelscope/modelscope#586]
![dd7a5b544ecb7cb76c41139ef87a41e](https://github.com/modelscope/modelscope/assets/84905965/dce98f47-02bc-4d42-ad8c-4c6c2d34ffba)
![image](https://github.com/modelscope/modelscope/assets/84905965/a8c7abd6-6e97-40ba-ae49-747329fc8715)
As title, I got some errors while using git lfs and code

**Comment by wenmengzhou** [comment]
does the error always exists?   the error from code means  network is not good so the file downloaded is not completed

**Comment by Ethan-Chen-plus** [comment]
@wenmengzhou This error still occurs after many trys. But during download we can see the progress about `50MB/s`. So I don't this is a network error.

**Comment by liuyhwangyh** [comment]
> @wenmengzhou This error still occurs after many trys. But during download we can see the progress about `50MB/s`. So I don't this is a network error.

Make sure the disk is not full？
