### ISSUE TITLE
Model Export Error. AttributeError: 'dict' object has no attribute 'model_dir'

### ISSUE THREAD

**Issue by chiragsamal** [modelscope/modelscope#587]
**Description:**

When trying to use the `Model.from_pretrained()` method with the following code:

```python
from modelscope.models import Model
from modelscope.exporters import Exporter
model_id = 'damo/cv_unet_skin-retouching'
model = Model.from_pretrained(model_id)
output_files = Exporter.from_model(model).export_onnx(opset=13, output_dir='/tmp', ...)
print(output_files)
```
I encounter the following error:
AttributeError                            Traceback (most recent call last)
----> model = Model.from_pretrained(model_id)

/usr/local/lib/python3.10/dist-packages/modelscope/models/base/base_model.py in from_pretrained(cls, model_name_or_path, revision, cfg_dict, device, **kwargs)
    168             return model
    169         # use ms
--> 170         model_cfg.model_dir = local_model_dir
    171 
    172         # install and import remote repos before build

AttributeError: 'dict' object has no attribute 'model_dir'

**Comment by wenmengzhou** [comment]
currently exporting skin retouching mode is not supported

**Comment by chiragsamal** [comment]
Is there any way I can export the model on my own?

**Comment by wenmengzhou** [comment]
you can refer to the model initalization code in the pipeline here (https://modelscope.cn/models/damo/cv_unet_skin_retouching_torch/file/view/master/ms_wrapper.py)  and try to use the pytorch interface to export the onnx model
