### ISSUE TITLE
显存泄漏

### ISSUE THREAD

**Issue by wen020** [modelscope/modelscope#588]
使用modelscope.pipelines加载模型使用完成之后
    del retinaface_detection
    del salient_detect
    del skin_retouching
    del portrait_enhancement
    del face_recognition
    torch.cuda.empty_cache()
    gc.collect()
使用如上方法清理模型，但是最后发现还是有部分显存泄漏

请问这个有人遇到过吗，有没有啥解决方案？

**Comment by huwenkai26** [comment]
我也遇到过使用lama模型时候，一旦显存升上去后就下不来了

**Comment by wenmengzhou** [comment]
查看下模型文件，有一部分模型中有tensorflow模型，只能通过销毁进程方式释放显存
