### ISSUE TITLE
Install issues about aliyun-python-sdk-core

### ISSUE THREAD

**Issue by THtianhao** [modelscope/modelscope#589]
您好我是写了一个Comfyui的插件叫 [ComfyUI-Portrait-Maker](https://github.com/THtianhao/ComfyUI-Portrait-Maker)，很多windows用户出现一个问题，我的windows用户安装modelscope包的时候依赖于aliyun-python-sdk-core 出现下面的错误：
```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.13.36.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\albam\AppData\Local\Temp\pip-install-025cd5tn\aliyun-python-sdk-core_78b82f9b135341b1a2825e5884118385\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]
```
不仅仅是我遇到了这样的问题，使用ComfyUI的用户只要是windows用户，使用了ComfyUI的整合包[release](https://github.com/comfyanonymous/ComfyUI/releases)有依赖于aliyun-python-sdk-core 的，都会出现pip安装不了的情况，也咨询了ComfyUI的作者，作者给出的解决方案也解决不了 如下[aliyunsdkcore error](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/223)
请阿里的大神们帮忙看看，毕竟这个问题不在少数，我在Stable-diffusion-webui的issue里面也看到过类似的问题，都是无法解决

* **Python Version**:3.10.11
* **aliyunsdkcore Version**:modelscope 1.9.2
* **API**:aliyun-python-sdk-core

**Comment by wenmengzhou** [comment]
这个看起来是aliyun python sdk core的问题，先pip uninstall 安装重新安装是否可以？

**Comment by THtianhao** [comment]
不可以的，只要是ComfyUI release安装包的python环境安装modelscope都安装不上

**Comment by RalphHan** [comment]
I resolved it by running
```
pip install aliyun-python-sdk-core-v3==2.13.10
```

**Comment by huahua-er** [comment]
下载离线包，修改setup.py，直接给version赋值，VERSION =  "你下载的版本号",再离线安装。我是这么解决的，不明白原因，感觉是ali的version赋值方式识别不了。
