### ISSUE TITLE
TTS 流式合成

### ISSUE THREAD

**Issue by FB-wh** [modelscope/modelscope#602]
如果想实现流式合成，需要把模型需要拆分成encoder, decoder和PostNet三个模型吗？

**Comment by hukai-sun** [comment]
是的，一般对于TTS模型而言，encoder耗时很小可以一次性计算完，而decoder和PostNet由于在帧级别进行计算，相对计算量大，属于流式合成重点关注的对象，且decoder和PostNet在look-ahead方面也存在一些差异，需要单独设计流式方案。
