### ISSUE TITLE
ARM架构提效

### ISSUE THREAD

**Issue by Emo1995** [modelscope/modelscope#605]
请问，ARM架构apple主推mps，torch2.0版本以上已经支持了mps，但是modelscope目前看来是对torch的包装，但是这层包装没支持mps，可否支持mps，让M系列提升效率

**Comment by wenmengzhou** [comment]
您好，我们支持torch2.0，您可以尝试对device传入device='mps'进行尝试，部分模型存在绑定gpu的写法，如有遇到请反馈给我们进行修改，也欢迎您提PR支持
