### ISSUE TITLE
what sheduler to use in damo/Video-to-Video finetuneing

### ISSUE THREAD

**Issue by hpoghos** [modelscope/modelscope#606]
Hi, I'm trying to finetune the `damo/Video-to-Video` model, (great model btw)
could you please share the details of the scheduler used in the progressive distillation process?

Model related: @wenmengzhou @tastelikefeet
Finetune related: @tastelikefeet  @Jintao-Huang

**Comment by oReano** [comment]
We use cosine schedule in Video-to-Video model.
Detailed codes are listed below:

```
num_timesteps=1000
betas = []
for step in range(num_timesteps):
    t1 = step / num_timesteps
    t2 = (step + 1) / num_timesteps
    fn = lambda u: math.cos((u + 0.008) / 1.008 * math.pi / 2) ** 2
    betas.append(min(1.0 - fn(t2) / fn(t1), 0.999))
```

**Comment by hpoghos** [comment]
Thanks a lot @oReano
