### ISSUE TITLE
自定义管道的模型输入路径

### ISSUE THREAD

**Issue by danyow-cheung** [modelscope/modelscope#608]
**General Question**

跟着https://www.modelscope.cn/models/damo/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/summary

想改变其他的模型作为使用，没有在pipeline找到相关的路径。目前只找到这部分 [def normalize_model_input(model, ](https://github.com/modelscope/modelscope/blob/cb0a44eda5d5b7728406ac7bb13271f5b7e8b014/modelscope/pipelines/builder.py#L24) 

我希望解决的是，

```python
# inference = pipeline(task=Tasks.text_to_speech, model=model_id) # 原始代码
inference = pipeline(task=Tasks.text_to_speech, model="/.../tmp_am/ckpt/checkpoint_2400000.pth") # 希望使用的
output = inference(input="xxx")
```
Pipeline related: @Firmament-cyou @wenmengzhou

**Comment by wenmengzhou** [comment]
你需要参考原始模型目录，copy一份替换其中的pytorch_model.bin文件，传入本地模型目录名进行加载

如果想要使用自己开发的pipeline,可以参考configuration.json中的pipeline.type找到对应的源码文件进行推理模型的修改
