### ISSUE TITLE
怎么把对话的历史信息传递给模型？

### ISSUE THREAD

**Issue by SilasTHU** [modelscope/modelscope#610]
官方调用llama2-70b-chat的文档如下，
inputs = {'text': "some words", 'max_length': 8, 'system': system}
output = model.chat(inputs, tokenizer)
我看源码第二行chat方法里面有可以传history参数来支持多轮对话，但是没有API的使用说明，请问具体是怎么传的呢？应该怎么处理输入输出呢？

**Comment by lylalala** [comment]
@SilasTHU 

hi，可以参考这段代码看到参数的解析过程 https://github.com/modelscope/modelscope/blob/master/modelscope/models/nlp/llama/text_generation.py#L95

在您的inputs中再加入"history"即可，它是一个List[Tuple[str, str]]，Tuple的前者是user_words，后者是assistant_words。例如：
inputs = {'text': 'What\'s fun there', 'max_length': 500, 'system': system, 'history':[('how are you', 'As an AI, I don\'t have feelings, but I\'m here to help you. How can I assist you today?'), ('where is London', 'London is the capital city of England and the United Kingdom.')]}
