### ISSUE TITLE
尝试解除对`datasets`库版本的限制

### ISSUE THREAD

**Issue by LZHgrla** [modelscope/modelscope#612]
**Describe the feature**
解除`modelscope`库对`datasets`库版本的限制
https://github.com/modelscope/modelscope/blob/eff11817a0eaf57ef788c0281b8e62641523fa5b/requirements/framework.txt#L3

**Motivation**
无法安装最新版本`datasets`，且容易与其它第三方仓库存在版本冲突

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by wangxingjun778** [comment]
Hi, the latest version of datasets will be supported in the next release, and you can install latest datasets manually for now.

**Comment by LZHgrla** [comment]
@wangxingjun778 
Thanks!

**Comment by LZHgrla** [comment]
Hi! @wangxingjun778 
If there is any progress on this issue about the `datasets` version?

**Comment by wangxingjun778** [comment]
The modelscope v1.10 is ready to launch; before that, you can reinstall the datasets==2.14.6 to solve your problem for now.

**Comment by wangxingjun778** [comment]
v1.10.0 has already released.
