### ISSUE TITLE
Removing weight norm...

### ISSUE THREAD

**Issue by zhuxiu1234** [modelscope/modelscope#616]
合成语音时：
Removing weight norm...
消失太多时间了，可以优化吗？

**Comment by wenmengzhou** [comment]
具体什么模型？  消失太多时间是指卡在哪里太久了么？

**Comment by zhuxiu1234** [comment]
> 具体什么模型？ 消失太多时间是指卡在哪里太久了么？

![136af424a975a906b72c88703fc5e19](https://github.com/modelscope/modelscope/assets/58240847/5c982d04-441f-4ad3-920b-ba88ea38d647)
![3696a55e366c12386bd0c2fe770d48b](https://github.com/modelscope/modelscope/assets/58240847/7af9fc38-3090-4616-bb40-84c979bccd7d)

模型：speech_tts/speech_sambert-hifigan_tts_ainan_zh-cn_16k

**Comment by zhuxiu1234** [comment]
请问“Removing weight norm...” 是在做什么工作？ 耗时了16秒，一直会报“Load pinyin_en_mix_dict failed”

**Comment by Insswer** [comment]
“Load pinyin_en_mix_dict failed”可以忽略，“Removing weight norm...”是vocoder模型推理前的日志，这个模型建议在gpu上推理

**Comment by zhuxiu1234** [comment]
![b1c01716bba802b64078fd69eff3f86](https://github.com/modelscope/modelscope/assets/58240847/d8df428c-1c4d-4f34-9932-42bf97c479cd)
是在用GPU的环境呀

**Comment by zhuxiu1234** [comment]
![04839d80f1137e2b3449d2391afcaea](https://github.com/modelscope/modelscope/assets/58240847/120be6fd-8906-43ed-a536-e98afff9cd64)

用的是GPU，跑起来显存占用3G左右，试了好多次，200个字，总耗时都在22秒
