### ISSUE TITLE
尝试从本地加载模型，但每次都从ModelScope下载到.cache中。

### ISSUE THREAD

**Issue by HUAWilliam** [modelscope/modelscope#619]
尝试从本地加载模型，但每次都从ModelScope下载到.cache中。
即使我将.cache内的模型CP到指定路径，并尝试加载这个路径，它依然从.cache内加载，如果.cache内没有就还是会去拉取模型，而不是从本地加载。
模型地址：https://www.modelscope.cn/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/summary
![image](https://github.com/modelscope/modelscope/assets/29301643/86c7327c-9b06-4ca8-8377-cc56ef011269)

**Comment by HUAWilliam** [comment]
实测加不加reversion都有这个bug。

**Comment by mumuszhang** [comment]
同问，为什么不能指定路径

**Comment by wenmengzhou** [comment]
![image](https://github.com/modelscope/modelscope/assets/4771825/d712d703-8a8c-44c4-b968-b6888ed0d834)
这个模型内部依赖了另一个模型，请把另一个模型也下载后，并修改configuration.json中的model对应的value为本地路径
