### ISSUE TITLE
movie_scene_segmentation 安装缺依赖包shotdetect_scenedetect_lgss

### ISSUE THREAD

**Issue by BMEI1314** [modelscope/modelscope#62]
你好, 我在尝试movie_scene_segmentation task时，不能正常pip install shotdetect_scenedetect_lgss. 目前暂未在公开源find这个library。

**Comment by yingdachen** [comment]
请参考我们的[官方文档](https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85)。

对于cv领域，可以使用
pip install ".[cv]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

具体到shotdetect_scenedetect_lgss这个包，这当前是host在modelscope的whl repo里的，要单独安装，可以用
pip install shotdetect_scenedetect_lgss -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by BMEI1314** [comment]
完美解决
