### ISSUE TITLE
容器离线部署时报错

### ISSUE THREAD

**Issue by qiangruoyu** [modelscope/modelscope#620]
我用的时damo/cv_tinynas_head-detection_damoyolo这个模型。
使用容器部署时报错：
HTTPConnectionPool(host='[www.modelscope.cn](https://www.modelscope.cn/)', port=80): Max retries exceeded with url
我传入的时本地local
代码如下
`model_id = 'damo/cv_tinynas_head-detection_damoyolo'
img=Image.open('image/image_detection.jpg')
head_detection = pipeline(Tasks.domain_specific_object_detection, model="src")`
我已经时用的离线部署了，为什么还会在部署容器的时候爆出这个错误。

**Comment by wenmengzhou** [comment]
src目录下存放了所有模型吗？请贴出调用堆栈和src目录的内容
