### ISSUE TITLE
微调mPLUG视觉问答模型-中文-base时，内存一直增加。

### ISSUE THREAD

**Issue by tianruochen** [modelscope/modelscope#623]
微调mPLUG视觉问答模型-中文-base时，内存一直增加。
![image](https://github.com/modelscope/modelscope/assets/34831314/dfa59704-abec-4b30-b277-77d2fc58ef54)

@tastelikefeet  @Jintao-Huang

**Comment by xhyandwyy** [comment]
请问是基于pytorch dataloader吗？这是torch的问题，最好数据切片
