### ISSUE TITLE
本地运行 LLM riddle 没有响应

### ISSUE THREAD

**Issue by DuskSwan** [modelscope/modelscope#629]
我试图在本地运行LLM riddle，按照

> 1. 克隆项目代码：`git clone https://github.com/modelscope/modelscope.git`
> 1. 进入到examples/apps/llm_riddles目录。
> 1. 安装所需的Python依赖pip install -r requirements.txt。
> 1. 执行启动命令python app.py.

执行后，控制台输出

```shell
Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.   

Also please ensure that your antivirus or firewall is not blocking the binary file located at: D:\Aquark\application\tools\Anaconda3\envs\modelscope\lib\site-packages\gradio\frpc_windows_amd64_v0.2
```

在`http://127.0.0.1:7860`可以打开网页，但发送输入后，模型一直在思考没有反馈。

按照控制台的提示，我尝试打开`https://status.gradio.app`，可以正常访问；关于防火墙，我在路径`D:\Aquark\application\tools\Anaconda3\envs\modelscope\lib\site-packages\gradio`下并没有看到有叫`frpc_windows_amd64_v0.2`的文件。

请问是哪里出了问题？是需要提供API吗？

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

**Comment by wenmengzhou** [comment]
模型没有反应的问题，前往[DashScope](https://dashscope.aliyun.com/)开通服务，获取token，配置环境变量DASHSCOPE_API_KEY=你的API-KEY

第二个没法创建共享链接应该是镜像中缺少frpc_windows_amd64_v0.2导致创建失败

**Comment by DuskSwan** [comment]
> 模型没有反应的问题，前往[DashScope](https://dashscope.aliyun.com/)开通服务，获取token，配置环境变量DASHSCOPE_API_KEY=你的API-KEY
> 
> 第二个没法创建共享链接应该是镜像中缺少frpc_windows_amd64_v0.2导致创建失败

好的，已经获取API-KEY，frpc_windows_amd64_v0.2也下载了。但打开的网页还是提交后一直无响应。我觉得可能是前端的问题，因为把函数generate_response(input)单独拿出来测试是有结果的，看起来似乎是网页没有正确更新……

另外，我觉得可以把题目和app.py分离，以便增减修改每个章节的题目。如果你认为这样做有意义，我想提交一个pull request来实现这个想法。

**Comment by wenmengzhou** [comment]
感谢您的建议，请参考下最新代码，题目和app.py已经分离，也欢迎贡献更多的功能哈

**Comment by wenmengzhou** [comment]
网页没有响应看下后台日志？ generate_response那块可以打一些debug log，目前代码如果运行出错后台会打印出报错信息

**Comment by DuskSwan** [comment]
才看到更新😂我会试着加入一些有趣的题目

**Comment by DuskSwan** [comment]
能否说一下gradio的版本？我认为也可能是我的gradio版本不合适。因为运行app.py时还会提示有一些无用的参数
 ```
d:/GithubRepos/modelscope/examples/apps/llm_riddles/app.py:192: UserWarning: You have unused kwarg parameters in Textbox, please remove them: {'disabled': True}
  challenge_result = gr.Textbox(label='挑战结果', disabled=True)
d:/GithubRepos/modelscope/examples/apps/llm_riddles/app.py:194: UserWarning: You have unused kwarg parameters in Chatbot, please remove them: {'lines': 8}
  lines=8, label='Qwen-plus', elem_classes='control-height')
d:/GithubRepos/modelscope/examples/apps/llm_riddles/app.py:201: UserWarning: `width` is deprecated in `Interface()`, please use it within `launch()` instead.
  shareImg = gr.Image(label='分享成绩', visible=False, width=400)
```

**Comment by DuskSwan** [comment]
已经确认是gradio版本的问题，根据最新版库的requirement.txt下载了3.39.0版本的gradio就可以正常运行了！

此外报告两个小bug：
1. 3.39.0版本的gradio要求python版本至少为3.8，但是modelscope主页README中的[Setup Local Python Environment](https://github.com/modelscope/modelscope#setup-local-python-environment)只提到3.7
2. app.py中，模型选择框的默认值为qwen-plus，与下拉框选项`['通义千问max', '通义千问plus', 'chatglm-turbo']`不符，如果不手动选择一次，就会在调用模型时报错

最后还有一个疑问：
运行时会警告说有多余的参数，虽然不影响功能，但总是有点碍眼。
```
d:/GithubRepos/modelscope/examples/apps/llm_riddles/app.py:183: GradioUnusedKwargWarning: You have unused kwarg parameters in Textbox, please remove them: {'disabled': True}
  challenge_info = gr.Textbox(
d:/GithubRepos/modelscope/examples/apps/llm_riddles/app.py:188: GradioUnusedKwargWarning: You have unused kwarg parameters in Textbox, please remove them: {'disabled': True}
  challenge_result = gr.Textbox(label='挑战结果', disabled=True)
d:/GithubRepos/modelscope/examples/apps/llm_riddles/app.py:189: GradioUnusedKwargWarning: You have unused kwarg parameters in Chatbot, please remove them: {'lines': 8}
  chatbot = gr.Chatbot(
```
我怀疑这也是gradio版本问题所致，可能这部分代码是LLM生成的，所以版本比较混乱？

**Comment by wenmengzhou** [comment]
1.  modelscope主库支持python3.7+以上，相关文档我改一下
2 的bug在PR #638 中已修复，待merge
3. 确实，这个app.py的代码主体是llm写的，但是disabled参数应该是老版本的参数，新版本的参数应该是interactive  https://www.gradio.app/docs/textbox

**Comment by diablov** [comment]
能把需要的依赖版本全指定下吗，安装失败了，从gradio、gradio_client、setuptools、jinja2都试过了，搞不定
