### ISSUE TITLE
unifold cpu 环境有问题

### ISSUE THREAD

**Issue by zzclynn** [modelscope/modelscope#63]
复现环境： modelscope notebook cpu版本

复现方式：
from modelscope.pipelines import pipeline

pipeline_ins = pipeline(
    task='protein-structure',
    model='DPTech/uni-fold-monomer')
protein = 'LILNLRGGAFVSNTQITMADKQKKFINEIQEGDLVRSYSITDETFQQNAVTSIVKHEADQLCQINFGKQHVVC'
outputs = pipeline_ins(protein)

问题：
![image](https://user-images.githubusercontent.com/5746653/210511706-66000492-3373-4c01-9159-a042c05f4b90.png)

**Comment by yingdachen** [comment]
unifold模型目前只支持gpu环境使用，已经在model card上添加明确说明。
