### ISSUE TITLE
SCRFD人脸检测关键点模型 示例報錯

### ISSUE THREAD

**Issue by HYL-Dave** [modelscope/modelscope#64]
```
import cv2
from modelscope.pipelines import pipeline
from modelscope.utils.constant import  Tasks

face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_resnet_facedetection_scrfd10gkps')
img_path = 'https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/face_detection2.jpeg'
result = face_detection(img_path)

# if you want to show the result, you can run
from modelscope.utils.cv.image_utils import draw_face_detection_result
from modelscope.preprocessors.image import LoadImage
img = LoadImage.convert_to_ndarray(img_path)
cv2.imwrite('srcImg.jpg', img)
img_draw = draw_face_detection_result('srcImg.jpg', result)
import matplotlib.pyplot as plt
plt.imshow(img_draw)
```
![螢幕快照 2023-01-04 18-22-30](https://user-images.githubusercontent.com/39075627/210534523-2bcbe976-8213-4dac-89f4-2477eab92561.png)

**Comment by yingdachen** [comment]
thank you for reporting the issue. this is a known regession that is caused by our last release, a fix will be available this week.

**Comment by HYL-Dave** [comment]
> thank you for reporting the issue. this is a known regession that is caused by our last release, a fix will be available this week.

Thanks! When I have updated modelscope, the new issue generate:
![螢幕快照 2023-01-06 11-52-17](https://user-images.githubusercontent.com/39075627/210926716-c0c37a83-a3a8-49d5-9b45-2b906d04adcd.png)
![螢幕快照 2023-01-06 11-53-24](https://user-images.githubusercontent.com/39075627/210926730-28c668ab-0a67-42a8-bd8c-5eda2fda9633.png)

**Comment by wenmengzhou** [comment]
> > thank you for reporting the issue. this is a known regession that is caused by our last release, a fix will be available this week.
> 
> Thanks! I have updated modelscope, the new issue generate: ![螢幕快照 2023-01-06 11-52-17](https://user-images.githubusercontent.com/39075627/210926716-c0c37a83-a3a8-49d5-9b45-2b906d04adcd.png) ![螢幕快照 2023-01-06 11-53-24](https://user-images.githubusercontent.com/39075627/210926730-28c668ab-0a67-42a8-bd8c-5eda2fda9633.png)

try to delete the local model cache and run it again？

**Comment by yingdachen** [comment]
please delete the entire local model cache folder:

![image](https://user-images.githubusercontent.com/5042027/211128754-831f7b52-1e9e-404a-8dbe-8a55517f0493.png)

and try again

**Comment by HYL-Dave** [comment]
> please delete the entire local model cache folder:
> 
> ![image](https://user-images.githubusercontent.com/5042027/211128754-831f7b52-1e9e-404a-8dbe-8a55517f0493.png)
> 
> and try again

Yes, it works. After I assign path to 'damo/cv_resnet_facedetection_scrfd10gkps', it is normal. But it is so strange. When I run the following code, it also works.


```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline('face-detection', 'cache_dir/damo/cv_resnet_facedetection_scrfd10gkps')

result = p('face_detection.png',)

print(result)
```

**Comment by yingdachen** [comment]
for this code

p = pipeline('face-detection', 'cache_dir/damo/cv_resnet_facedetection_scrfd10gkps')


the second parameter is model_id_or_model_dir, when model id (damo/cv_resnet_facedetection_scrfd10gkps) is supplied, it will fetch the correct version of the model from modelscope hub, when a local model_dir is provided, it will use the local dir path, in this case, user would be responsbile for enesuring that the correct version of modelscope library is used for the model dir.
