### ISSUE TITLE
目前测试结果反馈

### ISSUE THREAD

**Issue by freejacklee** [modelscope/modelscope#641]
个人觉得写实风格效果好于写真效果，眼睛处理效果不太好，原本戴着眼镜的图片生成后眼镜有残留痕迹，原本没有戴着眼镜的图片生成后眼睛效果也不太好。

**Comment by wenmengzhou** [comment]
应该发在modelscope/facechain repo下？https://github.com/modelscope/facechain

**Comment by freejacklee** [comment]
@wenmengzhou 谢谢你，已经转移发布了。
