### ISSUE TITLE
如何调用OCR ONNX模型

### ISSUE THREAD

**Issue by vance-coder** [modelscope/modelscope#646]
这边提供了ONNX model，但是不知道如何调用？
![image](https://github.com/modelscope/modelscope/assets/63489610/3e1d8411-a778-466c-95f9-edbd1af4b3ee)

**Comment by wenmengzhou** [comment]
https://modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E5%AF%BC%E5%87%BA#OCRRecognition%E7%9A%84ocr-recognition%E4%BB%BB%E5%8A%A1

**Comment by vance-coder** [comment]
文档好像有问题，按照文档写的，只有CRNN导出成功，damo/cv_convnextTiny_ocr-recognition-handwritten_damo 导出失败，换了input shape才可以，但是预处理的时候也不知道如何做？
![image](https://github.com/modelscope/modelscope/assets/63489610/f7243a56-f5be-4b2e-9221-f5b7336d8641)

**Comment by slin000111** [comment]
https://www.modelscope.cn/models/damo/cv_convnextTiny_ocr-recognition-handwritten_damo/summary模型卡片提供了示例代码——onnx模型使用，可以参考一下。

**Comment by vance-coder** [comment]
> https://www.modelscope.cn/models/damo/cv_convnextTiny_ocr-recognition-handwritten_damo/summary 模型卡片提供了示例代码——onnx模型使用，可以参考一下。

你好，我这边试了的，但是失败了

**Comment by scutyuanzhi** [comment]
> > https://www.modelscope.cn/models/damo/cv_convnextTiny_ocr-recognition-handwritten_damo/summary 模型卡片提供了示例代码——onnx模型使用，可以参考一下。
> 
> 你好，我这边试了的，但是失败了，报错如下：
> 
> `onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1507' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,75,192}, requested shape:{1,3,75,192}`

https://www.modelscope.cn/models/damo/cv_convnextTiny_ocr-recognition-handwritten_damo/summary 已经修复了，可以再看一下。

**Comment by vance-coder** [comment]
> > > https://www.modelscope.cn/models/damo/cv_convnextTiny_ocr-recognition-handwritten_damo/summary 模型卡片提供了示例代码——onnx模型使用，可以参考一下。
> > 
> > 
> > 你好，我这边试了的，但是失败了，报错如下：
> > `onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1507' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,75,192}, requested shape:{1,3,75,192}`
> 
> https://www.modelscope.cn/models/damo/cv_convnextTiny_ocr-recognition-handwritten_damo/summary 已经修复了，可以再看一下。

已经可以了，谢谢
