### ISSUE TITLE
为啥无法直接使用Model.from_pretrained  damo/cv_unet_image-matting

### ISSUE THREAD

**Issue by imkoe** [modelscope/modelscope#649]
很抱歉，我是一个小白，我想尝试使用Model.from_pretrained  去加载一个模型 cv_unet_image-matting，但是会报以下错误。

KeyError('`cfg` or `default_args` must contain the key "type", but got {\'model_dir\': \'/mnt/workspace/.cache/modelscope/damo/cv_unet_image-matting\'}\nNone')

![image](https://github.com/modelscope/modelscope/assets/19381461/a3fbb352-d5c2-44ea-9a1e-26bdc84510ad)

我不知道应该还要填写什么内容

**Comment by slin000111** [comment]
本地验证，该模型暂时不支持Model.from_pretrained。如果下载模型可以使用snapshot_download('damo/cv_unet_image-matting')，详见modelscope官网文档中心模型下载；如果推理，您可以使用模型卡片代码范例。
