### ISSUE TITLE
no attribute '_register_wrapper_optimizer_cls'

### ISSUE THREAD

**Issue by fadilparves** [modelscope/modelscope#651]
**General Question**

Hi. When I run this command
text_detector = pipeline(Tasks.ocr_detection, model = 'damo/cv_resnet18_ocr-detection-line-level_damo')

I am getting
AttributeError: OCRDetectionPipeline: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'

tensorflow==2.13.0
keras==2.13.1

Any idea how to solve this?

Thank you

**Comment by slin000111** [comment]
This model depends on tensorflow1.15.x, try to use tensorflow1.15.5.

**Comment by slin000111** [comment]
Try  tensorflow1.15.5, this model depends on tensorflow1.15.x.

**Comment by fadilparves** [comment]
Yup I changed to tf 2.12.0 and then it worked. Thank you @slin000111
