### ISSUE TITLE
怎么使用 Python SDK 下载数据集的数据文件（不是meta data

### ISSUE THREAD

**Issue by ChaosCodes** [modelscope/modelscope#653]
我通过 MsDataset.upload 上传了经过 tar 打包后的数据，然后我想在 linux 平台把数据拉下来，但是我发现通过 MsDataset.load 或者 git clone 的方法只能拉下**元数据文件**。请问一下有什么使用 Python SDK 的办法可以把**数据文件**（**非元数据文件**）下载下来么？
感谢！@wangxingjun778

**Comment by ChaosCodes** [comment]
我看了 get_file_download_url 以及 snapshot_download 这些方法，他们好像只支持 model 的下载，想问一下有什么方法可以下载数据文件么，因为我上传的是已经预处理好的数据，为了让不同的机器的数据集保持一致。

**Comment by wangxingjun778** [comment]
参考如下数据集： https://modelscope.cn/datasets/wangxingjun778/small_tar_file_test/files

**Comment by ChaosCodes** [comment]
好的谢谢
