### ISSUE TITLE
您好，请问基于langchain的外部知识库问答，如何构建多轮对话

### ISSUE THREAD

**Issue by whm233** [modelscope/modelscope#655]
class QianWenChatLLM(LLM):
    max_length = 10000
    temperature: float = 0.01
    top_p = 0.9

    def __init__(self):
        super().__init__()

    @property
    def _llm_type(self):
        return "ChatLLM"

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        print(prompt)
        response, history = model.chat(tokenizer, prompt, history=None)
        torch_gc()
        return response

我看这个模型的history=None，我需要怎么修改代码才能让模型有记忆

**Comment by slin000111** [comment]
模型history在modelscope官网qwen/Qwen-7B-Chat模型卡片快速使用中提供了样例，多轮对话部分您可以参考。详见https://modelscope.cn/models/qwen/Qwen-7B-Chat/summary
