### ISSUE TITLE
Cowardly refusing to serialize non-leaf tensor which requires_grad, since autograd does not support crossing process boundaries.

### ISSUE THREAD

**Issue by Aftershcoolha** [modelscope/modelscope#656]
![WeChat101b23bc8071d4dc2fb9e59661aa7139](https://github.com/modelscope/modelscope/assets/39073821/4b5f8975-b974-4553-8a82-04cf946dae7e)微调模型训练过程中报错

**Comment by slin000111** [comment]
是BlueLM-7B-Chat这个模型吗？这个模型微调用swift比较方便，https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/bluelm_7b_chat/lora/sft.sh

**Comment by Aftershcoolha** [comment]
> 是BlueLM-7B-Chat这个模型吗？这个模型微调用swift比较方便，https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/bluelm_7b_chat/lora/sft.sh

damo/nlp_gpt3_text-generation_chinese-base。是这个模型，本地跑的，会跟python的版本有关系吗

**Comment by slin000111** [comment]
看报错截图，像是evaluation报错了。如果你加了evaluation的话，可以参考modelscope/examples/pytorch/text_generation/finetune_text_generation.py，有gpt3_1.3B的例子。
