### ISSUE TITLE
movie_scene_segmentation  bug

### ISSUE THREAD

**Issue by BMEI1314** [modelscope/modelscope#66]
MovieSceneSegmentationModel  class 的 inference function有问题, 在batch inference时,计算 batch迭代次数时有小bug,当bs== input.size(0)时会error, `cnt = shot_num // bs + 1` -> `cat = math.ceil(shot_num/bs)`

**Comment by pida0** [comment]
Thank you for reporting the issue. A fix will be available soon

**Comment by pida0** [comment]
> MovieSceneSegmentationModel class 的 inference function有问题, 在batch inference时,计算 batch迭代次数时有小bug,当bs== input.size(0)时会error, `cnt = shot_num // bs + 1` -> `cat = math.ceil(shot_num/bs)`

Thank you for reporting the issue. A fix will be available soon
