### ISSUE TITLE
关于I2VGen-XL模型的问题

### ISSUE THREAD

**Issue by muximuxi** [modelscope/modelscope#663]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

按照modelscope提供的demo:
from modelscope.pipelines import pipeline
from modelscope.outputs import OutputKeys
pipe = pipeline(task="image-to-video", model='damo/Image-to-Video', model_revision='v1.1.0', device='cuda:0')
# IMG_PATH: your image path (url or local file)
output_video_path = pipe(IMG_PATH, output_video='./output.mp4')[OutputKeys.OUTPUT_VIDEO]
print(output_video_path)
执行后报错信息如下
WARNING - No preprocessor key ('image-to-video-model', 'image-to-video') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-12-06 18:54:38,779 - modelscope - WARNING - task image-to-video input definition is missing
2023-12-06 18:55:32,676 - modelscope - ERROR - Save Video Error with 
2023-12-06 18:55:32,678 - modelscope - WARNING - task image-to-video output keys are missing
没有结果生成，请问怎么解决？

**Comment by IceClear** [comment]
The reason is that the video generation process is fixed to use ffmpeg and no results will be generated if your ffmpeg does not support x264 codec. You can change the [video generation command](https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/multi_modal/video_to_video_pipeline.py#L113) to other commands such as imageio.

**Comment by muximuxi** [comment]
ok , thank you .By the way, there is also a problem, that is, if there is someone in the input picture, the face will be distorted and changed in the output video.
