### ISSUE TITLE
StructBERT是否能生成句向量，

### ISSUE THREAD

**Issue by song4875343** [modelscope/modelscope#67]
感觉structBert和双塔召回模型很像，但是好像并不能像一般的bert模型一样导出句向量，目前句向量的生成模型都太大了，速度慢不适合做召回用。如果sructbert 像cross bert一样不能输出句向量。是否能够提供一些能输出句向量的tiny模型

**Comment by dingkun-ldk** [comment]
你好, 目前ModelScope提供不同行业、中英文文本向量模型, 具体参考模型列表: [模型列表](https://modelscope.cn/models?page=1&tasks=sentence-embedding&type=nlp)

关于inference速度问题，后续我们会考虑提供比base模型计算资源消耗更小的lite/tiny模型

目前已有的base模型你看看是否可以通过离线缓存的方式满足实际使用的要求
