### ISSUE TITLE
请问模型库中video-stabilization(视频去抖动算法)如何做到边取流边去抖动

### ISSUE THREAD

**Issue by suncheng-guihub** [modelscope/modelscope#677]
您好，我想使用模型库中的video-stabilization做视频去抖动。目前我的步骤是：首先拉去摄像头rtsp流，然后使用算法得到稳定的视频流，最后推送到web端。但是我注意到算法依赖于连续的多张帧，那么就不能做到实时的去抖动算法。请问如何解决这个问题

**Comment by slin000111** [comment]
模型卡片上的使用建议：使用16G显存的显卡测试时，建议的最大输入为 30fps帧率下30s时长的1920x1080分辨率视频。您根据这个建议尝试看能否对摄像头视频进行处理，实现实时去抖动。
