### ISSUE TITLE
ROM/coROM系列模型是否可以支持自定义语料微调？

### ISSUE THREAD

**Issue by Gladiator566** [modelscope/modelscope#678]
诸如damo/nlp_rom_passage-ranking_chinese-base等语义相关性排序模型，目前我看是用DuReader模型进行训练的，请问是否可以支持用自己语料进行微调？

**Comment by slin000111** [comment]
有示例代码的模型是支持的，cfg和数据集格式参考模型卡片，加载本地数据集参考modelscope官网 / 文档中心 / modelscope library教程 / 数据集使用指南。

**Comment by Gladiator566** [comment]
多谢，我试一下
