### ISSUE TITLE
【ofa_mmspeech_asr_aishell1_large_zh】语音识别结果差别大

### ISSUE THREAD

**Issue by lhf860** [modelscope/modelscope#680]
### 使用模型：OFA-MMSpeech语音识别-中文-aishell1-large
问题描述：
1、在模型“ofa_mmspeech_asr_aishell1_large_zh”上使用自己的wav上进行中文识别，识别的结果差别很大
2、在模型“damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404”上使用上述wav文件进行语音识别，能够正确识别

## 使用代码：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

pretrained_model = "damo/ofa_mmspeech_asr_aishell1_large_zh"
pipe = pipeline(Tasks.auto_speech_recognition, model=pretrained_model, model_revision='v1.0.0')
result = pipe({"wav": "my_path.wav"})
print(result) 

音频时长：20s，mono=True, 采样率：16000

请问怎么解决

**Comment by slin000111** [comment]
用了https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_hotword.wav测试，两个模型pipeline均可识别，识别结果相同。你换不同时长的音频尝试，或者根据你的使用场景对比模型库里的其他语音识别模型。
