### ISSUE TITLE
在下载模型的时候出现问题

### ISSUE THREAD

**Issue by ThePoppingCordaDuck** [modelscope/modelscope#682]
OS: windows 操作系统

Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx

Command：git clone https://www.modelscope.cn/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx.git

问题描述：在使用 git clone https://www.modelscope.cn/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx.git 的时候让我登录 gitlab 账号 经切换电脑测试发现并不是所有都要登录才可以下载，有的可以直接下载。我登录 gitlab 账号也是没有下载成功
<img width="699" alt="微信图片_20231219151753" src="https://github.com/modelscope/modelscope/assets/131648363/1d32df92-8458-4582-ae38-3fa2089760d0">

Error log：Cloning into 'speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-online-onnx'...
warning: missing OAuth configuration for [www.modelscope.cn](http://www.modelscope.cn/) - see https://aka.ms/gcm/gitlab for more information

Model hub related: @liuyhwangyh

**Comment by liuyhwangyh** [comment]
您可以通过点"模型下载"
![image](https://github.com/modelscope/modelscope/assets/3191272/e5138695-f635-44bb-9bde-179d9f476156)
check 查看我的git token，复制命令来clone，另外确保用的是git token，而不是modelscope api token
