### ISSUE TITLE
下载模型Mixtral-8x7B-v0.1之后无法从本地读取

### ISSUE THREAD

**Issue by Tendo33** [modelscope/modelscope#684]
@liuyhwangyh

1. 首先我从model_hub 上下载了模型，我更改了保存模型的cashe地址
```
import os
os.environ['MODELSCOPE_CACHE'] = '/share_data/base_llms'
#模型下载
from modelscope import snapshot_download
model_dir = snapshot_download('AI-ModelScope/Mixtral-8x7B-v0.1')
```
2. 下载完之后尝试推理
```
from modelscope import AutoModelForCausalLM, AutoTokenizer

model_id = "/workspace/share_data/base_llms/AI-ModelScope/Mixtral-8x7B-v0.1"
model_name_or_path = "/workspace/share_data/base_llms/AI-ModelScope/Mixtral-8x7B-v0.1"

tokenizer = AutoTokenizer.from_pretrained(model_id, model_name_or_path=model_name_or_path)

model = AutoModelForCausalLM.from_pretrained(model_id, model_name_or_path=model_name_or_path, device_map='auto')

text = "Hello my name is"
inputs = tokenizer(text, return_tensors="pt")

outputs = model.generate(**inputs, max_new_tokens=20)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
```
3. 错误为：

为什么不能读取本地的模型，一直尝试去网站上找
```
HTTPError: 404 Client Error: Not Found for url: https://www.modelscope.cn/api/v1/models//workspace/share_data/base_llms/AI-ModelScope/Mixtral-8x7B-v0.1/revisions?EndTime=1703040689
```

**Comment by slin000111** [comment]
环境变量中/share_data/base_llms与model_id中/workspace/share_data/base_llms不一致，用model_id即可，不需要model_name_or_path。此外，modelscope升级到最新版本。

**Comment by Tendo33** [comment]
> 环境变量中/share_data/base_llms与model_id中/workspace/share_data/base_llms不一致，用model_id即可，不需要model_name_or_path。此外，modelscope升级到最新版本。

路径区别原因是下载在Docker外，运行是在Docker容器内部，所以多了一个workspace，这个应该不影响
已经升级到`Successfully installed datasets-2.15.0 modelscope-1.10.0 pyarrow-hotfix-0.6` 但是还是同样的错误，还是会去
hub上找：`HTTPError: 404 Client Error: Not Found for url: https://www.modelscope.cn/api/v1/models//workspace/share_data/base_llms/AI-ModelScope/Mixtral-8x7B-v0.1/revisions?EndTime=1703050916`

**Comment by slin000111** [comment]
你换其他模型测试一下，是否有这种已经下载了模型文件还需要重新下载的情况。这边在镜像registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda11.8.0-py310-torch2.1.0-tf2.14.0-1.10.0
中测试，没有重复下载情况。

**Comment by Pashisfisuta** [comment]
问题解决了吗，我用modelscope微调了一个基于chatglm2的模型并保存在本地，但是通过autotokenizer读取不成功，要么就是报错，错误代码是ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.要么是一直在读取中
`
model_name = "chatglm2-6b-cjdc"   -- 本地模型的路径
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=False)
model = AutoModel.from_pretrained(model_name, trust_remote_code=False).half().cuda()
`
我这种读取的方式有问题吗

**Comment by wenmengzhou** [comment]
最新版本已经修复
