### ISSUE TITLE
cv_HRN_head-reconstruction,我在使用社区提供的示例时候，并没有跑出社区的效果。

### ISSUE THREAD

**Issue by zgp123-wq** [modelscope/modelscope#693]
import os
import cv2
from modelscope.models.cv.face_reconstruction.utils import write_obj
from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

def save_results(result, save_root):
    os.makedirs(save_root, exist_ok=True)

    # export obj and texture
    mesh = result[OutputKeys.OUTPUT]['mesh']
    texture_map = result[OutputKeys.OUTPUT_IMG]
    mesh['texture_map'] = texture_map
    write_obj(os.path.join(save_root, 'head_recon_result.obj'), mesh)

    print(f'Output written to {os.path.abspath(save_root)}')

head_reconstruction = pipeline(Tasks.head_reconstruction, model='damo/cv_HRN_head-reconstruction', model_revision='v0.1')
result = head_reconstruction('https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/face_reconstruction.jpg')

上面的代码是mindescope社区给的示例，我尝试运行了代码，发现与社区的展示的效果不一致，此外我尝试更换了几张图片，发现模型生成的结果基本一致，请问是我哪里出问题了吗？@wenmengzhou @tastelikefeet @liuyhwangyh @Firmament-cyou @wenmengzho

**Comment by zgp123-wq** [comment]
请问是否可以生成铺平的normals可视化图？

**Comment by zgp123-wq** [comment]
![image](https://github.com/modelscope/modelscope/assets/58291725/7f4045ae-7a6a-48a5-8dcb-92b0c0018c77)
这个是推理产生的mesh文件

**Comment by slin000111** [comment]
head_reconstruction_results文件夹中有.obj、.mtl、.jpg，尝试下可否用其他工具处理。
