### ISSUE TITLE
【BUG】 ModuleNotFoundError: No module named 'fun_text_processing'

### ISSUE THREAD

**Issue by Zth9730** [modelscope/modelscope#697]
when i use itn model, an error in here:
https://github.com/modelscope/modelscope/blob/fb46e18351be42927042bc06b1aef80450b2062c/modelscope/pipelines/audio/inverse_text_processing_pipeline.py#L106
 how can i import the fun_text_processing module ?

**Comment by slin000111** [comment]
Try the following command:
pip install funtextprocessing -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by Zth9730** [comment]
Thank you! It works!
