### ISSUE TITLE
BaSSL视频场景分割GPU问题

### ISSUE THREAD

**Issue by huangyan20** [modelscope/modelscope#705]
* 模型
 cv_resnet50-bert_video-scene-segmentation_movienet
 * 配置文件
 configuration.json
 * 执行
video_scene_seg = pipeline(Tasks.movie_scene_segmentation,model='damo/cv_resnet50-bert_video-scene-segmentation_movienet', device='gpu')
 * 版本
 PyTorch version: 2.1.2+cu118
 * 问题
使用少量GPU显存，split video时很慢需要8分钟，与cpu执行时长差不多
官方介绍使用cpu大约需要8分钟，GPU大约需要1分钟左右
不知道问题出在哪里，有人帮忙解答一下吗，非常感谢

split video
![time](https://github.com/modelscope/modelscope/assets/52433708/209fecc6-35c9-47b6-9f1c-2387b03c228a)

nvidia used
![time2](https://github.com/modelscope/modelscope/assets/52433708/7dc2db8c-b6ea-46e9-a2e5-677557009082)

**Comment by slin000111** [comment]
镜像registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda11.8.0-py310-torch2.1.0-tf2.14.0-1.10.0，推理时长在40s左右，显存占用11.5G。你这里可能是文件下载占用了大部分时间。

**Comment by huangyan20** [comment]
> 镜像registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda11.8.0-py310-torch2.1.0-tf2.14.0-1.10.0，推理时长在40s左右，显存占用11.5G。你这里可能是文件下载占用了大部分时间。

感谢你的回复，看样子并不像在下载文件占用的时间，执行下一个视频也需要这么长时间，这边是自己构建的环境，后续使用官方镜像试下
