### ISSUE TITLE
face-recognition-ood_rts trian 工程代码

### ISSUE THREAD

**Issue by qiu-pinggaizi** [modelscope/modelscope#710]
仓库中有face-recognition-ood_rts的训练工程代码吗，找了一遍没找到呀，大佬指一条明路
 @wenmengzhou@tastelikefeet  @Jintao-Huang @liuyhwangyh

**Comment by slin000111** [comment]
目前还没提供训练示例代码。

**Comment by qiu-pinggaizi** [comment]
ok
