### ISSUE TITLE
读取“AI-ModelScope/Mixtral-8x7B-Instruct-v0.1”报错KeyError: 'mixtral'

### ISSUE THREAD

**Issue by Pashisfisuta** [modelscope/modelscope#716]
按照官方代码读取“AI-ModelScope/Mixtral-8x7B-Instruct-v0.1”报错
![image](https://github.com/modelscope/modelscope/assets/37166140/0cb96019-9a1e-47ca-8e6b-1a10730ad573)

**Comment by Pashisfisuta** [comment]
详细报错信息：
`
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 6
      3 model_id = "AI-ModelScope/Mixtral-8x7B-Instruct-v0.1"
      4 tokenizer = AutoTokenizer.from_pretrained(model_id)
----> 6 model = AutoModelForCausalLM.from_pretrained(model_id, device_map='auto')

File /opt/conda/lib/python3.8/site-packages/modelscope/utils/hf_util.py:111, in get_wrapped_class.<locals>.ClassWrapper.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    108 else:
    109     model_dir = pretrained_model_name_or_path
--> 111 module_obj = module_class.from_pretrained(model_dir, *model_args,
    112                                           **kwargs)
    114 if module_class.__name__.startswith('AutoModel'):
    115     module_obj.model_dir = model_dir

File /opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py:461, in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    458 if kwargs.get("torch_dtype", None) == "auto":
    459     _ = kwargs.pop("torch_dtype")
--> 461 config, kwargs = AutoConfig.from_pretrained(
    462     pretrained_model_name_or_path,
    463     return_unused_kwargs=True,
    464     trust_remote_code=trust_remote_code,
    465     **hub_kwargs,
    466     **kwargs,
    467 )
    469 # if torch_dtype=auto was passed here, ensure to pass it on
    470 if kwargs_orig.get("torch_dtype", None) == "auto":

File /opt/conda/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py:998, in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    996     return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
    997 elif "model_type" in config_dict:
--> 998     config_class = CONFIG_MAPPING[config_dict["model_type"]]
    999     return config_class.from_dict(config_dict, **unused_kwargs)
   1000 else:
   1001     # Fallback: use pattern matching on the string.
   1002     # We go from longer names to shorter names to catch roberta before bert (for instance)

File /opt/conda/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py:710, in _LazyConfigMapping.__getitem__(self, key)
    708     return self._extra_content[key]
    709 if key not in self._mapping:
--> 710     raise KeyError(key)
    711 value = self._mapping[key]
    712 module_name = model_type_to_module_name(key)

KeyError: 'mixtral'
`

**Comment by JiangFeng07** [comment]
The transformers version is out of date, update to the latest version

**Comment by chenbingweb** [comment]
> The transformers version is out of date, update to the latest version

it do not work 😂

**Comment by chenbingweb** [comment]
> 按照官方代码读取“AI-ModelScope/Mixtral-8x7B-Instruct-v0.1”报错 ![image](https://private-user-images.githubusercontent.com/37166140/295484644-0cb96019-9a1e-47ca-8e6b-1a10730ad573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTExOTUsIm5iZiI6MTcxNDQ5MDg5NSwicGF0aCI6Ii8zNzE2NjE0MC8yOTU0ODQ2NDQtMGNiOTYwMTktOWExZS00N2NhLThlNmItMWExMDczMGFkNTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE1MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Yzk0NWYzNzU1MzQyMTcwMGRmOThjNTVlMWJkYTQ2ODM0YjQxMGQ4NzMzNWE3YTg1YzVjNjNhOTQxYWFmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4o3NFexSjYOs4DsCvblYNVZtw8jHEccsLV72N8ljo4k)

解决了吗？
