### ISSUE TITLE
如何使用自定义的损失函数训练模型？

### ISSUE THREAD

**Issue by Ht-zhang-xianyu** [modelscope/modelscope#72]
训练时希望修改下损失函数，但是没有看到相关的文档可以参考。
想请教下是否有相关的小demo 代码可以参考？
以及修改了损失函数后是否还是得使用 build_trainer的接口进行后续的训练？

**Comment by tastelikefeet** [comment]
你好，loss是由模型的forward方法返回的，也就是说由模型负责计算，您可以对模型进行继承或定制，不需要定制trainer

**Comment by yingdachen** [comment]
close as "resolved"
