### ISSUE TITLE
run FaceDetectionPipeline  error

### ISSUE THREAD

**Issue by cqray1990** [modelscope/modelscope#721]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

  File "/modelscope/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: FaceLivenessXcPipeline: FaceDetectionPipeline: DamoFdDetect: MMCV==1.7.2 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

but when i min install mmcv==2.0.0rc4 also raised another error:

ImportError: FaceLivenessXcPipeline: FaceDetectionPipeline: DamoFdDetect: cannot import name 'Config' from 'mmcv' (/.conda/envs/paddle_env/lib/python3.9/site-packages/mmcv/__init__.py)

**Comment by alonewithyou** [comment]
@cqray1990 Hi I'm having the same problem, did you find a solution to this?

**Comment by minushuang** [comment]
same issue,
with `mmcv==1.7.`2, warning `incompatible`.
with `mmcv==2.0.0rc4`,  `cannot import name 'Config' from 'mmcv' `error.

**Comment by mqudsi** [comment]
Can you please reopen this issue? The remarks from @minushuang above remain the case:


> with `mmcv==1.7.`2, warning `incompatible`.
> with `mmcv==2.0.0rc4`, `cannot import name 'Config' from 'mmcv' `error.

The same also happens with `mmcv<2.2.0` and `mmcv==2.2.0`
