### ISSUE TITLE
Names of downloaded files are not match

### ISSUE THREAD

**Issue by LiJiaqi96** [modelscope/modelscope#726]
Hi, thanks for your work of modelscope. I'm trying to download one dataset using "MsDataset.load()" but found that the names of downloaded files are not readable.    

Specifically, my download code is:  
```
dataset = MsDataset.load(
    'Youku-AliceMind',  
    namespace='modelscope',  
    download_mode=DownloadMode.REUSE_DATASET_IF_EXISTS,    # if you need to clean the cache , please use it  
    subset_name="pretrain",  
    split='train',     # caption includes: train, validation, test  
    cache_dir="./youku/",  
    stream_batch_size=1,  
    use_streaming=True)  
```  
After download, I found the file name is like "8c424a33f3ceaf7fcc219d18364b1cd831e56e0d2e218ce418a77d41321375f3", which cannot match any file listed in the csv.  

Is there any transition of the file name during the download process? Thanks a lot for your help!

**Comment by 459737087** [comment]
Hi,Did you solve it

**Comment by wenmengzhou** [comment]
using git clone to download the raw files

**Comment by LiJiaqi96** [comment]
> using git clone to download the raw files

Hi, thanks for your reply. I tried the `git clone`, but only the tables were downloaded. Is it possible to download the raw videos with git clone?  

BTW, the names in tables downloaded from `git clone` are also mismatch with the video file name like "8c424a33f3ceaf7fcc219d18364b1cd831e56e0d2e218ce418a77d41321375f3"
