### ISSUE TITLE
How to use CPU for inference on GPU supported end.

### ISSUE THREAD

**Issue by shiyueGG** [modelscope/modelscope#729]
I installed it on windows  `pip install modelscope`

and it has been activated：`os.environ["CUDA_VISIBLE_DEVICES"] = "-1,"`

run：`res = pipeline(Tasks.image_face_fusion, model=self.ModelFile, device="cpu")`

error：`Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

**Comment by slin000111** [comment]
https://modelscope.cn/models/iic/cv_unet_face_fusion_torch/file/view/master/ms_wrapper.py?status=1  line94~97
