### ISSUE TITLE
funasr-pipeline  error

### ISSUE THREAD

**Issue by piplyman** [modelscope/modelscope#731]
'funasr-pipeline is not in the pipelines registry group voice-activity-detection. Please make sure the correct version of ModelScope library is used.'  请问这个是为什么啊？代码如下：
from modelscope.utils.constant import Tasks
vad_pipeline = pipeline(
    task=Tasks.voice_activity_detection,
    model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    model_revision=None,
    device='cuda'
)

**Comment by LauraGPT** [comment]
Solution 1. 

modelscope-1.10.0, funasr-0.8.7/0.8.8

 In the case, you should download models by default (the pipeline would download the models automatically). If you download the models by `git clone`, you would run with error!

Solution 2. 

modelscope-1.11.1, funasr-1.0.3 (`recommand`)

In the case, you should download the models by `git clone`:
 ```shell
git clone https://www.modelscope.cn/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.git
git clone https://www.modelscope.cn/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch.git
git clone https://www.modelscope.cn/iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch.git
# the mode of `ct-transformer-large` is better, and support `English` and `Chinese`
# git clone https://www.modelscope.cn/iic/punc_ct-transformer_cn-en-common-vocab471067-large.git
```
or pipeline (modify the code in https://github.com/RVC-Boss/GPT-SoVITS/blob/main/tools/damo_asr/cmd-asr.py):
```python
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4",
    vad_model="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch", vad_model_revision="v2.0.4",
    punc_model="damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch", punc_model_revision="v2.0.4",
)
```
and the `audio_in` -> `input` and `[0]`:
```python
text = inference_pipeline(input=audio)[0]["text"]
```

More detail could be found in https://www.modelscope.cn/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary


If it still runs with error, please raise a issue in : https://github.com/alibaba-damo-academy/FunASR
We would fix it.

**Comment by LauraGPT** [comment]
Solution: https://github.com/alibaba-damo-academy/FunASR/discussions/1319
