### ISSUE TITLE
我想请问关系抽取的数据 该以什么样的形式导入？

### ISSUE THREAD

**Issue by lemmon-0428** [modelscope/modelscope#732]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by slin000111** [comment]
方便提供相关模型吗。

**Comment by lemmon-0428** [comment]
就是modelscope 上的siamese uie 我想做关系抽取任务 不知道关系标签数据该以何种格式导入




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "modelscope/modelscope"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月5日(星期一) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [modelscope/modelscope] 我想请问关系抽取的数据 该以什么样的形式导入？ (Issue #732)





 
方便提供相关模型吗。

**Comment by zzzcccxx** [comment]
导入数据倒是可以，但finetune后的模型输出都不对或者都没有输出，请问你遇到了吗

**Comment by slin000111** [comment]
finetune用的模型卡片上的示例代码吗？

**Comment by zzzcccxx** [comment]
> finetune用的模型卡片上的示例代码吗？
@slin000111 
是的，在示例代码稍作修改
```python
import os
import json
from modelscope.trainers import build_trainer
from modelscope.msdatasets import MsDataset
from modelscope.utils.hub import read_config
from modelscope.metainfo import Metrics
from modelscope.utils.constant import DownloadMode


model_id = '/tmp/modelscope/nlp_structbert_siamese-uninlu_chinese-base'

WORK_DIR = '../outputs_test'

train_dataset = MsDataset.load('../data/my_data/test_train.csv', split='train')
eval_dataset = MsDataset.load('../data/my_data/test_dev.csv', split='validation')

max_epochs=1
kwargs = dict(
    model=model_id,
    model_revision='master',
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    max_epochs=max_epochs,
    work_dir=WORK_DIR)


trainer = build_trainer('siamese-uie-trainer', default_args=kwargs)

print('===============================================================')
print('pre-trained model loaded, training started:')
print('===============================================================')

trainer.train()

print('===============================================================')
print('train success.')
print('===============================================================')

for i in range(max_epochs):
    eval_results = trainer.evaluate(f'{WORK_DIR}/epoch_{i+1}.pth')
    print(f'epoch {i} evaluation result:')
    print(eval_results)


print('===============================================================')
print('evaluate success')
print('===============================================================')
```
