### ISSUE TITLE
Allow to use mirror link for faster download

### ISSUE THREAD

**Issue by khursani8** [modelscope/modelscope#74]
I'm currently trying to finetune asr model, when downloading the model the dl speed very slow, I think because of server location, I hope can programmatically change to use different url or let me download manually from google cloud like this issue
https://github.com/tinyvision/DAMO-YOLO/issues/52

![Screenshot from 2023-01-18 14-28-33](https://user-images.githubusercontent.com/5404903/213100810-1a034f24-f9b2-460a-9fc4-0faee412d567.png)

**Comment by yingdachen** [comment]
currently there is no definite plan to host model files in mirroring locations. we may consider it as part of adding multilingual support for ModelScope in future releases.

**Comment by hasan-muzak** [comment]
Hello, this problem still occurs. I'm trying to download a model from Europe, a virtual machine. However, it downloads with 300-400 kbps, which takes several hours to download.
