### ISSUE TITLE
请问如何实现多卡并行推理？

### ISSUE THREAD

**Issue by nnoyuwan** [modelscope/modelscope#76]
初始化pipeline的时候，请问可以指定哪张gpu吗？

**Comment by tastelikefeet** [comment]
Pipeline支持device参数：device str, should be either cpu, cuda, gpu, gpu:X or cuda:X

**Comment by nnoyuwan** [comment]
谢谢

**Comment by babyta** [comment]
实际使用的时候不生效啊 pipeline(Tasks.shop_segmentation, model=model_id,device = 'cuda:3')

**Comment by babyta** [comment]
环境是python 3.8 torhc1.8.0
