### ISSUE TITLE
现在我想用自己的本地数据集微调clip，请问我需要如何在本地构造数据然后加载本地数据集训练啊

### ISSUE THREAD

**Issue by C-rawler** [modelscope/modelscope#775]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by wangxingjun778** [comment]
# 1. Construct the dataset
train.jsonl (each line): {"query_id": "111", "query": "吃饭的猫猫1", "image_id": "222", "image": "/path/to/cat_1.jpg"}

validation.jsonl (each line): {"query_id": "333", "query": "吃饭的猫猫2", "image_id": "444", "image": "/path/to/cat_2.jpg"}

# 2. Load local dataset
from modelscope import MsDataset
ds = MsDataset.load('json', data_files={'train': ['/path/to/train.jsonl'], 'validation': ['/path/to/validation.jsonl']})
ds_train = ds['train'].to_hf_dataset()
ds_valid = ds['validation'].to_hf_dataset()
print(next(iter(ds_train)))

# 3. Transform the dataset with map_func (if needed)
import PIL.Image as Image

def map_func(item):
    item['image_obj'] = Image.open(item['image'])
    return item

ds_train_new = ds_train.map(map_func)
ds_valid_new = ds_valid.map(map_func)
print(next(iter(ds_train_new)))

# 4. Do the tuning clip model

# Refer to for details: https://modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

**Comment by C-rawler** [comment]
> # 1. Construct the dataset
> ```
> train.jsonl (each line): {"query_id": "111", "query": "吃饭的猫猫1", "image_id": "222", "image": "/path/to/cat_1.jpg"}
> validation.jsonl (each line): {"query_id": "333", "query": "吃饭的猫猫2", "image_id": "444", "image": "/path/to/cat_2.jpg"}
> ```
> 
> # 2. Load local dataset
> ```shell
> from modelscope import MsDataset
> ds = MsDataset.load('json', data_files={'train': ['/path/to/train.jsonl'], 'validation': ['/path/to/validation.jsonl']})
> ds_train = ds['train'].to_hf_dataset()
> ds_valid = ds['validation'].to_hf_dataset()
> print(next(iter(ds_train)))
> ```
> 
> # 3. Transform the dataset with map_func (if needed)
> ```shell
> import PIL.Image as Image
> 
> def map_func(item):
>     item['image_obj'] = Image.open(item['image'])
>     return item
> 
> ds_train_new = ds_train.map(map_func)
> ds_valid_new = ds_valid.map(map_func)
> print(next(iter(ds_train_new)))
> ```
> 
> # 4. Do the tuning clip model
> # 5. Refer to
> [本地数据集加载](https://modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

Thank you for your help. How can I load the trained model
