### ISSUE TITLE
请问modelscope的数据集部分可以添加上LLM的预训练，指令微调，奖励模型分类吗 

### ISSUE THREAD

**Issue by lainxx** [modelscope/modelscope#783]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by slin000111** [comment]
文档中数据集，https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E6%94%AF%E6%8C%81%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%92%8C%E6%95%B0%E6%8D%AE%E9%9B%86.md
