### ISSUE TITLE
'gbk' codec can't decode byte 0xa7 in position 4694: illegal multibyte sequence

### ISSUE THREAD

**Issue by littleManty** [modelscope/modelscope#79]
Collecting easyrobust
  Using cached easyrobust-0.2.3.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\PS\AppData\Local\Temp\pip-install-jrhihwnw\easyrobust_f9476defb7d148f480bdaebb21665f91\setup.py", line 5, in <module>
          readme = f.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 4694: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by vtddggg** [comment]
Hi @littleManty 

Sorry for the inconvenience. 
This error is cause by the chinese char in easyrobust. We have fix it in new pypi version of easyrobust. 
Can you run `pip install easyrobust` again to check if it is successfully installed?

If yes, we think you can continue to install modelscope without this error

**Comment by yingdachen** [comment]
close as "resolved"
