### ISSUE TITLE
请问sd_pipeline 支持batch推理吗

### ISSUE THREAD

**Issue by yangyyt** [modelscope/modelscope#792]
**General Question**
需求： 调用说话人识别模型进行大规模数据推理；
使用模型： 
                   task='speaker-diarization',
                   model='damo/speech_campplus_speaker-diarization_common',
                   model_revision='v1.0.0'
示例用法： result = sd_pipeline(input_wav)
请问sd_pipeline()能进行batch推理吗？

Please @ corresponding people according to your problem:

Pipeline related: @Firmament-cyou @wenmengzhou

**Comment by slin000111** [comment]
不支持
