### ISSUE TITLE
如何微调cv_resnest101_general_recognition模型

### ISSUE THREAD

**Issue by AnitaSherry** [modelscope/modelscope#795]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

@wenmengzhou @tastelikefeet 
@tastelikefeet  @Jintao-Huang

**Comment by slin000111** [comment]
目前还没有这个模型微调的示例代码
