### ISSUE TITLE
modelscope error: language type invalid: zhcn

### ISSUE THREAD

**Issue by yeswhos** [modelscope/modelscope#80]
TTS 运行示例代码时报错：
modelscope.utils.audio.tts_exceptions.TtsFrontendLanguageTypeInvalidException: TextToSpeechSambertHifiganPipeline: SambertHifigan: modelscope error: language type invalid: zhcn
运行环境：CENTOS

**Comment by yeswhos** [comment]
PS从官网复制运行的模型加载代码：

```
from scipy.io.wavfile import write
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.outputs import OutputKeys


text = '今天北京天气怎么样？'

sambert_hifigan_tts =pipeline(
    task=Tasks.text_to_speech, model='damo/speech_sambert-hifigan_tts_zhitian_emo_zh-cn_16k')
output = sambert_hifigan_tts(input=text)
pcm = output[OutputKeys.OUTPUT_PCM]
write('output.wav', 16000, pcm)
```

**Comment by Insswer** [comment]
请确认下ttsfrd版本，目前最新版本为0.1.1，理论上0.0.4也是ok的，另外官网示例代码应该早就更新了，现在pipeline输出的是wav，而非pcm了

from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

text = '待合成文本'
model_id = 'damo/speech_sambert-hifigan_tts_zhitian_emo_zh-cn_16k'
sambert_hifigan_tts = pipeline(task=Tasks.text_to_speech, model=model_id)
output = sambert_hifigan_tts(input=text)
wav = output[OutputKeys.OUTPUT_WAV]
with open('output.wav', 'wb') as f:
    f.write(wav)

**Comment by yeswhos** [comment]
正如您所说，我的ttsfrd版本是0.0.2，现在更新为0.1.1，解决问题，感谢您的回复

**Comment by yeswhos** [comment]
> 请确认下ttsfrd版本，目前最新版本为0.1.1，理论上0.0.4也是ok的，另外官网示例代码应该早就更新了，现在pipeline输出的是wav，而非pcm了，看上去你这个sample code还比较老
> 
> ```python
> from modelscope.outputs import OutputKeys
> from modelscope.pipelines import pipeline
> from modelscope.utils.constant import Tasks
> 
> text = '待合成文本'
> model_id = 'damo/speech_sambert-hifigan_tts_zhitian_emo_zh-cn_16k'
> sambert_hifigan_tts = pipeline(task=Tasks.text_to_speech, model=model_id)
> output = sambert_hifigan_tts(input=text)
> wav = output[OutputKeys.OUTPUT_WAV]
> with open('output.wav', 'wb') as f:
>     f.write(wav)
> ```

BTW我是按照文档中说的
pip install "modelscope[audio]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
命令进行安装，然后就不知道为什么安装了低版本的ttsfrd。

**Comment by yeswhos** [comment]
> damo/speech_sambert-hifigan_tts_zhitian

再请教一下换了其他预训练模型，如speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_24k就提示：
FileNotFoundError: TextToSpeechSambertHifiganPipeline: SambertHifigan: [Errno 2] No such file or directory: '/root/.cache/modelscope/hub/speech_tts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_24k/voices.zip'
然后我git下来voices.zip放入对应路径又提示：
zipfile.BadZipFile: TextToSpeechSambertHifiganPipeline: SambertHifigan: File is not a zip file
如何解决？

**Comment by yingdachen** [comment]
使用pipeline调用，会直接下载模型文件。如果要手工下载的话，请确保本地安装了git lfs (version>=2.5.0)
