### ISSUE TITLE
`pip install modelscope[audio]` always installs pytorch 2.2.1 with CUDA 12

### ISSUE THREAD

**Issue by yangb05** [modelscope/modelscope#801]
I need to install modelscope[audio], but the latest CUDA version supported in my server is CUDA 11.7. The `pip install modelscope[audio]` command always installs pytorch 2.2.1 with CUDA 12, which makes CUDA unavailable in my server. How can I change the pytorch version to 1.13.1 and CUDA  version to 11.7 while install modelscope[audio]?

**Comment by slin000111** [comment]
Install torch==1.13.1 before executing the command pip install modelscope[audio].

**Comment by LauraGPT** [comment]
pip install -U funasr modelscope 

docs: https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md
