### ISSUE TITLE
请问如何使用git下载数据集中的数据文件，不是元数据文件

### ISSUE THREAD

**Issue by lainxx** [modelscope/modelscope#804]

**Comment by slin000111** [comment]
使用git只能下载到数据集当中的“元数据文件”，如果该数据集还包含“数据文件”，则git clone方式并不能获取到该部分内容。可以使用Python SDK下载数据集或在页面上下载。

**Comment by wangxingjun778** [comment]
数据集从v1.13.2版本开始，做了一次底层数据存储结构的改造，无论是”元数据文件“，还是”数据文件“，均使用git做统一管理，二者在页面端合并为”数据集文件“tab，使用 git clone即可一次性下载所有文件。但该版本之前所创建的老数据集，仍使用SDK或页面端下载的方式。
