### ISSUE TITLE
KeyError: 'easycv is not in the trainers registry group default. Please make sure the correct version of ModelScope library is used.

### ISSUE THREAD

**Issue by timegoby** [modelscope/modelscope#808]
环境：modelscope==1.13.1

报错代码：
trainer_name = 'easycv'
trainer = build_trainer(trainer_name, kwargs)

**Comment by slin000111** [comment]
可以用哪个模型复现？

**Comment by timegoby** [comment]
https://modelscope.cn/models/iic/cv_cspnet_image-object-detection_yolox/summary
使用他们的推理代码报错
