### ISSUE TITLE
如何安装，项目内使用的 megatron_util

### ISSUE THREAD

**Issue by wylqq312715289** [modelscope/modelscope#81]
AttributeError: module 'megatron.mpu' has no attribute 'ColumnParallelLinearV3'

**Comment by yingdachen** [comment]
you should not have to install megatron_util manually if you follow the intallation guideline for latest version of modelscope:

https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85

but if you want, you can install it by:

pip install megatron_util -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by wylqq312715289** [comment]
Thanks
