### ISSUE TITLE
ValueError: 4 is not a valid DatasetFormations

### ISSUE THREAD

**Issue by monet-joe** [modelscope/modelscope#814]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by wenmengzhou** [comment]
Can you provide more information about this error,  stack track   example code will be helpful

**Comment by monet-joe** [comment]
这是我们的集成版数据集，按如下调用云端版本
ds = MsDataset.load("ccmusic/erhu_playing_tech")报上述错误
而在本地测试没有这个问题，即调用
ds = MsDataset.load("erhu_playing_tech.py")能正常运行
同时使用原生 datasets 的 load_dataset() 无论是本地版还是HF云端版都能正常使用

所以定位代码BUG应该在 ModelScope 平台处

**Comment by monet-joe** [comment]
> 这是我们的集成版数据集，按如下调用云端版本 ds = MsDataset.load("ccmusic/erhu_playing_tech")报上述错误 而在本地测试没有这个问题，即调用 ds = MsDataset.load("erhu_playing_tech.py")能正常运行 同时使用原生 datasets 的 load_dataset() 无论是本地版还是HF云端版都能正常使用
> 
> 所以定位代码BUG应该在 ModelScope 平台处

**Comment by wangxingjun778** [comment]
> > 这是我们的集成版数据集，按如下调用云端版本 ds = MsDataset.load("ccmusic/erhu_playing_tech")报上述错误 而在本地测试没有这个问题，即调用 ds = MsDataset.load("erhu_playing_tech.py")能正常运行 同时使用原生 datasets 的 load_dataset() 无论是本地版还是HF云端版都能正常使用
> > 所以定位代码BUG应该在 ModelScope 平台处

Make sure that your env settings as follows:

modelscope==1.13.3   datasets==2.18.0 

Try again  ~

**Comment by monet-joe** [comment]
fine~ it works
