### ISSUE TITLE
希望能够给modelscope上的仓库放开修改 commit 信息的权限

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#815]
尝试在 git 上对modelscope的仓库修正 commit 记录的 GIT_COMMITTER_NAME 等信息后 git push -f 运行结果如下：
![Snipaste_2024-03-31_19-47-36](https://github.com/modelscope/modelscope/assets/20459298/33af3d1c-2b99-4b0d-bfb6-a875b3a1d02f)
![Snipaste_2024-03-31_19-48-29](https://github.com/modelscope/modelscope/assets/20459298/f7c950d9-dbe6-465c-914b-3e57413f363d)
看起来像是权限不足的样子，请问如何才能放开这个权限，让自己的仓库能修正过去有误的 commit 信息并签入到云端

**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by monet-joe** [comment]
> 尝试在 git 上对modelscope的仓库修正 commit 记录的 GIT_COMMITTER_NAME 等信息后 git push -f 运行结果如下： ![Snipaste_2024-03-31_19-47-36](https://private-user-images.githubusercontent.com/20459298/318263569-33af3d1c-2b99-4b0d-bfb6-a875b3a1d02f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODYzMTQsIm5iZiI6MTcxMTg4NjAxNCwicGF0aCI6Ii8yMDQ1OTI5OC8zMTgyNjM1NjktMzNhZjNkMWMtMmI5OS00YjBkLWJmYjYtYTg3NWIzYTFkMDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDExNTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYjIwNWE0ZTZjOWQ5N2NlMjM0ZDQ0NTkzNzgzMmE1ZTdhMTYzMTc5NjEwZjE1ZjdiMTA3MmZiZTI5ZmQ4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.klRCjKT_cv2xOUVBiKzss2ALFzgFoETmXDuzRyuDvFw) ![Snipaste_2024-03-31_19-48-29](https://private-user-images.githubusercontent.com/20459298/318263586-f7c950d9-dbe6-465c-914b-3e57413f363d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODYzMTQsIm5iZiI6MTcxMTg4NjAxNCwicGF0aCI6Ii8yMDQ1OTI5OC8zMTgyNjM1ODYtZjdjOTUwZDktZGJlNi00NjVjLTkxNGItM2U1NzQxM2YzNjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDExNTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOGQwZGRjMzA4MjNmMTA2ODIwYTg4M2ViN2U2MjEyYTVmZDY5MTE0N2I0OTdkYmE2NzNiYmNmODRlNGQ3OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pmv2uDsRjHWWOyZI4RoW5m5hA8CyVmkto2BTPpdSJN4) 看起来像是权限不足的样子，请问如何才能放开这个权限，让自己的仓库能修正过去有误的 commit 信息并签入到云端
> 
> **Describe the feature** Features description
> 
> **Motivation** A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].
> 
> **Related resources** If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
> 
> **Additional context** Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

看起来在 modelscope 平台上没有修改受保护分支的选项，只有跳到这个仓库真正的 gitlab 大后方才可能有对其分支解除保护，但是怎样才能找到并控制 modelscope 上的 repo 对应到 gitlab 的那个仓库，感觉每个 modelscope 账号背后都对应着一个 gitlab 账号，但是这个账号看起来对 modelscope 用户是不可知的

**Comment by monet-joe** [comment]
How to remove the stale label? Nobody replied me and no action was conducted after I created this issue. What's the problem?
