### ISSUE TITLE
什么时候modelscope上的仓库支持修改仓库英文名

### ISSUE THREAD

**Issue by monet-joe** [modelscope/modelscope#819]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].
有了一堆star后发现仓库名起得不够严谨想修改没法改了，删除重建那么多star又可惜，原生HF支持修改仓库名，MS啥时候也支持

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by wenmengzhou** [comment]
这个需求在规划中，预计本月开发支持
