### ISSUE TITLE
如果一个模型仓库里面只改了一个小文件，是不是整个仓库都重新下载？

### ISSUE THREAD

**Issue by kratorado** [modelscope/modelscope#822]
通义千问1.5 14B模型几天前更新了 tokenizer.json 文件，今天我跑运行的时候，所有权重文件都一起下载了一遍

这个是feature还是bug？有没有选项可以控制这个行为呢？

谢谢！

**Comment by kratorado** [comment]
补充，通义千问1.5的所有模型仓库目前似乎都是master的，没有版本号revision，无法通过revision控制

**Comment by wenmengzhou** [comment]
目前只会增量更新有更新的文件， 如果所有文件都下载是非预期行为，可以把tokenizer.json删除后再执行下，看下是否能复现。


版本问题是由于模型官方提供者没有打版本导致，我们沟通下

**Comment by kratorado** [comment]
> 目前只会增量更新有更新的文件， 如果所有文件都下载是非预期行为，可以把tokenizer.json删除后再执行下，看下是否能复现。
> 
> 版本问题是由于模型官方提供者没有打版本导致，我们沟通下

对比试验过，应该是我本地文件的问题。
另：我有时候会在一台机器上下载好模型，然后传到另一台机器上做微调和推理，有的时候目标机上也是无法识别，会去执行新的下载任务的（已经排除了Qwen1.5和Qwen1___5的这个问题）。
