### ISSUE TITLE
跑 yolox_hand的时候出现以下错误ValueError: unknown url type: 'pai_easycv-0.11.6-py3-none-any.whl.metadata'

### ISSUE THREAD

**Issue by ChaocunChen** [modelscope/modelscope#823]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
ValueError: unknown url type: 'pai_easycv-0.11.6-py3-none-any.whl.metadata'
**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by ChaocunChen** [comment]
按照以下教程跑出现的问题https://www.modelscope.cn/models/iic/cv_yolox-pai_hand-detection/summary

**Comment by liuyhwangyh** [comment]
> 按照以下教程跑出现的问题https://www.modelscope.cn/models/iic/cv_yolox-pai_hand-detection/summary

请问您是自己搭环境还是用的官方镜像？

**Comment by ChaocunChen** [comment]
> > 按照以下教程跑出现的问题https://www.modelscope.cn/models/iic/cv_yolox-pai_hand-detection/summary
> 
> 请问您是自己搭环境还是用的官方镜像？

自己搭建的环境

**Comment by Lizhuoling** [comment]
The same question. It is still unsolved.

**Comment by davideuler** [comment]
Related problems:

https://developer.aliyun.com/ask/546681

https://developer.aliyun.com/ask/573118
