### ISSUE TITLE
官方文档环境安装能优化下吗？

### ISSUE THREAD

**Issue by Black-Gold** [modelscope/modelscope#825]
**优化官方文档**
在[环境安装](https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85)这个页面，当想使用镜像直接运行使用，文档就给了镜像地址。那么具体怎么用？直接docker run吗？文档能不能写清楚啊！参考下阿里云产品官方文档多好，再看看你们写的。真的就是半成品！

**Comment by wenmengzhou** [comment]
你好，直接docker run 拉起进行在里面运行代码就可以。 开源社区的文档更多的面向开发者，一些最基础的信息如果我们没有描述清楚可以借助搜索引擎查询即可

示例命令
```shell
docker run --gpus='"device=0"' registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda11.8.0-py310-torch2.1.0-tf2.14.0-1.10.0 bash
```
