### ISSUE TITLE
创建notebook失败，信息：当前用户已被列入黑名单 

### ISSUE THREAD

**Issue by klzhong69** [modelscope/modelscope#827]
notebook什么原因被列入黑名单。

**Comment by wenmengzhou** [comment]
请提供一下账号名称

**Comment by ysm2000** [comment]
我的也是，刚用 cpu 跑个模型还没跑完，直接黑名单了

**Comment by wenmengzhou** [comment]
可以在 该[文档](https://alidocs.dingtalk.com/notable/share/form/v01XNkOMMLovzv8OY74_EfWRnBm_V18ePoZ)中登记 ，魔搭同学会定期处理

**Comment by schild** [comment]
登记了还没有处理，这个定期需要多久啊

**Comment by Thompson-Chen** [comment]
同问登记后最快什么时候能处理，这边在正常跑实验，然后跑到一半都就显示拉黑了。谢谢
