### ISSUE TITLE
Image Person Reidentification Model Evaluation

### ISSUE THREAD

**Issue by erictan23** [modelscope/modelscope#832]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Model related: @wenmengzhou @tastelikefeet 

Hello! Thank you for the hardworking in creating such a great repository for AI and deep learning works.
I have some questions regarding how to evaluate the model for Image Person Reidentification. From the repository, you provided some mAP and Rank-1 metrics for your pretrained model, are there available codes or instructions on how we can evaluate the model? Do advise me if I want to re-evaluate the model using Market-1501 or other REID Datasets.

**Comment by wenmengzhou** [comment]
do you mean this model  https://modelscope.cn/models/iic/cv_passvitb_image-reid-person_market/summary?

you can use the pipeline  to extract feature from images from Market-1501 or other REID Dataset, and then use evaluation metrics from scikit-learn or any other opensource repos to get the eval result

**Comment by erictan23** [comment]
Ahhh I see, thank you for the hard work and reply. I will test it out on my end :)
