### ISSUE TITLE
modelscope audio 安装错误

### ISSUE THREAD

**Issue by OKC13** [modelscope/modelscope#835]
PyYAML-1.2.2-py3-none-any.whl (16 kB)
Collecting librosa==0.10.1
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/e2/a2/4f639c1168d7aada749a896afb4892a831e2041bebdcf636aebfe9e86556/librosa-0.10.1-py3-none-any.whl (253 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.7/253.7 kB 2.3 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of modelscope[audio] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement MinDAEC (from modelscope[audio]) (from versions: none)
ERROR: No matching distribution found for MinDAEC

**Comment by wenmengzhou** [comment]
try this package in python3 linux env

   https://modelscope.oss-cn-beijing.aliyuncs.com/releases/dependencies/MinDAEC-0.0.2-py3-none-any.whl

**Comment by thewh1teagle** [comment]
@wenmengzhou 
Does it available for WIndows?

**Comment by lin-jj-engine** [comment]
> try this package in python3 linux env
> 
> https://modelscope.oss-cn-beijing.aliyuncs.com/releases/dependencies/MinDAEC-0.0.2-py3-none-any.whl

best!!!!
