### ISSUE TITLE
Qwen1.5自我认知微调 官方教程运行报错ValueError: malformed node 

### ISSUE THREAD

**Issue by alexhmyang** [modelscope/modelscope#838]
运行报错
[Qwen1.5自我认知微调 官方教程 ](https://modelscope.cn/docs/Qwen1.5%E5%85%A8%E6%B5%81%E7%A8%8B%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)

ValueError: malformed node or string

![image.png](https://ucc.alicdn.com/pic/developer-ecology/p5al3zuywsdkm_8f6da23790b848289cc6131644653185.png)

![image.png](https://ucc.alicdn.com/pic/developer-ecology/p5al3zuywsdkm_a4d7097b57db4476854bfd203708b676.png)

感觉是json数据格式的问题

**Comment by hjh0119** [comment]
拉[swift](https://github.com/modelscope/swift)的最新代码更新环境

**Comment by alexhmyang** [comment]
gpu环境太不稳定了，动不动就掉卡了
