### ISSUE TITLE
离线部署问题

### ISSUE THREAD

**Issue by 20246688** [modelscope/modelscope#839]
from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

text = '待合成文本'
model_id = 'damo/speech_sambert-hifigan_tts_zh-cn_16k'
sambert_hifigan_tts = pipeline(task=Tasks.text_to_speech, model=model_id)
output = sambert_hifigan_tts(input=text, voice='zhitian_emo')
wav = output[OutputKeys.OUTPUT_WAV]
with open('output.wav', 'wb') as f:
    f.write(wav)
请问如何离线部署，我已经下载了模型文件，请问如何断网也可以运行

**Comment by wenmengzhou** [comment]
model_id换成本地模型路径即可
