### ISSUE TITLE
关于使用ModelScope离线启动已下载过的模型时遇到的问题

### ISSUE THREAD

**Issue by shaodj** [modelscope/modelscope#840]
在使用ModelScope在联网状态下下载好Qwen1.5_72B_chat模型后，运行启动模型正常。之后尝试断网启动该模型，遇到报错，大体意思是需要联网核对模型的MD5值，即验证模型完整性，因无法联网验证，导致模型启动失败。
[![Xnip2024-04-23_21-46-05](https://github.com/modelscope/modelscope/assets/37572734/5c762afe-ec1c-44fd-a2a2-f2cdb14867cd)](url)检查cache文件

![Xnip2024-04-23_21-46-25](https://github.com/modelscope/modelscope/assets/37572734/fb06f5da-b50f-49df-b6b4-ed41f10bb3c6)提示报错信息-无法联网

![Xnip2024-04-23_21-48-03](https://github.com/modelscope/modelscope/assets/37572734/686de4df-a6e6-449a-b21e-08399da55a83)
此时cache文件存在，且已下载完完整Qwen1.5-72B-chat模型。

请问这种情况想离线启动模型该如何操作？

**Comment by wenmengzhou** [comment]
model_id直接换成本地cache目录

**Comment by shaodj** [comment]
> model_id直接换成本地cache目录

能详细说说在哪里设置吗？刚接触不是很熟悉项目，谢谢赐教
