### ISSUE TITLE
缓存目录使用混乱，MODELSCOPE_CACHE环境变量在不同位置的作用不一致

### ISSUE THREAD

**Issue by wangzhe258369** [modelscope/modelscope#845]
**Describe the feature**

（已经`pip install -U modelscope`更新到最新版，目前版本号是：`modelscope==1.14.0`）

modelscope项目里目前默认的缓存目录或者说主目录是：`~/.cache/modelscope`，但是当通过设置环境变量，在这个非默认目录下加载或者下载模型时，就会遇到和默认目录不一致的问题。

比如希望把目标目录改成：`/data0/modelscope`，希望通过pipeline加载的模型`damo/nlp_raner_named-entity-recognition_chinese-base-ecom`，以及当前在任何目录下都没有这份模型文件。

在代码中加载模型的语句如下：

```
import modelscope
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

model_id = "damo/nlp_raner_named-entity-recognition_chinese-base-ecom"
pipe = pipeline(Tasks.named_entity_recognition, model_id)
```

* 如果不设置任何变量（默认行为），会创建索引文件`~/.cache/modelscope/ast_indexer`，下载时的临时目录`~/.cache/modelscope/hub/temp`，最终模型文件被下载到`~/.cache/modelscope/hub/damo/nlp_raner_named-entity-recognition_chinese-base-ecom`
* 设置环境变量`MS_CACHE_HOME=/data0/modelscope`，这个环境变量完全不起作用，仍然在`~/.cache/modelscope`目录下载文件
* 设置环境变量`MODELSCOPE_CACHE=/data0/modelscope`，则`import modelscope`时会创建索引文件`/data0/modelscope/ast_indexer`，同时下载模型文件的临时目录会使用`/data0/modelscope/temp`，最终模型文件被下载到`/data0/modelscope/damo/nlp_raner_named-entity-recognition_chinese-base-ecom`。这时`/data0/modelscope/hub`目录永远不会被使用。
* 设置环境变量`MODELSCOPE_CACHE=~/.cache/modelscope`，则`import modelscope`时会创建索引文件`~/.cache/modelscope/ast_indexer`，同时下载模型文件的临时目录会使用`~/.cache/modelscope/temp`，最终模型文件被下载到`~/.cache/modelscope/damo/nlp_raner_named-entity-recognition_chinese-base-ecom`。这时`~/.cache/modelscope/hub`目录永远不会被使用。

**Motivation**
统一环境变量`MS_CACHE_HOME`和`MODELSCOPE_CACHE`的作用。当把缓存目录设置到非默认位置时，规范下载行为在`hub`子目录进行。

**Comment by yingdachen** [comment]
感谢整理，我们看一下
