### ISSUE TITLE
🔥🔥🔥如何实现语音识别生成字幕文件

### ISSUE THREAD

**Issue by yfq512** [modelscope/modelscope#85]
看了下语音识别的相关项目，几乎都是输入是一个音频，输出是识别出的文字内容。
请问：是否有输入是音频，输出是字幕文件的例子。或者输出是文字和该段文字在音频中的时间戳呢？

**Comment by yfq512** [comment]
我的项目是为一段视频生成字幕

**Comment by langgz** [comment]
> 我的项目是为一段视频生成字幕

您好，我们已经开源了长音频识别模型，内部集成了vad，asr，标点与时间戳功能，可以用来做视频字幕，详见：https://www.modelscope.cn/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary

**Comment by junjiemao** [comment]
you can try  [autocut](https://github.com/mli/autocut)
