### ISSUE TITLE
face_detection和face_2d_keypoints不支持cv2读取图片后的numpy.ndarray格式

### ISSUE THREAD

**Issue by yangbo1989816** [modelscope/modelscope#850]
face_detection和face_2d_keypoints，目前只支持绝对地址的图片，不支持cv2读取图片后的numpy.ndarray格式。在实际使用场景，用绝对地址的情况比较少

**Comment by wenmengzhou** [comment]
您好，目前的pipeline主要考虑单场景的跑通，您可以考虑继承或直接修改pipeline对应的__call__函数完成你的定制化需求 
 
https://github.com/modelscope/modelscope/blob/master/modelscope/pipelines/cv/face_detection_pipeline.py#L54
