### ISSUE TITLE
Tasks.image_segmentation Error

### ISSUE THREAD

**Issue by xuhzyy** [modelscope/modelscope#854]
python=3.10
pytorch=2.1.2+cu118
modelscope=1.14.0

1. panoptic-segmentation
model_id = "damo/cv_r50_panoptic-segmentation_cocopan"
pipe = pipeline(Tasks.image_segmentation, model=model_id)
Error Info:  'image-panoptic-segmentation-easycv is not in the pipelines registry group image-segmentation. Please make sure the correct version of ModelScope library is used.'

2. semantic-segmentation
model_id = 'damo/cv_segformer-b0_image_semantic-segmentation_coco-stuff164k'
pipe = pipeline(Tasks.image_segmentation, model=model_id)
Error Info:  'easycv-segmentation is not in the pipelines registry group image-segmentation. Please make sure the correct version of ModelScope library is used.'

**Comment by wenmengzhou** [comment]
please install pai-easycv  by executing
```shell
pip install pai-easycv
```
