### ISSUE TITLE
UniASR models don't work with the latest version

### ISSUE THREAD

**Issue by treya-lin** [modelscope/modelscope#856]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

I am using this UniASR models (https://www.modelscope.cn/models/iic/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline/summary). However, I noticed that the methods described here (https://github.com/alibaba-damo-academy/FunASR/discussions/1319) does not work.

Does it mean all the models with "uniasr" in its name will not work in the latest modelscope and funasr? And only the  models with "paraformer" in its name can work in the latest environment?

### To Reproduce

Using the code snippet in https://github.com/alibaba-damo-academy/FunASR/discussions/1319  and replace the name of this uniASR model.

#### Code sample

```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='iic/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline',
    vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
    punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
    # spk_model="iic/speech_campplus_sv_zh-cn_16k-common",
    # spk_model_revision="v2.0.2",
)

res = inference_pipeline(input='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
print(res)
```

### Expected behavior

I expect to know more clearly what models work in the latest version and what models don't, and if it is the case that I need to apply or finetune all the uniasr models in the old version.

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0): 1.0.26
 - ModelScope Version (e.g., 1.11.0):  1.14.0
 - PyTorch Version (e.g., 2.0.0): 1.12.1
 - How you installed funasr (`pip`, source): 
 - Python version:
 - GPU (e.g., V100M32):
 - CUDA/cuDNN version (e.g., cuda11.7): 10.2
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
pip install funasr==0.8.8 modelscope==1.10.0
