### ISSUE TITLE
上传模型的时候，LFS track 的内容无法上传

### ISSUE THREAD

**Issue by noforit** [modelscope/modelscope#858]
**General Question**

我在上传模型的时候，LFS track 的文件无法上传，而其它不通过LFS管理的文件能正常push，请问有遇到类似问题的吗，或者是为什么？
麻烦了
![image](https://github.com/modelscope/modelscope/assets/97608046/7c9cc1a0-e6f8-422f-841e-3905bfdc7e9e)
![image](https://github.com/modelscope/modelscope/assets/97608046/c631f61e-b161-432c-8fdb-e03b3e2bf866)

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Model related: @wenmengzhou @tastelikefeet
Contribute your model: @zzclynn

**Comment by team79** [comment]
麻烦看下你的文件列表

**Comment by noforit** [comment]
> 麻烦看下你的文件列表

![image](https://github.com/modelscope/modelscope/assets/97608046/9e3230cc-50b1-412d-9972-eee3ffd8fd89)
请问是这个吗

**Comment by team79** [comment]
> > 麻烦看下你的文件列表
> 
> ![image](https://private-user-images.githubusercontent.com/97608046/331198650-9e3230cc-50b1-412d-9972-eee3ffd8fd89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDE0NTEsIm5iZiI6MTcxNzE0MTE1MSwicGF0aCI6Ii85NzYwODA0Ni8zMzExOTg2NTAtOWUzMjMwY2MtNTBiMS00MTJkLTk5NzItZWVlM2ZmZDhmZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2Y5OTFkNGQ0N2FkYzM5OTM4NzJjNGNjNjA5YmY2ZGNjYjNlNTJjYmFhNTAyNDViYTQ4ZDg4Y2VlZDc5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2U0XEKHrlQJOZO_KYHtr-jKA9lBGB96NI9OO2gAGf8A) 请问是这个吗

是不是有只有几百B的文件，之前遇到过从别处拷贝过来的模型文件，但其实非常小不是真实文件

**Comment by 100ZZ** [comment]
Uploading LFS objects: 100% (1/1), 1.2 GB | 0 B/s, done.
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 12 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 910.59 MiB | 1.50 MiB/s, done.
Total 11 (delta 3), reused 1 (delta 0), pack-reused 0
remote: [ModelScope]1bf1f09, repo size(1245339282) greater than max repo size(524288000).
To https://www.modelscope.cn/user/F16-GGUF-Models.git
 ! [remote rejected] master -> master (pre-receive hook declined)
 
 我这个也奇怪，一个1.2G的模型文件，也是报错

**Comment by noforit** [comment]
> > > 麻烦看下你的文件列表
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/97608046/331198650-9e3230cc-50b1-412d-9972-eee3ffd8fd89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDE0NTEsIm5iZiI6MTcxNzE0MTE1MSwicGF0aCI6Ii85NzYwODA0Ni8zMzExOTg2NTAtOWUzMjMwY2MtNTBiMS00MTJkLTk5NzItZWVlM2ZmZDhmZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2Y5OTFkNGQ0N2FkYzM5OTM4NzJjNGNjNjA5YmY2ZGNjYjNlNTJjYmFhNTAyNDViYTQ4ZDg4Y2VlZDc5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2U0XEKHrlQJOZO_KYHtr-jKA9lBGB96NI9OO2gAGf8A) 请问是这个吗
> 
> 是不是有只有几百B的文件，之前遇到过从别处拷贝过来的模型文件，但其实非常小不是真实文件

抱歉，现在已经解决了，我的问题可能是服务器网络问题导致的
