### ISSUE TITLE
BERT-语义对话预测模型预测问题

### ISSUE THREAD

**Issue by Beakboomboom** [modelscope/modelscope#860]
https://modelscope.cn/models/iic/speech_bert_dialogue-detetction_speaker-diarization_chinese/summary
为什么模型运行多次，结果不一致？

代码：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
dialogue_detection = pipeline(
    task=Tasks.speaker_diarization_dialogue_detection,
    model='damo/speech_bert_dialogue-detetction_speaker-diarization_chinese'
)
result = dialogue_detection(["没有找到黄金，查清了没有","秦风同学，你为什么要报考刑警学院"])
print(result)

运行第一次的结果：
[{'scores': [0.5162686705589294, 0.48373132944107056], 'labels': ['non_dialogue', 'dialogue']}, {'scores': [0.6872994303703308, 0.3127005100250244], 'labels': ['dialogue', 'non_dialogue']}]

运行第二次的结果：
[{'scores': [0.8084492087364197, 0.19155080616474152], 'labels': ['dialogue', 'non_dialogue']}, {'scores': [0.662169873714447, 0.337830126285553], 'labels': ['non_dialogue', 'dialogue']}]

连识别的标签都不一样

**Comment by slin000111** [comment]
用模型卡片上的代码测试，这这么大的偏差呢
