### ISSUE TITLE
有没有零样本训练的技术细节，要怎么在自己的数据集训练

### ISSUE THREAD

**Issue by LIUKAI0815** [modelscope/modelscope#863]
StructBERT零样本分类

**Comment by LIUKAI0815** [comment]
nlp_mt5_dialogue-rewriting_chinese-base
有没有训练细节

**Comment by wenmengzhou** [comment]
您好，该模型当前只提供了推理支持，暂未提供训练支持，您可以参考对应论文： https://arxiv.org/pdf/1910.10683
