### ISSUE TITLE
cpu memory leak

### ISSUE THREAD

**Issue by garychan22** [modelscope/modelscope#867]
After I calling the skin retouch pipeline, CPU memory increase about 100Mb for one time, later callings will keep on increasing the memory, does this relate to CPU memory leak?

**Comment by wenmengzhou** [comment]
can you provide the example code?

**Comment by slin000111** [comment]
It doesn't seem like a memory leak. The usage of CPU memory will increase in the early stage of inference, about the first 8 out of 2000 images, and then remain stable.
model id: damo/cv_unet_skin-retouching
