### ISSUE TITLE
Outdated Warning Message

### ISSUE THREAD

**Issue by enymfc25173** [modelscope/modelscope#869]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://www.modelscope.cn/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://www.modelscope.cn/zhongbing/table-transformer-finetuned.git/'

I can't open the guided url, and I clone the repo by http://zhongbing@modelscope.com/zhongbing/table-transformer-finetuned.git. When I push my model, the password is needed, but git token and password for modelscope get the same failed message as below, but the content of this url is 404.

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by team79** [comment]
you can clone repo like this：
git lfs install
git clone http://oauth2:your_git_token@www.modelscope.cn/<namespace>/<model-name>.git

your_git_token can be found here:
![image](https://github.com/modelscope/modelscope/assets/6183072/40b182e0-00ed-4c51-93b3-2dfecfbf4e4f)
