### ISSUE TITLE
部署在同一台服务器上，使用pipeline部署的scrfd人脸检测速度为什么比使用scrfd源代码检测人脸速度要慢？

### ISSUE THREAD

**Issue by zhangfusheng-163** [modelscope/modelscope#87]
我在第八代的I5nuc上分别使用pipeline部署scrfd和scrfd源代码进行测试同一张人脸，发现前者需要1s多，后者需要500ms，虽然在大头照和模糊照片上，前者的效果要好点，但是由于速度的问题，那只能使用源代码训练一个符合自己需求的模型了，为什么两者的速度会相差那么多？

**Comment by wenmengzhou** [comment]
你好，请贴一下使用pipeline和scrfd源代码分别做测试的代码，我们调查一下

**Comment by zhangfusheng-163** [comment]
pipeline部署的代码如下
import cv2
import os
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.outputs import OutputKeys
face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_resnet_facedetection_scrfd10gkps')
img_path = '/home/xunlong/lib/image'
img_list=os.listdir(img_path)
for img_name in img_list:
     print('the img name is ====={}'.format(img_name))
     img=cv2.imread(os.path.join(img_path,img_name))
     s=time.time()
     result = face_detection(img)
     print('detect face use time is {}'.format(time.time()-s))

scrfd源码部署，使用的是onnx模型，使用的代码是这个链接https://github.com/hpc203/scrfd-opencv/blob/main/main.py

都是scrfd10gkps模型

**Comment by wenmengzhou** [comment]
scrfd源码用的是10g的onnx模型，modelscope的是34g的torch模型导致了差异， modelscope 的model_id有问题
