### ISSUE TITLE
下载Tongyi-DataEngine/SA1B-Dense-Caption数据集，执行网页上命令from modelscope.msdatasets import MsDataset ds =  MsDataset.load('Tongyi-DataEngine/SA1B-Dense-Caption', subset_name='default', split='train')，modelscope版本：1.14.0，提示错误：TypeError: Value.__init__() missing 1 required positional argument: 'dtype'

### ISSUE THREAD

**Issue by XinPeiHou** [modelscope/modelscope#871]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by wangxingjun778** [comment]
暂未复现，可否帮忙补充一下如下信息：

1. datasets依赖的版本: pip show datasets
2. 平台： win / mac / linux ？
3. 错误出现的时机，是执行load()函数后立即报错，还是下载一段时间后报错？

**Comment by XinPeiHou** [comment]
> 暂未复现，可否帮忙补充一下如下信息：
> 
> 1. datasets依赖的版本: pip show datasets
> 2. 平台： win / mac / linux ？
> 3. 错误出现的时机，是执行load()函数后立即报错，还是下载一段时间后报错？

执行立马报错
![datasets_version](https://github.com/modelscope/modelscope/assets/31240098/94d18d82-553b-4552-a9bd-5bfeaec275d1)
[pip_list.txt](https://github.com/user-attachments/files/15527681/pip_list.txt)

**Comment by wangxingjun778** [comment]
看报错是因为dtype参数的问题，load()函数中不支持传入dtype参数。

**Comment by XinPeiHou** [comment]
> 看报错是因为dtype参数的问题，load()函数中不支持传入dtype参数。

我删掉之后，还是报相同错误

**Comment by XinPeiHou** [comment]
刚才我把文件夹下缓存删掉，重新执行，可以下载了，可以关闭这个issue了
