### ISSUE TITLE
ModelScope使用的，编码助手智能体

### ISSUE THREAD

**Issue by yulei1224** [modelscope/modelscope#872]
你好，能不能针对ModelScope的使用，出一个类似通义灵码的编码助手，

现在相关问题、需求，通义灵码给出的，总是基于Hugging Face的Transformers库的相关代码，
用这个代码，套ModelScope里的模型的使用，总是不行。

或者，能不能把你们ModelScope的文档，给智能体，先做一个智能体，给大家做编码助手用，

很多人都会用了，有助于ModelScope用户的增多。

**Comment by wenmengzhou** [comment]
你好，我们正在基于智能体制作答疑机器人，方便用户使用ModelScope使用，stay tuned
