### ISSUE TITLE
Config file should not be None if model is not from pretrained!

### ISSUE THREAD

**Issue by zhaoyuchen1128** [modelscope/modelscope#874]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
我的模型就是from petrained，也报错，代码如下：
kwargs = dict(
        model=Model.from_pretrained("d:/微调现成模型/Llama3-8B-Chinese-Chat"),
        train_dataset=ds,
cfg_modify_fn=cfg_modify_fn
       )
trainer = build_trainer(default_args=kwargs)
trainer.train()

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by wenmengzhou** [comment]
```python
from modelscope import AutoModel

AutoModel.from_pretrainedI(xxx)
```

或者参考modelscope/swift 下的微调推理教程: https://github.com/modelscope/swift
