### ISSUE TITLE
内网微调，检查基础模型文件及版本带来的调用超时过长

### ISSUE THREAD

**Issue by hzm-2018** [modelscope/modelscope#877]
您好！
我正在使用model scope，基于一些基础模型进行微调。
在内网环境，没有申请外网访问的情况下，检查基础模型是否完整以及版本时会等待60分钟超时。

跟踪代码发现，在trainers包下的 trainer.py 里 EpochBasedTrainer 基类的初始化阶段就会远程调用检查模型是否完整和版本。
是否可以添加参数对模型是否检查进行控制？

具体代码行：https://github.com/modelscope/modelscope/blob/894bc90d96f81ed8ed3d5e632017829b45aab034/modelscope/trainers/trainer.py#L145
https://github.com/modelscope/modelscope/blob/894bc90d96f81ed8ed3d5e632017829b45aab034/modelscope/trainers/base.py#L55
https://github.com/modelscope/modelscope/blob/894bc90d96f81ed8ed3d5e632017829b45aab034/modelscope/hub/api.py#L90
https://github.com/modelscope/modelscope/blob/894bc90d96f81ed8ed3d5e632017829b45aab034/modelscope/hub/constants.py#L19
@tastelikefeet  @Jintao-Huang

**Comment by slin000111** [comment]
尝试将模型文件拷贝到非默认缓存路径下，然后model传本地路径。

**Comment by hzm-2018** [comment]
@slin000111 我们没有把下载的基础模型放在cache里，是放在 /opt/base_model/dome/XXX 下，调试过程中发现还是会远程调用检查模型文件的sha125，主要是在 [modelscope/modelscope/trainers/base.py](https://github.com/modelscope/modelscope/blob/894bc90d96f81ed8ed3d5e632017829b45aab034/modelscope/trainers/base.py#L55)

**Comment by slin000111** [comment]
环境中modelscope版本是？

**Comment by hzm-2018** [comment]
现在使用的版本：modelscope-1.6.1，我们使用 modelscope-1.13.3 实验过，有相同的问题，从你们的提交来看，没有对其修改过。
