### ISSUE TITLE
'model_id' extra fields not permitted | langchain embedding

### ISSUE THREAD

**Issue by asynchat** [modelscope/modelscope#878]
![ModeScopeErr](https://github.com/modelscope/modelscope/assets/156287065/2f65b64c-7a08-4285-86e9-df5135080cb6)

langchain-community = "^0.2.4"

**Comment by slin000111** [comment]
netease-youdao/bce-embedding-base_v1，参考 https://github.com/netease-youdao/BCEmbedding

**Comment by asynchat** [comment]
> netease-youdao/bce-embedding-base_v1，参考 https://github.com/netease-youdao/BCEmbedding

不是BCEmbedding的问题，是ModelScopeEmbeddings这个类在使用时会提示找不到 model_id 这个属性，可能是不能被IDE感知到还是怎样

**Comment by slin000111** [comment]
从这个demo来看，是支持的。https://github.com/modelscope/modelscope/blob/master/examples/pytorch/application/qwen_doc_search_QA_based_on_langchain.ipynb

**Comment by asynchat** [comment]
> 从这个demo来看，是支持的。https://github.com/modelscope/modelscope/blob/master/examples/pytorch/application/qwen_doc_search_QA_based_on_langchain.ipynb

功能是否OK我还测试，估计功能是OK的，就是这个红色提示难受。。
