### ISSUE TITLE
TypeError: object of type 'IterableDataset' has no len()

### ISSUE THREAD

**Issue by David-Lee-1990** [modelscope/modelscope#88]
你好，在使用GPT-3模型做二次训练的时候，用stream的方式load数据，比如 
`dataset_dict = load_dataset('./local_data/', streaming=True)`
或者 
`dataset_dict = MsDataset.load('DuReader_robust-QG', use_streaming=True)`

在训练阶段，会报错：`AttributeError: 'IterableDataset' object has no attribute 'reset_format'`，请问怎么解决呢

**Comment by wangxingjun778** [comment]
您好，目前streaming方式还不支持train的过程，且不推荐使用此方式来做训练。streaming load每执行一次iter都会从modelscope hub端加载一次数据，效率较低，一般用于数据探查，创建mock training流程等。

如果需要进行二次训练，可直接使用如下方式：
train_dataset = MsDataset.load('DuReader_robust-QG', split='train').remap_columns({'text1': 'src_txt'})
eval_dataset = MsDataset.load('DuReader_robust-QG', split='evaluation').remap_columns({'text1': 'src_txt'})
（remap_columns()的使用具体取决于数据集字段和模型要求字段的实际映射关系）

kwargs = dict(
    model='xxx',
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    max_epochs=max_epochs,
    work_dir=tmp_dir,
    cfg_modify_fn=cfg_modify_fn)

# 构造 trainer 并进行训练
trainer = build_trainer(
    name=Trainers.xxx_trainer, default_args=kwargs)
trainer.train()

另外，如果一定要使用streaming load方式训练的话，非官方的建议，可以尝试如下方式：
1. 加载 train_dataset = MsDataset.load('DuReader_robust-QG', split='train', use_streaming=True)
2. 自定义构建 class MyTrainDataset(torch.utils.data.Dataset)
3. 遍历train_dataset（比如iter前100条数据），将其用来初始化MyTrainDataset类
4. 最后将该类的实例传入kwargs = dict(model='xxx', train_dataset=my_train_dataset, ...)，再走下面的train流程即可

以上，供参考。

**Comment by David-Lee-1990** [comment]
感谢回复，我是要从本地加载数据进行二次训练，训练数据有20G，因此需要使用streaming 的方式。

从本地加载数据，使用streaming的方式的话，也会报错没有reset_format函数的问题，舍弃remap这一步，直接进入到训练流程的话，会报错 object of type 'IterableDataset' has no len() 

请问，是需要什么配置吗？ 

我理解你们在进行预训练的时候，应该也是用的streaming的方式吧？

**Comment by David-Lee-1990** [comment]
最根本的问题就是：如何用model scope上的GPT-3，使用多卡对20G的数据，进行二次训练？ 麻烦指导下～

**Comment by zzclynn** [comment]
https://www.modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary
参考这个文档里面的finetune去做，数据并行我们用的是torch ddp拉起来的
``` shell
torchrun --nproc_per_node $N finetune_dureader.py
```
20g在4卡或者8卡机器上应该可以训起来的，不过注意需要的是单机多卡的情况

**Comment by David-Lee-1990** [comment]
好的，那我就直接load所有的数据进行训练。多谢啦！

**Comment by yingdachen** [comment]
for comprehensive support for streaming load would be implented in future release @wenmengzhou @wangxingjun778 , for now loading all data can unblock the issue. close it for now.
