### ISSUE TITLE
gpu跑paraformer larger onnx模型时候，模型内部出现维度不匹配错误

### ISSUE THREAD

**Issue by zhu-gu-an** [modelscope/modelscope#882]
gpu跑paraformer larger onnx模型时候，模型内部出现维度不匹配错误
模型使用的是：https://modelscope.cn/models/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx/files
没有量化模型；
错误：
<img width="818" alt="错误" src="https://github.com/modelscope/modelscope/assets/76513567/18963762-ace0-4483-bfa9-4c3b21b39884">

请问，这个和什么有关系？如何更好解决或者定位问题？

**Comment by slin000111** [comment]
在modelscope官方镜像还是funasr镜像上运行的呢

**Comment by zhu-gu-an** [comment]
在sherpa-onnx上跑的，单条跑cpu没有问题，但是使用gpu跑偶发出现这个问题，

**Comment by slin000111** [comment]
https://github.com/modelscope/FunASR/issues
