### ISSUE TITLE
TTS流式合成功能的需求

### ISSUE THREAD

**Issue by YuYiandMinsky** [modelscope/modelscope#883]
**Describe the feature**
例如像iic/speech_sambert-hifigan_tts_zh-cn_16k这样的模型，模型本身不错。
https://modelscope.cn/models/iic/speech_sambert-hifigan_tts_zh-cn_16k/summary
但是工作的应用场景有对TTS合成的流式能力的需求，看官方能不能完善这个功能，多谢！

**Motivation**
之前查了相关的历史issue，应该还是有一部分人都有需求。

**Related resources**
流式语音合成实现 - 风影的文章 - 知乎
https://zhuanlan.zhihu.com/p/694971011
可能可以参考下。我本来有打算自己实现，但是被派去做其他工作了，暂时就没有时间了。

**Additional context**
None

**Comment by slin000111** [comment]
这个pr提到了流式合成，https://github.com/modelscope/KAN-TTS/pull/84
