### ISSUE TITLE
question about installing modelscope  from source using setup.py 

### ISSUE THREAD

**Issue by DamonsJ** [modelscope/modelscope#887]
I want to install modescope from source using :

```python
python setup.py bdist_wheel
```

but in the setup.py, there are tow imports  :

from modelscope.utils.ast_utils import generate_ast_template
from modelscope.utils.constant import Fields

which have dependency gast in utils/ast_utils.py
but at this time gast has not been installed 
so I wonder why there is no problem here?

I think this should be  a bug

**Comment by wenmengzhou** [comment]
try to execute 
```shell
PYTHONPATH=. python setup.py bdist_wheel
```
