### ISSUE TITLE
'EXPORTERS', 'face-detection', 'scrfd') not found in ast index file

### ISSUE THREAD

**Issue by zhouzhimin-hz** [modelscope/modelscope#89]
use model-scope to export scrfd onnx model error

**Comment by tuoyuxiang** [comment]
>
Hi, you can just use official tools [scrfd2onnx.py](https://github.com/deepinsight/insightface/blob/master/detection/scrfd/tools/scrfd2onnx.py), but need to comment line 149, and set opset_version to 9.
