### ISSUE TITLE
训练好的模型加载出错

### ISSUE THREAD

**Issue by yangjianchun** [modelscope/modelscope#891]
我是这样调用的：

import torch
from modelscope.utils.constant import Tasks
from modelscope.pipelines import pipeline
from modelscope.preprocessors.image import load_image

pipeline = pipeline(task=Tasks.multi_modal_embedding,
    model='/home/video-test/workspace/ckpts/clip/output_best',device="gpu:1")
input_img = load_image('https://xmgd-recruit.obs.cn-south-1.myhuaweicloud.com/train/cyhva/cuiyonghui9.png') # 支持皮卡丘示例图片路径/本地图片 返回PIL.Image
input_texts = ["杰尼龟", "妙蛙种子", "方法", "皮卡丘"]

# 支持一张图片(PIL.Image)或多张图片(List[PIL.Image])输入，输出归一化特征向量
img_embedding = pipeline.forward({'img': input_img})['img_embedding'] # 2D Tensor, [图片数, 特征维度]

# 支持一条文本(str)或多条文本(List[str])输入，输出归一化特征向量
text_embedding = pipeline.forward({'text': input_texts})['text_embedding'] # 2D Tensor, [文本数, 特征维度]

# 计算图文相似度
with torch.no_grad():
    # 计算内积得到logit，考虑模型temperature
    logits_per_image = (img_embedding / pipeline.model.temperature) @ text_embedding.t()
    # 根据logit计算概率分布
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("图文匹配概率:", probs)

报错信息如下：

2024-06-26 21:01:18,465 - modelscope - INFO - initiate model from [/home/video-test/workspace/ckpts/clip/output_best](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/video-test/workspace/ckpts/clip/output_best)
2024-06-26 21:01:18,466 - modelscope - INFO - initiate model from location /home/video-test/workspace/ckpts/clip/output_best.
2024-06-26 21:01:18,472 - modelscope - WARNING - No preprocessor field found in cfg.
2024-06-26 21:01:18,474 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-06-26 21:01:18,475 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/home/video-test/workspace/ckpts/clip/output_best'}. trying to build by task and model information.
2024-06-26 21:01:18,476 - modelscope - WARNING - Find task: multi-modal-embedding, model type: None. Insufficient information to build preprocessor, skip building preprocessor
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File [/home/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/utils/registry.py:212](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/utils/registry.py#line=211), in build_from_cfg(cfg, registry, group_key, default_args)
    211     else:
--> 212         return obj_cls(**args)
    213 except Exception as e:
    214     # Normal TypeError does not print class name.

File [/home/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/pipelines/multi_modal/multi_modal_embedding_pipeline.py:32](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/pipelines/multi_modal/multi_modal_embedding_pipeline.py#line=31), in MultiModalEmbeddingPipeline.__init__(self, model, preprocessor, **kwargs)
     31 super().__init__(model=model, preprocessor=preprocessor, **kwargs)
---> 32 self.model.eval()
     33 if preprocessor is None:

AttributeError: 'str' object has no attribute 'eval'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[6], line 10
      7 from modelscope.pipelines import pipeline
      8 from modelscope.preprocessors.image import load_image
---> 10 pipeline = pipeline(task=Tasks.multi_modal_embedding,
     11     model='[/home/video-test/workspace/ckpts/clip/output_best](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/video-test/workspace/ckpts/clip/output_best)',device="gpu:1")
     12 input_img = load_image('https://xmgd-recruit.obs.cn-south-1.myhuaweicloud.com/train/cyhva/cuiyonghui9.png') # 支持皮卡丘示例图片路径/本地图片 返回PIL.Image
     13 input_texts = ["杰尼龟", "妙蛙种子", "崔永辉", "皮卡丘"]

File [/home/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/pipelines/builder.py:170](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/pipelines/builder.py#line=169), in pipeline(task, model, preprocessor, config_file, pipeline_name, framework, device, model_revision, ignore_file_pattern, **kwargs)
    167 if preprocessor is not None:
    168     cfg.preprocessor = preprocessor
--> 170 return build_pipeline(cfg, task_name=task)

File [/home/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/pipelines/builder.py:65](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/pipelines/builder.py#line=64), in build_pipeline(cfg, task_name, default_args)
     54 def build_pipeline(cfg: ConfigDict,
     55                    task_name: str = None,
     56                    default_args: dict = None):
     57     """ build pipeline given model config dict.
     58 
     59     Args:
   (...)
     63         default_args (dict, optional): Default initialization arguments.
     64     """
---> 65     return build_from_cfg(
     66         cfg, PIPELINES, group_key=task_name, default_args=default_args)

File [/home/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/utils/registry.py:215](http://192.168.101.232:9527/lab/workspaces/auto-Q/tree/video-test/miniconda3/envs/video/lib/python3.10/site-packages/modelscope/utils/registry.py#line=214), in build_from_cfg(cfg, registry, group_key, default_args)
    212         return obj_cls(**args)
    213 except Exception as e:
    214     # Normal TypeError does not print class name.
--> 215     raise type(e)(f'{obj_cls.__name__}: {e}')

AttributeError: MultiModalEmbeddingPipeline: 'str' object has no attribute 'eval'

训练出来的文件目录如下：

![5551719404764_ pic](https://github.com/modelscope/modelscope/assets/12193393/838f9ca9-8587-4014-887a-7cd28fb46dee)

其中：output_best目录下的configuration.json

{
    "framework": "pytorch",
    "task": "multi-modal-embedding",
    "pipeline": {
        "type": "multi-modal-embedding"
    },
    "pretrained_model": {
        "model_name": "/home/video-test/models/multi-modal_clip-vit-huge-patch14_zh"
    },
    "dataset": {
        "column_map": {
            "img": "image",
            "text": "query"
        }
    },
    "train": {
        "work_dir": "./workspace/ckpts/clip",
        "max_epochs": 10,
        "use_fp16": true,
        "dataloader": {
            "batch_size_per_gpu": 2,
            "workers_per_gpu": 0,
            "shuffle": true,
            "drop_last": true
        },
        "lr_scheduler": {
            "warmup_proportion": 0.1
        },
        "lr_scheduler_hook": {
            "type": "LrSchedulerHook",
            "by_epoch": false
        },
        "optimizer": {
            "type": "AdamW"
        },
        "optimizer_hparams": {
            "lr": 2.5e-05,
            "weight_decay": 0.001,
            "beta1": 0.9,
            "beta2": 0.999,
            "eps": 1e-08
        },
        "optimizer_hook": {
            "cumulative_iters": 1,
            "loss_keys": "loss"
        },
        "loss_cfg": {
            "aggregate": true
        },
        "hooks": [
            {
                "type": "IterTimerHook"
            },
            {
                "type": "ClipClampLogitScaleHook"
            }
        ],
        "logging": {
            "interval": 1,
            "out_dir": "./workspace/ckpts/clip"
        },
        "checkpoint": {
            "best": {
                "metric_key": "inbatch_t2i_recall_at_1",
                "by_epoch": false,
                "interval": 200,
                "save_dir": "./workspace/ckpts/clip"
            },
            "period": {
                "interval": 1,
                "save_dir": "./workspace/ckpts/clip"
            }
        }
    },
    "evaluation": {
        "dataloader": {
            "batch_size_per_gpu": 2,
            "workers_per_gpu": 0,
            "shuffle": false,
            "drop_last": true
        },
        "metrics": [
            {
                "type": "inbatch_recall"
            }
        ],
        "period": {
            "by_epoch": true,
            "interval": 1
        }
    },
    "preprocessor": []
}

**Comment by slin000111** [comment]
configuration.json少了
"model": {
        "type": "clip-multi-modal-embedding"
    }
可用原模型文件中的configuration.json替换
