### ISSUE TITLE
1.15版本存在问题

### ISSUE THREAD

**Issue by MindLostGuy** [modelscope/modelscope#894]
modelscope自动更新到1.15后，出现如下错误：Failed to import swift.tuners.mapping because of the following error (look up to see its traceback):
During ast indexing the file /opt/conda/lib/python3.10/site-packages/modelscope/models/audio/aec/layers/activations.py, a related error excepted in the file /opt/conda/lib/python3.10/site-packages/modelscope/utils/ast_utils.py at line: 152: "attr = getattr(node, field)" with error msg: "AttributeError: 'ClassDef' object has no attribute 'type_params'", please double check the origin file /opt/conda/lib/python3.10/site-packages/modelscope/models/audio/aec/layers/activations.py to see whether the file is correctly edited.

当modelscope降级为1.14后，可正常运行

**Comment by wenmengzhou** [comment]
can you provide the example code which can reproduce   this problem？

**Comment by MindLostGuy** [comment]
细节报错：

> Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/ast_utils.py", line 466, in _get_single_file_scan_result
    output = self.astScaner.generate_ast(file)
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/ast_utils.py", line 365, in generate_ast
    output = self.scan_import(node, show_offsets=False)
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/ast_utils.py", line 164, in scan_import
    local_out = _scan_import(el, type(el).__name__)
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/ast_utils.py", line 133, in _scan_import
    return self.scan_import(
  File "/opt/conda/lib/python3.10/site-packages/modelscope/utils/ast_utils.py", line 151, in scan_import
    attr = getattr(node, field)
AttributeError: 'ClassDef' object has no attribute 'type_params'

example code为使用k8s拉取docker跑代码，主要为：

> pip install -e '.[llm]' -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q;\
  pip install transformers==4.37.2 -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install Pillow -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install modelscope==1.14 -i https://mirrors.bfsu.edu.cn/pypi/web/simple -q; \
  pip install flash-attn --no-build-isolation -q; \
  export NCCL_SOCKET_IFNAME=enp24s0,enp25s0; \
  export MKL_THREADING_LAYER=GNU; \
  export MODELSCOPE_CACHE=PATH; \
  CUDA_VISIBLE_DEVICES=0 swift infer

是否与modelscope_cache的ast_index有关？

**Comment by MindLostGuy** [comment]
我可能找到了原因，目前每次运行后，会生成一个新的ast_indexer，而这个ast_indexer会导致再次运行时的程序出现上述问题。当我使用了之前的ast_indexer后，可以正常运行，但程序会自动生成一个会报错的ast_indexer覆盖可以正常运行的ast_indexer

**Comment by slin000111** [comment]
你好，这里看起来用的不是modelscope官方镜像，方便提供一下你的镜像吗？

**Comment by MindLostGuy** [comment]
很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？

**Comment by Azir1** [comment]
ast_indexer 是在哪里啊？  我在断网环境下运行模型，也出现同样的错误了，模型我已经改为从本地cache中加载了。
你具体是怎么解决报错的？
是把modelscope降级为1.14就行了吗？

**Comment by slin000111** [comment]
> 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？

多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。

**Comment by Azir1** [comment]
> > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> 
> 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。

请问你是怎么解决这个问题的？

**Comment by liuyhwangyh** [comment]
> > > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> > 
> > 
> > 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。
> 
> 请问你是怎么解决这个问题的？

多机器多卡训练，您是共享了MODELSCOPE_CACHE 目录？

**Comment by Azir1** [comment]
> > > > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> > > 
> > > 
> > > 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。
> > 
> > 
> > 请问你是怎么解决这个问题的？
> 
> 多机器多卡训练，您是共享了MODELSCOPE_CACHE 目录？

我是单机器单卡，我的模型是放在docker容器中的，容器打包到内网环境，就报和这条issue一样的错误

**Comment by liuyhwangyh** [comment]
> > > > > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> > > > 
> > > > 
> > > > 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。
> > > 
> > > 
> > > 请问你是怎么解决这个问题的？
> > 
> > 
> > 多机器多卡训练，您是共享了MODELSCOPE_CACHE 目录？
> 
> 我是单机器单卡，我的模型是放在docker容器中的，容器打包到内网环境，就报和这条issue一样的错误
模型打包到容器中，在load模型时也用容器中打包好的模型？

**Comment by Azir1** [comment]
> > > > > > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> > > > > 
> > > > > 
> > > > > 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。
> > > > 
> > > > 
> > > > 请问你是怎么解决这个问题的？
> > > 
> > > 
> > > 多机器多卡训练，您是共享了MODELSCOPE_CACHE 目录？
> > 
> > 
> > 我是单机器单卡，我的模型是放在docker容器中的，容器打包到内网环境，就报和这条issue一样的错误
> > 模型打包到容器中，在load模型时也用容器中打包好的模型？

没错，模型是保存在docker容器中的，load 模型也是用的容器中的模型，，
把modelscope版本降1.14.0能解决这个问题吗

**Comment by liuyhwangyh** [comment]
> 我可能找到了原因，目前每次运行后，会生成一个新的ast_indexer，而这个ast_indexer会导致再次运行时的程序出现上述问题。当我使用了之前的ast_indexer后，可以正常运行，但程序会自动生成一个会报错的ast_indexer覆盖可以正常运行的ast_indexer

如果您是多机器多卡，可能会有多个worker同时些ast_indexer可能，您可以尝试让master先启动生成这个文件，其他worker使用同一个已经生成的。

**Comment by liuyhwangyh** [comment]
> > > > > > > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> > > > > > 
> > > > > > 
> > > > > > 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。
> > > > > 
> > > > > 
> > > > > 请问你是怎么解决这个问题的？
> > > > 
> > > > 
> > > > 多机器多卡训练，您是共享了MODELSCOPE_CACHE 目录？
> > > 
> > > 
> > > 我是单机器单卡，我的模型是放在docker容器中的，容器打包到内网环境，就报和这条issue一样的错误
> > > 模型打包到容器中，在load模型时也用容器中打包好的模型？
> 
> 没错，模型是保存在docker容器中的，load 模型也是用的容器中的模型，， 把modelscope版本降1.14.0能解决这个问题吗

您可以尝试下在打镜像安装完modelscope后加一条

**Comment by Azir1** [comment]
> > > > > > > > 很抱歉，镜像我无法提供。但是我可以提供可以正常运行的ast_indexer和之后生成的错误ast_indexer。目前，我不再映射MODELSCOPE_CACHE到现有路径，而是使用k8s临时的默认MODELSCOPE_CACHE来避免之前的问题。我使用的多机多卡训练策略是否会对这个问题产生影响？
> > > > > > > 
> > > > > > > 
> > > > > > > 多机多卡训练应该不会产生影响。最近也遇到了在其他镜像上install modelscope之后，再次运行出现同你的描述一样的报错。
> > > > > > 
> > > > > > 
> > > > > > 请问你是怎么解决这个问题的？
> > > > > 
> > > > > 
> > > > > 多机器多卡训练，您是共享了MODELSCOPE_CACHE 目录？
> > > > 
> > > > 
> > > > 我是单机器单卡，我的模型是放在docker容器中的，容器打包到内网环境，就报和这条issue一样的错误
> > > > 模型打包到容器中，在load模型时也用容器中打包好的模型？
> > 
> > 
> > 没错，模型是保存在docker容器中的，load 模型也是用的容器中的模型，， 把modelscope版本降1.14.0能解决这个问题吗
> 
> 您可以尝试下在打镜像安装完modelscope后加一个RUN python -c 'import modelscope; print(modelscope.**version**)' 注意version前后都有__

我把modelscope版本降低到 1.14.0后，能够正常运行模型了 
![6B42340F](https://github.com/modelscope/modelscope/assets/59249690/09e84f9e-c473-4b20-9853-b4e292d406a3)

**Comment by MindLostGuy** [comment]
> > 我可能找到了原因，目前每次运行后，会生成一个新的ast_indexer，而这个ast_indexer会导致再次运行时的程序出现上述问题。当我使用了之前的ast_indexer后，可以正常运行，但程序会自动生成一个会报错的ast_indexer覆盖可以正常运行的ast_indexer
> 
> 如果您是多机器多卡，可能会有多个worker同时些ast_indexer可能，您可以尝试让master先启动生成这个文件，其他worker使用同一个已经生成的。

这可能不是原因。在我使用单机单卡运行时，同样会出现这个问题

**Comment by tastelikefeet** [comment]
~/.cache/modelscope/ast_indexer 这个文件删除一下就会好了

**Comment by tastelikefeet** [comment]
如果该文件不存在这个路径下，可能在/mnt/workspace/.cache/modelscope下

**Comment by Downupanddownup** [comment]
> ~/.cache/modelscope/ast_indexer 这个文件删除一下就会好了

确实可行
