### ISSUE TITLE
限制GPU显存占用

### ISSUE THREAD

**Issue by algfwq** [modelscope/modelscope#898]
我使用RTX 3050 4GB运行模型，提示CUDA out of memory. Tried to allocate 72.00 MiB. GPU
我希望通过某种方式限制模型的显存占用应该怎么做？
代码：
pasd = pipeline(Tasks.image_super_resolution_pasd, model='damo/PASD_v2_image_super_resolutions',
                download_path=r'D:\pytorch_study\models')

**Comment by slin000111** [comment]
尝试device_map="auto"

**Comment by algfwq** [comment]
> 尝试device_map=“auto”

无法解决问题
