### ISSUE TITLE
安装audio报错

### ISSUE THREAD

**Issue by maydayxx** [modelscope/modelscope#901]
pip install modelscope[audio] -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

报错：
        File "<string>", line 38, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by slin000111** [comment]
操作系统，modelscope，python版本提供一下
