### ISSUE TITLE
已经有音频和对应的文本，如何使用run_auto_label实现音素标注呢？

### ISSUE THREAD

**Issue by WhXmURandom** [modelscope/modelscope#902]
已经有音频和对应的文本，如何使用run_auto_label实现音素标注呢？需要如何修改脚本呢？

**Comment by slin000111** [comment]
run_auto_label链接贴一下

**Comment by WhXmURandom** [comment]
https://modelscope.cn/models/iic/speech_ptts_autolabel_16k

**Comment by WhXmURandom** [comment]
请问有解决办法吗~
