### ISSUE TITLE
希望datasets提供造成viewer不显示的debug logs查看接口

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#905]
**Describe the feature**
Features description
明明本地调试都正常打印，一push到云端自动viewer就不工作了，也没法找原因
**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by monetjoe** [comment]
另外看起来目前的datasets的viewer对subset还不支持，只要涉及 BUILDER_CONFIGS = [] 的方式添加 subset ，viewer就会不工作

**Comment by wangxingjun778** [comment]
不同于MsDataset.load()时手动指定subset，Viewer端事先并不知道该指定哪些subset，所以目前默认是扫描全部的subset，现在发现在某类数据集上，使用datasets.get_dataset_config_names和builder_instance.builder_configs方式并不能成功获取subset和split的全量mapping；该问题已收到，我们会在后续的小版本中fix掉。

另外，可否发一下目前碰到问题的dataset链接，我们case by case看一下。

**Comment by monetjoe** [comment]
> 不同于MsDataset.load()时手动指定subset，Viewer端事先并不知道该指定哪些subset，所以目前默认是扫描全部的subset，现在发现在某类数据集上，使用datasets.get_dataset_config_names和builder_instance.builder_configs方式并不能成功获取subset和split的全量mapping；该问题已收到，我们会在后续的小版本中fix掉。
> 
> 另外，可否发一下目前碰到问题的dataset链接，我们case by case看一下。

感谢回复，当前有8款数据集出现问题，经过归纳发现均为使用了subset情况的数据集，我选择一款较为轻量级的数据集作为案例：https://www.modelscope.cn/datasets/ccmusic-database/bel_canto

另外数据集一旦挂掉，发现没有再部署的按钮，即使本地修复完毕修改代码push，也不会立即触发viewer的自动重新部署。但是我并不清楚后台重新部署的触发机制，也没有具体的是将概念，会感觉很茫然。由于近期发表数据集需要给期刊的reviewer提供数据的可视化review，对于能够恢复viewer的有着强烈的需求，非常感谢您能够帮忙针对具体数据集进行排查

**Comment by monetjoe** [comment]
暂时通过避开使用 BUILDER_CONFIGS 来规避 viewer 完全不工作的情况，将最重要的subset设为default subset以应对 reviewer对数据的review
