### ISSUE TITLE
对训练好的模型微调时报错：RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by xxd-hub** [modelscope/modelscope#909]
在微调时打印发现模型权重：Warning: Found NaN or Inf in parameter transformer.h.21.mlp.c_proj.weight
Warning: Found NaN or Inf in parameter transformer.h.22.attn.c_attn.weight
Warning: Found NaN or Inf in parameter transformer.h.22.attn.c_proj.weight
Warning: Found NaN or Inf in parameter transformer.h.22.mlp.w1.weight
Warning: Found NaN or Inf in parameter transformer.h.22.mlp.w2.weight
Warning: Found NaN or Inf in parameter transformer.h.22.mlp.c_proj.weight
Warning: Found NaN or Inf in parameter transformer.h.23.attn.c_attn.weight
Warning: Found NaN or Inf in parameter transformer.h.23.attn.c_proj.weight
Warning: Found NaN or Inf in parameter transformer.h.23.mlp.w1.weight
Warning: Found NaN or Inf in parameter transformer.h.23.mlp.w2.weight
Warning: Found NaN or Inf in parameter transformer.h.23.mlp.c_proj.weight
### **我的训练代码：**
"""
* @Class => qw_train_mode.py
* @Author => 銇嗐倖銇�
* @Data => 2024/7/11
* @Time => 10:27
"""
import json
import pandas as pd
import torch
from datasets import Dataset, load_dataset
from modelscope import snapshot_download, AutoTokenizer
from swanlab.integration.huggingface import SwanLabCallback
from peft import LoraConfig, TaskType, get_peft_model
from transformers import AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForSeq2Seq
import os
import swanlab

# 加载模型权重
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_path = "D:\\tonyi\\qwen\\Qwen-1_8B"
tokenizer = AutoTokenizer.from_pretrained(model_path, padding=True, trust_remote_code=True)
tokenizer.pad_token_id = tokenizer.eod_id
model = (AutoModelForCausalLM.from_pretrained(model_path,
                                              revision='master',
                                              device_map={"": device},
                                              trust_remote_code=True).eval())
model.enable_input_require_grads()

def process_funcs(example):
    """
    将数据集进行预处理
    """
    MAX_LENGTH = 384
    conversations = example['conversations']
    user_input = ''
    assistant_response = ''

    # 遍历对话记录
    for conv in conversations:
        if conv['from'] == 'user':
            user_input = conv['value']
        elif conv['from'] == 'assistant':
            assistant_response = conv['value']

    # 响应编码
    input_encoding = tokenizer(user_input, add_special_tokens=False)
    response_encoding = tokenizer(assistant_response, add_special_tokens=False)

    # 组合编码
    input_ids = input_encoding["input_ids"] + response_encoding["input_ids"] + [tokenizer.pad_token_id]
    attention_mask = (
        input_encoding["attention_mask"] + response_encoding["attention_mask"] + [1]
    )
    labels = [-100] * len(input_encoding["input_ids"]) + response_encoding["input_ids"] + [tokenizer.pad_token_id]

    # 序列超过最大长度，截断
    if len(input_ids) > MAX_LENGTH:
        input_ids = input_ids[:MAX_LENGTH]
        attention_mask = attention_mask[:MAX_LENGTH]
        labels = labels[:MAX_LENGTH]

    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

# 加载数据集
json_file_path = os.path.join(os.getcwd(), "data.json")
dataset = load_dataset("json", data_files=json_file_path)
print(dataset.data)
# 数据集分割
train_dataset = dataset['train']
# half_length = len(train_dataset) // 2
#
# reduced_dataset = train_dataset.select(range(half_length))
#
train_dataset = train_dataset.map(process_funcs, remove_columns=train_dataset.column_names)

# 生成 target_modules 列表
num_layers = 272
target_modules = [
    f'transformer.h.{i}.{sub_module}'
    for i in range(num_layers)
    for sub_module in ['attn.c_attn', 'attn.c_proj', 'mlp.w1', 'mlp.w2', 'mlp.c_proj']
]
# LoRA 配置
config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    target_modules=target_modules,
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
)

model = get_peft_model(model, config)

# 训练参数
args = TrainingArguments(
    output_dir="./output/Qwen1.8n",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    logging_steps=10,
    num_train_epochs=2,
    save_steps=1,
    learning_rate=1e-4,
    save_on_each_node=True,
    gradient_checkpointing=True,
    report_to="none",
)

# 数据预处理
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, padding=True)

# Trainer 配置
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    data_collator=data_collator,
)

# 开始训练
trainer.train()
**### 我的测试代码：**
from modelscope import AutoModelForCausalLM, AutoTokenizer
import torch
from peft import PeftModel

print(torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_path = "output/Qwen1.8n/nc"

# 加载基础模型
base_model = AutoModelForCausalLM.from_pretrained(model_path, device_map={"": device},
                                                  trust_remote_code=True).eval()

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
tokenizer.pad_token_id = tokenizer.eod_id

# 添加了适配器
# adapter_name = base_model.add_adapter("output/Qwen1.8v1/checkpoint-100/adapter_config.json")

# 加载权重
# base_model.load_adapter("output/Qwen1.8v1/checkpoint-100/adapter_model.bin", load_as=adapter_name)

# 设置适配器
# base_model.set_active_adapters(adapter_name)

# PEFT加载适配器
# model = PeftModel.from_pretrained(base_model, "output/Qwen1.8/checkpoint-400")

history = []

while True:
    message = input('User:')
    inputs = tokenizer(message, return_tensors="pt").to(device)
    # 检查模型权重
    for name, param in base_model.named_parameters():
        if torch.isnan(param).any() or torch.isinf(param).any():
            print(f"Warning: Found NaN or Inf in parameter {name}")

    # 检查输入数据
    # if torch.isnan(inputs['input_ids']).any() or torch.isinf(inputs['input_ids']).any():
    #     print("Warning: Found NaN or Inf in input_ids")
    # model.to(torch.float32)
    outputs = base_model.generate(**inputs, num_return_sequences=1, pad_token_id=tokenizer.pad_token_id)
    # self.softmax = nn.Softmax()
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print('System:', end='')
    print(response)

**### 数据集：**
[data.json](https://github.com/user-attachments/files/16202108/data.json)

**Comment by wenmengzhou** [comment]
在训练过程中计算精度溢出了，请尝试调小学习率或者对剃度进行裁剪。 如果还不行可以逐层查看模型输出是在哪里出现了inf
