### ISSUE TITLE
AttributeError: type object 'Tasks' has no attribute 'face_quality_assessment'？

### ISSUE THREAD

**Issue by zhangfusheng-163** [modelscope/modelscope#91]
The Tasks have not  face_quality_assessment,why?
AttributeError: type object 'Tasks' has no attribute 'face_quality_assessment'

**Comment by yingdachen** [comment]
which model are you tying to used? from the error, it looks like the model is still in the process of integrating into modelscope, and is not ready for usage yet.

**Comment by zhangfusheng-163** [comment]
> which model are you tying to use? from the error, it looks like the model is still in the process of integrating into modelscope, and is not ready for usage yet.

OK,thanks!
