### ISSUE TITLE
如果同时用到transformer和modelscope，会出现在~/.cache/huggingface中找不到模型的错误。

### ISSUE THREAD

**Issue by CodingWZP** [modelscope/modelscope#911]
import torch

import sys
sys.path.append('./')
from videollama2.conversation import conv_templates, SeparatorStyle
from videollama2.constants import DEFAULT_MMODAL_TOKEN, MMODAL_TOKEN_INDEX
from videollama2.mm_utils import get_model_name_from_path, tokenizer_MMODAL_token, KeywordsStoppingCriteria, process_video, process_image
from videollama2.model.builder import load_pretrained_model

from modelscope import AutoModelForCausalLM, AutoTokenizer

class VideoUnderstandRunner():
    def __init__(self, model_path, prompt) -> None:
        self.model_path = model_path
        self.prompt = prompt
        self.device = 'cuda'
        self.conv_mode = 'llama_2'
        self.tokenizer, self.model, self.processor = self.load_model()

    def load_model(self):
        # 1. Initialize the model.
        model_name = get_model_name_from_path(self.model_path)
        tokenizer, model, processor, context_len = load_pretrained_model(self.model_path, None, model_name)
        model = model.to(self.device)

        return tokenizer, model, processor

    def run(self, clip_path):
        paths = [clip_path]
        questions = [self.prompt]
        modal_list = ['video']

        # 2. Visual preprocess (load & transform image or video).
        if modal_list[0] == 'video':
            tensor = process_video(paths[0], self.processor, self.model.config.image_aspect_ratio).to(dtype=torch.float16, device=self.device, non_blocking=True)
            default_mm_token = DEFAULT_MMODAL_TOKEN["VIDEO"]
            modal_token_index = MMODAL_TOKEN_INDEX["VIDEO"]
        else:
            tensor = process_image(paths[0], self.processor, self.model.config.image_aspect_ratio)[0].to(dtype=torch.float16, device=self.device, non_blocking=True)
            default_mm_token = DEFAULT_MMODAL_TOKEN["IMAGE"]
            modal_token_index = MMODAL_TOKEN_INDEX["IMAGE"]
        tensor = [tensor]

        # 3. Text preprocess (tag process & generate prompt).
        question = default_mm_token + "\n" + questions[0]
        conv = conv_templates[self.conv_mode].copy()
        conv.append_message(conv.roles[0], question)
        conv.append_message(conv.roles[1], None)
        prompt = conv.get_prompt()
        input_ids = tokenizer_MMODAL_token(prompt, self.tokenizer, modal_token_index, return_tensors='pt').unsqueeze(0).to(self.device)

        # 4. Generate a response according to visual signals and prompts.
        stop_str = conv.sep if conv.sep_style in [SeparatorStyle.SINGLE] else conv.sep2
        # keywords = ["<s>", "</s>"]
        keywords = [stop_str]
        stopping_criteria = KeywordsStoppingCriteria(keywords, self.tokenizer, input_ids)

        with torch.inference_mode():
            output_ids = self.model.generate(
                input_ids,
                images_or_videos=tensor,
                modal_list=modal_list,
                do_sample=True,
                temperature=0.2,
                max_new_tokens=1024,
                use_cache=True,
                stopping_criteria=[stopping_criteria],
            )

        outputs = self.tokenizer.batch_decode(output_ids, skip_special_tokens=True)

        return outputs[0]

if __name__ == '__main__':
    model_path = "~/lm/VideoLLaMA2/videollama_weights"
    prompt = "Describe the video in detail."
    video_path = '~/lm/GenData/output/v_ZZ71FIfxX-c_1/v_ZZ71FIfxX-c_1.mp4'
    video_understand_runner = VideoUnderstandRunner(model_path=model_path, prompt=prompt)
    answer = video_understand_runner.run(clip_path=video_path)
    print(answer)
    
    
    在上面的代码中，会提示找不到clip模型，但是该模型我已经通过transformer库下载到~/.cache/huggingface中了
如果我将from modelscope import AutoModelForCausalLM, AutoTokenizer注释掉，就不会报错。
我怀疑是from modelscope import AutoModelForCausalLM, AutoTokenizer中修改了查找默认缓存模型路径，导致不会去~/.cache/huggingface中去查找模型权重，而是只会在~/.modelscope中查找。

能否将查找路径同时保留查找~/.cache/huggingface 和 ~/.cache/modelscope ?

**Comment by slin000111** [comment]
一般使用`from modelscope import AutoModelForCausalLM, AutoTokenizer` 之前用modelscope `snapshot_download` 。如下：

**Comment by slin000111** [comment]
可以在 `from modelscope import AutoModelForCausalLM, AutoTokenizer` 之前加一下modelscope `snapshot_download`。
例如：
```python
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer


model_path = snapshot_download("01ai/Yi-34B-Chat")

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()
```
