### ISSUE TITLE
MODELSCOPE_MODULES_CACHE 这个环境变量还需要设置吗？在modelscope代码里没有搜到这个变量

### ISSUE THREAD

**Issue by stu-GYULA** [modelscope/modelscope#912]
搜到一些设置modelscope环境变量的文章，一般让设置MODELSCOPE_CACHE和MODELSCOPE_MODULES_CACHE这两个环境变量。但是在modelscope代码里面没看到使用MODELSCOPE_MODULES_CACHE，是不是不需要设置了

**Comment by yingdachen** [comment]
使用MODELSCOPE_CACHE即可。请问在哪里看到使用了MODELSCOPE_MODULES_CACHE？我们更新一下文档

**Comment by stu-GYULA** [comment]
没找到官方文档里设置环境变量的内容，一些博客上要设置MODELSCOPE_CACHE和MODELSCOPE_MODULES_CACHE，那应该没事了
