### ISSUE TITLE
用个性化语音合成-自动标注模型-16k进行音素标注的时候，为什么会产生badlist呢

### ISSUE THREAD

**Issue by WhXmURandom** [modelscope/modelscope#915]
**General Question**

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by slin000111** [comment]
测试[iic/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k](https://modelscope.cn/models/iic/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k)模型卡片上sample_test_female和sample_test_male示例音频文件，未出现上述error。
