### ISSUE TITLE
datasets 版本依赖错误

### ISSUE THREAD

**Issue by Crystal-girl** [modelscope/modelscope#916]
datasets版本依赖过低，报错cannot import name '_datasets_server' from 'datasets.utils'。
目前仅支持 <=2.18.0的版本，高版本报错。

**Comment by wangxingjun778** [comment]
Refer to this PR: https://github.com/modelscope/modelscope/pull/921

**Comment by lizaibeim** [comment]
> @wangxingjun778 @Alexez please evaluate possiblity of upating to latest version

Hello, the latest version doesn't fully solve the problem #931
