### ISSUE TITLE
StructBERT问句识别-中文口语-通用领域项目BUG

### ISSUE THREAD

**Issue by lqzzy** [modelscope/modelscope#919]
## 问题
[StructBERT问句识别-中文口语-通用领域](https://www.modelscope.cn/models/iic/nlp_structbert_qd_spoken_chinese-base?spm=a2c6h.13066369.question.1.65e750ed4SSbfR)项目中，采用魔塔提供的notebook免费环境，试了各种镜像，都存在一个这样的问题：

**TypeError: PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'label2id'**

## 复现
复现这个问题非常简单，只需要点开这个项目的网址，然后打开[魔塔平台免费实例](https://modelscope.cn/my/mynotebook/preset?spm=a2c6h.13066369.question.2.65e750ed4SSbfR)这个网址，然后创建一个实例，在创建好的notebook中运行下面的代码，这也是这个项目网页给出的demo。

```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.outputs import OutputKeys



text_classification = pipeline(Tasks.text_classification, model='damo/nlp_structbert_alimeeting_action-classification_chinese-base')
output = text_classification("今天会议的第一个结论是明天先收集用户的需求吗？")

```

## 我的尝试
- 尝试了notebook提供的各种环境镜像，包括python=3.7,3.8,3.10等等
- 在google,github上搜索了这个问题，没有找到直接的相同问题，但是根据搜索的结果，判断是和transformers库版本有关系
- 尝试了各种transformers库的版本
- 在[StructBERT问句识别-中文口语-通用领域](https://www.modelscope.cn/models/iic/nlp_structbert_qd_spoken_chinese-base?spm=a2c6h.13066369.question.3.65e750ed4SSbfR)项目中提出了相关的issue，但是半年没有人回答

**Comment by tastelikefeet** [comment]
模型配置存在问题，已经更新，请使用如下代码：
```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.outputs import OutputKeys
text_classification = pipeline(Tasks.text_classification, model='iic/nlp_structbert_alimeeting_action-classification_chinese-base', model_revision='v1.0.1')
output = text_classification("今天会议的第一个结论是明天先收集用户的需求吗？")
print(output)
```

**Comment by XYZliang** [comment]
> 模型配置存在问题，已经更新，请使用如下代码：
> 
> ```python
> from modelscope.pipelines import pipeline
> from modelscope.utils.constant import Tasks
> from modelscope.outputs import OutputKeys
> text_classification = pipeline(Tasks.text_classification, model='iic/nlp_structbert_alimeeting_action-classification_chinese-base', model_revision='v1.0.1')
> output = text_classification("今天会议的第一个结论是明天先收集用户的需求吗？")
> print(output)
> ```

nlp_structbert_backbone_large_std模型有一样的问题，我正在尝试微调，发生错误TypeError: PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'label2id'
`train_dataset = MsDataset.load('data/labeled_questions.csv')
print(next(iter(train_dataset)))
eval_dataset = MsDataset.load('data/labeled_questions_validation.csv')

max_epochs = 2
def cfg_modify_fn(cfg):
    cfg.train.max_epochs = max_epochs
    cfg.train.hooks = [{
            'type': 'TextLoggerHook',
            'interval': 100
        }, {
            "type": "CheckpointHook",
            "interval": 1
        }]
    cfg.evaluation.metrics = [Metrics.seq_cls_metric]
    cfg['dataset'] = {
        'train': {
            'labels': ['非链式问句','链式问句'],
            'first_sequence': 'sentence',
            'label': 'label',
        }
    }
    cfg.train.optimizer.lr = 3e-5
    return cfg
    # map float to index
#def map_labels(examples):
#     map_dict = {0: "非链式问句", 1: "链式问句"}
#     examples['label'] = map_dict[int(examples['label'])]
#     return examples
#
# train_dataset = train_dataset.map(map_labels)
# eval_dataset = eval_dataset.map(map_labels)

for data in train_dataset:
    if data['label'] == 0:
        data['label'] = '非链式问句'
    else:
        data['label'] = '链式问句'
for data in eval_dataset:
    if data['label'] == 0:
        data['label'] = '非链式问句'
    else:
        data['label'] = '链式问句'


WORK_DIR = '/data/ccks2024/ccks_2024_pj/chain_que/model'
model_id = 'iic/nlp_structbert_backbone_large_std'

kwargs = dict(
    model=model_id,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    work_dir=WORK_DIR,
    cfg_modify_fn=cfg_modify_fn)

trainer = build_trainer(name='nlp-base-trainer', default_args=kwargs)

print('===============================================================')
print('pre-trained model loaded, training started:')
print('===============================================================')

trainer.train()

print('===============================================================')
print('train success.')
print('===============================================================')

for i in range(max_epochs):
    eval_results = trainer.evaluate(f'{WORK_DIR}/epoch_{i+1}.pth')
    print(f'epoch {i} evaluation result:')
    print(eval_results)


print('===============================================================')
print('evaluate success')
print('===============================================================')
    `
