### ISSUE TITLE
数据集中有数据被误封了，见desc中的截图，请求帮忙解封

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#925]
**General Question**
![image](https://github.com/user-attachments/assets/3485e124-8c51-432b-942a-ae6d54a241bb)

问题数据集：
https://www.modelscope.cn/datasets/ccmusic-database/bel_canto/files

Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by yingdachen** [comment]
数据可以通过git 历史回滚，在本地恢复
