### ISSUE TITLE
Converting safetensors to modelscope format

### ISSUE THREAD

**Issue by julkaztwittera** [modelscope/modelscope#932]
How to convert standard safetensors model format to modelscope? In other words, how [this](https://huggingface.co/ali-vilab/text-to-video-ms-1.7b) was converted to [this](https://huggingface.co/ali-vilab/modelscope-damo-text-to-video-synthesis)?

**Comment by slin000111** [comment]
Maybe you can try safetensors.torch.save_file and torch.save

**Comment by julkaztwittera** [comment]
It doesn't help, because modelscope has its own definition of UNet.

**Comment by yingdachen** [comment]
> How to convert standard safetensors model format to modelscope? In other words, how [this](https://huggingface.co/ali-vilab/text-to-video-ms-1.7b) was converted to [this](https://huggingface.co/ali-vilab/modelscope-damo-text-to-video-synthesis)?

modelscope does not define its own model format, please provide model link on modelscope, so that we can help refer to model owners to take a look.
