### ISSUE TITLE
pip install 1.17.1 及以往版本暂无法屏蔽  - modelscope - INFO -  和 WARNING 级别的log打印，待latest code上架后才能解决问题

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#934]
**General Question**
![image](https://github.com/user-attachments/assets/da90f267-206e-48b4-aa72-b4b82f0c6953)
多次调用的时候被这些东西刷屏很烦欸
Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by slin000111** [comment]
```python
import logging
from modelscope.utils.logger import get_logger
logger = get_logger()
logger.setLevel(logging.ERROR)
```

**Comment by monetjoe** [comment]
> ```python
> import logging
> from modelscope.utils.logger import get_logger
> logger = get_logger()
> logger.setLevel(logging.ERROR)
> ```

社区里摘的吧，查到过，不好用

**Comment by zsh123abc** [comment]
找到方法了，导航到 modelscope.utils.logger文件里面，把def get_logger(log_file: Optional[str] = None,
               log_level: int = logging.INFO,
               file_mode: str = 'w'):，把INFO改为ERROR就行了

**Comment by monetjoe** [comment]
> 找到方法了，导航到 modelscope.utils.logger文件里面，把def get_logger(log_file: Optional[str] = None, log_level: int = logging.INFO, file_mode: str = 'w'):，把INFO改为ERROR就行了


这是要动人家包里面的东西嘛。。。

**Comment by yingdachen** [comment]
this was fixed in #958. 

with the latest code, you can make the logging less verbose by setting env variable MODELSCOPE_LOG_LEVEL to 30(for WARNING) or to 40(for ERROR).

**Comment by monetjoe** [comment]
> this was fixed in #958.
> 
> with the latest code, you can make the logging less verbose by setting env variable MODELSCOPE_LOG_LEVEL to 30(for WARNING) or to 40(for ERROR).

不好用，问题未解决就关闭？

**Comment by yingdachen** [comment]
> > this was fixed in #958.
> > with the latest code, you can make the logging less verbose by setting env variable MODELSCOPE_LOG_LEVEL to 30(for WARNING) or to 40(for ERROR).
> 
> 不好用，问题未解决就关闭？

have  you tried with the latest code? if you are using pip install, you would need to wait for next release (scheduled next week)

**Comment by monetjoe** [comment]
> > > this was fixed in #958.
> > > with the latest code, you can make the logging less verbose by setting env variable MODELSCOPE_LOG_LEVEL to 30(for WARNING) or to 40(for ERROR).
> > 
> > 
> > 不好用，问题未解决就关闭？
> 
> have you tried with the latest code? if you are using pip install, you would need to wait for next release (scheduled next week)

pip 的 latest 是 1.17.1，不好用，那既然还要等下次发布才能解决问题，说明还未解决，为什么要关闭issue？

**Comment by yingdachen** [comment]
> > > > this was fixed in #958.
> > > > with the latest code, you can make the logging less verbose by setting env variable MODELSCOPE_LOG_LEVEL to 30(for WARNING) or to 40(for ERROR).
> > > 
> > > 
> > > 不好用，问题未解决就关闭？
> > 
> > 
> > have you tried with the latest code? if you are using pip install, you would need to wait for next release (scheduled next week)
> 
> pip 的 latest 是 1.17.1，不好用，那既然还要等下次发布才能解决问题，说明还未解决，为什么要关闭issue？

this is github opensource code. the standard of closing issue is fixing in latest  source code.

**Comment by yingdachen** [comment]
> > > > > this was fixed in #958.
> > > > > with the latest code, you can make the logging less verbose by setting env variable MODELSCOPE_LOG_LEVEL to 30(for WARNING) or to 40(for ERROR).
> > > > 
> > > > 
> > > > 不好用，问题未解决就关闭？
> > > 
> > > 
> > > have you tried with the latest code? if you are using pip install, you would need to wait for next release (scheduled next week)
> > 
> > 
> > pip 的 latest 是 1.17.1，不好用，那既然还要等下次发布才能解决问题，说明还未解决，为什么要关闭issue？
> 
> this is github opensource code. the standard of closing issue is fixing in latest source code.

but it makes our community memebers feel better, we can keep it open for a while ;)

**Comment by yingdachen** [comment]
1.8 has released. closing it now

**Comment by monetjoe** [comment]
> 1.8 has released. closing it now

1.8??? 1.18吧？

**Comment by buptcjj** [comment]
import logging
os.environ['MODELSCOPE_LOG_LEVEL'] = str(logging.ERROR)

我看了代码，实测这样可以
