### ISSUE TITLE
in facechain rp

### ISSUE THREAD

**Issue by ucasiggcas** [modelscope/modelscope#937]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

https://www.modelscope.cn/studios/CVstudio/FaceChain-FACT/feedback/issueDetail/14266
直接运行python app.py出现如下错误。

RuntimeError: Failed to import modelscope.models.cv.image_human_parsing.m2fp_net because of the following error (look up to see its traceback):
bezier_align_forward miss in module _ext

这是啥原因啊？
感谢指点！！
试了几个版本的modelscope都不行，所以来这问问。

**Comment by slin000111** [comment]
facechain readme有验证过的环境
