### ISSUE TITLE
md中的<a href="#id"> 或者(id)[#id] 在平台上会被重置成file/view 导致其正常跳转至readme某章节失效

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#939]
Thanks for your error report and we appreciate it a lot.
跳转至哪个文件很好获得原始链接，然而这个readme跳转章节反而需要有易用性，舍本逐末的设计
**Checklist**
另外<img src="./xxx.png相对路径现在也不支持了，只能去仓库找其公网url贴进去了，正像前面所说，找文件直链url很好找，因此这个可以规避就忍了

但这样随意说改就改太坑了平台一遍下面的用户的文档就会显示不正常
* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.
另外 v1 版文件直链API现在也都统一成 /resolve/master了，未来那个旧API是不是也要突然就没啊？
v1版API获取的文件直链还是与仓库最新版文件同步的嘛？
一个API变化几十个数据集都要改脚本
**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by yingdachen** [comment]
thanks for bringing this up. we will take a look asap

**Comment by justmywyw** [comment]
@monetjoe  您好，感谢反馈平台使用的问题，关于您上面的问题：
1. 锚点支持问题

> “md中的<a href="#id"> 或者(id)[#id] 在平台上会被重置成file/view”

这个是近期平台更新产生的 bug，在对齐支持相对路径的功能上我们考虑不周，抱歉给您的使用带来麻烦，我们将在今天修复上线；

2. 图片相对路径问题

> <img src="./xxx.png 相对路径现在也不支持了

这个我们目前实测并未复现，如果您有相关有问题的地址，欢迎附上链接；

3. 文件直链 API 更改问题

> v1 版文件直链API现在也都统一成 /resolve/master了，未来那个旧API是不是也要突然就没啊？v1版API获取的文件直链还是与仓库最新版文件同步的嘛？

目前为了对齐常规 API 规范我们更新了 /resolve/branch 格式的文件直链地址，考虑到原有各处使用旧版 API 仍会长期保留；
v1 版 API 获取的文件直链还是会与仓库最新版文件同步，新旧两版功能上完全等价，仅为路由修订。

**Comment by monetjoe** [comment]
> @monetjoe 您好，感谢反馈平台使用的问题，关于您上面的问题：
> 
> 1. 锚点支持问题
> 
> > “md中的[ 或者(id)[#id] 在平台上会被重置成file/view”](#id)
> 
> 这个是近期平台更新产生的 bug，在对齐支持相对路径的功能上我们考虑不周，抱歉给您的使用带来麻烦，我们将在今天修复上线；
> 
> 2. 图片相对路径问题
> 
> > <img src="./xxx.png 相对路径现在也不支持了
> 
> 这个我们目前实测并未复现，如果您有相关有问题的地址，欢迎附上链接；
> 
> 3. 文件直链 API 更改问题
> 
> > v1 版文件直链API现在也都统一成 /resolve/master了，未来那个旧API是不是也要突然就没啊？v1版API获取的文件直链还是与仓库最新版文件同步的嘛？
> 
> 目前为了对齐常规 API 规范我们更新了 /resolve/branch 格式的文件直链地址，考虑到原有各处使用旧版 API 仍会长期保留； v1 版 API 获取的文件直链还是会与仓库最新版文件同步，新旧两版功能上完全等价，仅为路由修订。

2.图像相对路径问题举例：这是我们维护的其中一个数据集的md，https://www.modelscope.cn/datasets/ccmusic-database/erhu_playing_tech

![image](https://github.com/user-attachments/assets/6db129a7-5ef6-43de-a22d-24b271fb48ee)
![image](https://github.com/user-attachments/assets/63227362-7e8a-4617-be08-3416bfa8b200)

**Comment by monetjoe** [comment]
> @monetjoe 您好，感谢反馈平台使用的问题，关于您上面的问题：
> 
> 1. 锚点支持问题
> 
> > “md中的[ 或者(id)[#id] 在平台上会被重置成file/view”](#id)
> 
> 这个是近期平台更新产生的 bug，在对齐支持相对路径的功能上我们考虑不周，抱歉给您的使用带来麻烦，我们将在今天修复上线；
> 
> 2. 图片相对路径问题
> 
> > <img src="./xxx.png 相对路径现在也不支持了
> 
> 这个我们目前实测并未复现，如果您有相关有问题的地址，欢迎附上链接；
> 
> 3. 文件直链 API 更改问题
> 
> > v1 版文件直链API现在也都统一成 /resolve/master了，未来那个旧API是不是也要突然就没啊？v1版API获取的文件直链还是与仓库最新版文件同步的嘛？
> 
> 目前为了对齐常规 API 规范我们更新了 /resolve/branch 格式的文件直链地址，考虑到原有各处使用旧版 API 仍会长期保留； v1 版 API 获取的文件直链还是会与仓库最新版文件同步，新旧两版功能上完全等价，仅为路由修订。

另外图片相对路径问题还有一个疑问，若文件以lfs形式储存而非以普通文件签入，虽然仓库里看起来路径是一致的，是不是lfs实质路径并不是那个相对路径，导致这种引用图片显示不正常？曾经测试过好像不是这个问题，我把.gitattr 改了一下让图片转成非lfs重新签入，还是没法正常显示，当然还未排除路径缓存之类的问题。  另一个可能性就是跟前面readme那个bug一类，修改别的什么东西的时候引入的bug

**Comment by justmywyw** [comment]
@monetjoe 您好，关于之前反馈的锚点问题：

> “md中的[ 或者(id)[#id] 在平台上会被重置成file/view”](https://github.com/modelscope/modelscope/issues/939#id)

这个问题已经修复上线了，相关锚点跳转也已优化。

另外关于上述的相对路径问题：
1. 原有的数据集中并未兼容 ./ 开头的相对路径前缀 （ 仅支持形如 "\<img src="data/erhu.png" /\>" ），在模型库和创空间中有支持，数据集的文件访问中确实遗漏了，我们也已经刚刚补充相应兼容支持，目前可以在数据集 Readme 中通过 "\<img src="./data/erhu.png" /\>" 正常进行嵌入了；

2. LFS 文件在早期的平台版本中确实并不支持通过文件链接访问，但是在约两个月前我们也支持了 LFS 文件的正常链接访问和嵌入，您可以再尝试一下。

如还有其他任何问题，欢迎随时反馈～

**Comment by monetjoe** [comment]
> @monetjoe 您好，关于之前反馈的锚点问题：
> 
> > “md中的[ 或者(id)[#id] 在平台上会被重置成file/view”](https://github.com/modelscope/modelscope/issues/939#id)
> 
> 这个问题已经修复上线了，相关锚点跳转也已优化。
> 
> 另外关于上述的相对路径问题：
> 
> 1. 原有的数据集中并未兼容 ./ 开头的相对路径前缀 （ 仅支持形如 "<img src="data/erhu.png" />" ），在模型库和创空间中有支持，数据集的文件访问中确实遗漏了，我们也已经刚刚补充相应兼容支持，目前可以在数据集 Readme 中通过 "<img src="./data/erhu.png" />" 正常进行嵌入了；
> 2. LFS 文件在早期的平台版本中确实并不支持通过文件链接访问，但是在约两个月前我们也支持了 LFS 文件的正常链接访问和嵌入，您可以再尝试一下。
> 
> 如还有其他任何问题，欢迎随时反馈～

这个感觉不像是兼容支持问题，应该是业务逻辑变更引入的BUG，因为在我印象中，以往数据集readme插入相对路径是能正常显示过的。不过无所谓了，现在无论通过什么手段只要修好就行
