### ISSUE TITLE
GPT3 13B,30B下载和175B模型体验开放时间？

### ISSUE THREAD

**Issue by liuxz0801** [modelscope/modelscope#94]
您好GPT3的13B，30B模型现在是没有放出的状态，现在实验室想使用一下模型做一些实验，是否有申请下载的途径？
175B的之前在modelscope说一月份放出在线体验，何时放出？会延期么？

**Comment by ccyhxg** [comment]
您好，实验室申请模型下载，可以辛苦您写出具体的实验室的名称，以及申请的背景，发送邮件到contact@modelscope.cn, 我们请模型的贡献者评估后给您答复。
175B的模型目前还没有明确在modelscope社区的在线体验的时间，如果确认可以体验后，会随着release note发出，请关注社区公告，谢谢您

**Comment by liuxz0801** [comment]
好的邮件已经发送，希望尽快回复哈

**Comment by chasonlee** [comment]
@ccyhxg 请问1.3B和2.7B的中文预训练模型有计划开放下载的时间吗？

**Comment by yingdachen** [comment]
> @ccyhxg 请问1.3B和2.7B的中文预训练模型有计划开放下载的时间吗？

1.3B:
https://www.modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary

2.7B:
https://www.modelscope.cn/models/damo/nlp_gpt3_text-generation_2.7B/summary
