### ISSUE TITLE
打扰问下目前是不是还没法解散组织

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#941]
**General Question**
若不能，请问什么时候上线此功能？还是说需要人工审核帮助解散？
Before asking a question, make sure you have:

* Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* Googled your question.
* Searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by monetjoe** [comment]
另外能重命名组织也可

**Comment by GLSHOW** [comment]
1

**Comment by GLSHOW** [comment]
@GLSHOW

**Comment by monetjoe** [comment]
> @GLSHOW

啥意思啊，是At你私聊处理嘛

**Comment by yingdachen** [comment]
> **General Question** 若不能，请问什么时候上线此功能？还是说需要人工审核帮助解散？ Before asking a question, make sure you have:
> 
> * Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
> * Googled your question.
> * Searched related issues but cannot get the expected help.
> * The bug has not been fixed in the latest version.
> 
> Please @ corresponding people according to your problem:
> 
> Model related: @wenmengzhou @tastelikefeet
> 
> Model hub related: @liuyhwangyh
> 
> Dataset releated: @wangxingjun778
> 
> Finetune related: @tastelikefeet @Jintao-Huang
> 
> Pipeline related: @Firmament-cyou @wenmengzhou
> 
> Contribute your model: @zzclynn

是的。目前还不支持。目前只能组织里的一个个模型/数据集做处理（删除或者转移）。

**Comment by monetjoe** [comment]
> > **General Question** 若不能，请问什么时候上线此功能？还是说需要人工审核帮助解散？ Before asking a question, make sure you have:
> > 
> > * Searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
> > * Googled your question.
> > * Searched related issues but cannot get the expected help.
> > * The bug has not been fixed in the latest version.
> > 
> > Please @ corresponding people according to your problem:
> > Model related: @wenmengzhou @tastelikefeet
> > Model hub related: @liuyhwangyh
> > Dataset releated: @wangxingjun778
> > Finetune related: @tastelikefeet @Jintao-Huang
> > Pipeline related: @Firmament-cyou @wenmengzhou
> > Contribute your model: @zzclynn
> 
> 是的。目前还不支持。目前只能组织里的一个个模型/数据集做处理（删除或者转移）。

预计啥时候开放功能

**Comment by yingdachen** [comment]
目前还没有明确的规划支持这个功能。

**Comment by monetjoe** [comment]
人工能解散嘛？

**Comment by yingdachen** [comment]
> 人工能解散嘛？

删除组织里所有的模型以及数据集等内容后，可以加入钉钉用户群，请求手动删除。

**Comment by monetjoe** [comment]
> > 人工能解散嘛？
> 
> 删除组织里所有的模型以及数据集等内容后，可以加入钉钉用户群，请求手动删除。

钉钉用户群具体怎么进，有二维码之类的么

**Comment by monetjoe** [comment]
感谢，已人工解决 @yingdachen
