### ISSUE TITLE
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

### ISSUE THREAD

**Issue by zphilip** [modelscope/modelscope#951]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
   
image_body_reshaping = pipeline(Tasks.image_body_reshaping,  model='damo/cv_flow-based-body-reshaping_damo')
result = image_body_reshaping(image_input)
input image is np.asarray...

system report: 
  .....
  File "/workspace/modelscope/pipelines/base.py", line 254, in _process_single
    out = self._collate_fn(out)
  File "/workspace/modelscope/pipelines/base.py", line 241, in _collate_fn
    return collate_fn(data, self.device)
  File "/workspace/modelscope/pipelines/base.py", line 557, in collate_fn
    return type(data)({
  File "/workspace/modelscope/pipelines/base.py", line 558, in <dictcomp>
    k: collate_fn(v, device) if k != 'img_metas' else v
  File "/workspace/modelscope/pipelines/base.py", line 572, in collate_fn
    return collate_fn(torch.from_numpy(data), device)
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

modify the /workspace/modelscope/pipelines/base.py - line 573
            # Ensure the numpy array has positive strides by making a copy
            data = data.copy()     -- new added.         
            return collate_fn(torch.from_numpy(data), device)

**Comment by slin000111** [comment]
There is no error when executing this inference in my environment.
```shell
torch                             2.3.1
numpy                             1.26.3
modelscope                        1.17.1
```

**Comment by zphilip** [comment]
torch                             2.3.0+cu121
