### ISSUE TITLE
如何屏蔽 - modelscope - INFO - 和 WARNING 级别的log打印 

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#959]
问题 #934 未解决就关闭，重新开启

Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by monetjoe** [comment]
而且为了测试这个是否解决还装了1.17新版本，新版本又引入一堆新问题比如：
trust_remote_code = True 这个 arg 报错了
TypeError: modelscope.msdatasets.utils.hf_datasets_util.load_dataset_with_ctx() got multiple values for keyword argument 'trust_remote_code'

还需要依赖 oss2 addict 一堆新包，也每默认放到 modelscope 的 req 里，还需要手动安装 datasets包（这个应该是1.16版本开始的，当时退回1.15最稳定）

而且对于私库获取附件直链的时候还报 403
![image](https://github.com/user-attachments/assets/5834c688-1fc8-4121-91d8-a9efe80a384c)

注意我已经加我自己的sdk了 HubApi().login(XXX)

测试环境 python 3.9-10

**Comment by yingdachen** [comment]
> 而且为了测试这个是否解决还装了1.17新版本，新版本又引入一堆新问题比如： trust_remote_code = True 这个 arg 报错了 TypeError: modelscope.msdatasets.utils.hf_datasets_util.load_dataset_with_ctx() got multiple values for keyword argument 'trust_remote_code'
> 
> 还需要依赖 oss2 addict 一堆新包，也没默认放到 modelscope 的 req 里，还需要手动安装 datasets包（这个应该是1.16版本开始的，退回1.15是最稳定的）
> 
> 而且对于私库获取附件直链的时候还报 403 ![image](https://private-user-images.githubusercontent.com/20459298/362034301-5834c688-1fc8-4121-91d8-a9efe80a384c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDg4MjgsIm5iZiI6MTcyNDgwODUyOCwicGF0aCI6Ii8yMDQ1OTI5OC8zNjIwMzQzMDEtNTgzNGM2ODgtMWZjOC00MTIxLTkxZDgtYTllZmU4MGEzODRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxMjg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMTk1ODFhMjZhYzllODhkMmViOWFjMmM3MjAxNDRjNDVkNGM4NjY3ZDQyYWU0Y2M2MTJhZjk4YWVlNmQ2NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IcFBpNdwu2nRQdH5y28P5D-Wq5D7QScaRAgXtb9BePU)
> 
> 注意我已经加我自己的sdk了 HubApi().login(XXX)
> 
> 测试环境 win10 python 3.9-10

#934 was closed since it was fixed in the latest master branch. if you are using released version (pip install), you would need to wait for next release.

the restructure of whl package was done in 1.16 release, and the latest instruction can be found at https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#modelscope-library-%E5%AE%89%E8%A3%85

for 403 problem, please open sepearte issue to track.
