### ISSUE TITLE
bmt_clipit and videofeatures_clipit

### ISSUE THREAD

**Issue by yunlong10** [modelscope/modelscope#96]
https://github.com/modelscope/modelscope/blob/fb17fb01a6ad5857a040c27ac30cb968ba25c69e/modelscope/models/cv/language_guided_video_summarization/summarizer.py#L13

should I copy the single_video_prediction.py in [https://github.com/viashin/BMT/blob/master/sample/](https://github.com/viashin/BMT/blob/master/sample/) to `/modelscope/models/cv/language_guided_video_summarization`?

![image](https://user-images.githubusercontent.com/25357731/217828821-5a0c5ccd-495a-47e2-b253-0ce872377f35.png)

**Comment by yingdachen** [comment]
these dependencies are hoste on modelscope's proprietary repo, you can install it with 

pip install bmt_clipit  -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

and 

pip install videofeatures_clipit -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
