### ISSUE TITLE
1.16版本起，modelscope 安装增加了新的依赖项oss2 addict等，未加入pypi包的requires里

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#962]
这导致安装 modelscope 后运行时还需要补全这些依赖项，奇怪的是 datasets 这个依赖项也需要手动安装依赖了
1.15 比较稳定，并未发现此问题

测试环境 win10 python3.9-10
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by yingdachen** [comment]
we apologize for the breaking changes introduced in release 1.16, but please note that this is the expected behavior going forward. please install modelscope according to documentation:

https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#modelscope-library-%E5%AE%89%E8%A3%85

**Comment by monetjoe** [comment]
> we apologize for the breaking changes introduced in release 1.16, but please note that this is the expected behavior going forward. please install modelscope according to documentation:
> 
> https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#modelscope-library-%E5%AE%89%E8%A3%85

强烈建议默认 pip install modelscope 就设置成 modelscope[framework] ,完全裸轻量级 modelscope 看不出有啥用，还容易误导使用者
