### ISSUE TITLE
请问下载模型一直报签名错误是什么情况？

### ISSUE THREAD

**Issue by leavegee** [modelscope/modelscope#968]
modelscope.hub.errors.FileIntegrityError: File /home/apple/.cache/modelscope/hub/._____temp/qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4/model-00002-of-00002.safetensors integrity check failed, expected sha256 signature is e41d9af09037c50f37b14d9f20b04f984ebde3259545641aa8206b8c21361b20, actual is ec708eee6fed25eb9924486d990f9807d132d0c12bb240bb032042b898ee1199, the download may be incomplete, please try again.

请问如何解决呢？

**Comment by yingdachen** [comment]
可能是下载过程中有问题，导致数据写脏了。可以尝试把/home/apple/.cache/modelscope/hub/._____temp/qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4/ 文件夹删掉。然后重新下载试试

**Comment by laiyingxin2** [comment]
I encountered the same problem when downloading thomas/siglip-so400m-patch14-384, but it was still useless to download the model after deleting it

**Comment by HOTSaber** [comment]
I have also encountered this problem, and delete the ._____temp doesn't work.

**Comment by HOTSaber** [comment]
I have also encountered this problem, and delete the ._____temp file doesn't work.

**Comment by skysbird** [comment]
就这么对待用户的问题。。。服了
