### ISSUE TITLE
modelscope网页什么时候支持暗黑模式

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#971]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by yingdachen** [comment]
this is currently in internal-beta, would be made public sometime this month

**Comment by yingdachen** [comment]
dark mode is now avaiable, feel free to try it out

**Comment by monetjoe** [comment]
> dark mode is now avaiable, feel free to try it out

暗黑模式下的字体有点看不清，建议调整一下

**Comment by yingdachen** [comment]
> > dark mode is now avaiable, feel free to try it out
> 
> 暗黑模式下的字体有点看不清，建议调整一下

收到，也欢迎通过页面上的反馈入口直接提交反馈。

**Comment by monetjoe** [comment]
另外一旦点击返回旧版就回不来了。。。

**Comment by monetjoe** [comment]
> > > dark mode is now avaiable, feel free to try it out
> > 
> > 
> > 暗黑模式下的字体有点看不清，建议调整一下
> 
> 收到，也欢迎通过页面上的反馈入口直接提交反馈。

另外一旦点击返回旧版就回不来了。。。

**Comment by yingdachen** [comment]
<img width="370" alt="image" src="https://github.com/user-attachments/assets/8ee70d3f-68dd-4e22-a902-21ec42f211f4">
切换新版没有展示吗

**Comment by monetjoe** [comment]
> <img alt="image" width="370" src="https://private-user-images.githubusercontent.com/5042027/376899463-8ee70d3f-68dd-4e22-a902-21ec42f211f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTY0NzYsIm5iZiI6MTcyOTA1NjE3NiwicGF0aCI6Ii81MDQyMDI3LzM3Njg5OTQ2My04ZWU3MGQzZi02OGRkLTRlMjItYTkwMi0yMWVjNDJmMjExZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDUyMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNjNDJmMjdkMjY2OWI3YzNmZDkwMGUzZmY1OWYyMDBlZDE5Y2VmMWViZmJiZWJlNDdkZGVmNTFmYTQyMjIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iwaP0AnHpt4bgF2LB1hJlaX71eg0mAmfeNYT3q5uqHY"> 切换新版没有展示吗

![image](https://github.com/user-attachments/assets/19b7726b-3a97-4042-81e5-523dd1f9d13c)
