### ISSUE TITLE
创空间发布配置时，提示 Internal Server Error

### ISSUE THREAD

**Issue by Li-Lai** [modelscope/modelscope#972]
![image](https://github.com/user-attachments/assets/df485cf4-5cf6-4991-8358-96505d844310)
第一次时，已经授权关联相关帐号。后续想切换到GPU资源，提升上面的错误。

**Comment by slin000111** [comment]
在魔搭群44837352留言咨询

**Comment by yingdachen** [comment]
已经在答疑群里解决
