### ISSUE TITLE
请问下为何 qwen/Qwen-14B-Chat 模型在离开modelscope加载环境外，会出现退化现象？

### ISSUE THREAD

**Issue by tigflanker** [modelscope/modelscope#973]
Model related: @wenmengzhou @tastelikefeet

Pipeline related: @Firmament-cyou @wenmengzhou

请问一下modelscope大佬，我在使用 qwen/Qwen-14B-Chat 的时候，两种不同的方式，产生了完全不同的结果。

方法一：正常的modelscope调用方式，采用[官网-快速使用](https://modelscope.cn/models/qwen/qwen-14b-chat)的方式加载模型。
对话结果正常：

代码为：
```
model_id = "qwen/Qwen-14B-Chat"

model_dir = snapshot_download(
    model_id=model_id,
    revision="master"
)

tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True,)
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto", trust_remote_code=True, force_download=False).eval()  # fp16=True, 
model.generation_config = GenerationConfig.from_pretrained(model_dir, trust_remote_code=True, ) # 可指定不同的生成长度、top_p等相关超参

response, history = model.chat(tokenizer, "你好", history=None)
print(response)
# 你好！有什么我能帮助你的吗？

response, history = model.chat(tokenizer, "浙江的省会在哪里？", history=history) 
print(response)
# 浙江省的省会是杭州。
```

方法二：通过 ollama 依次经过：gguf转化、量化。量化后的模型ollama加载失败，gguf直接转化后的半精度gguf能加载成功。
```
# 格式转化，ollama加载成功
sudo /mnt/sdc/data/miniconda3/envs/llm/bin/python convert_hf_to_gguf.py /data/hf-pretrained/qwen/Qwen-14B-Chat/

# 量化，ollama加载失败
sudo ./llama-quantize /data/hf-pretrained/qwen/Qwen-14B-Chat/Qwen-14B-Chat-F16.gguf Q4_K_M
```
但是ollama加载半精度gguf后，模型就从 chat 退化成 base 模型了，只会玩儿文字接龙。如图：
![微信截图_20240903171955](https://github.com/user-attachments/assets/ed858a07-323d-4263-87a5-cb6abd267dc5)

想问下大佬，这是咋回事？
过程中比较有可能的两个问题点：
1. 会不会是modelscope的模型加载函数中间，对模型有一些prompt？
2. 会不会ollama转化gguf的过程中，把instruction的一些东西洗掉了？

**Comment by slin000111** [comment]
参考https://github.com/QwenLM/qwen.cpp

**Comment by yingdachen** [comment]
> Model related: @wenmengzhou @tastelikefeet
> 
> Pipeline related: @Firmament-cyou @wenmengzhou
> 
> 请问一下modelscope大佬，我在使用 qwen/Qwen-14B-Chat 的时候，两种不同的方式，产生了完全不同的结果。
> 
> 方法一：正常的modelscope调用方式，采用[官网-快速使用](https://modelscope.cn/models/qwen/qwen-14b-chat)的方式加载模型。 对话结果正常：
> 
> 代码为：
> 
> ```
> model_id = "qwen/Qwen-14B-Chat"
> 
> model_dir = snapshot_download(
>     model_id=model_id,
>     revision="master"
> )
> 
> tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True,)
> model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto", trust_remote_code=True, force_download=False).eval()  # fp16=True, 
> model.generation_config = GenerationConfig.from_pretrained(model_dir, trust_remote_code=True, ) # 可指定不同的生成长度、top_p等相关超参
> 
> response, history = model.chat(tokenizer, "你好", history=None)
> print(response)
> # 你好！有什么我能帮助你的吗？
> 
> response, history = model.chat(tokenizer, "浙江的省会在哪里？", history=history) 
> print(response)
> # 浙江省的省会是杭州。
> ```
> 
> 方法二：通过 ollama 依次经过：gguf转化、量化。量化后的模型ollama加载失败，gguf直接转化后的半精度gguf能加载成功。
> 
> ```
> # 格式转化，ollama加载成功
> sudo /mnt/sdc/data/miniconda3/envs/llm/bin/python convert_hf_to_gguf.py /data/hf-pretrained/qwen/Qwen-14B-Chat/
> 
> # 量化，ollama加载失败
> sudo ./llama-quantize /data/hf-pretrained/qwen/Qwen-14B-Chat/Qwen-14B-Chat-F16.gguf Q4_K_M
> ```
> 
> 但是ollama加载半精度gguf后，模型就从 chat 退化成 base 模型了，只会玩儿文字接龙。如图： ![微信截图_20240903171955](https://private-user-images.githubusercontent.com/22868157/363920604-ed858a07-323d-4263-87a5-cb6abd267dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTUzNDYsIm5iZiI6MTcyNTg1NTA0NiwicGF0aCI6Ii8yMjg2ODE1Ny8zNjM5MjA2MDQtZWQ4NThhMDctMzIzZC00MjYzLTg3YTUtY2I2YWJkMjY3ZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA0MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMWMwMTU1OTFmNTFlNDBlY2RkNTYyYmRlMWY1Mjk1NmU3NTczNTk4MzU2M2VmMzkyNzMzODg0NjU2NDEyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ojJzYbTv4mTjP0LpRiMXYOSBoDe3ndOiOkfYRy5Wl7A)
> 
> 想问下大佬，这是咋回事？ 过程中比较有可能的两个问题点：
> 
> 1. 会不会是modelscope的模型加载函数中间，对模型有一些prompt？
> 2. 会不会ollama转化gguf的过程中，把instruction的一些东西洗掉了？

qwen系列模型应该是从qwen 1.5后才开始提供gguf和ollama支持的，qwen1的14b模型是否gguf能直接使用，社区没有明确的答案。建议还是使用qwen1或qwen2系列的模型。
