### ISSUE TITLE
function http_get_model_file can not handler file size of 0

### ISSUE THREAD

**Issue by linxiaohui** [modelscope/modelscope#980]
https://github.com/modelscope/modelscope/blob/96e33878b450eff56a63db128cbe1b10d631e515/modelscope/hub/file_download.py#L474

when a file has size of 0 (such as some `__init__.py`), it will fail to create the file.

**Comment by yingdachen** [comment]
> https://github.com/modelscope/modelscope/blob/96e33878b450eff56a63db128cbe1b10d631e515/modelscope/hub/file_download.py#L474
> 
> when a file has size of 0 (such as some `__init__.py`), it will fail to create the file.

thanks for reporting the issue. we will look into this
