### ISSUE TITLE
windows modelscope 1.7 1.8 无法下载数据集

### ISSUE THREAD

**Issue by tiandiweizun** [modelscope/modelscope#981]
windows modelscope 1.7 1.8 无法下载数据集，提示json解析错误（但是可以下载readme等文件）

然后重新装回1.4 可以下载，但是1.5、1.6未进行测试

**Comment by Yunnglin** [comment]
麻烦提供一下具体的报错信息和modelscope的版本

**Comment by wangxingjun778** [comment]
尝试升级到最新的版本，pip3 install modelscope[dataset] -U

**Comment by tiandiweizun** [comment]
> 尝试升级到最新的版本，pip3 install modelscope[dataset] -U

这个是可以解决的
