### ISSUE TITLE
在用像qwen2这样的大模型做对话时，如何添加对话记录作为cache使其具有记忆功能呢？

### ISSUE THREAD

**Issue by kli017** [modelscope/modelscope#986]

**Comment by kli017** [comment]
能否提供个简单例子

**Comment by tastelikefeet** [comment]
https://swift.readthedocs.io/zh-cn/latest/Instruction/LLM%E6%8E%A8%E7%90%86%E6%96%87%E6%A1%A3.html 查看下这个文档
