### ISSUE TITLE
 model 无法使用

### ISSUE THREAD

**Issue by Amazing-J** [modelscope/modelscope#99]
PAI/nlp_gpt3_text-generation_1.3B_MoE-32
无法使用

**Comment by jerryli1981** [comment]
现在应该可以了，微调的时候可以参考诗歌生成微调的例子：https://www.modelscope.cn/models/PAI/nlp_gpt3_text-generation_0.35B_MoE-64/summary

**Comment by jerryli1981** [comment]
下个版本发布的时候会修复
