### ISSUE TITLE
Hope to give repositories on modelscope permissions to modify commit messages

### ISSUE THREAD

**Issue by monetjoe** [modelscope/modelscope#992]
**Describe the feature**
Features description

**Motivation**
A clear and concise description of the motivation of the feature. Ex1. It is inconvenient when [....]. Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
 If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
Add any other context or screenshots about the feature request here. If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

此需求很重要，见 #815

**Comment by yingdachen** [comment]
开发中
