### ISSUE TITLE
pipline无法用yolo模型吗

### ISSUE THREAD

**Issue by Alan-zhong** [modelscope/modelscope#996]
![image](https://github.com/user-attachments/assets/a810c212-c37e-4829-bdd8-7e8e2edee905)

**Comment by yingdachen** [comment]
提供一下具体的代码

**Comment by Alan-zhong** [comment]
> 提供一下具体的代码

import cv2
from ultralytics import YOLO
import numpy as np
from PIL import Image
import os
import time
# 初始化摄像头
import cv2
from ultralytics import YOLO
import cv2
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
import numpy as np
from PIL import Image
import os
import time
import queue
import threading
import time

local_model_path = r"F:\ai construction\clothes_detect\clothes_detect_model\last.pt"
model_id = "Liberty2023/cloths_detect"

cap = cv2.VideoCapture(0) 
safety_hat_detection = pipeline(Tasks.domain_specific_object_detection, model=model_id)

报错：
Downloading [configuration.json]: 100%|██████████| 116/116 [00:00<00:00, 241B/s]
Downloading [last.pt]:   0%|          | 0.00/34.9M [00:00<?, ?B/s]
Downloading [last.pt]:   0%|          | 0.00/34.9M [00:03<?, ?B/s]

Downloading [last.pt]:   3%|▎         | 1.00M/34.9M [00:01<01:02, 568kB/s]
Downloading [last.pt]:   9%|▊         | 3.00M/34.9M [00:02<00:18, 1.80MB/s]
Downloading [last.pt]:  11%|█▏        | 4.00M/34.9M [00:02<00:17, 1.86MB/s]
Downloading [last.pt]:  14%|█▍        | 5.00M/34.9M [00:02<00:14, 2.24MB/s]
Downloading [last.pt]:  20%|██        | 7.00M/34.9M [00:03<00:07, 3.90MB/s]
Downloading [last.pt]:  26%|██▌       | 9.00M/34.9M [00:03<00:04, 5.74MB/s]
Downloading [last.pt]:  31%|███▏      | 11.0M/34.9M [00:03<00:05, 4.96MB/s]
Downloading [last.pt]:  34%|███▍      | 12.0M/34.9M [00:03<00:04, 5.57MB/s]
Downloading [last.pt]:  37%|███▋      | 13.0M/34.9M [00:04<00:04, 5.17MB/s]
Downloading [last.pt]:  40%|████      | 14.0M/34.9M [00:04<00:04, 4.44MB/s]
Downloading [last.pt]:  46%|████▌     | 16.0M/34.9M [00:04<00:03, 5.51MB/s]
Downloading [last.pt]:  52%|█████▏    | 18.0M/34.9M [00:04<00:03, 5.78MB/s]
Downloading [last.pt]:  54%|█████▍    | 19.0M/34.9M [00:05<00:04, 4.16MB/s]
Downloading [last.pt]:  57%|█████▋    | 20.0M/34.9M [00:05<00:03, 4.81MB/s]
Downloading [last.pt]:  63%|██████▎   | 22.0M/34.9M [00:05<00:02, 6.78MB/s]
Downloading [last.pt]:  69%|██████▊   | 24.0M/34.9M [00:05<00:01, 7.93MB/s]
Downloading [last.pt]:  74%|███████▍  | 26.0M/34.9M [00:06<00:01, 8.71MB/s]
Downloading [last.pt]:  80%|████████  | 28.0M/34.9M [00:06<00:00, 9.27MB/s]
Downloading [last.pt]:  86%|████████▌ | 30.0M/34.9M [00:06<00:00, 9.85MB/s]
Downloading [last.pt]:  92%|█████████▏| 32.0M/34.9M [00:06<00:00, 10.0MB/s]
Downloading [last.pt]: 100%|██████████| 34.9M/34.9M [00:06<00:00, 5.29MB/s]
Downloading [README.md]: 100%|██████████| 1.43k/1.43k [00:00<00:00, 3.30kB/s]
2024-09-23 15:39:55,990 - modelscope - WARNING - ('PIPELINES', 'domain-specific-object-detection', 'YOLOX') not found in ast index file
Traceback (most recent call last):
  File "F:/ai construction/clothes_detect/test.py", line 25, in <module>
    safety_hat_detection = pipeline(Tasks.domain_specific_object_detection, model=model_id)
  File "D:\Users\94540\anaconda3\envs\huanjing\lib\site-packages\modelscope\pipelines\builder.py", line 169, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\Users\94540\anaconda3\envs\huanjing\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\Users\94540\anaconda3\envs\huanjing\lib\site-packages\modelscope\utils\registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'YOLOX is not in the pipelines registry group domain-specific-object-detection. Please make sure the correct version of ModelScope library is used.'

**Comment by yingdachen** [comment]
Liberty2023/cloths_detect 这个模型看起来是没有接入pipelien。需要按照其模型卡片上的说明使用。接入pipeline的yolox模型可以参见比如https://www.modelscope.cn/models/iic/cv_yolox_image-object-detection-auto
