### ISSUE TITLE
怎么准确过滤出 GGUF 的模型？

### ISSUE THREAD

**Issue by hibig** [modelscope/modelscope#998]
问题：

1. 可以通过查询参数准确过滤出 GGUF 的模型吗？

当前状况：

1. 搜索模型时可以通过空格加上 gguf 字符串，比如：“qwen1.5  gguf”，这样搜索的结果大多数都是 gguf 的模型，但是还会返回一些不是 gguf 的模型。

2. 返回的模型 Tags 中也没有相应的标识。

期望：

1. 类似 Hugging Face 一样可以通过参数查询 gguf 的模型。

@wenmengzhou @tastelikefeet

**Comment by yingdachen** [comment]
类似hugging face的通过library页面选项勾选gguf的功能正在开发。

目前gguf模型应该会自动打标的，所以通过这个类似这种链接，是可以找到所有需要的gguf模型的，其中“qwen”是搜索关键词。

https://www.modelscope.cn/models?name=qwen&tags=gguf

如果有发现gguf模型没有被自动打标的话，可以这里报告一下

**Comment by hibig** [comment]
未打 GGUF 标签的模型：
1. LLM-Research/mxbai-embed-large-v1-Q4_K_M-GGUF

**Comment by yingdachen** [comment]
> 未打 GGUF 标签的模型：
> 
> 1. LLM-Research/mxbai-embed-large-v1-Q4_K_M-GGUF

收到。我们看一下这个是什么问题

**Comment by yingdachen** [comment]
this was due to a bug on our backend, we have updated meta data to ensure proper tagging for gguf models. but we are keeping this issue open until our backend code is updated.

**Comment by yingdachen** [comment]
backend fix is done. closing now
